# fix this shitty average

In [1]:


# the calculation is still wrong 
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json

#Data Source(Pandas Data Reader)
#import yfinance as yf

In [2]:
## draft 
import os
live = pd.to_datetime('today')
start = pd.to_datetime('2021-02-01')
end = pd.to_datetime('2021-06-30')

The problem is the below to_numeric error in the string to float conversion

In [3]:
directory = 'Orders'
for filename in os.listdir(directory):
    if filename.endswith('.csv'):
        df = pd.read_csv(directory+'/'+filename)
        df.columns=['Date','OrderNo', 'Pair','Type','Side' ,'Order_Price','Order_Amount','Time','Executed' ,'Average_Price', 'Trading_total','Status']
        
        df.Executed =df.Executed.str.slice(start=0,stop=6)
        df['Executed'] = pd.to_numeric(df['Executed'],errors = 'coerce')
        df.Executed.astype(float)

        df.Trading_total = df.Trading_total.str.slice(start=0,stop=6)
        df['Trading_total'] = pd.to_numeric(df['Trading_total'],errors = 'coerce')
        df.Trading_total.astype(float)
        
        
        #df.Order_Amount = df.Order_Amount.str.slice(start=0,stop=9)
        #df.Order_Amount.astype(str)
        #df.Order_Amount = df.Order_Amount.str.split(",")
        #df.Order_Amount = df.Order_Amount[0]
        #df.Order_Amount = df.Order_Amount.replace('.',',', inplace=True)
        #df.Order_Amount = df.Order_Amount.str.lstrip('.')
        #df.Order_Amount.astype(str)
        #print(df.Order_Amount.dtypes)
        #df['Order_Amount'] = pd.to_numeric(df['Order_Amount'],errors = 'coerce')
        #df.Exectuted = df.Executed.astype(str)
        #df.Executed= df.Executed.replace(',','', inplace=True)
        #df.Order_Amount.astype(float)

        

        #df.Trading_total =df.Trading_total.replace(",","", inplace=True)
        #df.Executed =(df.Executed.str.slice(start=0,stop=5)).astype(float)
        #df.Executed =pd.to_numeric(df.Executed)
        #df.Trading_total = (df.Trading_total.str.slice(start=0,stop=6)).astype(float)
        #df.astype({'Executed' :'float'})
        #df.index = ['Pair','Side']
        #df=df[(df['Status']=='FILLED')]
     
df = df.loc[(df['Status']=='FILLED')]
df.Pair= df.Pair.str.replace('BUSD','USDT')
df = df[df["Pair"].str.contains("BTC")==False]
df = df[df["Pair"].str.contains("USDTT")==False]
df = df[df["Pair"].str.contains("ETH")==False]
df = df[df["Pair"].str.contains("PROM")==False]
df = df[df["Pair"].str.contains("USDTUSDT")==False]


#df = df[df["team"].str.contains("Team 1|Team 2") == False]

df['Average_Price'] = pd.to_numeric(df['Average_Price'],errors = 'coerce')
#df.Average_Price =df.Average_Price.replace(",","", inplace=True)
#df.Average_Price = df.Average_Price.str.slice(start=0,stop=5)
df.Average_Price.astype(float)

df.Trading_total = df['Average_Price']*df['Executed']
## df.groupby(['Pair','Side','Average_Price']).Executed.sum()  
#test['Sumtrading'] = df.groupby(['Pair','Side']).Trading_total.sum()
#test['Sumcount'] = df.groupby(['Pair','Side']).Executed.sum()

test = df.groupby(['Pair','Side']).agg(
     sum_trading = ('Trading_total','sum'),
     sum_coins     = ('Executed','sum'),
 ).reset_index()
#print(df.index)
df
#test = df.groupby(['Pair','Side']).sum().reset_index()
#pairlist = test
#pair =test.loc[(test['Pair']=='DOTUSDT')]
#pair

,Date,OrderNo,Pair,Type,Side,Order_Price,Order_Amount,Time,Executed,Average_Price,Trading_total,Status
0,2022-02-01 17:34:02,664044006,CRVUSDT,Limit,SELL,3.4130000000,5.9000000000CRV,2022-02-01 17:34:03,5.900,3.413000,20.136700,FILLED
1,2022-02-01 16:57:59,3954584568,XRPUSDT,Limit,SELL,0.6274000000,32.0000000000XRP,2022-02-01 16:58:02,32.000,0.627400,20.076800,FILLED
4,2022-02-01 16:51:19,663907989,CRVUSDT,Limit,SELL,3.4270000000,5.9000000000CRV,2022-02-01 16:51:19,5.900,3.427000,20.219300,FILLED
5,2022-02-01 16:48:54,2693960208,LTCUSDT,Limit,SELL,114.0000000000,0.0880000000LTC,2022-02-01 16:49:00,0.088,114.000000,10.032000,FILLED
6,2022-02-01 16:36:00,663860966,CRVUSDT,Limit,SELL,3.4140000000,5.9000000000CRV,2022-02-01 16:36:02,5.900,3.414000,20.142600,FILLED
...,...,...,...,...,...,...,...,...,...,...,...,...
20408,2021-03-05 19:09:08,704262174,VETUSDT,Limit,BUY,0.0527750000,"3,790.0000000000VET",2021-03-05 19:09:08,NaN,0.052775,NaN,FILLED
20409,2021-03-05 18:30:36,198390011,IOTAUSDT,Limit,BUY,1.3655000000,134.0200000000IOTA,2021-03-05 18:30:36,134.020,1.364000,182.803280,FILLED
20410,2021-03-05 14:03:27,198076732,IOTAUSDT,Limit,BUY,1.4101000000,129.1800000000IOTA,2021-03-05 14:03:35,129.180,1.410100,182.156718,FILLED
20411,2021-03-05 09:06:09,1068450885,ADAUSDT,Limit,BUY,1.1108000000,449.6000000000ADA,2021-03-05 09:06:09,449.600,1.110560,499.307776,FILLED
20414,2021-03-05 08:39:36,463604391,THETAUSDT,Limit,BUY,4.2701300000,468.4000000000THETA,2021-03-05 08:41:43,468.400,4.270130,2000.128892,FILLED

In [4]:
buy = df[(df['Side']=='BUY') & (df['Status']=='FILLED') ] 
sell = df[(df['Side']=='SELL') & (df['Status']=='FILLED') ] 


buy
sell

,Date,OrderNo,Pair,Type,Side,Order_Price,Order_Amount,Time,Executed,Average_Price,Trading_total,Status
0,2022-02-01 17:34:02,664044006,CRVUSDT,Limit,SELL,3.4130000000,5.9000000000CRV,2022-02-01 17:34:03,5.900,3.413000,20.1367,FILLED
1,2022-02-01 16:57:59,3954584568,XRPUSDT,Limit,SELL,0.6274000000,32.0000000000XRP,2022-02-01 16:58:02,32.000,0.627400,20.0768,FILLED
4,2022-02-01 16:51:19,663907989,CRVUSDT,Limit,SELL,3.4270000000,5.9000000000CRV,2022-02-01 16:51:19,5.900,3.427000,20.2193,FILLED
5,2022-02-01 16:48:54,2693960208,LTCUSDT,Limit,SELL,114.0000000000,0.0880000000LTC,2022-02-01 16:49:00,0.088,114.000000,10.0320,FILLED
6,2022-02-01 16:36:00,663860966,CRVUSDT,Limit,SELL,3.4140000000,5.9000000000CRV,2022-02-01 16:36:02,5.900,3.414000,20.1426,FILLED
...,...,...,...,...,...,...,...,...,...,...,...,...
20308,2021-03-12 09:47:25,210281339,MATICUSDT,Stop-Limit,SELL,0.3420000000,113.9000000000MATIC,2021-03-22 20:46:29,113.900,0.343000,39.0677,FILLED
20319,2021-03-11 21:47:43,160965528,TFUELUSDT,Stop-Limit,SELL,0.3000000000,100.0000000000TFUEL,2021-03-17 09:48:26,100.000,0.300000,30.0000,FILLED
20327,2021-03-11 12:16:29,174960276,CHZUSDT,Limit,SELL,0.2630300000,"4,920.0000000000CHZ",2021-03-11 12:16:29,NaN,0.263093,NaN,FILLED
20357,2021-03-10 20:51:37,477282339,THETAUSDT,Limit,SELL,6.1400000000,16.3000000000THETA,2021-03-10 21:22:10,16.300,6.140000,100.0820,FILLED
20373,2021-03-09 10:41:11,165038453,CHZUSDT,Stop-Limit,SELL,0.2950000000,"1,326.0000000000CHZ",2021-03-09 10:44:27,NaN,0.295000,NaN,FILLED

In [18]:
test1=buy.loc[(buy['Pair']=='RENUSDT')]
#test1['Trading_total']=test['Order_Amount']*test['Order_Price']
#test1=sell.loc[(sell['Pair']=='ZRXUSDT')]

test1

,Date,OrderNo,Pair,Type,Side,Order_Price,Order_Amount,Time,Executed,Average_Price,Trading_total,Status
196,2022-01-24 11:14:17,568083555,RENUSDT,Limit,BUY,0.2547000000,393.0000000000REN,2022-01-24 11:14:26,393.0,0.25470,100.097100,FILLED
230,2022-01-22 10:42:20,566507602,RENUSDT,Limit,BUY,0.2807000000,356.0000000000REN,2022-01-22 10:46:03,356.0,0.28070,99.929200,FILLED
312,2022-01-08 05:14:20,558716010,RENUSDT,Limit,BUY,0.4777000000,209.0000000000REN,2022-01-08 05:14:54,209.0,0.47770,99.839300,FILLED
344,2021-12-31 19:41:50,554109702,RENUSDT,Limit,BUY,0.5324000000,187.0000000000REN,2021-12-31 19:43:29,187.0,0.53240,99.558800,FILLED
365,2021-12-24 14:12:20,550564092,RENUSDT,Limit,BUY,0.6638000000,150.0000000000REN,2021-12-24 14:31:05,150.0,0.66380,99.570000,FILLED
388,2021-12-15 23:24:29,542658974,RENUSDT,Limit,BUY,0.5136000000,194.0000000000REN,2021-12-15 23:24:29,194.0,0.51360,99.638400,FILLED
414,2021-12-05 18:31:34,536543125,RENUSDT,Limit,BUY,0.6290000000,158.0000000000REN,2021-12-05 18:31:40,158.0,0.62900,99.382000,FILLED
510,2021-11-18 13:24:07,11983940,RENUSDT,Limit,BUY,0.7600000000,131.0000000000REN,2021-11-18 13:25:51,131.0,0.76000,99.560000,FILLED
517,2021-11-16 15:40:11,11717157,RENUSDT,Limit,BUY,0.8252000000,242.0000000000REN,2021-11-16 15:42:41,242.0,0.82520,199.698400,FILLED
549,2021-11-10 21:29:55,520429177,RENUSDT,Limit,BUY,0.9016000000,110.0000000000REN,2021-11-10 21:29:57,110.0,0.90160,99.176000,FILLED
596,2021-10-11 20:35:56,6705094,RENUSDT,Limit,BUY,0.9959000000,50.0000000000REN,2021-10-11 20:36:12,50.0,0.99590,49.795000,FILLED
600,2021-10-11 20:00:34,6699680,RENUSDT,Limit,BUY,0.9971000000,50.0000000000REN,2021-10-11 20:00:34,50.0,0.99710,49.855000,FILLED
606,2021-10-10 21:50:05,6502133,RENUSDT,Limit,BUY,1.0207000000,49.0000000000REN,2021-10-10 21:51:04,49.0,1.02070,50.014300,FILLED
607,2021-10-10 21:16:24,6498895,RENUSDT,Limit,BUY,1.0110000000,49.0000000000REN,2021-10-10 21:17:42,49.0,1.01100,49.539000,FILLED
610,2021-10-10 21:02:33,6496171,RENUSDT,Limit,BUY,1.0290000000,48.0000000000REN,2021-10-10 21:02:37,48.0,1.02900,49.392000,FILLED
611,2021-10-10 20:37:37,6492918,RENUSDT,Limit,BUY,1.0409000000,48.0000000000REN,2021-10-10 20:48:54,48.0,1.04090,49.963200,FILLED
612,2021-10-10 20:37:22,6492869,RENUSDT,Limit,BUY,1.0400000000,48.0000000000REN,2021-10-10 20:48:55,48.0,1.04000,49.920000,FILLED
1476,2021-09-07 16:05:40,456224606,RENUSDT,Limit,BUY,0.6813000000,29.0000000000REN,2021-09-07 16:05:43,29.0,0.68130,19.757700,FILLED
8427,2021-07-06 00:08:53,399977534,RENUSDT,Limit,BUY,0.3738400000,53.4000000000REN,2021-07-06 00:17:09,53.4,0.37384,19.963056,FILLED
9134,2021-06-25 02:01:38,390412514,RENUSDT,Limit,BUY,0.3533500000,42.4000000000REN,2021-06-25 02:01:50,42.4,0.35335,14.982040,FILLED
12901,2021-05-02 06:57:25,320555116,RENUSDT,Limit,BUY,0.9510000000,210.3000000000REN,2021-05-02 07:01:25,210.3,0.95100,199.995300,FILLED
12902,2021-05-02 06:29:13,320518222,RENUSDT,Limit,BUY,0.9489000000,210.7000000000REN,2021-05-02 06:43:57,210.7,0.94890,199.933230,FILLED
12908,2021-05-02 06:07:47,320492571,RENUSDT,Limit,BUY,0.9552100000,209.3000000000REN,2021-05-02 06:07:47,209.3,0.95521,199.925453,FILLED
12910,2021-05-02 05:58:19,320482728,RENUSDT,Limit,BUY,0.9400000000,212.7000000000REN,2021-05-02 07:31:51,212.7,0.94000,199.938000,FILLED
13471,2021-04-25 19:16:26,309949391,RENUSDT,Limit,BUY,0.7716300000,19.4000000000REN,2021-04-25 19:16:37,19.4,0.77163,14.969622,FILLED
14650,2021-04-17 13:01:41,293397663,RENUSDT,Limit,BUY,1.1308600000,13.2000000000REN,2021-04-17 13:02:08,13.2,1.13086,14.927352,FILLED
14742,2021-04-17 06:30:46,292786188,RENUSDT,Limit,BUY,1.1840600000,12.6000000000REN,2021-04-17 06:30:51,12.6,1.18406,14.919156,FILLED
14871,2021-04-16 12:01:42,291113543,RENUSDT,Limit,BUY,1.0516400000,14.2000000000REN,2021-04-16 12:02:23,14.2,1.05164,14.933288,FILLED
15934,2021-04-09 03:18:42,279087939,RENUSDT,Limit,BUY,1.0183900000,14.7000000000REN,2021-04-09 03:20:58,14.7,1.01839,14.970333,FILLED
16588,2021-04-06 22:31:50,275620099,RENUSDT,Limit,BUY,1.0838900000,13.8000000000REN,2021-04-06 22:31:56,13.8,1.08389,14.957682,FILLED
16590,2021-04-06 22:31:26,275619768,RENUSDT,Limit,BUY,1.0820800000,13.8000000000REN,2021-04-06 22:31:34,13.8,1.08208,14.932704,FILLED
16628,2021-04-06 21:46:54,275590267,RENUSDT,Limit,BUY,1.0770300000,13.9000000000REN,2021-04-06 21:47:00,13.9,1.07703,14.970717,FILLED
17563,2021-04-04 19:01:50,272635840,RENUSDT,Limit,BUY,1.0879100000,13.7000000000REN,2021-04-04 19:02:17,13.7,1.08791,14.904367,FILLED
17578,2021-04-04 17:01:54,272543913,RENUSDT,Limit,BUY,1.0817200000,13.8000000000REN,2021-04-04 17:03:16,13.8,1.08172,14.927736,FILLED
17617,2021-04-04 14:46:44,272423417,RENUSDT,Limit,BUY,1.0740800000,13.9000000000REN,2021-04-04 14:46:46,13.9,1.07408,14.929712,FILLED
18836,2021-03-31 14:17:05,267773173,RENUSDT,Limit,BUY,1.0056100000,14.9000000000REN,2021-03-31 14:18:23,14.9,1.00561,14.983589,FILLED
19588,2021-03-30 07:28:03,266200385,RENUSDT,Limit,BUY,1.0840100000,13.8000000000REN,2021-03-30 07:35:04,13.8,1.08401,14.959338,FILLED
20037,2021-03-27 22:23:34,263484453,RENUSDT,Limit,BUY,0.9876400000,20.2000000000REN,2021-03-27 22:24:27,20.2,0.98764,19.950328,FILLED
20056,2021-03-27 22:00:21,263467932,RENUSDT,Limit,BUY,1.0059900000,14.9000000000REN,2021-03-27 22:00:24,14.9,1.00599,14.989251,FILLED

In [6]:
test = test
test['TotalBought'] = (test['sum_trading'].loc[(test['Side']=='BUY')])
test['TotalSold'] = (test['sum_trading'].loc[(test['Side']=='SELL')])
test['CoinsBought'] = (test['sum_coins'].loc[(test['Side']=='BUY')])
test['CoinsSold'] = (test['sum_coins'].loc[(test['Side']=='SELL')])
new = test[['Pair','CoinsBought','CoinsSold','TotalBought','TotalSold']]
#test['Total Dollars'] = 
#test['Total'] = (test['sum_trading'].loc[(test['Side']=='BUY')]) - (test['sum_trading'].loc[(test['Side']=='SELL')])

test

new.head()

        Pair  CoinsBought  CoinsSold  TotalBought    TotalSold
0  1INCHUSDT    1037.7100        NaN  3652.947401          NaN
1  1INCHUSDT          NaN     482.58          NaN  2338.794280
2   AAVEUSDT       1.9204        NaN   592.165712          NaN
3   AAVEUSDT          NaN       1.92          NaN   600.076447
4    ACMUSDT      27.7820        NaN   249.668796          NaN

In [7]:
pair =new.loc[(new['Pair']=='ZILUSDT')]
pair

        Pair  CoinsBought  CoinsSold  TotalBought   TotalSold
511  ZILUSDT       6712.9        NaN  1180.227406         NaN
512  ZILUSDT          NaN     1319.9          NaN  190.553036

In [8]:
new1 =new.groupby('Pair').agg(
     Total_Bought = ('TotalBought','sum'),
     Coins_Bought   = ('CoinsBought','sum'),
     Total_Sold = ('TotalSold','sum'),
     Coins_Sold   = ('CoinsSold','sum'),

        
 ).reset_index()

new1['differenc_usd']=new1['Total_Bought']- new1['Total_Sold']
new1['differenc_coins']=new1['Coins_Bought']- new1['Coins_Sold']
new1['Average_price'] =new1['differenc_usd'] / new1['differenc_coins']
#new1.sort_values('differenc_usd',inplace =True ,ascending=False)
#new1.to_csv("Marsh-spetember.csv")
new1

,Pair,Total_Bought,Coins_Bought,Total_Sold,Coins_Sold,differenc_usd,differenc_coins,Average_price
0,1INCHUSDT,3652.947401,1037.7100,2338.794280,482.5800,1314.153121,555.1300,2.367289e+00
1,AAVEUSDT,592.165712,1.9204,600.076447,1.9200,-7.910735,0.0004,-1.977684e+04
2,ACMUSDT,249.668796,27.7820,229.454487,27.7820,20.214309,0.0000,inf
3,ADAAUD,19.786295,12.6430,0.000000,0.0000,19.786295,12.6430,1.565000e+00
4,ADAUSDT,20966.756313,14330.8600,12262.355302,7520.6200,8704.401011,6810.2400,1.278134e+00
...,...,...,...,...,...,...,...,...
257,YFIUSDT,0.000000,0.0064,0.000000,0.0057,0.000000,0.0007,0.000000e+00
258,ZECUSDT,224.781823,1.4143,209.782621,1.2683,14.999202,0.1460,1.027343e+02
259,ZENUSDT,154.625469,2.0440,151.410648,2.0440,3.214821,0.0000,inf
260,ZILUSDT,1180.227406,6712.9000,190.553036,1319.9000,989.674370,5393.0000,1.835109e-01
261,ZRXUSDT,1142.490831,786.3400,747.687218,484.4600,394.803613,301.8800,1.307816e+00

In [9]:
final = new1 [['Pair','Average_price']]
final=final.rename(columns={'Pair':'Indicator'})

print(final.iloc[0:60,0:9])
print(final.iloc[60:110,])
print(final.iloc[110:160,])

     Indicator  Average_price
0    1INCHUSDT   2.367289e+00
1     AAVEUSDT  -1.977684e+04
2      ACMUSDT            inf
3       ADAAUD   1.565000e+00
4      ADAUSDT   1.278134e+00
5     AIONUSDT   2.890301e-01
6     AKROUSDT   7.415658e-02
7     ALGOUSDT   6.439134e-01
8    ALICEUSDT   2.840272e+01
9   ALPACAUSDT           -inf
10   ALPHAUSDT            inf
11    ANKRUSDT   1.251853e-01
12     ANTUSDT  -5.334145e+02
13    ARDRUSDT            inf
14    ARPAUSDT   8.546370e-02
15      ARUSDT   3.744862e+01
16     ASRUSDT   1.253639e+01
17     ATAUSDT           -inf
18     ATMUSDT   1.795573e+03
19    ATOMUSDT   6.762010e+01
20   AUDIOUSDT   8.232864e-01
21     AUDUSDT   7.534143e-01
22    AUTOUSDT           -inf
23     AVAUSDT            inf
24    AVAXUSDT   7.944364e+01
25     AXSUSDT  -4.061925e+00
26  BADGERUSDT  -3.214663e+03
27    BAKEUSDT   1.389318e+00
28     BALUSDT   2.408332e+01
29    BANDUSDT   1.044500e+01
30     BARUSDT           -inf
31     BATUSDT   1.299509e+00
32     BCHUSDT  -6.376668e+01
33    BEAMUSDT  -3.063313e+03
34     BELUSDT           -inf
35     BLZUSDT   7.884284e-01
36     BNBUSDT   3.620000e+02
37     BNTUSDT   3.528367e+02
38    BONDUSDT            inf
39     BTGUSDT            inf
40     BTSUSDT   9.169486e-02
41     BTTUSDT            NaN
42  BURGERUSDT            inf
43    BZRXUSDT   1.503144e+03
44     C98USDT  -1.298171e+00
45    CAKEUSDT   1.532443e+01
46    CELOUSDT   4.571796e+00
47    CELRUSDT   9.910134e-02
48     CFXUSDT            inf
49     CHRUSDT  -4.731093e-01
50     CHZUSDT   1.024002e+00
51     CLVUSDT            inf
52   COCOSUSDT           -inf
53    COMPUSDT   4.660341e+02
54     COSUSDT   9.168514e-02
55    COTIUSDT   3.515048e-01
56     CRVUSDT   3.622548e+00
57     CTKUSDT            inf
58    CTSIUSDT  -2.011367e+00
59    CTXCUSDT   5.448606e-01
     Indicator  Average_price
60     CVCUSDT   6.203065e+00
61    DASHUSDT   3.803031e+05
62    DATAUSDT   2.011281e-01
63     DCRUSDT  -3.411617e+04
64    DEGOUSDT           -inf
65    DENTUSDT   1.876045e-02
66    DEXEUSDT            inf
67     DIAUSDT   5.265354e+00
68     DNTUSDT   2.429818e-01
69    DOCKUSDT   8.399197e-01
70    DODOUSDT   2.962137e+00
71    DOGEUSDT  -4.343458e-01
72     DOTUSDT   2.435036e+01
73    DREPUSDT            inf
74    DUSKUSDT  -1.954427e+01
75    DYDXUSDT   6.426734e+00
76    EGLDUSDT   1.804990e+02
77     ENJUSDT   1.932457e+00
78     EOSUSDT   9.204386e-01
79     EPSUSDT            inf
80     ERNUSDT            inf
81     ETCUSDT  -1.563821e+03
82     EURUSDT  -1.684710e+01
83    FARMUSDT            inf
84     FETUSDT   9.161356e-01
85    FIDAUSDT           -inf
86     FILUSDT   4.261733e+01
87     FIOUSDT   1.908382e+02
88    FIROUSDT            inf
89     FISUSDT            inf
90     FLMUSDT   4.712041e+13
91    FLOWUSDT   2.304069e+01
92    FLUXUSDT   1.798195e+00
93   FORTHUSDT            inf
94     FORUSDT           -inf
95     FTMUSDT   3.561964e-01
96     FTTUSDT   5.430711e+01
97     FUNUSDT   4.370586e-02
98    GALAUSDT   3.447877e-01
99     GBPUSDT  -9.696600e+00
100    GRTUSDT   6.040578e-01
101    GTCUSDT            inf
102    GTOUSDT   1.379097e+00
103    GXSUSDT   1.423370e+02
104   HARDUSDT   4.215972e+00
105   HBARUSDT   2.860211e-01
106   HIVEUSDT   1.405163e+00
107    HNTUSDT   2.044806e+01
108    HOTUSDT   2.871242e-02
109    ICPUSDT   2.880956e+01
     Indicator  Average_price
110    ICXUSDT       4.854025
111   IDEXUSDT            inf
112    INJUSDT       5.448183
113   IOSTUSDT       0.099479
114   IOTAUSDT       0.609052
115   IOTXUSDT       0.120925
116   IRISUSDT       0.120951
117    JSTUSDT       0.165439
118    JUVUSDT   -4031.489000
119   KAVAUSDT           -inf
120   KEEPUSDT           -inf
121    KEYUSDT       0.027676
122   KLAYUSDT            inf
123    KMDUSDT            inf
124    KNCUSDT            inf
125    KSMUSDT     206.652768
126   LINAUSDT       0.068862
127   LINKUSDT      26.219018
128    LITUSDT       3.806403
129    LPTUSDT            inf
130    LRCUSDT       1.495290
131    LSKUSDT            inf
132    LTCUSDT     238.887651
133    LTOUSDT       0.870178
134    LUNABNB       0.025756
135   LUNAUSDT      16.201695
136   MANAUSDT       2.827701
137   MASKUSDT     -90.425875
138   MATICBNB       0.002785
139  MATICUSDT       0.877233
140    MBLUSDT       0.069261
141   MBOXUSDT            inf
142    MDTUSDT      58.337710
143    MDXUSDT            inf
144    MFTUSDT            inf
145   MINAUSDT       4.375246
146    MIRUSDT       2.809441
147   MITHUSDT       0.123985
148    MKRUSDT       0.000000
149    MLNUSDT            inf
150    MTLUSDT            inf
151   NANOUSDT           -inf
152    NBSUSDT      -3.282369
153   NEARUSDT      12.023222
154    NEOUSDT      53.453010
155    NKNUSDT       2.718137
156    NMRUSDT            inf
157   NPXSUSDT            NaN
158   NULSUSDT      -4.216122
159     NUUSDT           -inf

In [10]:
pair =new1.loc[(new1['Pair']=='ZILUSDT')]
pair

,Pair,Total_Bought,Coins_Bought,Total_Sold,Coins_Sold,differenc_usd,differenc_coins,Average_price
260,ZILUSDT,1180.227406,6712.9,190.553036,1319.9,989.67437,5393.0,0.183511

In [11]:
final

     Indicator  Average_price
0    1INCHUSDT   2.367289e+00
1     AAVEUSDT  -1.977684e+04
2      ACMUSDT            inf
3       ADAAUD   1.565000e+00
4      ADAUSDT   1.278134e+00
..         ...            ...
257    YFIUSDT   0.000000e+00
258    ZECUSDT   1.027343e+02
259    ZENUSDT            inf
260    ZILUSDT   1.835109e-01
261    ZRXUSDT   1.307816e+00

[262 rows x 2 columns]

In [12]:
final.to_csv('avgentries.csv')