In [1]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta


#Data Source(Pandas Data Reader)

In [2]:
whitelist = 'LINA/USDT, CHR/USDT, ORN/USDT, VIDT/USDT, IRIS/USDT, SHIB/USDT, MATIC/USDT,ALGO/USDT, BTC/USDT, ETH/USDT, AXS/USDT, SOL/USDT, MATIC/USDT, ADA/USDT, BNB/USDT, FIL/USDT, XRP/USDT, CVC/USDT, FTM/USDT, ICP/USDT, DOGE/USDT, XEC/USDT, IOTA/USDT, AVAX/USDT, DOT/USDT, LTC/USDT, EOS/USDT, IOST/USDT, STMX/USDT, FTT/USDT, TWT/USDT, ALICE/USDT, ATA/USDT, ETC/USDT, VET/USDT, SAND/USDT, LINK/USDT, THETA/USDT, SHIB/USDT, CHZ/USDT, LUNA/USDT, IOTX/USDT, TRX/USDT, TLM/USDT, BCH/USDT, REEF/USDT, CAKE/USDT, NEO/USDT,RVN/USDT, ATOM/USDT, SUSHI/USDT, ARDR/USDT, OMG/USDT, GRT/USDT, 1INCH/USDT, AAVE/USDT, C98/USDT, UNI/USDT, HBAR/USDT, CRV/USDT, DENT/USDT, MBOX/USDT, BTT/USDT, SRM/USDT, YFI/USDT, HOT/USDT, XLM/USDT, FIS/USDT, REQ/USDT, SXP/USDT, KSM/USDT, QNT/USDT, NEAR/USDT, COMP/USDT, QTUM/USDT, CHR/USDT, SC/USDT, XVS/USDT, ONT/USDT, COTI/USDT, NKN/USDT, RUNE/USDT, ANKR/USDT, MANA/USDT, CTXC/USDT, AR/USDT, RAY/USDT, BAKE/USDT, ARPA/USDT, XTZ/USDT, ZIL/USDT, ONG/USDT, ROSE/USDT, PNT/USDT, ALGO/USDT, MINA/USDT, WIN/USDT, AUDIO/USDT, STORJ/USDT, EPS/USDT, MDX/USDT, ZEC/USDT, ENJ/USDT, HIVE/USDT, TFUEL/USDT, WRX/USDT, SNX/USDT, SKL/USDT, LINA/USDT, DODO/USDT, UNFI/USDT, XEM/USDT, EGLD/USDT, ICX/USDT, WAVES/USDT, ONE/USDT, DASH/USDT, KAVA/USDT, SUPER/USDT, TKO/USDT, OGN/USDT, XMR/USDT, OCEAN/USDT, CELO/USDT, BAT/USDT, FUN/USDT, LRC/USDT, ALPHA/USDT, MASK/USDT, TRU/USDT, DNT/USDT, LIT/USDT, FET/USDT, GTC/USDT, CELR/USDT, DEXE/USDT, ZEN/USDT, WAXP/USDT, CTSI/USDT, HNT/USDT, YFII/USDT, BEL/USDT, ZRX/USDT, DEGO/USDT, RSR/USDT, COS/USDT, FLM/USDT, BAL/USDT, MFT/USDT, RLC/USDT, KNC/USDT, REN/USDT, INJ/USDT, FLOW/USDT, SFP/USDT, BAND/USDT, CTK/USDT, SUN/USDT, AKRO/USDT, XVG/USDT, NANO/USDT, STRAX/USDT, PUNDIX/USDT, TVK/USDT, MKR/USDT, CLV/USDT, TRB/USDT, ETHUP/USDT, KEEP/USDT, TCT/USDT, POND/USDT, LTO/USDT, ANT/USDT, TOMO/USDT, ACM/USDT, FIO/USDT, VITE/USDT, MBL/USDT, JST/USDT, MTL/USDT, UTK/USDT, BLZ/USDT, ORN/USDT, STPT/USDT, CFX/USDT, OM/USDT, PERP/USDT, MIR/USDT, STX/USDT, ERN/USDT, TUSD/USDT, PSG/USDT, NULS/USDT, OXT/USDT, REP/USDT, BNBUP/USDT, DATA/USDT, WAN/USDT, BURGER/USDT, RAMP/USDT, ATM/USDT, DGB/USDT, DIA/USDT, BEAM/USDT, UMA/USDT, ETHDOWN/USDT, CKB/USDT, TRIBE/USDT, FARM/USDT, BTCUP/USDT, BZRX/USDT, ALPACA/USDT, DOTUP/USDT, BTS/USDT, FOR/USDT, ADAUP/USDT, HARD/USDT, LSK/USDT, POLS/USDT, FORTH/USDT, TORN/USDT, VTHO/USDT, BTG/USDT, QUICK/USDT, FILUP/USDT, PAX/USDT, MITH/USDT, SUSHIUP/USDT, BTCDOWN/USDT, XRPDOWN/USDT, BNBDOWN/USDT, DUSK/USDT, XRPUP/USDT, WTC/USDT, DOCK/USDT, AUTO/USDT, BTCST/USDT, KLAY/USDT, WNXM/USDT, KEY/USDT, FILDOWN/USDT, NU/USDT, IRIS/USDT, KMD/USDT, TROY/USDT, WING/USDT, AION/USDT, PHA/USDT, SUSHIDOWN/USDT, EOSUP/USDT, LTCUP/USDT, GHST/USDT, PAXG/USDT, BNT/USDT, AVA/USDT, BADGER/USDT, PERL/USDT, COCOS/USDT, GXS/USDT, MDT/USDT, 1INCHUP/USDT, GTO/USDT, LINKUP/USDT, AAVEUP/USDT, FIRO/USDT, JUV/USDT, MLN/USDT, UNIUP/USDT, LPT/USDT, NMR/USDT, AAVEDOWN/USDT, 1INCHDOWN/USDT, ASR/USDT, OG/USDT, BAR/USDT, DREP/USDT, BOND/USDT, DCR/USDT, GNO/USDT, NBS/USDT, RIF/USDT, NEAR/USDT'
#whitelist = 'LINK/USDT, DOT/USDT'
startdate = '2020-01-01'
enddate = '2022-02-17'
interval = '1w'

"id": "mimatic",
    "symbol": "mimatic",
    "name": "MAI",
    "image": "https://assets.coingecko.com/coins/images/15264/large/mimatic-red.png?1620281018",
    "current_price": 1.004,
    "market_cap": 265391467,
    "market_cap_rank": 231,
    "fully_diluted_valuation": null,
    "total_volume": 2027839,
    "high_24h": 1.012,
    "low_24h": 0.990852,
    "price_change_24h": 0.00248919,
    "price_change_percentage_24h": 0.24866,
    "market_cap_change_24h": 204809,
    "market_cap_change_percentage_24h": 0.07723,
    "circulating_supply": 265198596.172783,
    "total_supply": 265208882.298472,
    "max_supply": null,
    "ath": 1.35,
    "ath_change_percentage": -25.9812,
    "ath_date": "2021-05-29T21:51:31.732Z",
    "atl": 0.809109,
    "atl_change_percentage": 23.87953,
    "atl_date": "2022-01-24T14:55:16.883Z",
    "roi": null,
    "last_updated": "2022-02-18T08:47:13.009Z"

In [3]:
root_url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=1000&page=1&sparkline=false&price_change_percentage=365d'
url = root_url
data = json.loads(requests.get(url).text)
dflive = pd.DataFrame(data)

In [4]:
dflive.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://assets.coingecko.com/coins/images/1/la...,29391.000,559607139062,1,6.172142e+11,2.517436e+10,30122.000,...,2.100000e+07,21000000.0,69045.00,-57.42914,2021-11-10T14:24:11.849Z,67.810000,43246.68787,2013-07-06T00:00:00.000Z,None,2022-05-14T21:09:53.556Z
1,ethereum,eth,Ethereum,https://assets.coingecko.com/coins/images/279/...,1999.160,241456554290,2,NaN,1.438415e+10,2082.390,...,NaN,NaN,4878.26,-58.98271,2021-11-10T14:24:19.604Z,0.432979,462031.20715,2015-10-20T00:00:00.000Z,"{'times': 89.95112024746906, 'currency': 'btc'...",2022-05-14T21:09:34.199Z
2,tether,usdt,Tether,https://assets.coingecko.com/coins/images/325/...,1.000,76720227550,3,NaN,5.296157e+10,1.005,...,7.670815e+10,NaN,1.32,-24.37027,2018-07-24T00:00:00.000Z,0.572521,74.78022,2015-03-02T00:00:00.000Z,None,2022-05-14T21:07:18.333Z
3,usd-coin,usdc,USD Coin,https://assets.coingecko.com/coins/images/6319...,1.002,51157579406,4,NaN,8.291024e+09,1.007,...,5.103907e+10,NaN,1.17,-14.55488,2019-05-08T00:40:28.300Z,0.891848,12.35325,2021-05-19T13:14:05.611Z,None,2022-05-14T21:10:55.341Z
4,binancecoin,bnb,BNB,https://assets.coingecko.com/coins/images/825/...,288.110,48442467686,5,4.844247e+10,7.487959e+08,299.850,...,1.681370e+08,168137035.9,686.31,-58.03155,2021-05-10T07:24:17.097Z,0.039818,723277.37640,2017-10-19T00:00:00.000Z,None,2022-05-14T21:08:44.050Z

In [5]:
filter = dflive.loc[:,('id','symbol','name','current_price','market_cap','fully_diluted_valuation','total_volume','high_24h','total_volume','price_change_percentage_24h','circulating_supply','total_supply','max_supply','ath','ath_change_percentage')]
filter['supply_ratio'] =dflive['circulating_supply']/filter['max_supply']
filter['cap_ratio'] =dflive['market_cap']/filter['fully_diluted_valuation']

#drop = filter.loc[(filter['supply_ratio']>0.8)&(filter['market_cap']<1000000000),:]
#drop = filter.loc[(filter['supply_ratio']>0.5)&(filter['cap_ratio'] > 0.5)&(filter['market_cap']<2000000000),:]
drop = filter.loc[(filter['cap_ratio'] > 0.5)&(filter['market_cap']<5000000000),:]
drop = filter.loc[(filter['cap_ratio'] > 0.5),:]

drop.sort_values(by=['supply_ratio'],ascending=False,inplace = True) 
drop 
#sort = drop.sort_values(by=['supply_ratio'],ascending=False,inplace = True) 
#filter1
#filter1 = drop.sort_values(by=['supply_ratio'],ascending=False,inplace = True) 
#filter1
#sort

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,id,symbol,name,current_price,market_cap,fully_diluted_valuation,total_volume,high_24h,total_volume,price_change_percentage_24h,circulating_supply,total_supply,max_supply,ath,ath_change_percentage,supply_ratio,cap_ratio
244,iron-bank-euro,ibeur,Iron Bank EURO,1.018000e+00,122234207,1.222342e+08,44637.0,1.047000e+00,44637.0,1.12984,1.200000e+08,1.200000e+08,1.200000e+08,1.770000,-42.53756,1.000000,1.000000
185,renbtc,renbtc,renBTC,2.937300e+04,199546646,1.995466e+08,20837679.0,3.015600e+04,20837679.0,-1.38489,6.783680e+03,6.783680e+03,6.783680e+03,68977.000000,-57.35447,1.000000,1.000000
4,binancecoin,bnb,BNB,2.881100e+02,48442467686,4.844247e+10,748795871.0,2.998500e+02,748795871.0,-2.38691,1.681370e+08,1.681370e+08,1.681370e+08,686.310000,-58.03155,1.000000,1.000000
109,nxm,nxm,Nexus Mutual,6.794000e+01,467477562,4.674776e+08,63291.0,7.068000e+01,63291.0,-2.48801,6.881100e+06,6.881100e+06,6.881100e+06,185.970000,-63.42915,1.000000,1.000000
123,livepeer,lpt,Livepeer,1.486000e+01,379001994,3.790020e+08,33106634.0,1.548000e+01,33106634.0,1.52819,2.549689e+07,2.549689e+07,2.549689e+07,99.030000,-85.04049,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,nexo,nexo,NEXO,1.340000e+00,750187050,1.339620e+09,9918847.0,1.350000e+00,9918847.0,0.73429,5.600000e+08,1.000000e+09,1.000000e+09,4.070000,-67.09500,0.560000,0.560000
162,dogelon-mars,elon,Dogelon Mars,4.698210e-07,258919237,4.698207e+08,20673364.0,5.617400e-07,20673364.0,-14.71725,5.511023e+14,1.000000e+15,1.000000e+15,0.000003,-81.83580,0.551102,0.551102
167,wax,waxp,WAX,1.198390e-01,239990264,4.533075e+08,25795196.0,1.332530e-01,25795196.0,2.81939,1.996076e+09,3.770303e+09,3.770303e+09,2.770000,-95.66718,0.529420,0.529420
178,tether-eurt,eurt,Euro Tether,1.037000e+00,214535668,4.165765e+08,1995816.0,1.049000e+00,1995816.0,-0.49801,2.059988e+08,4.000000e+08,4.000000e+08,1.310000,-20.24180,0.514997,0.514997
149,skale,skl,SKALE,7.962100e-02,278794866,5.572748e+08,9557868.0,8.831500e-02,9557868.0,-5.55899,3.501978e+09,4.706715e+09,7.000000e+09,1.220000,-93.45451,0.500283,0.500283

In [6]:
change = drop[['symbol','price_change_percentage_24h']]
change.sort_values(by=['price_change_percentage_24h'],ascending=False,inplace = True) 
change

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

     symbol  price_change_percentage_24h
57      grt                     18.22999
51      mkr                     15.50066
43     mana                      9.91852
242  pundix                      9.59946
54      zec                      8.39014
..      ...                          ...
193     uma                     -5.94700
83      cvx                    -13.64852
162    elon                    -14.71725
155     syn                    -17.77033
102     fxs                    -22.98430

[72 rows x 2 columns]

In [7]:
capratio = drop[['symbol','supply_ratio','cap_ratio']]
capratio.symbol =capratio.symbol+'usdt'
capratio.symbol =capratio.symbol.str.upper()
capratio

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/pandas/core/generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

         symbol  supply_ratio  cap_ratio
244   IBEURUSDT      1.000000   1.000000
185  RENBTCUSDT      1.000000   1.000000
4       BNBUSDT      1.000000   1.000000
109     NXMUSDT      1.000000   1.000000
123     LPTUSDT      1.000000   1.000000
..          ...           ...        ...
79     NEXOUSDT      0.560000   0.560000
162    ELONUSDT      0.551102   0.551102
167    WAXPUSDT      0.529420   0.529420
178    EURTUSDT      0.514997   0.514997
149     SKLUSDT      0.500283   0.500283

[72 rows x 3 columns]

In [8]:
capratio = capratio.rename(columns={'symbol': 'Indicator'})
capratio
capratio.to_csv("capratio.csv")