In [12]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta


#Data Source(Pandas Data Reader)

In [13]:
whitelist = 'MOVR/USDT,AVAX/USDT,GALA/USDT, WAXP/USDT, HIVE/USDT, BAT/USDT, VIDT/USDT, MIR/USDT, IRIS/USDT, SHIB/USDT, MATIC/USDT, ZRX/USDT, BTC/USDT, ETH/USDT, AXS/USDT, SOL/USDT, MATIC/USDT, ADA/USDT, BNB/USDT, FIL/USDT, XRP/USDT, CVC/USDT, FTM/USDT, ICP/USDT, DOGE/USDT, XEC/USDT, IOTA/USDT, AVAX/USDT, DOT/USDT, LTC/USDT, EOS/USDT, IOST/USDT, STMX/USDT, FTT/USDT, TWT/USDT, ALICE/USDT, ATA/USDT, ETC/USDT, VET/USDT, SAND/USDT, LINK/USDT, THETA/USDT, SHIB/USDT, CHZ/USDT, LUNA/USDT, IOTX/USDT, TRX/USDT, TLM/USDT, BCH/USDT, REEF/USDT, CAKE/USDT, NEO/USDT, SLP/USDT, RVN/USDT, ATOM/USDT, SUSHI/USDT, ARDR/USDT, OMG/USDT, GRT/USDT, 1INCH/USDT, AAVE/USDT, C98/USDT, UNI/USDT, HBAR/USDT, CRV/USDT, DENT/USDT, MBOX/USDT, BTT/USDT, SRM/USDT, YFI/USDT, HOT/USDT, XLM/USDT, FIS/USDT, REQ/USDT, SXP/USDT, KSM/USDT, QNT/USDT, NEAR/USDT, COMP/USDT, QTUM/USDT, CHR/USDT, SC/USDT, XVS/USDT, ONT/USDT, COTI/USDT, NKN/USDT, RUNE/USDT, ANKR/USDT, MANA/USDT, CTXC/USDT, AR/USDT, RAY/USDT, BAKE/USDT, ARPA/USDT, XTZ/USDT, ZIL/USDT, ONG/USDT, ROSE/USDT, PNT/USDT, ALGO/USDT, MINA/USDT, WIN/USDT, AUDIO/USDT, STORJ/USDT, EPS/USDT, MDX/USDT, ZEC/USDT, ENJ/USDT, HIVE/USDT, TFUEL/USDT, WRX/USDT, SNX/USDT, SKL/USDT, LINA/USDT, DODO/USDT, UNFI/USDT, XEM/USDT, EGLD/USDT, ICX/USDT, WAVES/USDT, ONE/USDT, DASH/USDT, KAVA/USDT, SUPER/USDT, TKO/USDT, OGN/USDT, XMR/USDT, OCEAN/USDT, CELO/USDT, BAT/USDT, FUN/USDT, LRC/USDT, ALPHA/USDT, MASK/USDT, TRU/USDT, DNT/USDT, LIT/USDT, FET/USDT, GTC/USDT, CELR/USDT, DEXE/USDT, ZEN/USDT, WAXP/USDT, CTSI/USDT, HNT/USDT, YFII/USDT, BEL/USDT, ZRX/USDT, DEGO/USDT, RSR/USDT, COS/USDT, FLM/USDT, BAL/USDT, MFT/USDT, RLC/USDT, KNC/USDT, REN/USDT, INJ/USDT, FLOW/USDT, SFP/USDT, BAND/USDT, CTK/USDT, SUN/USDT, AKRO/USDT, XVG/USDT, NANO/USDT, STRAX/USDT, PUNDIX/USDT, TVK/USDT, MKR/USDT, CLV/USDT, TRB/USDT, ETHUP/USDT, KEEP/USDT, TCT/USDT, POND/USDT, LTO/USDT, ANT/USDT, TOMO/USDT, ACM/USDT, FIO/USDT, VITE/USDT, MBL/USDT, JST/USDT, MTL/USDT, UTK/USDT, BLZ/USDT, ORN/USDT, STPT/USDT, CFX/USDT, OM/USDT, PERP/USDT, MIR/USDT, STX/USDT, ERN/USDT, TUSD/USDT, PSG/USDT, NULS/USDT, OXT/USDT, REP/USDT, BNBUP/USDT, DATA/USDT, WAN/USDT, BURGER/USDT, RAMP/USDT, ATM/USDT, DGB/USDT, DIA/USDT, BEAM/USDT, UMA/USDT, ETHDOWN/USDT, CKB/USDT, TRIBE/USDT, FARM/USDT, BTCUP/USDT, BZRX/USDT, ALPACA/USDT, DOTUP/USDT, BTS/USDT, FOR/USDT, ADAUP/USDT, HARD/USDT, LSK/USDT, POLS/USDT, FORTH/USDT, TORN/USDT, VTHO/USDT, BTG/USDT, QUICK/USDT, FILUP/USDT, PAX/USDT, MITH/USDT, SUSHIUP/USDT, BTCDOWN/USDT, XRPDOWN/USDT, BNBDOWN/USDT, DUSK/USDT, XRPUP/USDT, WTC/USDT, DOCK/USDT, AUTO/USDT, BTCST/USDT, KLAY/USDT, WNXM/USDT, KEY/USDT, FILDOWN/USDT, NU/USDT, IRIS/USDT, KMD/USDT, TROY/USDT, WING/USDT, AION/USDT, PHA/USDT, SUSHIDOWN/USDT, EOSUP/USDT, LTCUP/USDT, GHST/USDT, PAXG/USDT, BNT/USDT, AVA/USDT, BADGER/USDT, PERL/USDT, COCOS/USDT, GXS/USDT, MDT/USDT, 1INCHUP/USDT, GTO/USDT, LINKUP/USDT, AAVEUP/USDT, FIRO/USDT, JUV/USDT, MLN/USDT, UNIUP/USDT, LPT/USDT, NMR/USDT, AAVEDOWN/USDT, 1INCHDOWN/USDT, ASR/USDT, OG/USDT, BAR/USDT, DREP/USDT, ADADOWN/USDT, BOND/USDT, DCR/USDT, DOTDOWN/USDT, GNO/USDT, NBS/USDT, SXPUP/USDT, EOSDOWN/USDT, YFIUP/USDT, RIF/USDT, LTCDOWN/USDT, XLMUP/USDT, YFIDOWN/USDT, LINKDOWN/USDT, TRXUP/USDT, BCHUP/USDT, XTZUP/USDT, SXPDOWN/USDT, UNIDOWN/USDT, XTZDOWN/USDT, BCHDOWN/USDT, TRXDOWN/USDT, XLMDOWN/USDT, SUSD/USDT'
#entrylist =[['ANKR/USDT',0.07684],['AVAX/USDT',57],['WAXP/USDT',0.3818],['REEF/USDT',0.01346],['LINK/USDT',14.15],['AR/USDT',30],['ATOM/USDT',23],['MIR/USDT',2.343],['ALGO/USDT',0.909],['ZRX/USDT',0.90],['XTZ/USDT',2.856],['KSM/USDT',163],]
#entrylist =[['ANKRUSDT',0.07684],['AVAXUSDT',57],['WAXPUSDT',0.3818],['REEFUSDT',0.01131],['LINKUSDT',14.15],['ARUSDT',30],['ATOMUSDT',23],['MIRUSDT',2.343],['ALGOUSDT',0.909],['ZRXUSDT',0.60],['XTZUSDT',2.856],['KSMUSDT',163],['NEARUSDT',14],['WINUSDT',0.0003138],['CELRUSDT',0.05063],['DENTUSDT',0.002459],['LRCUSDT',0.7047],['CRVUSDT',3.529],['IMXUSDT',2.709],['SCRTUSDT',5],['RENUSDT',0.2547],['SUSHIUSDT',4.522],['CAKEUSDT',11.24],['XLMUSDT',0.2109],['HNTUSDT',30],['OMGUSDT',4.5],['LINAUSDT',0.024],['MIRUSDT',2.343],['FLUXUSDT',1.523]]
entrylist =[['ANKRUSDT',0.07684],['AVAXUSDT',57],['WAXPUSDT',0.3174],['REEFUSDT',0.01131],['LINKUSDT',14.15],['ARUSDT',30],['ATOMUSDT',23],['MIRUSDT',2.343],['ALGOUSDT',0.909],['ZRXUSDT',0.60],['XTZUSDT',2.856],['KSMUSDT',150],['NEARUSDT',10.320],['WINUSDT',0.0003138],['DENTUSDT',0.002459],['LRCUSDT',0.7047],['CRVUSDT',3.529],['IMXUSDT',2.509],['SCRTUSDT',5],['RENUSDT',0.2547],['SUSHIUSDT',4.522],['CAKEUSDT',11.24],['XLMUSDT',0.2109],['HNTUSDT',30],['OMGUSDT',4.5],['LINAUSDT',0.024],['FLUXUSDT',1.523],['SRMUSDT',2.322],['VTHOUSDT',0.003938],['ANTUSDT',5.616],['RAYUSDT',3.54],['ROSEUSDT',0.30055],['MOVRUSDT',92.9],['TFUELUSDT',0.22],['GLMRUSDT',4.5],['COTIUSDT',0.2277],['ONEUSDT',0.17045],['VETUSDT',0.05138],['RUNEUSDT',3.709],['CELRUSDT',0.05063],['ONTUSDT',0.4652],['GALAUSDT',0.24794]]

startdate = '2020-01-01'
enddate = '2022-02-20'
interval = '4h'
easyband = pd.read_csv('easyband.csv')
#Columns=['Indicator','ALLTIME','CLOSERATIO','SMA100','SMA55']
easyband = pd.DataFrame(easyband,columns=['Indicator','ATH','CLOSERATIO','RED','ORANGE','GREEN'])
#easyband = easyband.loc[:,['Indicator','SMA21','GREENEASY']]
#EASY=float(easyband.loc[(easyband.Indicator=='BANDUSDT')].SMA100.values)
#print(easyband)
#EASY[0]
easyband

     Indicator         ATH  CLOSERATIO         RED      ORANGE       GREEN
0      RAYUSDT   17.800000    0.203460   13.995524    6.997762    3.498881
1      MDXUSDT    2.780000    0.151401    1.060571    0.530286    0.265143
2     PERPUSDT   26.210000    0.151209   21.112381   10.556190    5.278095
3     BONDUSDT   75.000000    0.150910   37.404762   18.702381    9.351190
4      CLVUSDT    2.485000    0.125684    1.582952    0.791476    0.395738
5     RAMPUSDT    1.300000    0.090927    0.394248    0.197124    0.098562
6     PONDUSDT    0.318000    0.070163    0.135508    0.067754    0.033877
7      LITUSDT   18.826400    0.061959    6.268381    3.134190    1.567095
8     DEGOUSDT   34.700000    0.059654   12.548571    6.274286    3.137143
9     DODOUSDT   10.000000    0.052295    1.966857    0.983429    0.491714
10     FETUSDT    1.198500    0.051004    1.095333    0.547667    0.273833
11    TROYUSDT    0.040128    0.048031    0.021786    0.010893    0.005446
12    REEFUSDT    0.300000    0.046241    0.038576    0.019288    0.009644
13     OGNUSDT    3.390000    0.045281    1.305933    0.652967    0.326483
14    BAKEUSDT    8.487000    0.039725    2.490952    1.245476    0.622738
15     KSMUSDT  625.000000    0.039374  562.133333  281.066667  140.533333
16     ICXUSDT    3.200000    0.036259    2.729048    1.364524    0.682262
17     FISUSDT    4.880000    0.031275    2.393543    1.196771    0.598386
18     SUNUSDT   54.560000    0.026811    0.047565    0.023782    0.011891
19     SRMUSDT   13.732000    0.022991    8.446190    4.223095    2.111548
20  BURGERUSDT   29.000000    0.021648    5.728000    2.864000    1.432000
21   ALPHAUSDT    2.943250    0.020976    1.391181    0.695590    0.347795
22    MASKUSDT   22.581000    0.018016   19.368952    9.684476    4.842238
23   AUDIOUSDT    4.990000    0.016910    3.221524    1.610762    0.805381
24    NANOUSDT   17.700000    0.013914    9.021524    4.510762    2.255381
25    LINAUSDT    1.000000    0.013436    0.081939    0.040970    0.020485
26   SUSHIUSDT   23.430000    0.012255   14.011714    7.005857    3.502929
27  BADGERUSDT   64.900000    0.010480   35.532381   17.766190    8.883095
28     PHAUSDT    1.245200    0.010164    0.936086    0.468043    0.234021
29     RSRUSDT    0.119000    0.009907    0.058257    0.029129    0.014564

In [14]:
capratio = pd.read_csv('capratio.csv')
capratio = pd.DataFrame(capratio,columns=['Indicator','supply_ratio','cap_ratio'])
capratio

     Indicator  supply_ratio  cap_ratio
0    STSOLUSDT      1.000002   1.000002
1   RENBTCUSDT      1.000000   1.000000
2     KP3RUSDT      1.000000   1.000000
3      UFOUSDT      1.000000   1.000000
4   PEOPLEUSDT      1.000000   1.000000
..         ...           ...        ...
58    WAXPUSDT      0.519529   0.519529
59    HEROUSDT      0.516376   0.516376
60     CVXUSDT      0.516310   0.516310
61    EURTUSDT      0.514997   0.514997
62   HEARTUSDT      0.000000   1.000000

[63 rows x 3 columns]

In [15]:
#easycap = pd.concat([easyband, capratio], axis=1, join="inner",keys='Indicator')
#easycap =pd.merge(left=easyband, right=capratio, left_on='Indicator', right_on='Indicator')
easycap =easyband.merge(capratio, how = 'left', on ='Indicator')
easycap = easycap.dropna(subset=['cap_ratio'])
easycap

,Indicator,ATH,CLOSERATIO,RED,ORANGE,GREEN,supply_ratio,cap_ratio
15,KSMUSDT,625.00,0.039374,562.133333,281.066667,140.533333,0.898010,0.898010
23,AUDIOUSDT,4.99,0.016910,3.221524,1.610762,0.805381,0.563721,0.563721
26,SUSHIUSDT,23.43,0.012255,14.011714,7.005857,3.502929,0.771157,0.771157

In [16]:
easycaplist = easycap['Indicator']
easycaplist

for item in easycaplist :
    
    x=item.replace('USDT','')
    print('$'+x)

$KSM
$AUDIO
$SUSHI

In [17]:
entries = pd.DataFrame(entrylist, columns =['Indicator', 'lowest_entry'],dtype = float) 
entries
entries.lowest_entry.astype(float)
indicator_list = entries['Indicator']
#indicator_list
#entries

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)

In [18]:
## Entries for coins with good cap ratio
entries = pd.read_csv('entries.csv')
entries = pd.DataFrame(entries,columns=['Indicator','lowest_entry'])
entriescap =pd.merge(left=entries, right=capratio, left_on='Indicator', right_on='Indicator')

entriescap

    Indicator  lowest_entry  supply_ratio  cap_ratio
0    ANKRUSDT      0.054150      0.816290   0.816290
1    WAXPUSDT      0.317400      0.519529   0.519529
2      ARUSDT     30.000000      0.759220   0.759220
3     ZRXUSDT      0.600000      0.847496   0.847496
4     KSMUSDT    150.000000      0.898010   0.898010
5     LRCUSDT      0.677000      0.906496   0.906496
6     RENUSDT      0.304700      1.000000   1.000000
7   SUSHIUSDT      3.500000      0.771157   0.771157
8     OMGUSDT      4.500000      1.000000   1.000000
9     ONEUSDT      0.131710      0.890739   0.890739
10   RUNEUSDT      3.709000      0.601510   0.601510
11   CELRUSDT      0.034063      0.564545   0.564545
12    GRTUSDT      0.390000      0.615723   0.615723
13    FTMUSDT      1.000000      0.800363   0.800363
14  AUDIOUSDT      1.000000      0.563721   0.563721