Generate the easy band in the first section based on live data 
compare it to the entries in the second part

In [63]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta


#Data Source(Pandas Data Reader)

In [64]:
whitelist = 'POWR/USDT, MDT/USDT,BLZ/USDT, CHR/USDT, ORN/USDT, VIDT/USDT, IRIS/USDT, SHIB/USDT, MATIC/USDT,ALGO/USDT, BTC/USDT, ETH/USDT, AXS/USDT, SOL/USDT, MATIC/USDT, ADA/USDT, BNB/USDT, FIL/USDT, XRP/USDT, CVC/USDT, FTM/USDT, ICP/USDT, DOGE/USDT, XEC/USDT, IOTA/USDT, AVAX/USDT, DOT/USDT, LTC/USDT, EOS/USDT, IOST/USDT, STMX/USDT, FTT/USDT, TWT/USDT, ALICE/USDT, ATA/USDT, ETC/USDT, VET/USDT, SAND/USDT, LINK/USDT, THETA/USDT, SHIB/USDT, CHZ/USDT, LUNA/USDT, IOTX/USDT, TRX/USDT, TLM/USDT, BCH/USDT, REEF/USDT, CAKE/USDT, NEO/USDT,RVN/USDT, ATOM/USDT, SUSHI/USDT, ARDR/USDT, OMG/USDT, GRT/USDT, 1INCH/USDT, AAVE/USDT, C98/USDT, UNI/USDT, HBAR/USDT, CRV/USDT, DENT/USDT, MBOX/USDT, BTT/USDT, SRM/USDT, YFI/USDT, HOT/USDT, XLM/USDT, FIS/USDT, REQ/USDT, SXP/USDT, KSM/USDT, QNT/USDT, NEAR/USDT, COMP/USDT, QTUM/USDT, CHR/USDT, SC/USDT, XVS/USDT, ONT/USDT, COTI/USDT, NKN/USDT, RUNE/USDT, ANKR/USDT, MANA/USDT, CTXC/USDT, AR/USDT, RAY/USDT, BAKE/USDT, ARPA/USDT, XTZ/USDT, ZIL/USDT, ONG/USDT, ROSE/USDT, PNT/USDT,MINA/USDT, WIN/USDT, AUDIO/USDT, STORJ/USDT, EPS/USDT, MDX/USDT, ZEC/USDT, ENJ/USDT, HIVE/USDT, TFUEL/USDT, WRX/USDT, SNX/USDT, SKL/USDT, LINA/USDT, DODO/USDT, UNFI/USDT, XEM/USDT, EGLD/USDT, ICX/USDT, WAVES/USDT, ONE/USDT, DASH/USDT, KAVA/USDT, SUPER/USDT, TKO/USDT, OGN/USDT, XMR/USDT, OCEAN/USDT, CELO/USDT, BAT/USDT, FUN/USDT, LRC/USDT, ALPHA/USDT, MASK/USDT, TRU/USDT, DNT/USDT, LIT/USDT, FET/USDT, GTC/USDT, CELR/USDT, DEXE/USDT, ZEN/USDT, WAXP/USDT, CTSI/USDT, HNT/USDT, YFII/USDT, BEL/USDT, ZRX/USDT, DEGO/USDT, RSR/USDT, COS/USDT, FLM/USDT, BAL/USDT, MFT/USDT, RLC/USDT, KNC/USDT, REN/USDT, INJ/USDT, FLOW/USDT, SFP/USDT, BAND/USDT, CTK/USDT, SUN/USDT, AKRO/USDT, XVG/USDT, NANO/USDT, STRAX/USDT, PUNDIX/USDT, TVK/USDT, MKR/USDT, CLV/USDT, TRB/USDT, ETHUP/USDT, KEEP/USDT, TCT/USDT, POND/USDT, LTO/USDT, ANT/USDT, TOMO/USDT, ACM/USDT, FIO/USDT, VITE/USDT, MBL/USDT, JST/USDT, MTL/USDT, UTK/USDT, BLZ/USDT, ORN/USDT, STPT/USDT, CFX/USDT, OM/USDT, PERP/USDT, MIR/USDT, STX/USDT, ERN/USDT, TUSD/USDT, PSG/USDT, NULS/USDT, OXT/USDT, REP/USDT, BNBUP/USDT, DATA/USDT, WAN/USDT, BURGER/USDT, RAMP/USDT, ATM/USDT, DGB/USDT, DIA/USDT, BEAM/USDT, UMA/USDT, ETHDOWN/USDT, CKB/USDT, TRIBE/USDT, FARM/USDT, BTCUP/USDT, BZRX/USDT, ALPACA/USDT, DOTUP/USDT, BTS/USDT, FOR/USDT, ADAUP/USDT, HARD/USDT, LSK/USDT, POLS/USDT, FORTH/USDT, TORN/USDT, VTHO/USDT, BTG/USDT, QUICK/USDT, FILUP/USDT, PAX/USDT, MITH/USDT, SUSHIUP/USDT, BTCDOWN/USDT, XRPDOWN/USDT, BNBDOWN/USDT, DUSK/USDT, XRPUP/USDT, WTC/USDT, DOCK/USDT, AUTO/USDT, BTCST/USDT, KLAY/USDT, WNXM/USDT, KEY/USDT, FILDOWN/USDT, NU/USDT, IRIS/USDT, KMD/USDT, TROY/USDT, WING/USDT, AION/USDT, PHA/USDT, SUSHIDOWN/USDT, EOSUP/USDT, LTCUP/USDT, GHST/USDT, PAXG/USDT, BNT/USDT, AVA/USDT, BADGER/USDT, PERL/USDT, COCOS/USDT, GXS/USDT, MDT/USDT, 1INCHUP/USDT, GTO/USDT, LINKUP/USDT, AAVEUP/USDT, FIRO/USDT, JUV/USDT, MLN/USDT, UNIUP/USDT, LPT/USDT, NMR/USDT, AAVEDOWN/USDT, 1INCHDOWN/USDT, ASR/USDT, OG/USDT, BAR/USDT, DREP/USDT, BOND/USDT, DCR/USDT, GNO/USDT, NBS/USDT, RIF/USDT'
#whitelist = 'LINK/USDT, DOT/USDT'
startdate = '2020-01-01'
enddate = '2022-03-22'
enddate = pd.to_datetime('today')

interval = '1w'

In [65]:
def FRSI(series, period=14):
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    return 100 - (100 / (1 + rs))


# calculating Stoch RSI (gives the same values as TradingView)
# https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI) 
def STRSIA(series, period=14, smoothK=3, smoothD=3):
    # Calculate RSI 
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    rsi = 100 - 100 / (1 + rs)

    # Calculate StochRSI 
    stochrsi  = (rsi - rsi.rolling(period).min()) / (rsi.rolling(period).max() - rsi.rolling(period).min())
    stochrsi_K = stochrsi.rolling(smoothK).mean()
    stochrsi_D = stochrsi_K.rolling(smoothD).mean()
    return stochrsi, stochrsi_K, stochrsi_D

#Calulate SMA 
def SMA(series,size):
    sma = series.rolling(size).mean()
    return sma
#Calculate SMA55

In [66]:
whitelist=whitelist.lstrip()
array = whitelist.split(",")
array
wl = []
bl = []
blacklist = ""
whitelist = ""
symbols =[]
for i in range(0 ,len(array)):
    if (array[i].find('DOWN') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])
    elif (array[i].find('UP') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])

    else:
        wl.append(str(array[i]).lstrip().replace("/",""))
        whitelist +=str(array[i]).lstrip()
        #print ("Doesn't contains given substring")
    

    
#symbols to be used to get the prices from binance url
symbols = np.array(wl)


## get the data 
import os

live = pd.to_datetime('today')
start = pd.to_datetime(startdate)
end = pd.to_datetime(enddate)

root_url = 'https://api.binance.com/api/v1/klines'
symbol = 'STEEMETH'
#interval = '1d'
url = root_url + '?symbol=' + symbol + '&interval=' + interval
print(url)


directory = 'BN-main'
table = []
   
      
        

for symbol in symbols:
        url = root_url + '?symbol=' + symbol + '&interval=' + interval
        data = json.loads(requests.get(url).text)
        dflive = pd.DataFrame(data ,columns =['open_time',
              'o', 'h', 'l', 'c', 'v',
              'close_time', 'qav', 'num_trades',
              'taker_base_vol', 'taker_quote_vol', 'ignore'])
        dflive.open_time = pd.to_datetime(dflive['open_time'],unit='ms')
        dflive=dflive.loc[(dflive.open_time>start)]
        
        dflive = dflive.astype ({'o': float ,'h':float,'l':float ,'c':float ,'v':float})
        dflive['SMA21'] = SMA(dflive['c'],21)
        dflive['SMA55'] = SMA(dflive['c'],55)
        dflive['SMA100'] = SMA(dflive['c'],100)
        
        
        
        #print(symbol)
        lastrow = dflive.iloc[-1]
        now = float(lastrow.c)
        SMA21 = float(lastrow.SMA21)
        SMA55 = float(lastrow.SMA55)
        SMA100 = float(lastrow.SMA100)
        
        
        alth = dflive.h.max()
        altl = dflive.l.min()
        
        
        ## past 1 month 
        past_month = end - relativedelta(months=1)
        
        back1Mdata = dflive.loc[(dflive.open_time> past_month)]
        omh = back1Mdata.h.max()
        oml = back1Mdata.l.min()
        ## past 2 month
        
        past_2month = end - relativedelta(months=2)
        back2Mdata = dflive.loc[(dflive.open_time> past_2month)]
        tmh = back2Mdata.h.max()
        tml = back2Mdata.l.min()
        ## past 3 month 
        
        past_3month = end - relativedelta(months=3)
        back3Mdata = dflive.loc[(dflive.open_time> past_3month)]
        thmh = back3Mdata.h.max()
        thml = back3Mdata.l.min()
        
 
        tuple =(symbol,alth,altl,now,omh,oml,tmh,tml,thmh,thml,SMA21,SMA55,SMA100,)
        table.append(tuple)
        del dflive
        #print("name is: ",array[0] ,alth,altl)
        #print("name is: ",symbol)
        

table[0]
AllTime = pd.DataFrame(table,columns=['Indicator','ATH','ATL','Current','OMH','OML','TMH','TML','THMH','THML','SMA21','SMA55','SMA100'])
AllTime.ATH=AllTime.ATH.astype(float)
AllTime.ATL=AllTime.ATL.astype(float)
AllTime.Current=AllTime.Current.astype(float)
AllTime.OMH=AllTime.OMH.astype(float)
AllTime.OML=AllTime.OML.astype(float)
AllTime.TMH=AllTime.TMH.astype(float)
AllTime.TML=AllTime.TML.astype(float)
AllTime.THMH=AllTime.THMH.astype(float)
AllTime.THML=AllTime.THML.astype(float)
AllTime.dtypes

AllTime['ALLTIME']=(AllTime['Current']/AllTime['ATH'])*100
AllTime['MONTH']=(AllTime['Current']/AllTime['OMH'])*100
AllTime['2MONTH']=(AllTime['Current']/AllTime['TMH'])*100
AllTime['3MONTH']=(AllTime['Current']/AllTime['THMH'])*100
AllTime['SMADIFF']= abs(AllTime['SMA21']- AllTime['SMA55'])
AllTime['SMARATIO']= (AllTime['SMA21']/AllTime['SMA55'])
AllTime['GREEN'] = (AllTime['SMA21'])/2
AllTime['GREEN15'] = (AllTime['SMA21'])/1.5
AllTime['ORANGE'] = (AllTime['SMA21'])
AllTime['RED'] = (AllTime['SMA21'])*2
AllTime['CLOSERATIO']= ((AllTime['Current']- AllTime['GREEN']))/AllTime['GREEN']



AllTime.sort_values(by=['ALLTIME'],ascending=True,inplace = True)
#AllTime.sort_values(by='ATH',ascending=False)
#AllTime.to_csv("alltimeHL.csv", mode="w")
#data.sort_values("Name", axis = 0, ascending = True,inplace = True, na_position ='last')

## Display the Data 
AllTime

https://api.binance.com/api/v1/klines?symbol=STEEMETH&interval=1w

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,...,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,GREEN,GREEN15,ORANGE,RED,CLOSERATIO
157,SUNUSDT,54.560,0.00854,0.00862,0.01709,0.00854,0.02039,0.00854,0.02039,0.00854,...,50.438853,42.275625,42.275625,3.554493,0.004280,0.007640,0.010187,0.015280,0.030560,0.128272
218,PAXUSDT,999.000,0.93880,0.99960,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000014,0.999986,0.499755,0.666340,0.999510,1.999019,1.000181
21,ICPUSDT,2831.020,7.76000,7.76000,17.85000,7.76000,23.52000,7.76000,23.52000,7.76000,...,43.473389,32.993197,32.993197,NaN,NaN,9.934048,13.245397,19.868095,39.736190,-0.218848
45,TLMUSDT,5.950,0.03080,0.03130,0.10480,0.03080,0.14830,0.03080,0.14830,0.03080,...,29.866412,21.105866,21.105866,0.086629,0.581783,0.060255,0.080340,0.120510,0.241019,-0.480539
224,BTCSTUSDT,1000.000,6.72000,6.97000,18.00000,6.72000,22.73000,6.72000,26.50000,6.72000,...,38.722222,30.664320,26.301887,8.651009,0.657180,8.291905,11.055873,16.583810,33.167619,-0.159421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,BTCUSDT,69000.000,3782.13000,29129.00000,42976.00000,29121.00000,48189.84000,29121.00000,48189.84000,29121.00000,...,67.779691,60.446351,60.446351,4169.092823,0.906743,20268.165952,27024.221270,40536.331905,81072.663810,0.437180
11,ETHUSDT,4868.000,86.00000,2136.00000,3180.00000,2136.00000,3580.34000,2136.00000,3580.34000,2136.00000,...,67.169811,59.659139,59.659139,193.854424,0.938418,1477.018333,1969.357778,2954.036667,5908.073333,0.446157
235,GHSTUSDT,3.400,1.50800,1.72600,1.95000,1.69000,2.19900,1.69000,2.19900,1.69000,...,88.512821,78.490223,78.490223,NaN,NaN,1.004929,1.339905,2.009857,4.019714,0.717535
167,KEEPUSDT,1.209,0.21130,0.62510,NaN,NaN,NaN,NaN,0.67000,0.58000,...,NaN,NaN,93.298507,NaN,NaN,0.322624,0.430165,0.645248,1.290495,0.937551
236,PAXGUSDT,2100.850,1687.57000,1839.00000,1999.00000,1832.00000,1999.00000,1832.00000,2076.00000,1832.00000,...,91.995998,91.995998,88.583815,48.636606,1.026380,946.166667,1261.555556,1892.333333,3784.666667,0.943632

In [67]:
#for i, j in zip(range(0,len(AllTime.index),70), range(70,len(AllTime.index),70)):
    #print(i,j)
    #print(AllTime.iloc[i:j,0:5])
    #if j+70 > len(AllTime.index):
        #print(j,len(AllTime.index))
        #print(AllTime.iloc[j:len(AllTime.index),0:5])
test=AllTime.loc[AllTime['Indicator']=='INJUSDT']
test

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,...,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,GREEN,GREEN15,ORANGE,RED,CLOSERATIO
152,INJUSDT,25.306,0.18,2.391,5.44,2.36,7.587,2.36,7.676,2.36,...,43.952206,31.514433,31.149036,3.095006,0.640102,2.752333,3.669778,5.504667,11.009333,-0.131283

In [68]:
#drop = AllTime.loc[(AllTime['RSI'] < 30)& (AllTime['STRSI'] < 0.1)]
#drop = AllTime.loc[(AllTime['SMARATIO'] <  1.05 ) &(AllTime['SMARATIO'] > 0.95)& (AllTime['ALLTIME'] <70) ]
#drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21'])]
drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21']/1.8)]
#drop = AllTime.loc[(AllTime['Current'] <= AllTime['GREEN15'])]

#drop = AllTime.loc[(AllTime['SMARATIO'] <  1 ) &(AllTime['SMARATIO'] > 0.95) & (AllTime['ALLTIME'] <70)]

#drop = AllTime.loc[(AllTime['MONTH'] < 80)&(AllTime[ '2MONTH'] < 70)&(AllTime['ALLTIME'] < 40)]
#drop = AllTime.loc[(AllTime['MONTH'] <70)&(AllTime['2MONTH'] > (AllTime['3MONTH']))]

sort = drop.sort_values(by=['CLOSERATIO'],ascending=False,inplace = True) 
#sort = drop.sort_values(by=['ALLTIME'],ascending=True,inplace = True) 

#drop = drop.loc[(drop['ALLTIME'] < drop['3MONTH'])]
display = drop[['Indicator','ATH','RED','ORANGE','GREEN','Current']]
#print(drop)
save = drop[['Indicator','ATH','CLOSERATIO','RED','ORANGE','GREEN','Current']]
save=save.drop_duplicates(subset='Indicator',keep='last')

#print(save)

save.to_csv("easyband.csv")
print(str(date.today()))
#print(date)
save.to_csv("easyband"+str(date.today())+".csv")

print("Low EASY Band")

display    
#print(display.iloc[0:60,0:14])
#print(display.iloc[60:110,])
#print(display.iloc[110:160,])

2022-05-11
Low EASY Band

/home/haytham/anaconda3/envs/ML20/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

      Indicator         ATH         RED      ORANGE      GREEN   Current
29     IOSTUSDT    0.091254    0.054103    0.027051   0.013526   0.01499
117    DASHUSDT  478.000000  217.104762  108.552381  54.276190  59.70000
162  PUNDIXUSDT    9.699000    1.665714    0.832857   0.416429   0.45800
226    WNXMUSDT  134.200000   71.885714   35.942857  17.971429  19.76000
184      OMUSDT    0.887600    0.194981    0.097490   0.048745   0.05350
..          ...         ...         ...         ...        ...       ...
116     ONEUSDT    0.380000    0.336603    0.168301   0.084151   0.03751
169    PONDUSDT    0.318000    0.077451    0.038726   0.019363   0.00821
186     MIRUSDT   14.550000    2.979048    1.489524   0.744762   0.27700
20      FTMUSDT    3.484200    3.257610    1.628805   0.814402   0.27160
42     LUNAUSDT  119.550000  149.279390   74.639695  37.319848   0.91360

[209 rows x 6 columns]

In [69]:
allbands = AllTime[['Indicator','RED','ORANGE','GREEN','Current']]
allbands.to_csv("allbands.csv")
allbands

     Indicator           RED        ORANGE         GREEN      Current
157    SUNUSDT      0.030560      0.015280      0.007640      0.00862
218    PAXUSDT      1.999019      0.999510      0.499755      0.99960
21     ICPUSDT     39.736190     19.868095      9.934048      7.76000
45     TLMUSDT      0.241019      0.120510      0.060255      0.03130
224  BTCSTUSDT     33.167619     16.583810      8.291905      6.97000
..         ...           ...           ...           ...          ...
10     BTCUSDT  81072.663810  40536.331905  20268.165952  29129.00000
11     ETHUSDT   5908.073333   2954.036667   1477.018333   2136.00000
235   GHSTUSDT      4.019714      2.009857      1.004929      1.72600
167   KEEPUSDT      1.290495      0.645248      0.322624      0.62510
236   PAXGUSDT   3784.666667   1892.333333    946.166667   1839.00000

[259 rows x 5 columns]

In [70]:
# red band 

## band to sell in down trends
redband = AllTime.loc[(AllTime['Current'] >= 2*AllTime['SMA21'])]
redband.to_csv("redband.csv")
redband

Empty DataFrame
Columns: [Indicator, ATH, ATL, Current, OMH, OML, TMH, TML, THMH, THML, SMA21, SMA55, SMA100, ALLTIME, MONTH, 2MONTH, 3MONTH, SMADIFF, SMARATIO, GREEN, GREEN15, ORANGE, RED, CLOSERATIO]
Index: []

[0 rows x 24 columns]

In [71]:
## band to sell in down trends
orangeband = AllTime.loc[(AllTime['Current'] >= AllTime['SMA21'])]
test = orangeband[['Indicator','GREEN','ORANGE','RED','Current']]
test.to_csv("orangeband.csv")
test

    Indicator      GREEN     ORANGE        RED   Current
218   PAXUSDT   0.499755   0.999510   1.999019   0.99960
242   GXSUSDT   0.853738   1.707476   3.414952   1.79230
189  TUSDUSDT   0.499986   0.999971   1.999943   1.00430
44    TRXUSDT   0.033287   0.066575   0.133150   0.06758
214  TORNUSDT  19.182619  38.365238  76.730476  39.13000

In [72]:
#easybandlist = display['Indicator']
#easybandlist

## GREEN 15

In [73]:
## GREEN 15
#display.Current.astype(float)

display = display.loc[:] 
display['ORatio'] = display['ORANGE']/display['Current'] 
#display = display.loc[display.Current < display.GREEN*1.05]
display = display.loc[display.Current < display.GREEN*.8]

#display = display.loc[display['CLOSERATIO']> 0.01]
display

#display

    Indicator       ATH         RED     ORANGE      GREEN  Current     ORatio
187   STXUSDT    3.2560    2.824952   1.412476   0.706238  0.56400   2.504390
252   BARUSDT   73.8000   14.040000   7.020000   3.510000  2.79000   2.516129
175  VITEUSDT    0.3490    0.105833   0.052917   0.026458  0.02096   2.524650
219  MITHUSDT    0.1990    0.076064   0.038032   0.019016  0.01500   2.535460
17    FILUSDT  430.0000   43.323810  21.661905  10.830952  8.50000   2.548459
..        ...       ...         ...        ...        ...      ...        ...
116   ONEUSDT    0.3800    0.336603   0.168301   0.084151  0.03751   4.486842
169  PONDUSDT    0.3180    0.077451   0.038726   0.019363  0.00821   4.716896
186   MIRUSDT   14.5500    2.979048   1.489524   0.744762  0.27700   5.377342
20    FTMUSDT    3.4842    3.257610   1.628805   0.814402  0.27160   5.997072
42   LUNAUSDT  119.5500  149.279390  74.639695  37.319848  0.91360  81.698440

[86 rows x 7 columns]

# entries

In [74]:

#entrylist =[['ANKRUSDT',0.07684],['AVAXUSDT',57],['WAXPUSDT',0.3818],['REEFUSDT',0.01131],['LINKUSDT',14.15],['ARUSDT',30],['ATOMUSDT',23],['MIRUSDT',2.343],['ALGOUSDT',0.909],['ZRXUSDT',0.60],['XTZUSDT',2.856],['KSMUSDT',163],['NEARUSDT',14],['WINUSDT',0.0003138],['CELRUSDT',0.05063],['DENTUSDT',0.002459],['LRCUSDT',0.7047],['CRVUSDT',3.529],['IMXUSDT',2.709],['SCRTUSDT',5],['RENUSDT',0.2547],['SUSHIUSDT',4.522],['CAKEUSDT',11.24],['XLMUSDT',0.2109],['HNTUSDT',30],['OMGUSDT',4.5],['LINAUSDT',0.024],['MIRUSDT',2.343],['FLUXUSDT',1.523]]
entrylist =[['ANKRUSDT',0.05415],['AVAXUSDT',57],['WAXPUSDT',0.2551],['REEFUSDT',0.00806],['LINKUSDT',12],['ARUSDT',23],['ATOMUSDT',18],['MIRUSDT',2.343],['ALGOUSDT',0.63],['ZRXUSDT',0.50],['XTZUSDT',2.856],['KSMUSDT',115],['NEARUSDT',10.320],['WINUSDT',0.00025],['DENTUSDT',0.002459],['LRCUSDT',0.677],['CRVUSDT',2.12],['IMXUSDT',1.30],['SCRTUSDT',3.7],['RENUSDT',0.3047],['SUSHIUSDT',3.5],['CAKEUSDT',11.24],['XLMUSDT',0.2109],['HNTUSDT',13.9],['OMGUSDT',4.5],['LINAUSDT',0.01759],['FLUXUSDT',1.523],['SRMUSDT',1.8],['VTHOUSDT',0.0031],['ANTUSDT',3.8],['RAYUSDT',2.5],['ROSEUSDT',0.18],['MOVRUSDT',33.7],['TFUELUSDT',0.16],['GLMRUSDT',2.311],['COTIUSDT',0.2],['ONEUSDT',0.08],['VETUSDT',0.05138],['RUNEUSDT',3.709],['CELRUSDT',0.034063],['ONTUSDT',0.4652],['GALAUSDT',0.17],['GRTUSDT',0.3164],['DOTUSDT',15],['ZILUSDT',0.04410],['FILUSDT',20],['SCUSDT',0.011],['MATICUSDT',1.4],['FTMUSDT',0.72],['BANDUSDT',3.6],['1INCHUSDT',1.3],['AUDIOUSDT',1.0],['IOTXUSDT','0.07109'],['CTSIUSDT','0.32'],['LUNAUSDT','13'],['SOLUSDT','35'],['MINAUSDT','1.96'],['BTCUSDT','39000'],['ADAUSDT','0.86'],['STORJUSDT','1.05'],['THETAUSDT','2.8'],['MANAUSDT','1.65'],['PAXGUSDT','1785'],['INJUSDT','5'],['PERPUSDT','2.22']]
exposurelist =[['ANKRUSDT',311],['AVAXUSDT',2850],['WAXPUSDT',527],['REEFUSDT',700],['LINKUSDT',6000],['ARUSDT',2450],['ATOMUSDT',1863],['MIRUSDT',85],['ALGOUSDT',3300],['ZRXUSDT',245],['XTZUSDT',1200],['KSMUSDT',7800],['NEARUSDT',1360],['WINUSDT',285],['DENTUSDT',385],['LRCUSDT',660],['CRVUSDT',323],['IMXUSDT',269],['SCRTUSDT',601],['RENUSDT',684],['SUSHIUSDT',2730],['CAKEUSDT',4000],['XLMUSDT',368],['HNTUSDT',1250],['OMGUSDT',765],['LINAUSDT',205],['FLUXUSDT',224],['SRMUSDT',587],['VTHOUSDT',413],['ANTUSDT',200],['RAYUSDT',100],['ROSEUSDT',634],['MOVRUSDT',500],['TFUELUSDT',344],['GLMRUSDT',400],['COTIUSDT',500],['ONEUSDT',1000],['VETUSDT',500],['RUNEUSDT',750],['CELRUSDT',500],['ONTUSDT',400],['GALAUSDT',650],['GRTUSDT',1700],['DOTUSDT',10000],['ZILUSDT',1000],['FILUSDT',2000],['SCUSDT',200],['MATICUSDT',8000],['FTMUSDT',2000],['BANDUSDT',750],['1INCHUSDT',1000],['AUDIOUSDT',700],['IOTXUSDT',500],['CTSIUSDT',325],['LUNAUSDT','4000'],['SOLUSDT','3000'],['DOTUSDT','10000']]
startdate = '2021-01-01'
entries = pd.DataFrame(entrylist, columns =['Indicator', 'lowest_entry'],dtype = float) 
entries
entries.lowest_entry.astype(float)

indicator_list = entries['Indicator']
#indicator_list
#entries
entries.to_csv("entries.csv")

exposure = pd.DataFrame(exposurelist, columns =['Indicator', 'exposure'],dtype = float) 
exposure
exposure.exposure.astype(float)
#indicator_list
#entries
exposure.to_csv("exposure.csv")

entries = entries.merge(exposure ,how="left",on="Indicator")
#entries

fixentries = entries.merge(display ,how='left',on=['Indicator'])
#fixentries = fixentries.merge(exposure,how='left',on=['Indicator'])
#fixentries
#entries1 = entries.merge(fixentries,how='left',on=['Indicator'])
fixentries = fixentries.dropna(axis=0,subset=['ATH'])
fixentries=fixentries.drop_duplicates(subset='Indicator',keep='last')
fixentries.lowest_entry.astype(float)
fixentries.Current.astype(float)


fixentries['DROP'] = ((fixentries.lowest_entry - fixentries.Current)/fixentries.lowest_entry)*100
fixentries.sort_values(by=['DROP'],ascending=False,inplace = True)
fixentries

/home/haytham/anaconda3/envs/ML20/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP
55,LUNAUSDT,13.000000,4000.0,119.5500,149.279390,74.639695,37.319848,0.91360,81.698440,92.972308
7,MIRUSDT,2.343000,85.0,14.5500,2.979048,1.489524,0.744762,0.27700,5.377342,88.177550
20,SUSHIUSDT,3.500000,2730.0,23.4300,8.400762,4.200381,2.100190,1.30900,3.208847,62.600000
49,FTMUSDT,0.720000,2000.0,3.4842,3.257610,1.628805,0.814402,0.27160,5.997072,62.277778
52,AUDIOUSDT,1.000000,700.0,4.9900,2.153333,1.076667,0.538333,0.39100,2.753623,60.900000
54,CTSIUSDT,0.320000,325.0,1.7500,0.851886,0.425943,0.212971,0.12890,3.304444,59.718750
29,ANTUSDT,3.800000,200.0,43.0000,11.453429,5.726714,2.863357,1.58100,3.622210,58.394737
53,IOTXUSDT,0.071090,500.0,0.2630,0.163707,0.081853,0.040927,0.02972,2.754150,58.193839
31,ROSEUSDT,0.180000,634.0,0.5980,0.551479,0.275740,0.137870,0.07595,3.630540,57.805556
46,FILUSDT,20.000000,2000.0,430.0000,43.323810,21.661905,10.830952,8.50000,2.548459,57.500000
2,WAXPUSDT,0.255100,527.0,0.9835,0.631362,0.315681,0.157840,0.10960,2.880301,57.036456
25,LINAUSDT,0.017590,205.0,1.0000,0.050252,0.025126,0.012563,0.00775,3.242089,55.940875
61,THETAUSDT,2.800000,NaN,15.8800,6.461143,3.230571,1.615286,1.25400,2.576213,55.214286
39,CELRUSDT,0.034063,500.0,0.1987,0.102853,0.051427,0.025713,0.01560,3.296581,54.202507
1,AVAXUSDT,57.000000,2850.0,147.0000,155.186667,77.593333,38.796667,26.22000,2.959319,54.000000
3,REEFUSDT,0.008060,700.0,0.3000,0.021303,0.010651,0.005326,0.00371,2.871005,53.970223
36,ONEUSDT,0.080000,1000.0,0.3800,0.336603,0.168301,0.084151,0.03751,4.486842,53.112500
62,MANAUSDT,1.650000,NaN,5.9000,4.929895,2.464948,1.232474,0.81220,3.034902,50.775758
6,ATOMUSDT,18.000000,1863.0,44.8000,55.006667,27.503333,13.751667,9.34000,2.944682,48.111111
30,RAYUSDT,2.500000,100.0,17.8000,6.990095,3.495048,1.747524,1.33600,2.616054,46.560000
15,LRCUSDT,0.677000,660.0,3.8500,2.080286,1.040143,0.520071,0.40520,2.566986,40.147710
23,HNTUSDT,13.900000,1250.0,59.2700,48.430476,24.215238,12.107619,8.66000,2.796217,37.697842
65,PERPUSDT,2.220000,NaN,26.2100,11.003810,5.501905,2.750952,1.43000,3.847486,35.585586

# Red Band

In [75]:
## over red entries 
overred = redband.merge(entries ,how="left",on="Indicator")
overed = overred.dropna(axis=0,subset=['RED'])
overred= overred[['Indicator','GREEN','ORANGE','RED','Current']]
overred

Empty DataFrame
Columns: [Indicator, GREEN, ORANGE, RED, Current]
Index: []

# Orange Band

In [76]:
## over orange entries 
overorange = entries.merge(orangeband ,how="left",on="Indicator")
overorange = overorange.dropna(axis=0,subset=['GREEN'])
overoranged= overorange[['Indicator','GREEN','ORANGE','RED','Current']]
overoranged

Empty DataFrame
Columns: [Indicator, GREEN, ORANGE, RED, Current]
Index: []

In [77]:
save = fixentries
save.to_csv("fixoneasy.csv")
save
del fixentries

In [78]:
#Gap is an acceptable area for rebounce and exit
orangedrop = save.loc[:]
orangedrop['GapOrange']= orangedrop['ORANGE']/orangedrop['Current']
orangedrop['GapRed']= orangedrop['RED']/orangedrop['Current']
orangedrop['GapATH']= orangedrop['ATH']/orangedrop['Current']
#orangedrop['GapAORT']= (orangedrop['GapATH']*orangedrop['GapOrange'])


orangedrop

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH
55,LUNAUSDT,13.000000,4000.0,119.5500,149.279390,74.639695,37.319848,0.91360,81.698440,92.972308,81.698440,163.396881,130.855954
7,MIRUSDT,2.343000,85.0,14.5500,2.979048,1.489524,0.744762,0.27700,5.377342,88.177550,5.377342,10.754685,52.527076
20,SUSHIUSDT,3.500000,2730.0,23.4300,8.400762,4.200381,2.100190,1.30900,3.208847,62.600000,3.208847,6.417694,17.899160
49,FTMUSDT,0.720000,2000.0,3.4842,3.257610,1.628805,0.814402,0.27160,5.997072,62.277778,5.997072,11.994144,12.828424
52,AUDIOUSDT,1.000000,700.0,4.9900,2.153333,1.076667,0.538333,0.39100,2.753623,60.900000,2.753623,5.507246,12.762148
54,CTSIUSDT,0.320000,325.0,1.7500,0.851886,0.425943,0.212971,0.12890,3.304444,59.718750,3.304444,6.608888,13.576416
29,ANTUSDT,3.800000,200.0,43.0000,11.453429,5.726714,2.863357,1.58100,3.622210,58.394737,3.622210,7.244420,27.197976
53,IOTXUSDT,0.071090,500.0,0.2630,0.163707,0.081853,0.040927,0.02972,2.754150,58.193839,2.754150,5.508300,8.849260
31,ROSEUSDT,0.180000,634.0,0.5980,0.551479,0.275740,0.137870,0.07595,3.630540,57.805556,3.630540,7.261080,7.873601
46,FILUSDT,20.000000,2000.0,430.0000,43.323810,21.661905,10.830952,8.50000,2.548459,57.500000,2.548459,5.096919,50.588235
2,WAXPUSDT,0.255100,527.0,0.9835,0.631362,0.315681,0.157840,0.10960,2.880301,57.036456,2.880301,5.760601,8.973540
25,LINAUSDT,0.017590,205.0,1.0000,0.050252,0.025126,0.012563,0.00775,3.242089,55.940875,3.242089,6.484178,129.032258
61,THETAUSDT,2.800000,NaN,15.8800,6.461143,3.230571,1.615286,1.25400,2.576213,55.214286,2.576213,5.152427,12.663477
39,CELRUSDT,0.034063,500.0,0.1987,0.102853,0.051427,0.025713,0.01560,3.296581,54.202507,3.296581,6.593162,12.737179
1,AVAXUSDT,57.000000,2850.0,147.0000,155.186667,77.593333,38.796667,26.22000,2.959319,54.000000,2.959319,5.918637,5.606407
3,REEFUSDT,0.008060,700.0,0.3000,0.021303,0.010651,0.005326,0.00371,2.871005,53.970223,2.871005,5.742010,80.862534
36,ONEUSDT,0.080000,1000.0,0.3800,0.336603,0.168301,0.084151,0.03751,4.486842,53.112500,4.486842,8.973683,10.130632
62,MANAUSDT,1.650000,NaN,5.9000,4.929895,2.464948,1.232474,0.81220,3.034902,50.775758,3.034902,6.069805,7.264221
6,ATOMUSDT,18.000000,1863.0,44.8000,55.006667,27.503333,13.751667,9.34000,2.944682,48.111111,2.944682,5.889365,4.796574
30,RAYUSDT,2.500000,100.0,17.8000,6.990095,3.495048,1.747524,1.33600,2.616054,46.560000,2.616054,5.232107,13.323353
15,LRCUSDT,0.677000,660.0,3.8500,2.080286,1.040143,0.520071,0.40520,2.566986,40.147710,2.566986,5.133973,9.501481
23,HNTUSDT,13.900000,1250.0,59.2700,48.430476,24.215238,12.107619,8.66000,2.796217,37.697842,2.796217,5.592434,6.844111
65,PERPUSDT,2.220000,NaN,26.2100,11.003810,5.501905,2.750952,1.43000,3.847486,35.585586,3.847486,7.694972,18.328671

In [79]:
# multiplying the gap with the value of the drop for a reasonable recovery
exposuredrop = orangedrop
exposuredrop['Total']= exposuredrop['exposure']*exposuredrop['DROP']*exposuredrop['GapOrange']
#exposuredrop['Total']= exposuredrop['DROP']*exposuredrop['GapOrange']*exposuredrop['CLOSERATIO']
#exposuredrop['Total']= exposuredrop['GapOrange']*exposuredrop['DROP']
#exposuredrop = exposuredrop.loc[exposuredrop['DROP']>0]

#exposuredrop.sort_values(by=['GapOrange'],ascending=False,inplace = True)
#exposuredrop.sort_values(by=['CLOSERATIO'],ascending=False,inplace = True)

exposuredrop

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total
55,LUNAUSDT,13.000000,4000.0,119.5500,149.279390,74.639695,37.319848,0.91360,81.698440,92.972308,81.698440,163.396881,130.855954,3.038277e+07
7,MIRUSDT,2.343000,85.0,14.5500,2.979048,1.489524,0.744762,0.27700,5.377342,88.177550,5.377342,10.754685,52.527076,4.030367e+04
20,SUSHIUSDT,3.500000,2730.0,23.4300,8.400762,4.200381,2.100190,1.30900,3.208847,62.600000,3.208847,6.417694,17.899160,5.483856e+05
49,FTMUSDT,0.720000,2000.0,3.4842,3.257610,1.628805,0.814402,0.27160,5.997072,62.277778,5.997072,11.994144,12.828424,7.469686e+05
52,AUDIOUSDT,1.000000,700.0,4.9900,2.153333,1.076667,0.538333,0.39100,2.753623,60.900000,2.753623,5.507246,12.762148,1.173870e+05
54,CTSIUSDT,0.320000,325.0,1.7500,0.851886,0.425943,0.212971,0.12890,3.304444,59.718750,3.304444,6.608888,13.576416,6.413462e+04
29,ANTUSDT,3.800000,200.0,43.0000,11.453429,5.726714,2.863357,1.58100,3.622210,58.394737,3.622210,7.244420,27.197976,4.230360e+04
53,IOTXUSDT,0.071090,500.0,0.2630,0.163707,0.081853,0.040927,0.02972,2.754150,58.193839,2.754150,5.508300,8.849260,8.013728e+04
31,ROSEUSDT,0.180000,634.0,0.5980,0.551479,0.275740,0.137870,0.07595,3.630540,57.805556,3.630540,7.261080,7.873601,1.330547e+05
46,FILUSDT,20.000000,2000.0,430.0000,43.323810,21.661905,10.830952,8.50000,2.548459,57.500000,2.548459,5.096919,50.588235,2.930728e+05
2,WAXPUSDT,0.255100,527.0,0.9835,0.631362,0.315681,0.157840,0.10960,2.880301,57.036456,2.880301,5.760601,8.973540,8.657669e+04
25,LINAUSDT,0.017590,205.0,1.0000,0.050252,0.025126,0.012563,0.00775,3.242089,55.940875,3.242089,6.484178,129.032258,3.717989e+04
61,THETAUSDT,2.800000,NaN,15.8800,6.461143,3.230571,1.615286,1.25400,2.576213,55.214286,2.576213,5.152427,12.663477,NaN
39,CELRUSDT,0.034063,500.0,0.1987,0.102853,0.051427,0.025713,0.01560,3.296581,54.202507,3.296581,6.593162,12.737179,8.934148e+04
1,AVAXUSDT,57.000000,2850.0,147.0000,155.186667,77.593333,38.796667,26.22000,2.959319,54.000000,2.959319,5.918637,5.606407,4.554391e+05
3,REEFUSDT,0.008060,700.0,0.3000,0.021303,0.010651,0.005326,0.00371,2.871005,53.970223,2.871005,5.742010,80.862534,1.084641e+05
36,ONEUSDT,0.080000,1000.0,0.3800,0.336603,0.168301,0.084151,0.03751,4.486842,53.112500,4.486842,8.973683,10.130632,2.383074e+05
62,MANAUSDT,1.650000,NaN,5.9000,4.929895,2.464948,1.232474,0.81220,3.034902,50.775758,3.034902,6.069805,7.264221,NaN
6,ATOMUSDT,18.000000,1863.0,44.8000,55.006667,27.503333,13.751667,9.34000,2.944682,48.111111,2.944682,5.889365,4.796574,2.639348e+05
30,RAYUSDT,2.500000,100.0,17.8000,6.990095,3.495048,1.747524,1.33600,2.616054,46.560000,2.616054,5.232107,13.323353,1.218035e+04
15,LRCUSDT,0.677000,660.0,3.8500,2.080286,1.040143,0.520071,0.40520,2.566986,40.147710,2.566986,5.133973,9.501481,6.801869e+04
23,HNTUSDT,13.900000,1250.0,59.2700,48.430476,24.215238,12.107619,8.66000,2.796217,37.697842,2.796217,5.592434,6.844111,1.317642e+05
65,PERPUSDT,2.220000,NaN,26.2100,11.003810,5.501905,2.750952,1.43000,3.847486,35.585586,3.847486,7.694972,18.328671,NaN

In [80]:
exposuredrop.to_csv("exposuredrop.csv")

In [81]:
# easy band and cap ratio
capratio = pd.read_csv('capratio.csv')
capratio = pd.DataFrame(capratio,columns=['Indicator','supply_ratio','cap_ratio'])
capratio

exposuredrop = exposuredrop.merge(capratio ,how='left',on=['Indicator'])
sort = exposuredrop.sort_values(by=['Total'],ascending=False,inplace = True)

exposuredrop

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total,supply_ratio,cap_ratio
0,LUNAUSDT,13.000000,4000.0,119.5500,149.279390,74.639695,37.319848,0.91360,81.698440,92.972308,81.698440,163.396881,130.855954,3.038277e+07,NaN,NaN
3,FTMUSDT,0.720000,2000.0,3.4842,3.257610,1.628805,0.814402,0.27160,5.997072,62.277778,5.997072,11.994144,12.828424,7.469686e+05,0.800363,0.800363
2,SUSHIUSDT,3.500000,2730.0,23.4300,8.400762,4.200381,2.100190,1.30900,3.208847,62.600000,3.208847,6.417694,17.899160,5.483856e+05,0.771157,0.771157
14,AVAXUSDT,57.000000,2850.0,147.0000,155.186667,77.593333,38.796667,26.22000,2.959319,54.000000,2.959319,5.918637,5.606407,4.554391e+05,NaN,NaN
9,FILUSDT,20.000000,2000.0,430.0000,43.323810,21.661905,10.830952,8.50000,2.548459,57.500000,2.548459,5.096919,50.588235,2.930728e+05,NaN,NaN
18,ATOMUSDT,18.000000,1863.0,44.8000,55.006667,27.503333,13.751667,9.34000,2.944682,48.111111,2.944682,5.889365,4.796574,2.639348e+05,NaN,NaN
16,ONEUSDT,0.080000,1000.0,0.3800,0.336603,0.168301,0.084151,0.03751,4.486842,53.112500,4.486842,8.973683,10.130632,2.383074e+05,0.906918,0.906918
8,ROSEUSDT,0.180000,634.0,0.5980,0.551479,0.275740,0.137870,0.07595,3.630540,57.805556,3.630540,7.261080,7.873601,1.330547e+05,NaN,NaN
21,HNTUSDT,13.900000,1250.0,59.2700,48.430476,24.215238,12.107619,8.66000,2.796217,37.697842,2.796217,5.592434,6.844111,1.317642e+05,NaN,NaN
4,AUDIOUSDT,1.000000,700.0,4.9900,2.153333,1.076667,0.538333,0.39100,2.753623,60.900000,2.753623,5.507246,12.762148,1.173870e+05,0.571528,0.571528
15,REEFUSDT,0.008060,700.0,0.3000,0.021303,0.010651,0.005326,0.00371,2.871005,53.970223,2.871005,5.742010,80.862534,1.084641e+05,NaN,NaN
13,CELRUSDT,0.034063,500.0,0.1987,0.102853,0.051427,0.025713,0.01560,3.296581,54.202507,3.296581,6.593162,12.737179,8.934148e+04,0.564545,0.564545
10,WAXPUSDT,0.255100,527.0,0.9835,0.631362,0.315681,0.157840,0.10960,2.880301,57.036456,2.880301,5.760601,8.973540,8.657669e+04,0.519301,0.519301
7,IOTXUSDT,0.071090,500.0,0.2630,0.163707,0.081853,0.040927,0.02972,2.754150,58.193839,2.754150,5.508300,8.849260,8.013728e+04,0.999427,0.999427
20,LRCUSDT,0.677000,660.0,3.8500,2.080286,1.040143,0.520071,0.40520,2.566986,40.147710,2.566986,5.133973,9.501481,6.801869e+04,0.906496,0.906496
5,CTSIUSDT,0.320000,325.0,1.7500,0.851886,0.425943,0.212971,0.12890,3.304444,59.718750,3.304444,6.608888,13.576416,6.413462e+04,NaN,NaN
6,ANTUSDT,3.800000,200.0,43.0000,11.453429,5.726714,2.863357,1.58100,3.622210,58.394737,3.622210,7.244420,27.197976,4.230360e+04,NaN,NaN
1,MIRUSDT,2.343000,85.0,14.5500,2.979048,1.489524,0.744762,0.27700,5.377342,88.177550,5.377342,10.754685,52.527076,4.030367e+04,NaN,NaN
11,LINAUSDT,0.017590,205.0,1.0000,0.050252,0.025126,0.012563,0.00775,3.242089,55.940875,3.242089,6.484178,129.032258,3.717989e+04,NaN,NaN
19,RAYUSDT,2.500000,100.0,17.8000,6.990095,3.495048,1.747524,1.33600,2.616054,46.560000,2.616054,5.232107,13.323353,1.218035e+04,NaN,NaN
12,THETAUSDT,2.800000,NaN,15.8800,6.461143,3.230571,1.615286,1.25400,2.576213,55.214286,2.576213,5.152427,12.663477,NaN,NaN,NaN
17,MANAUSDT,1.650000,NaN,5.9000,4.929895,2.464948,1.232474,0.81220,3.034902,50.775758,3.034902,6.069805,7.264221,NaN,0.690353,0.690353
22,PERPUSDT,2.220000,NaN,26.2100,11.003810,5.501905,2.750952,1.43000,3.847486,35.585586,3.847486,7.694972,18.328671,NaN,NaN,NaN

In [82]:
undergreen = exposuredrop.loc[exposuredrop['Current'] < exposuredrop['GREEN']]
undergreen

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total,supply_ratio,cap_ratio
0,LUNAUSDT,13.000000,4000.0,119.5500,149.279390,74.639695,37.319848,0.91360,81.698440,92.972308,81.698440,163.396881,130.855954,3.038277e+07,NaN,NaN
3,FTMUSDT,0.720000,2000.0,3.4842,3.257610,1.628805,0.814402,0.27160,5.997072,62.277778,5.997072,11.994144,12.828424,7.469686e+05,0.800363,0.800363
2,SUSHIUSDT,3.500000,2730.0,23.4300,8.400762,4.200381,2.100190,1.30900,3.208847,62.600000,3.208847,6.417694,17.899160,5.483856e+05,0.771157,0.771157
14,AVAXUSDT,57.000000,2850.0,147.0000,155.186667,77.593333,38.796667,26.22000,2.959319,54.000000,2.959319,5.918637,5.606407,4.554391e+05,NaN,NaN
9,FILUSDT,20.000000,2000.0,430.0000,43.323810,21.661905,10.830952,8.50000,2.548459,57.500000,2.548459,5.096919,50.588235,2.930728e+05,NaN,NaN
18,ATOMUSDT,18.000000,1863.0,44.8000,55.006667,27.503333,13.751667,9.34000,2.944682,48.111111,2.944682,5.889365,4.796574,2.639348e+05,NaN,NaN
16,ONEUSDT,0.080000,1000.0,0.3800,0.336603,0.168301,0.084151,0.03751,4.486842,53.112500,4.486842,8.973683,10.130632,2.383074e+05,0.906918,0.906918
8,ROSEUSDT,0.180000,634.0,0.5980,0.551479,0.275740,0.137870,0.07595,3.630540,57.805556,3.630540,7.261080,7.873601,1.330547e+05,NaN,NaN
21,HNTUSDT,13.900000,1250.0,59.2700,48.430476,24.215238,12.107619,8.66000,2.796217,37.697842,2.796217,5.592434,6.844111,1.317642e+05,NaN,NaN
4,AUDIOUSDT,1.000000,700.0,4.9900,2.153333,1.076667,0.538333,0.39100,2.753623,60.900000,2.753623,5.507246,12.762148,1.173870e+05,0.571528,0.571528
15,REEFUSDT,0.008060,700.0,0.3000,0.021303,0.010651,0.005326,0.00371,2.871005,53.970223,2.871005,5.742010,80.862534,1.084641e+05,NaN,NaN
13,CELRUSDT,0.034063,500.0,0.1987,0.102853,0.051427,0.025713,0.01560,3.296581,54.202507,3.296581,6.593162,12.737179,8.934148e+04,0.564545,0.564545
10,WAXPUSDT,0.255100,527.0,0.9835,0.631362,0.315681,0.157840,0.10960,2.880301,57.036456,2.880301,5.760601,8.973540,8.657669e+04,0.519301,0.519301
7,IOTXUSDT,0.071090,500.0,0.2630,0.163707,0.081853,0.040927,0.02972,2.754150,58.193839,2.754150,5.508300,8.849260,8.013728e+04,0.999427,0.999427
20,LRCUSDT,0.677000,660.0,3.8500,2.080286,1.040143,0.520071,0.40520,2.566986,40.147710,2.566986,5.133973,9.501481,6.801869e+04,0.906496,0.906496
5,CTSIUSDT,0.320000,325.0,1.7500,0.851886,0.425943,0.212971,0.12890,3.304444,59.718750,3.304444,6.608888,13.576416,6.413462e+04,NaN,NaN
6,ANTUSDT,3.800000,200.0,43.0000,11.453429,5.726714,2.863357,1.58100,3.622210,58.394737,3.622210,7.244420,27.197976,4.230360e+04,NaN,NaN
1,MIRUSDT,2.343000,85.0,14.5500,2.979048,1.489524,0.744762,0.27700,5.377342,88.177550,5.377342,10.754685,52.527076,4.030367e+04,NaN,NaN
11,LINAUSDT,0.017590,205.0,1.0000,0.050252,0.025126,0.012563,0.00775,3.242089,55.940875,3.242089,6.484178,129.032258,3.717989e+04,NaN,NaN
19,RAYUSDT,2.500000,100.0,17.8000,6.990095,3.495048,1.747524,1.33600,2.616054,46.560000,2.616054,5.232107,13.323353,1.218035e+04,NaN,NaN
12,THETAUSDT,2.800000,NaN,15.8800,6.461143,3.230571,1.615286,1.25400,2.576213,55.214286,2.576213,5.152427,12.663477,NaN,NaN,NaN
17,MANAUSDT,1.650000,NaN,5.9000,4.929895,2.464948,1.232474,0.81220,3.034902,50.775758,3.034902,6.069805,7.264221,NaN,0.690353,0.690353
22,PERPUSDT,2.220000,NaN,26.2100,11.003810,5.501905,2.750952,1.43000,3.847486,35.585586,3.847486,7.694972,18.328671,NaN,NaN,NaN