Generate the easy band in the first section based on live data 
compare it to the entries in the second part

In [176]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta


#Data Source(Pandas Data Reader)

In [177]:
whitelist = 'CHR/USDT, ORN/USDT, VIDT/USDT, IRIS/USDT, SHIB/USDT, MATIC/USDT,ALGO/USDT, BTC/USDT, ETH/USDT, AXS/USDT, SOL/USDT, MATIC/USDT, ADA/USDT, BNB/USDT, FIL/USDT, XRP/USDT, CVC/USDT, FTM/USDT, ICP/USDT, DOGE/USDT, XEC/USDT, IOTA/USDT, AVAX/USDT, DOT/USDT, LTC/USDT, EOS/USDT, IOST/USDT, STMX/USDT, FTT/USDT, TWT/USDT, ALICE/USDT, ATA/USDT, ETC/USDT, VET/USDT, SAND/USDT, LINK/USDT, THETA/USDT, SHIB/USDT, CHZ/USDT, LUNA/USDT, IOTX/USDT, TRX/USDT, TLM/USDT, BCH/USDT, REEF/USDT, CAKE/USDT, NEO/USDT,RVN/USDT, ATOM/USDT, SUSHI/USDT, ARDR/USDT, OMG/USDT, GRT/USDT, 1INCH/USDT, AAVE/USDT, C98/USDT, UNI/USDT, HBAR/USDT, CRV/USDT, DENT/USDT, MBOX/USDT, BTT/USDT, SRM/USDT, YFI/USDT, HOT/USDT, XLM/USDT, FIS/USDT, REQ/USDT, SXP/USDT, KSM/USDT, QNT/USDT, NEAR/USDT, COMP/USDT, QTUM/USDT, CHR/USDT, SC/USDT, XVS/USDT, ONT/USDT, COTI/USDT, NKN/USDT, RUNE/USDT, ANKR/USDT, MANA/USDT, CTXC/USDT, AR/USDT, RAY/USDT, BAKE/USDT, ARPA/USDT, XTZ/USDT, ZIL/USDT, ONG/USDT, ROSE/USDT, PNT/USDT, ALGO/USDT, MINA/USDT, WIN/USDT, AUDIO/USDT, STORJ/USDT, EPS/USDT, MDX/USDT, ZEC/USDT, ENJ/USDT, HIVE/USDT, TFUEL/USDT, WRX/USDT, SNX/USDT, SKL/USDT, LINA/USDT, DODO/USDT, UNFI/USDT, XEM/USDT, EGLD/USDT, ICX/USDT, WAVES/USDT, ONE/USDT, DASH/USDT, KAVA/USDT, SUPER/USDT, TKO/USDT, OGN/USDT, XMR/USDT, OCEAN/USDT, CELO/USDT, BAT/USDT, FUN/USDT, LRC/USDT, ALPHA/USDT, MASK/USDT, TRU/USDT, DNT/USDT, LIT/USDT, FET/USDT, GTC/USDT, CELR/USDT, DEXE/USDT, ZEN/USDT, WAXP/USDT, CTSI/USDT, HNT/USDT, YFII/USDT, BEL/USDT, ZRX/USDT, DEGO/USDT, RSR/USDT, COS/USDT, FLM/USDT, BAL/USDT, MFT/USDT, RLC/USDT, KNC/USDT, REN/USDT, INJ/USDT, FLOW/USDT, SFP/USDT, BAND/USDT, CTK/USDT, SUN/USDT, AKRO/USDT, XVG/USDT, NANO/USDT, STRAX/USDT, PUNDIX/USDT, TVK/USDT, MKR/USDT, CLV/USDT, TRB/USDT, ETHUP/USDT, KEEP/USDT, TCT/USDT, POND/USDT, LTO/USDT, ANT/USDT, TOMO/USDT, ACM/USDT, FIO/USDT, VITE/USDT, MBL/USDT, JST/USDT, MTL/USDT, UTK/USDT, BLZ/USDT, ORN/USDT, STPT/USDT, CFX/USDT, OM/USDT, PERP/USDT, MIR/USDT, STX/USDT, ERN/USDT, TUSD/USDT, PSG/USDT, NULS/USDT, OXT/USDT, REP/USDT, BNBUP/USDT, DATA/USDT, WAN/USDT, BURGER/USDT, RAMP/USDT, ATM/USDT, DGB/USDT, DIA/USDT, BEAM/USDT, UMA/USDT, ETHDOWN/USDT, CKB/USDT, TRIBE/USDT, FARM/USDT, BTCUP/USDT, BZRX/USDT, ALPACA/USDT, DOTUP/USDT, BTS/USDT, FOR/USDT, ADAUP/USDT, HARD/USDT, LSK/USDT, POLS/USDT, FORTH/USDT, TORN/USDT, VTHO/USDT, BTG/USDT, QUICK/USDT, FILUP/USDT, PAX/USDT, MITH/USDT, SUSHIUP/USDT, BTCDOWN/USDT, XRPDOWN/USDT, BNBDOWN/USDT, DUSK/USDT, XRPUP/USDT, WTC/USDT, DOCK/USDT, AUTO/USDT, BTCST/USDT, KLAY/USDT, WNXM/USDT, KEY/USDT, FILDOWN/USDT, NU/USDT, IRIS/USDT, KMD/USDT, TROY/USDT, WING/USDT, AION/USDT, PHA/USDT, SUSHIDOWN/USDT, EOSUP/USDT, LTCUP/USDT, GHST/USDT, PAXG/USDT, BNT/USDT, AVA/USDT, BADGER/USDT, PERL/USDT, COCOS/USDT, GXS/USDT, MDT/USDT, 1INCHUP/USDT, GTO/USDT, LINKUP/USDT, AAVEUP/USDT, FIRO/USDT, JUV/USDT, MLN/USDT, UNIUP/USDT, LPT/USDT, NMR/USDT, AAVEDOWN/USDT, 1INCHDOWN/USDT, ASR/USDT, OG/USDT, BAR/USDT, DREP/USDT, BOND/USDT, DCR/USDT, GNO/USDT, NBS/USDT, RIF/USDT, NEAR/USDT'
#whitelist = 'LINK/USDT, DOT/USDT'
startdate = '2020-01-01'
enddate = '2022-02-25'
interval = '1w'

In [178]:
def FRSI(series, period=14):
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    return 100 - (100 / (1 + rs))


# calculating Stoch RSI (gives the same values as TradingView)
# https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI) 
def STRSIA(series, period=14, smoothK=3, smoothD=3):
    # Calculate RSI 
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    rsi = 100 - 100 / (1 + rs)

    # Calculate StochRSI 
    stochrsi  = (rsi - rsi.rolling(period).min()) / (rsi.rolling(period).max() - rsi.rolling(period).min())
    stochrsi_K = stochrsi.rolling(smoothK).mean()
    stochrsi_D = stochrsi_K.rolling(smoothD).mean()
    return stochrsi, stochrsi_K, stochrsi_D

#Calulate SMA 
def SMA(series,size):
    sma = series.rolling(size).mean()
    return sma
#Calculate SMA55

In [179]:
whitelist=whitelist.lstrip()
array = whitelist.split(",")
array
wl = []
bl = []
blacklist = ""
whitelist = ""
symbols =[]
for i in range(0 ,len(array)):
    if (array[i].find('DOWN') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])
    elif (array[i].find('UP') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])

    else:
        wl.append(str(array[i]).lstrip().replace("/",""))
        whitelist +=str(array[i]).lstrip()
        #print ("Doesn't contains given substring")
    

    
#symbols to be used to get the prices from binance url
symbols = np.array(wl)


## get the data 
import os

live = pd.to_datetime('today')
start = pd.to_datetime(startdate)
end = pd.to_datetime(enddate)

root_url = 'https://api.binance.com/api/v1/klines'
symbol = 'STEEMETH'
#interval = '1d'
url = root_url + '?symbol=' + symbol + '&interval=' + interval
print(url)


directory = 'BN-main'
table = []
   
      
        

for symbol in symbols:
        url = root_url + '?symbol=' + symbol + '&interval=' + interval
        data = json.loads(requests.get(url).text)
        dflive = pd.DataFrame(data ,columns =['open_time',
              'o', 'h', 'l', 'c', 'v',
              'close_time', 'qav', 'num_trades',
              'taker_base_vol', 'taker_quote_vol', 'ignore'])
        dflive.open_time = pd.to_datetime(dflive['open_time'],unit='ms')
        dflive=dflive.loc[(dflive.open_time>start)]
        
        dflive = dflive.astype ({'o': float ,'h':float,'l':float ,'c':float ,'v':float})
        dflive['SMA21'] = SMA(dflive['c'],21)
        dflive['SMA55'] = SMA(dflive['c'],55)
        dflive['SMA100'] = SMA(dflive['c'],100)
        
        
        
        
        lastrow = dflive.iloc[-1]
        now = float(lastrow.c)
        SMA21 = float(lastrow.SMA21)
        SMA55 = float(lastrow.SMA55)
        SMA100 = float(lastrow.SMA100)
        
        
        alth = dflive.h.max()
        altl = dflive.l.min()
        
        
        ## past 1 month 
        past_month = end - relativedelta(months=1)
        
        back1Mdata = dflive.loc[(dflive.open_time> past_month)]
        omh = back1Mdata.h.max()
        oml = back1Mdata.l.min()
        ## past 2 month
        
        past_2month = end - relativedelta(months=2)
        back2Mdata = dflive.loc[(dflive.open_time> past_2month)]
        tmh = back2Mdata.h.max()
        tml = back2Mdata.l.min()
        ## past 3 month 
        
        past_3month = end - relativedelta(months=3)
        back3Mdata = dflive.loc[(dflive.open_time> past_3month)]
        thmh = back3Mdata.h.max()
        thml = back3Mdata.l.min()
        
 
        tuple =(symbol,alth,altl,now,omh,oml,tmh,tml,thmh,thml,SMA21,SMA55,SMA100,)
        table.append(tuple)
        del dflive
        #print("name is: ",array[0] ,alth,altl)
        #print("name is: ",symbol)
        

table[0]
AllTime = pd.DataFrame(table,columns=['Indicator','ATH','ATL','Current','OMH','OML','TMH','TML','THMH','THML','SMA21','SMA55','SMA100'])
AllTime.ATH=AllTime.ATH.astype(float)
AllTime.ATL=AllTime.ATL.astype(float)
AllTime.Current=AllTime.Current.astype(float)
AllTime.OMH=AllTime.OMH.astype(float)
AllTime.OML=AllTime.OML.astype(float)
AllTime.TMH=AllTime.TMH.astype(float)
AllTime.TML=AllTime.TML.astype(float)
AllTime.THMH=AllTime.THMH.astype(float)
AllTime.THML=AllTime.THML.astype(float)
AllTime.dtypes

AllTime['ALLTIME']=(AllTime['Current']/AllTime['ATH'])*100
AllTime['MONTH']=(AllTime['Current']/AllTime['OMH'])*100
AllTime['2MONTH']=(AllTime['Current']/AllTime['TMH'])*100
AllTime['3MONTH']=(AllTime['Current']/AllTime['THMH'])*100
AllTime['SMADIFF']= abs(AllTime['SMA21']- AllTime['SMA55'])
AllTime['SMARATIO']= (AllTime['SMA21']/AllTime['SMA55'])
AllTime['GREEN'] = (AllTime['SMA21'])/2
AllTime['ORANGE'] = (AllTime['SMA21'])
AllTime['RED'] = (AllTime['SMA21'])*2
AllTime['CLOSERATIO']= (abs(AllTime['Current']- AllTime['GREEN']))/AllTime['GREEN']



AllTime.sort_values(by=['ALLTIME'],ascending=True,inplace = True)
#AllTime.sort_values(by='ATH',ascending=False)
#AllTime.to_csv("alltimeHL.csv", mode="w")
#data.sort_values("Name", axis = 0, ascending = True,inplace = True, na_position ='last')

## Display the Data 
AllTime

https://api.binance.com/api/v1/klines?symbol=STEEMETH&interval=1w

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,...,ALLTIME,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,GREEN,ORANGE,RED,CLOSERATIO
155,SUNUSDT,54.56,0.01066,0.01239,0.0194,0.01066,0.02548,0.01066,0.03197,0.01066,...,0.022709,63.865979,48.626374,38.755083,8.697345,0.002728,0.011895,0.023791,0.047582,0.041572
216,PAXUSDT,999.00,0.93880,0.99960,NaN,NaN,NaN,NaN,NaN,NaN,...,0.100060,NaN,NaN,NaN,0.000014,0.999986,0.499755,0.999510,1.999019,1.000181
18,ICPUSDT,2831.02,14.68000,20.19000,24.6800,14.68000,38.02000,14.68000,42.96000,14.68000,...,0.713171,81.807131,53.103630,46.997207,NaN,NaN,15.759048,31.518095,63.036190,0.281169
98,EPSUSDT,22.50,0.14180,0.17630,0.2950,0.14180,0.35760,0.14180,0.49500,0.14180,...,0.783556,59.762712,49.300895,35.616162,NaN,NaN,0.163560,0.327119,0.654238,0.077895
222,BTCSTUSDT,1000.00,8.00000,18.98000,22.6300,12.21000,26.29000,12.21000,34.89000,12.21000,...,1.898000,83.870968,72.194751,54.399541,25.788413,0.497832,12.782857,25.565714,51.131429,0.484801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,ETHUSDT,4868.00,86.00000,2929.86000,3283.6600,2300.00000,4127.46000,2159.00000,4778.75000,2159.00000,...,60.186113,89.225437,70.984576,61.310175,633.484580,1.212572,1806.792381,3613.584762,7227.169524,0.621581
7,BTCUSDT,69000.00,3782.13000,43375.13000,45821.0000,34322.28000,52088.00000,32917.17000,59176.99000,32917.17000,...,62.862507,94.662120,83.272788,73.297290,1717.992234,1.036098,24655.268571,49310.537143,98621.074286,0.759264
48,ATOMUSDT,44.80,1.06100,31.93000,33.1900,21.40000,44.70000,21.40000,44.70000,20.18000,...,71.272321,96.203676,71.431767,71.431767,6.429517,1.261479,15.509286,31.018571,62.037143,1.058767
39,LUNAUSDT,103.60,0.27330,89.24000,95.3800,43.44000,103.60000,43.44000,103.60000,43.44000,...,86.138996,93.562592,86.138996,86.138996,27.948704,1.812319,31.177381,62.354762,124.709524,1.862332
234,PAXGUSDT,2100.85,1687.57000,1893.00000,2076.0000,1790.00000,2076.00000,1772.00000,2076.00000,1759.00000,...,90.106386,91.184971,91.184971,91.184971,18.084173,1.009983,914.761905,1829.523810,3659.047619,1.069391

In [180]:
#drop = AllTime.loc[(AllTime['RSI'] < 30)& (AllTime['STRSI'] < 0.1)]
#drop = AllTime.loc[(AllTime['SMARATIO'] <  1.05 ) &(AllTime['SMARATIO'] > 0.95)& (AllTime['ALLTIME'] <70) ]
#drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21'])]
drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21']/1.9)]

#drop = AllTime.loc[(AllTime['SMARATIO'] <  1 ) &(AllTime['SMARATIO'] > 0.95) & (AllTime['ALLTIME'] <70)]

#drop = AllTime.loc[(AllTime['MONTH'] < 80)&(AllTime[ '2MONTH'] < 70)&(AllTime['ALLTIME'] < 40)]
#drop = AllTime.loc[(AllTime['MONTH'] <70)&(AllTime['2MONTH'] > (AllTime['3MONTH']))]

sort = drop.sort_values(by=['CLOSERATIO'],ascending=False,inplace = True) 
#sort = drop.sort_values(by=['ALLTIME'],ascending=True,inplace = True) 

#drop = drop.loc[(drop['ALLTIME'] < drop['3MONTH'])]
display = drop[['Indicator','ATH','CLOSERATIO','RED','ORANGE','GREEN','Current']]
#print(drop)
save = drop[['Indicator','ATH','CLOSERATIO','RED','ORANGE','GREEN','Current']]
print(save)
print("Low EASY Band")
print(display.iloc[0:60,0:14])
print(display.iloc[60:110,])
print(display.iloc[110:160,])

      Indicator        ATH  CLOSERATIO         RED      ORANGE       GREEN  \
85      RAYUSDT   17.80000    0.199815   13.996762    6.998381    3.499190
252    BONDUSDT   75.00000    0.170827   37.386667   18.693333    9.346667
99      MDXUSDT    2.78000    0.144011    1.060762    0.530381    0.265190
183    PERPUSDT   26.21000    0.140074   21.118095   10.559048    5.279524
163     CLVUSDT    2.48500    0.133109    1.582667    0.791333    0.395667
195    RAMPUSDT    1.30000    0.111782    0.394048    0.197024    0.098512
167    PONDUSDT    0.31800    0.084601    0.135460    0.067730    0.033865
108    DODOUSDT   10.00000    0.058259    1.966571    0.983286    0.491643
69      KSMUSDT  625.00000    0.055372  561.914286  280.957143  140.478571
129     LITUSDT   18.82640    0.051356    6.270000    3.135000    1.567500
132    CELRUSDT    0.19870    0.045483    0.167578    0.083789    0.041895
141    DEGOUSDT   34.70000    0.044079   12.553333    6.276667    3.138333
155     SUNUSDT   54.56000    0.041572    0.047582    0.023791    0.011895
112     ICXUSDT    3.20000    0.040547    2.729333    1.364667    0.682333
96    AUDIOUSDT    4.99000    0.037497    3.223143    1.611571    0.805786
194  BURGERUSDT   29.00000    0.035270    5.729905    2.864952    1.432476
66      FISUSDT    4.88000    0.035024    2.393762    1.196881    0.598440
118     OGNUSDT    3.39000    0.033610    1.306305    0.653152    0.326576
86     BAKEUSDT    8.48700    0.027176    2.491714    1.245857    0.622929
107    LINAUSDT    1.00000    0.018200    0.081949    0.040974    0.020487
158    NANOUSDT   17.70000    0.013914    9.021524    4.510762    2.255381
237  BADGERUSDT   64.90000    0.012679   35.530476   17.765238    8.882619
49    SUSHIUSDT   23.43000    0.011983   14.020000    7.010000    3.505000
232     PHAUSDT    1.24520    0.011832    0.936124    0.468062    0.234031
62      SRMUSDT   13.73200    0.006808    8.449524    4.224762    2.112381
125   ALPHAUSDT    2.94325    0.002880    1.391990    0.695995    0.347998
126    MASKUSDT   22.58100    0.002143   19.378476    9.689238    4.844619
142     RSRUSDT    0.11900    0.001863    0.058269    0.029134    0.014567

       Current
85     2.80000
252    7.75000
99     0.22700
183    4.54000
163    0.34300
195    0.08750
167    0.03100
108    0.46300
69   132.70000
129    1.48700
132    0.04380
141    3.00000
155    0.01239
112    0.71000
96     0.83600
194    1.48300
66     0.61940
118    0.31560
86     0.60600
107    0.02086
158    2.22400
237    8.77000
49     3.54700
232    0.23680
62     2.09800
125    0.34900
126    4.85500
142    0.01454
Low EASY Band
      Indicator        ATH  CLOSERATIO         RED      ORANGE       GREEN  \
85      RAYUSDT   17.80000    0.199815   13.996762    6.998381    3.499190
252    BONDUSDT   75.00000    0.170827   37.386667   18.693333    9.346667
99      MDXUSDT    2.78000    0.144011    1.060762    0.530381    0.265190
183    PERPUSDT   26.21000    0.140074   21.118095   10.559048    5.279524
163     CLVUSDT    2.48500    0.133109    1.582667    0.791333    0.395667
195    RAMPUSDT    1.30000    0.111782    0.394048    0.197024    0.098512
167    PONDUSDT    0.31800    0.084601    0.135460    0.067730    0.033865
108    DODOUSDT   10.00000    0.058259    1.966571    0.983286    0.491643
69      KSMUSDT  625.00000    0.055372  561.914286  280.957143  140.478571
129     LITUSDT   18.82640    0.051356    6.270000    3.135000    1.567500
132    CELRUSDT    0.19870    0.045483    0.167578    0.083789    0.041895
141    DEGOUSDT   34.70000    0.044079   12.553333    6.276667    3.138333
155     SUNUSDT   54.56000    0.041572    0.047582    0.023791    0.011895
112     ICXUSDT    3.20000    0.040547    2.729333    1.364667    0.682333
96    AUDIOUSDT    4.99000    0.037497    3.223143    1.611571    0.805786
194  BURGERUSDT   29.00000    0.035270    5.729905    2.864952    1.432476
66      FISUSDT    4.88000    0.035024    2.393762    1.196881    0.598440
118     OGNUSDT    3.39000    0.033610    1.306305    0.653152    0.326576
86     BAKEUSDT    8.48700    0.027176    2.491714    1.245857    0.622929
107    LINAUSDT    1.00000    0.018200    0.081949    0.040974    0.020487
158    NANOUSDT   17.70000    0.013914    9.021524    4.510762    2.255381
237  BADGERUSDT   64.90000    0.012679   35.530476   17.765238    8.882619
49    SUSHIUSDT   23.43000    0.011983   14.020000    7.010000    3.505000
232     PHAUSDT    1.24520    0.011832    0.936124    0.468062    0.234031
62      SRMUSDT   13.73200    0.006808    8.449524    4.224762    2.112381
125   ALPHAUSDT    2.94325    0.002880    1.391990    0.695995    0.347998
126    MASKUSDT   22.58100    0.002143   19.378476    9.689238    4.844619
142     RSRUSDT    0.11900    0.001863    0.058269    0.029134    0.014567

       Current
85     2.80000
252    7.75000
99     0.22700
183    4.54000
163    0.34300
195    0.08750
167    0.03100
108    0.46300
69   132.70000
129    1.48700
132    0.04380
141    3.00000
155    0.01239
112    0.71000
96     0.83600
194    1.48300
66     0.61940
118    0.31560
86     0.60600
107    0.02086
158    2.22400
237    8.77000
49     3.54700
232    0.23680
62     2.09800
125    0.34900
126    4.85500
142    0.01454
Empty DataFrame
Columns: [Indicator, ATH, CLOSERATIO, RED, ORANGE, GREEN, Current]
Index: []
Empty DataFrame
Columns: [Indicator, ATH, CLOSERATIO, RED, ORANGE, GREEN, Current]
Index: []

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [181]:
## band to sell in down trends
orangeband = AllTime.loc[(AllTime['Current'] >= AllTime['SMA21'])]
orangeband

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,...,ALLTIME,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,GREEN,ORANGE,RED,CLOSERATIO
216,PAXUSDT,999.0000,0.9388,0.9996,NaN,NaN,NaN,NaN,NaN,NaN,...,0.100060,NaN,NaN,NaN,0.000014,0.999986,0.499755,0.999510,1.999019,1.000181
240,GXSUSDT,5.7031,0.2656,1.5374,2.0127,1.2010,3.0381,1.1338,5.7031,0.5733,...,26.957269,76.384956,50.603996,26.957269,0.423809,1.430667,0.703943,1.407886,2.815771,1.183984
187,TUSDUSDT,3.0000,0.4654,0.9997,0.9998,0.9993,1.0003,0.9993,1.0003,0.9910,...,33.323333,99.989998,99.940018,99.940018,0.000037,1.000037,0.499798,0.999595,1.999190,1.000210
148,KNCUSDT,4.3600,0.6830,2.4410,2.5700,1.5160,2.5700,1.1840,2.5700,1.1690,...,55.986239,94.980545,94.980545,94.980545,0.235397,0.879708,0.860738,1.721476,3.442952,1.835938
22,AVAXUSDT,147.0000,0.8500,87.8900,98.7700,64.2500,120.9600,52.9500,127.4100,52.9500,...,59.789116,88.984509,72.660384,68.982027,34.944915,1.670368,43.536429,87.072857,174.145714,1.018769
48,ATOMUSDT,44.8000,1.0610,31.9300,33.1900,21.4000,44.7000,21.4000,44.7000,20.1800,...,71.272321,96.203676,71.431767,71.431767,6.429517,1.261479,15.509286,31.018571,62.037143,1.058767
39,LUNAUSDT,103.6000,0.2733,89.2400,95.3800,43.4400,103.6000,43.4400,103.6000,43.4400,...,86.138996,93.562592,86.138996,86.138996,27.948704,1.812319,31.177381,62.354762,124.709524,1.862332
234,PAXGUSDT,2100.8500,1687.5700,1893.0000,2076.0000,1790.0000,2076.0000,1772.0000,2076.0000,1759.0000,...,90.106386,91.184971,91.184971,91.184971,18.084173,1.009983,914.761905,1829.523810,3659.047619,1.069391

In [182]:
#easybandlist = display['Indicator']
#easybandlist

In [183]:
save.to_csv("easyband.csv")
print(date.today)
save.to_csv("easyband"+str(date.today())+".csv")
save

<built-in method today of type object at 0x1079404d8>

,Indicator,ATH,CLOSERATIO,RED,ORANGE,GREEN,Current
85,RAYUSDT,17.80000,0.199815,13.996762,6.998381,3.499190,2.80000
252,BONDUSDT,75.00000,0.170827,37.386667,18.693333,9.346667,7.75000
99,MDXUSDT,2.78000,0.144011,1.060762,0.530381,0.265190,0.22700
183,PERPUSDT,26.21000,0.140074,21.118095,10.559048,5.279524,4.54000
163,CLVUSDT,2.48500,0.133109,1.582667,0.791333,0.395667,0.34300
195,RAMPUSDT,1.30000,0.111782,0.394048,0.197024,0.098512,0.08750
167,PONDUSDT,0.31800,0.084601,0.135460,0.067730,0.033865,0.03100
108,DODOUSDT,10.00000,0.058259,1.966571,0.983286,0.491643,0.46300
69,KSMUSDT,625.00000,0.055372,561.914286,280.957143,140.478571,132.70000
129,LITUSDT,18.82640,0.051356,6.270000,3.135000,1.567500,1.48700
132,CELRUSDT,0.19870,0.045483,0.167578,0.083789,0.041895,0.04380
141,DEGOUSDT,34.70000,0.044079,12.553333,6.276667,3.138333,3.00000
155,SUNUSDT,54.56000,0.041572,0.047582,0.023791,0.011895,0.01239
112,ICXUSDT,3.20000,0.040547,2.729333,1.364667,0.682333,0.71000
96,AUDIOUSDT,4.99000,0.037497,3.223143,1.611571,0.805786,0.83600
194,BURGERUSDT,29.00000,0.035270,5.729905,2.864952,1.432476,1.48300
66,FISUSDT,4.88000,0.035024,2.393762,1.196881,0.598440,0.61940
118,OGNUSDT,3.39000,0.033610,1.306305,0.653152,0.326576,0.31560
86,BAKEUSDT,8.48700,0.027176,2.491714,1.245857,0.622929,0.60600
107,LINAUSDT,1.00000,0.018200,0.081949,0.040974,0.020487,0.02086
158,NANOUSDT,17.70000,0.013914,9.021524,4.510762,2.255381,2.22400
237,BADGERUSDT,64.90000,0.012679,35.530476,17.765238,8.882619,8.77000
49,SUSHIUSDT,23.43000,0.011983,14.020000,7.010000,3.505000,3.54700
232,PHAUSDT,1.24520,0.011832,0.936124,0.468062,0.234031,0.23680
62,SRMUSDT,13.73200,0.006808,8.449524,4.224762,2.112381,2.09800
125,ALPHAUSDT,2.94325,0.002880,1.391990,0.695995,0.347998,0.34900
126,MASKUSDT,22.58100,0.002143,19.378476,9.689238,4.844619,4.85500
142,RSRUSDT,0.11900,0.001863,0.058269,0.029134,0.014567,0.01454

In [184]:
#display.Current.astype(float)

display = display.loc[:] 
display['ORatio'] = display['ORANGE']/display['Current'] 
display = display.loc[display['ORatio']> 2]
display

#display

,Indicator,ATH,CLOSERATIO,RED,ORANGE,GREEN,Current,ORatio
85,RAYUSDT,17.8000,0.199815,13.996762,6.998381,3.499190,2.80000,2.499422
252,BONDUSDT,75.0000,0.170827,37.386667,18.693333,9.346667,7.75000,2.412043
99,MDXUSDT,2.7800,0.144011,1.060762,0.530381,0.265190,0.22700,2.336480
183,PERPUSDT,26.2100,0.140074,21.118095,10.559048,5.279524,4.54000,2.325781
163,CLVUSDT,2.4850,0.133109,1.582667,0.791333,0.395667,0.34300,2.307094
195,RAMPUSDT,1.3000,0.111782,0.394048,0.197024,0.098512,0.08750,2.251701
167,PONDUSDT,0.3180,0.084601,0.135460,0.067730,0.033865,0.03100,2.184839
108,DODOUSDT,10.0000,0.058259,1.966571,0.983286,0.491643,0.46300,2.123727
69,KSMUSDT,625.0000,0.055372,561.914286,280.957143,140.478571,132.70000,2.117235
129,LITUSDT,18.8264,0.051356,6.270000,3.135000,1.567500,1.48700,2.108272
141,DEGOUSDT,34.7000,0.044079,12.553333,6.276667,3.138333,3.00000,2.092222
118,OGNUSDT,3.3900,0.033610,1.306305,0.653152,0.326576,0.31560,2.069558
86,BAKEUSDT,8.4870,0.027176,2.491714,1.245857,0.622929,0.60600,2.055870
158,NANOUSDT,17.7000,0.013914,9.021524,4.510762,2.255381,2.22400,2.028220
237,BADGERUSDT,64.9000,0.012679,35.530476,17.765238,8.882619,8.77000,2.025683
62,SRMUSDT,13.7320,0.006808,8.449524,4.224762,2.112381,2.09800,2.013709
142,RSRUSDT,0.1190,0.001863,0.058269,0.029134,0.014567,0.01454,2.003734

# entries

In [185]:

entrylist =[['ANKRUSDT',0.05415],['AVAXUSDT',57],['WAXPUSDT',0.3174],['REEFUSDT',0.00930],['LINKUSDT',14.15],['ARUSDT',30],['ATOMUSDT',23],['MIRUSDT',2.343],['ALGOUSDT',0.909],['ZRXUSDT',0.60],['XTZUSDT',2.856],['KSMUSDT',150],['NEARUSDT',10.320],['WINUSDT',0.0003138],['DENTUSDT',0.002459],['LRCUSDT',0.677],['CRVUSDT',3.529],['IMXUSDT',2.509],['SCRTUSDT',5],['RENUSDT',0.3047],['SUSHIUSDT',3.5],['CAKEUSDT',11.24],['XLMUSDT',0.2109],['HNTUSDT',30],['OMGUSDT',4.5],['LINAUSDT',0.01759],['FLUXUSDT',1.523],['SRMUSDT',2.322],['VTHOUSDT',0.003938],['ANTUSDT',5.616],['RAYUSDT',3.54],['ROSEUSDT',0.25055],['MOVRUSDT',92.9],['TFUELUSDT',0.22],['GLMRUSDT',4.5],['COTIUSDT',0.2277],['ONEUSDT',0.13171],['VETUSDT',0.05138],['RUNEUSDT',3.709],['CELRUSDT',0.034063],['ONTUSDT',0.4652],['GALAUSDT',0.24794],['GRTUSDT',0.39],['DOTUSDT',16.31],['ZILUSDT',0.04410],['FILUSDT',20],['SCUSDT',0.015],['MATICUSDT',1.4],['FTMUSDT',1.0],['BANDUSDT',3.6],['1INCHUSDT',1.6],['AUDIOUSDT',1.0],['BAKEUSDT',0.615]]
exposurelist =[['ANKRUSDT',311],['AVAXUSDT',2850],['WAXPUSDT',527],['REEFUSDT',603],['LINKUSDT',6000],['ARUSDT',2450],['ATOMUSDT',1863],['MIRUSDT',85],['ALGOUSDT',2735],['ZRXUSDT',245],['XTZUSDT',1200],['KSMUSDT',7800],['NEARUSDT',1360],['WINUSDT',285],['DENTUSDT',385],['LRCUSDT',660],['CRVUSDT',323],['IMXUSDT',269],['SCRTUSDT',601],['RENUSDT',684],['SUSHIUSDT',2730],['CAKEUSDT',4000],['XLMUSDT',368],['HNTUSDT',999],['OMGUSDT',765],['LINAUSDT',205],['FLUXUSDT',224],['SRMUSDT',587],['VTHOUSDT',313],['ANTUSDT',200],['RAYUSDT',100],['ROSEUSDT',634],['MOVRUSDT',500],['TFUELUSDT',244],['GLMRUSDT',400],['COTIUSDT',500],['ONEUSDT',1000],['VETUSDT',500],['RUNEUSDT',750],['CELRUSDT',500],['ONTUSDT',400],['GALAUSDT',650],['GRTUSDT',1700],['DOTUSDT',10000],['ZILUSDT',1000],['FILUSDT',2000],['SCUSDT',200],['MATICUSDT',8000],['FTMUSDT',2000],['BANDUSDT',750],['1INCHUSDT',1000],['AUDIOUSDT',700]]
startdate = '2021-01-01'
entries = pd.DataFrame(entrylist, columns =['Indicator', 'lowest_entry'],dtype = float) 
entries
entries.lowest_entry.astype(float)

indicator_list = entries['Indicator']
#indicator_list
#entries
entries.to_csv("entries.csv")

exposure = pd.DataFrame(exposurelist, columns =['Indicator', 'exposure'],dtype = float) 
exposure
exposure.exposure.astype(float)
#indicator_list
#entries
entries.to_csv("exposure.csv")

entries = entries.merge(exposure ,how="left",on="Indicator")
#entries

fixentries = entries.merge(display ,how='left',on=['Indicator'])
#fixentries = fixentries.merge(exposure,how='left',on=['Indicator'])
#fixentries
#entries1 = entries.merge(fixentries,how='left',on=['Indicator'])
fixentries = fixentries.dropna(axis=0,subset=['ATH'])
fixentries=fixentries.drop_duplicates(subset='Indicator',keep='last')
fixentries.lowest_entry.astype(float)
fixentries.Current.astype(float)


fixentries['DROP'] = ((fixentries.lowest_entry - fixentries.Current)/fixentries.lowest_entry)*100
fixentries.sort_values(by=['DROP'],ascending=False,inplace = True)
fixentries

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)

,Indicator,lowest_entry,exposure,ATH,CLOSERATIO,RED,ORANGE,GREEN,Current,ORatio,DROP
30,RAYUSDT,3.540,100.0,17.800,0.199815,13.996762,6.998381,3.499190,2.800,2.499422,20.903955
11,KSMUSDT,150.000,7800.0,625.000,0.055372,561.914286,280.957143,140.478571,132.700,2.117235,11.533333
27,SRMUSDT,2.322,587.0,13.732,0.006808,8.449524,4.224762,2.112381,2.098,2.013709,9.646856
52,BAKEUSDT,0.615,NaN,8.487,0.027176,2.491714,1.245857,0.622929,0.606,2.055870,1.463415

In [186]:
save = fixentries
save.to_csv("fixoneasy.csv")
save
del fixentries

In [187]:
#Gap is an acceptable area for rebounce and exit
orangedrop = save.loc[:]
orangedrop['GapOrange']= orangedrop['ORANGE']/orangedrop['Current']
orangedrop['GapRed']= orangedrop['RED']/orangedrop['Current']
orangedrop['GapATH']= orangedrop['ATH']/orangedrop['Current']
#orangedrop['GapAORT']= (orangedrop['GapATH']*orangedrop['GapOrange'])


orangedrop

,Indicator,lowest_entry,exposure,ATH,CLOSERATIO,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH
30,RAYUSDT,3.540,100.0,17.800,0.199815,13.996762,6.998381,3.499190,2.800,2.499422,20.903955,2.499422,4.998844,6.357143
11,KSMUSDT,150.000,7800.0,625.000,0.055372,561.914286,280.957143,140.478571,132.700,2.117235,11.533333,2.117235,4.234471,4.709872
27,SRMUSDT,2.322,587.0,13.732,0.006808,8.449524,4.224762,2.112381,2.098,2.013709,9.646856,2.013709,4.027418,6.545281
52,BAKEUSDT,0.615,NaN,8.487,0.027176,2.491714,1.245857,0.622929,0.606,2.055870,1.463415,2.055870,4.111740,14.004950

In [188]:
# multiplying the gap with the value of the drop for a reasonable recovery
exposuredrop = orangedrop
exposuredrop['Total']= exposuredrop['exposure']*exposuredrop['DROP']*exposuredrop['GapOrange']
#exposuredrop['Total']= exposuredrop['DROP']*exposuredrop['GapOrange']*exposuredrop['CLOSERATIO']
#exposuredrop['Total']= exposuredrop['GapOrange']*exposuredrop['DROP']
exposuredrop = exposuredrop.loc[exposuredrop['DROP']>0]

exposuredrop.sort_values(by=['GapOrange'],ascending=False,inplace = True)
exposuredrop

,Indicator,lowest_entry,exposure,ATH,CLOSERATIO,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total
30,RAYUSDT,3.540,100.0,17.800,0.199815,13.996762,6.998381,3.499190,2.800,2.499422,20.903955,2.499422,4.998844,6.357143,5224.779968
11,KSMUSDT,150.000,7800.0,625.000,0.055372,561.914286,280.957143,140.478571,132.700,2.117235,11.533333,2.117235,4.234471,4.709872,190466.500161
52,BAKEUSDT,0.615,NaN,8.487,0.027176,2.491714,1.245857,0.622929,0.606,2.055870,1.463415,2.055870,4.111740,14.004950,NaN
27,SRMUSDT,2.322,587.0,13.732,0.006808,8.449524,4.224762,2.112381,2.098,2.013709,9.646856,2.013709,4.027418,6.545281,11403.040288

In [189]:
exposuredrop.to_csv("exposuredrop.csv")

In [190]:
# easy band and cap ratio
capratio = pd.read_csv('capratio.csv')
capratio = pd.DataFrame(capratio,columns=['Indicator','supply_ratio','cap_ratio'])
capratio

exposuredrop = exposuredrop.merge(capratio ,how='left',on=['Indicator'])
sort = exposuredrop.sort_values(by=['cap_ratio'],ascending=False,inplace = True)

exposuredrop

,Indicator,lowest_entry,exposure,ATH,CLOSERATIO,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total,supply_ratio,cap_ratio
1,KSMUSDT,150.000,7800.0,625.000,0.055372,561.914286,280.957143,140.478571,132.700,2.117235,11.533333,2.117235,4.234471,4.709872,190466.500161,0.89801,0.89801
0,RAYUSDT,3.540,100.0,17.800,0.199815,13.996762,6.998381,3.499190,2.800,2.499422,20.903955,2.499422,4.998844,6.357143,5224.779968,NaN,NaN
2,BAKEUSDT,0.615,NaN,8.487,0.027176,2.491714,1.245857,0.622929,0.606,2.055870,1.463415,2.055870,4.111740,14.004950,NaN,NaN,NaN
3,SRMUSDT,2.322,587.0,13.732,0.006808,8.449524,4.224762,2.112381,2.098,2.013709,9.646856,2.013709,4.027418,6.545281,11403.040288,NaN,NaN