In [39]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta


#Data Source(Pandas Data Reader)

In [40]:
whitelist = 'VIDT/USDT, IRIS/USDT, SHIB/USDT,  LINK/USDT, MATIC/USDT, ZRX/USDT,  ALGO/USDT, BTC/USDT, ETH/USDT, AXS/USDT, SOL/USDT, MATIC/USDT, ADA/USDT, BNB/USDT, FIL/USDT, XRP/USDT, CVC/USDT, FTM/USDT, ICP/USDT, DOGE/USDT, XEC/USDT, IOTA/USDT, AVAX/USDT, DOT/USDT, LTC/USDT, EOS/USDT, IOST/USDT, STMX/USDT, FTT/USDT, TWT/USDT, ALICE/USDT, ATA/USDT, ETC/USDT, VET/USDT, SAND/USDT, LINK/USDT, THETA/USDT, SHIB/USDT, CHZ/USDT, LUNA/USDT, IOTX/USDT, TRX/USDT, TLM/USDT, BCH/USDT, REEF/USDT, CAKE/USDT, NEO/USDT,RVN/USDT, ATOM/USDT, SUSHI/USDT, ARDR/USDT, OMG/USDT, GRT/USDT, 1INCH/USDT, AAVE/USDT, C98/USDT, UNI/USDT, HBAR/USDT, CRV/USDT, DENT/USDT, MBOX/USDT, BTT/USDT, SRM/USDT, YFI/USDT, HOT/USDT, XLM/USDT, FIS/USDT, REQ/USDT, SXP/USDT, KSM/USDT, QNT/USDT, NEAR/USDT, COMP/USDT, QTUM/USDT, CHR/USDT, SC/USDT, XVS/USDT, ONT/USDT, COTI/USDT, NKN/USDT, RUNE/USDT, ANKR/USDT, MANA/USDT, CTXC/USDT, AR/USDT, RAY/USDT, BAKE/USDT, ARPA/USDT, XTZ/USDT, ZIL/USDT, ONG/USDT, ROSE/USDT, PNT/USDT, ALGO/USDT, MINA/USDT, WIN/USDT, AUDIO/USDT, STORJ/USDT, EPS/USDT, MDX/USDT, ZEC/USDT, ENJ/USDT, HIVE/USDT, TFUEL/USDT, WRX/USDT, SNX/USDT, SKL/USDT, LINA/USDT, DODO/USDT, UNFI/USDT, XEM/USDT, EGLD/USDT, ICX/USDT, WAVES/USDT, ONE/USDT, DASH/USDT, KAVA/USDT, SUPER/USDT, TKO/USDT, OGN/USDT, XMR/USDT, OCEAN/USDT, CELO/USDT, BAT/USDT, FUN/USDT, LRC/USDT, ALPHA/USDT, MASK/USDT, TRU/USDT, DNT/USDT, LIT/USDT, FET/USDT, GTC/USDT, CELR/USDT, DEXE/USDT, ZEN/USDT, WAXP/USDT, CTSI/USDT, HNT/USDT, YFII/USDT, BEL/USDT, ZRX/USDT, DEGO/USDT, RSR/USDT, COS/USDT, FLM/USDT, BAL/USDT, MFT/USDT, RLC/USDT, KNC/USDT, REN/USDT, INJ/USDT, FLOW/USDT, SFP/USDT, BAND/USDT, CTK/USDT, SUN/USDT, AKRO/USDT, XVG/USDT, NANO/USDT, STRAX/USDT, PUNDIX/USDT, TVK/USDT, MKR/USDT, CLV/USDT, TRB/USDT, ETHUP/USDT, KEEP/USDT, TCT/USDT, POND/USDT, LTO/USDT, ANT/USDT, TOMO/USDT, ACM/USDT, FIO/USDT, VITE/USDT, MBL/USDT, JST/USDT, MTL/USDT, UTK/USDT, BLZ/USDT, ORN/USDT, STPT/USDT, CFX/USDT, OM/USDT, PERP/USDT, MIR/USDT, STX/USDT, ERN/USDT, TUSD/USDT, PSG/USDT, NULS/USDT, OXT/USDT, REP/USDT, BNBUP/USDT, DATA/USDT, WAN/USDT, BURGER/USDT, RAMP/USDT, ATM/USDT, DGB/USDT, DIA/USDT, BEAM/USDT, UMA/USDT, ETHDOWN/USDT, CKB/USDT, TRIBE/USDT, FARM/USDT, BTCUP/USDT, BZRX/USDT, ALPACA/USDT, DOTUP/USDT, BTS/USDT, FOR/USDT, ADAUP/USDT, HARD/USDT, LSK/USDT, POLS/USDT, FORTH/USDT, TORN/USDT, VTHO/USDT, BTG/USDT, QUICK/USDT, FILUP/USDT, PAX/USDT, MITH/USDT, SUSHIUP/USDT, BTCDOWN/USDT, XRPDOWN/USDT, BNBDOWN/USDT, DUSK/USDT, XRPUP/USDT, WTC/USDT, DOCK/USDT, AUTO/USDT, BTCST/USDT, KLAY/USDT, WNXM/USDT, KEY/USDT, FILDOWN/USDT, NU/USDT, IRIS/USDT, KMD/USDT, TROY/USDT, WING/USDT, AION/USDT, PHA/USDT, SUSHIDOWN/USDT, EOSUP/USDT, LTCUP/USDT, GHST/USDT, PAXG/USDT, BNT/USDT, AVA/USDT, BADGER/USDT, PERL/USDT, COCOS/USDT, GXS/USDT, MDT/USDT, 1INCHUP/USDT, GTO/USDT, LINKUP/USDT, AAVEUP/USDT, FIRO/USDT, JUV/USDT, MLN/USDT, UNIUP/USDT, LPT/USDT, NMR/USDT, AAVEDOWN/USDT, 1INCHDOWN/USDT, ASR/USDT, OG/USDT, BAR/USDT, DREP/USDT, BOND/USDT, DCR/USDT, GNO/USDT, NBS/USDT, RIF/USDT, SUSD/USDT'
#whitelist = 'LINK/USDT, DOT/USDT'
startdate = '2020-01-01'
enddate = '2022-02-01'
interval = '1w'

In [41]:
def FRSI(series, period=14):
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    return 100 - (100 / (1 + rs))


# calculating Stoch RSI (gives the same values as TradingView)
# https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI) 
def STRSIA(series, period=14, smoothK=3, smoothD=3):
    # Calculate RSI 
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    rsi = 100 - 100 / (1 + rs)

    # Calculate StochRSI 
    stochrsi  = (rsi - rsi.rolling(period).min()) / (rsi.rolling(period).max() - rsi.rolling(period).min())
    stochrsi_K = stochrsi.rolling(smoothK).mean()
    stochrsi_D = stochrsi_K.rolling(smoothD).mean()
    return stochrsi, stochrsi_K, stochrsi_D

#Calulate SMA 
def SMA(series,size):
    sma = series.rolling(size).mean()
    return sma
#Calculate SMA55

In [42]:
whitelist=whitelist.lstrip()
array = whitelist.split(",")
array
wl = []
bl = []
blacklist = ""
whitelist = ""
symbols =[]
for i in range(0 ,len(array)):
    if (array[i].find('DOWN') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])
    elif (array[i].find('UP') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])

    else:
        wl.append(str(array[i]).lstrip().replace("/",""))
        whitelist +=str(array[i]).lstrip()
        #print ("Doesn't contains given substring")
    

    
#symbols to be used to get the prices from binance url
symbols = np.array(wl)


## get the data 
import os

live = pd.to_datetime('today')
start = pd.to_datetime(startdate)
end = pd.to_datetime(enddate)

root_url = 'https://api.binance.com/api/v1/klines'
symbol = 'STEEMETH'
#interval = '1d'
url = root_url + '?symbol=' + symbol + '&interval=' + interval
print(url)


directory = 'BN-main'
table = []
   
      
        

for symbol in symbols:
        url = root_url + '?symbol=' + symbol + '&interval=' + interval
        data = json.loads(requests.get(url).text)
        dflive = pd.DataFrame(data ,columns =['open_time',
              'o', 'h', 'l', 'c', 'v',
              'close_time', 'qav', 'num_trades',
              'taker_base_vol', 'taker_quote_vol', 'ignore'])
        dflive.open_time = pd.to_datetime(dflive['open_time'],unit='ms')
        dflive=dflive.loc[(dflive.open_time>start)]
        
        dflive = dflive.astype ({'o': float ,'h':float,'l':float ,'c':float ,'v':float})
        dflive['SMA21'] = SMA(dflive['c'],21)
        dflive['SMA55'] = SMA(dflive['c'],55)
        dflive['SMA100'] = SMA(dflive['c'],100)
        
        
        
        
        lastrow = dflive.iloc[-1]
        now = float(lastrow.c)
        SMA21 = float(lastrow.SMA21)
        SMA55 = float(lastrow.SMA55)
        SMA100 = float(lastrow.SMA100)
        
        
        alth = dflive.h.max()
        altl = dflive.l.min()
        
        
        ## past 1 month 
        past_month = end - relativedelta(months=1)
        
        back1Mdata = dflive.loc[(dflive.open_time> past_month)]
        omh = back1Mdata.h.max()
        oml = back1Mdata.l.min()
        ## past 2 month
        
        past_2month = end - relativedelta(months=2)
        back2Mdata = dflive.loc[(dflive.open_time> past_2month)]
        tmh = back2Mdata.h.max()
        tml = back2Mdata.l.min()
        ## past 3 month 
        
        past_3month = end - relativedelta(months=3)
        back3Mdata = dflive.loc[(dflive.open_time> past_3month)]
        thmh = back3Mdata.h.max()
        thml = back3Mdata.l.min()
        
 
        tuple =(symbol,alth,altl,now,omh,oml,tmh,tml,thmh,thml,SMA21,SMA55,SMA100,)
        table.append(tuple)
        del dflive
        #print("name is: ",array[0] ,alth,altl)
        print("name is: ",symbol)
        

table[0]
AllTime = pd.DataFrame(table,columns=['Indicator','ATH','ATL','Current','OMH','OML','TMH','TML','THMH','THML','SMA21','SMA55','SMA100'])
AllTime.ATH=AllTime.ATH.astype(float)
AllTime.ATL=AllTime.ATL.astype(float)
AllTime.Current=AllTime.Current.astype(float)
AllTime.OMH=AllTime.OMH.astype(float)
AllTime.OML=AllTime.OML.astype(float)
AllTime.TMH=AllTime.TMH.astype(float)
AllTime.TML=AllTime.TML.astype(float)
AllTime.THMH=AllTime.THMH.astype(float)
AllTime.THML=AllTime.THML.astype(float)
AllTime.dtypes

AllTime['ALLTIME']=(AllTime['Current']/AllTime['ATH'])*100
AllTime['MONTH']=(AllTime['Current']/AllTime['OMH'])*100
AllTime['2MONTH']=(AllTime['Current']/AllTime['TMH'])*100
AllTime['3MONTH']=(AllTime['Current']/AllTime['THMH'])*100
AllTime['SMADIFF']= abs(AllTime['SMA21']- AllTime['SMA55'])
AllTime['SMARATIO']= (AllTime['SMA21']/AllTime['SMA55'])
AllTime['CLOSERATIO']= (abs(AllTime['Current']- AllTime['SMA100'])/AllTime['SMA100'])


AllTime.sort_values(by=['ALLTIME'],ascending=True,inplace = True)
#AllTime.sort_values(by='ATH',ascending=False)
#AllTime.to_csv("alltimeHL.csv", mode="w")
#data.sort_values("Name", axis = 0, ascending = True,inplace = True, na_position ='last')

## Display the Data 
AllTime

https://api.binance.com/api/v1/klines?symbol=STEEMETH&interval=1w
name is:  VIDTUSDT
name is:  IRISUSDT
name is:  SHIBUSDT
name is:  LINKUSDT
name is:  MATICUSDT
name is:  ZRXUSDT
name is:  ALGOUSDT
name is:  BTCUSDT
name is:  ETHUSDT
name is:  AXSUSDT
name is:  SOLUSDT
name is:  MATICUSDT
name is:  ADAUSDT
name is:  BNBUSDT
name is:  FILUSDT
name is:  XRPUSDT
name is:  CVCUSDT
name is:  FTMUSDT
name is:  ICPUSDT
name is:  DOGEUSDT
name is:  XECUSDT
name is:  IOTAUSDT
name is:  AVAXUSDT
name is:  DOTUSDT
name is:  LTCUSDT
name is:  EOSUSDT
name is:  IOSTUSDT
name is:  STMXUSDT
name is:  FTTUSDT
name is:  TWTUSDT
name is:  ALICEUSDT
name is:  ATAUSDT
name is:  ETCUSDT
name is:  VETUSDT
name is:  SANDUSDT
name is:  LINKUSDT
name is:  THETAUSDT
name is:  SHIBUSDT
name is:  CHZUSDT
name is:  LUNAUSDT
name is:  IOTXUSDT
name is:  TRXUSDT
name is:  TLMUSDT
name is:  BCHUSDT
name is:  REEFUSDT
name is:  CAKEUSDT
name is:  NEOUSDT
name is:  RVNUSDT
name is:  ATOMUSDT
name is:  SUSHIUSDT
name is:  ARDRUSDT
name is:  OMGUSDT
name is:  GRTUSDT
name is:  1INCHUSDT
name is:  AAVEUSDT
name is:  C98USDT
name is:  UNIUSDT
name is:  HBARUSDT
name is:  CRVUSDT
name is:  DENTUSDT
name is:  MBOXUSDT
name is:  BTTUSDT
name is:  SRMUSDT
name is:  YFIUSDT
name is:  HOTUSDT
name is:  XLMUSDT
name is:  FISUSDT
name is:  REQUSDT
name is:  SXPUSDT
name is:  KSMUSDT
name is:  QNTUSDT
name is:  NEARUSDT
name is:  COMPUSDT
name is:  QTUMUSDT
name is:  CHRUSDT
name is:  SCUSDT
name is:  XVSUSDT
name is:  ONTUSDT
name is:  COTIUSDT
name is:  NKNUSDT
name is:  RUNEUSDT
name is:  ANKRUSDT
name is:  MANAUSDT
name is:  CTXCUSDT
name is:  ARUSDT
name is:  RAYUSDT
name is:  BAKEUSDT
name is:  ARPAUSDT
name is:  XTZUSDT
name is:  ZILUSDT
name is:  ONGUSDT
name is:  ROSEUSDT
name is:  PNTUSDT
name is:  ALGOUSDT
name is:  MINAUSDT
name is:  WINUSDT
name is:  AUDIOUSDT
name is:  STORJUSDT
name is:  EPSUSDT
name is:  MDXUSDT
name is:  ZECUSDT
name is:  ENJUSDT
name is:  HIVEUSDT
name is:  TFUELUSDT
name is:  WRXUSDT
name is:  SNXUSDT
name is:  SKLUSDT
name is:  LINAUSDT
name is:  DODOUSDT
name is:  UNFIUSDT
name is:  XEMUSDT
name is:  EGLDUSDT
name is:  ICXUSDT
name is:  WAVESUSDT
name is:  ONEUSDT
name is:  DASHUSDT
name is:  KAVAUSDT
name is:  TKOUSDT
name is:  OGNUSDT
name is:  XMRUSDT
name is:  OCEANUSDT
name is:  CELOUSDT
name is:  BATUSDT
name is:  FUNUSDT
name is:  LRCUSDT
name is:  ALPHAUSDT
name is:  MASKUSDT
name is:  TRUUSDT
name is:  DNTUSDT
name is:  LITUSDT
name is:  FETUSDT
name is:  GTCUSDT
name is:  CELRUSDT
name is:  DEXEUSDT
name is:  ZENUSDT
name is:  WAXPUSDT
name is:  CTSIUSDT
name is:  HNTUSDT
name is:  YFIIUSDT
name is:  BELUSDT
name is:  ZRXUSDT
name is:  DEGOUSDT
name is:  RSRUSDT
name is:  COSUSDT
name is:  FLMUSDT
name is:  BALUSDT
name is:  MFTUSDT
name is:  RLCUSDT
name is:  KNCUSDT
name is:  RENUSDT
name is:  INJUSDT
name is:  FLOWUSDT
name is:  SFPUSDT
name is:  BANDUSDT
name is:  CTKUSDT
name is:  SUNUSDT
name is:  AKROUSDT
name is:  XVGUSDT
name is:  NANOUSDT
name is:  STRAXUSDT
name is:  PUNDIXUSDT
name is:  TVKUSDT
name is:  MKRUSDT
name is:  CLVUSDT
name is:  TRBUSDT
name is:  KEEPUSDT
name is:  TCTUSDT
name is:  PONDUSDT
name is:  LTOUSDT
name is:  ANTUSDT
name is:  TOMOUSDT
name is:  ACMUSDT
name is:  FIOUSDT
name is:  VITEUSDT
name is:  MBLUSDT
name is:  JSTUSDT
name is:  MTLUSDT
name is:  UTKUSDT
name is:  BLZUSDT
name is:  ORNUSDT
name is:  STPTUSDT
name is:  CFXUSDT
name is:  OMUSDT
name is:  PERPUSDT
name is:  MIRUSDT
name is:  STXUSDT
name is:  ERNUSDT
name is:  TUSDUSDT
name is:  PSGUSDT
name is:  NULSUSDT
name is:  OXTUSDT
name is:  REPUSDT
name is:  DATAUSDT
name is:  WANUSDT
name is:  BURGERUSDT
name is:  RAMPUSDT
name is:  ATMUSDT
name is:  DGBUSDT
name is:  DIAUSDT
name is:  BEAMUSDT
name is:  UMAUSDT
name is:  CKBUSDT
name is:  TRIBEUSDT
name is:  FARMUSDT
name is:  BZRXUSDT
name is:  ALPACAUSDT
name is:  BTSUSDT
name is:  FORUSDT
name is:  HARDUSDT
name is:  LSKUSDT
name is:  POLSUSDT
name is:  FORTHUSDT
name is:  TORNUSDT
name is:  VTHOUSDT
name is:  BTGUSDT
name is:  QUICKUSDT
name is:  PAXUSDT
name is:  MITHUSDT
name is:  DUSKUSDT
name is:  WTCUSDT
name is:  DOCKUSDT
name is:  AUTOUSDT
name is:  BTCSTUSDT
name is:  KLAYUSDT
name is:  WNXMUSDT
name is:  KEYUSDT
name is:  NUUSDT
name is:  IRISUSDT
name is:  KMDUSDT
name is:  TROYUSDT
name is:  WINGUSDT
name is:  AIONUSDT
name is:  PHAUSDT
name is:  GHSTUSDT
name is:  PAXGUSDT
name is:  BNTUSDT
name is:  AVAUSDT
name is:  BADGERUSDT
name is:  PERLUSDT
name is:  COCOSUSDT
name is:  GXSUSDT
name is:  MDTUSDT
name is:  GTOUSDT
name is:  FIROUSDT
name is:  JUVUSDT
name is:  MLNUSDT
name is:  LPTUSDT
name is:  NMRUSDT
name is:  ASRUSDT
name is:  OGUSDT
name is:  BARUSDT
name is:  DREPUSDT
name is:  BONDUSDT
name is:  DCRUSDT
name is:  GNOUSDT
name is:  NBSUSDT
name is:  RIFUSDT
name is:  SUSDUSDT

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,SMA21,SMA55,SMA100,ALLTIME,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,CLOSERATIO
155,SUNUSDT,54.5600,0.01314,0.01472,0.0233,0.01314,0.02987,0.01314,0.04273,0.01314,0.026736,9.586641,NaN,0.026979,63.175966,49.280214,34.448865,9.559905,0.002789,NaN
216,PAXUSDT,999.0000,0.93880,0.99960,NaN,NaN,NaN,NaN,NaN,NaN,0.999510,0.999524,NaN,0.100060,NaN,NaN,NaN,0.000014,0.999986,NaN
98,EPSUSDT,22.5000,0.14230,0.15640,0.3248,0.14230,0.36000,0.14230,0.62000,0.14230,0.394429,NaN,NaN,0.695111,48.152709,43.444444,25.225806,NaN,NaN,NaN
18,ICPUSDT,2831.0200,18.06000,20.79000,38.0200,18.06000,38.02000,18.06000,58.30000,18.06000,37.120000,NaN,NaN,0.734364,54.681746,54.681746,35.660377,NaN,NaN,NaN
222,BTCSTUSDT,1000.0000,8.00000,15.09000,26.2900,13.26000,29.00000,13.26000,48.95000,13.26000,27.080476,56.867782,NaN,1.509000,57.398250,52.034483,30.827375,29.787306,0.476201,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,ETHUSDT,4868.0000,86.00000,2641.09000,3900.7300,2159.00000,4488.00000,2159.00000,4868.00000,2159.00000,3697.692857,2883.071636,1759.938200,54.254108,67.707583,58.847816,54.254108,814.621221,1.282553,0.500672
17,FTMUSDT,3.4842,0.00170,1.93340,3.3788,1.77000,3.37880,1.23840,3.37880,1.15380,2.135676,1.070408,0.596155,55.490500,57.221499,57.221499,57.221499,1.065268,1.995198,2.243116
48,ATOMUSDT,44.8000,1.06100,26.33000,44.7000,25.50000,44.70000,20.18000,44.70000,20.18000,32.891905,23.378509,14.803770,58.772321,58.903803,58.903803,58.903803,9.513396,1.406929,0.778601
233,GHSTUSDT,3.4000,1.50800,2.01100,2.6450,1.97500,2.64500,1.97500,3.40000,1.97500,2.129190,NaN,NaN,59.147059,76.030246,76.030246,59.147059,NaN,NaN,NaN
234,PAXGUSDT,2100.8500,1687.57000,1809.00000,1869.0000,1772.00000,1869.00000,1759.00000,1885.00000,1759.00000,1801.238095,1807.229818,NaN,86.108004,96.789727,96.789727,95.968170,5.991723,0.996685,NaN

In [48]:
#drop = AllTime.loc[(AllTime['RSI'] < 30)& (AllTime['STRSI'] < 0.1)]
#drop = AllTime.loc[(AllTime['SMARATIO'] <  1.05 ) &(AllTime['SMARATIO'] > 0.95)& (AllTime['ALLTIME'] <70) ]
drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA100'])]

#drop = AllTime.loc[(AllTime['SMARATIO'] <  1 ) &(AllTime['SMARATIO'] > 0.95) & (AllTime['ALLTIME'] <70)]

#drop = AllTime.loc[(AllTime['MONTH'] < 80)&(AllTime[ '2MONTH'] < 70)&(AllTime['ALLTIME'] < 40)]
#drop = AllTime.loc[(AllTime['MONTH'] <70)&(AllTime['2MONTH'] > (AllTime['3MONTH']))]

sort = drop.sort_values(by=['CLOSERATIO'],ascending=False,inplace = True) 
#drop = drop.loc[(drop['ALLTIME'] < drop['3MONTH'])]
display = drop[['Indicator','ALLTIME','CLOSERATIO','SMA100','SMA55','Current']]

print("Low 4h SMADIFF")
print(display.iloc[0:60,0:14])
print(display.iloc[60:110,])
print(display.iloc[110:160,])

Low 4h SMADIFF
     Indicator    ALLTIME  CLOSERATIO      SMA100       SMA55     Current
153   BANDUSDT  14.301897    0.544360    7.314980    9.294978    3.333000
118    OGNUSDT   9.123894    0.476964    0.591355    0.889129    0.309300
206    BTSUSDT  12.847978    0.454599    0.041126    0.056053    0.022430
77     ONTUSDT  16.174830    0.420372    0.825529    1.030907    0.478500
199   BEAMUSDT  16.190476    0.392132    0.559332    0.737500    0.340000
149    RENUSDT  16.673913    0.390759    0.503578    0.730944    0.306800
25     EOSUSDT  15.268456    0.388437    3.719978    4.548438    2.275000
231   AIONUSDT  12.873993    0.380340    0.144434    0.190418    0.089500
46     NEOUSDT  14.035461    0.371630   31.494200   45.804218   19.790000
43     BCHUSDT  16.836364    0.371606  442.079000  584.846182  277.800000
89     ZILUSDT  17.111051    0.365367    0.069268    0.107689    0.043960
193    WANUSDT  15.271347    0.345757    0.615062    0.904362    0.402400
115   DASHUSDT  19.330544    0.344330  140.924600  190.188364   92.400000
158   NANOUSDT  12.564972    0.344233    3.391447    5.404011    2.224000
209    LSKUSDT  13.956522    0.341493    2.437330    3.425038    1.605000
123    FUNUSDT  14.143180    0.339227    0.014695    0.023511    0.009710
112    ICXUSDT  22.031250    0.301386    1.009141    1.526555    0.705000
170   TOMOUSDT  28.188776    0.279884    1.534474    2.252433    1.105000
36   THETAUSDT  17.267003    0.278473    3.800273    6.479770    2.742000
189   NULSUSDT  18.103960    0.257459    0.492498    0.646684    0.365700
140    ZRXUSDT  23.916667    0.253364    0.768782    1.093451    0.574000
5      ZRXUSDT  23.916667    0.253364    0.768782    1.093451    0.574000
229   TROYUSDT  15.744617    0.247192    0.008393    0.012412    0.006318
113  WAVESUSDT  20.495915    0.225119   11.072674   17.713435    8.580000
238   PERLUSDT  16.208828    0.217028    0.061343    0.089915    0.048030
65     XLMUSDT  24.157796    0.193824    0.239278    0.355393    0.192900
119    XMRUSDT  27.854295    0.189344  178.374000  248.236909  144.600000
147    RLCUSDT  11.096970    0.184679    2.245742    3.403715    1.831000
33     VETUSDT  18.539894    0.171398    0.062611    0.103865    0.051880
35    LINKUSDT  29.509434    0.165024   18.731069   26.541664   15.640000
3     LINKUSDT  29.509434    0.165024   18.731069   26.541664   15.640000
235    BNTUSDT  25.584647    0.162946    2.863616    4.396147    2.397000
95     WINUSDT  10.020202    0.162929    0.000356    0.000577    0.000298
64     HOTUSDT  13.518987    0.161672    0.005096    0.008805    0.004272
146    MFTUSDT  18.640186    0.154205    0.007601    0.012442    0.006429
24     LTCUSDT  26.215870    0.148413  127.291800  181.104909  108.400000
168    LTOUSDT  21.419142    0.148036    0.228531    0.354071    0.194700
220   DOCKUSDT  22.576923    0.147782    0.048215    0.077703    0.041090
173   VITEUSDT  14.154728    0.140905    0.057502    0.091057    0.049400
59    DENTUSDT  10.801762    0.117027    0.002777    0.004882    0.002452
73    QTUMUSDT  16.853019    0.110313    6.759680   10.510418    6.014000
100    ZECUSDT  26.827957    0.098479  110.701800  152.158182   99.800000
116   KAVAUSDT  34.465177    0.094121    3.507089    4.972782    3.177000
166    TCTUSDT  16.709075    0.089141    0.021628    0.032744    0.019700
51     OMGUSDT  23.027231    0.081472    5.045029    7.211491    4.634000
174    MBLUSDT  13.443983    0.044346    0.006103    0.009742    0.005832
47     RVNUSDT  22.237395    0.043807    0.068124    0.109947    0.065140
225    KEYUSDT  19.597122    0.015401    0.006917    0.011136    0.006810
79     NKNUSDT  13.337811    0.002767    0.199151    0.345193    0.198600
103  TFUELUSDT  23.750349    0.000304    0.161549    0.285710    0.161500
Empty DataFrame
Columns: [Indicator, ALLTIME, CLOSERATIO, SMA100, SMA55, Current]
Index: []
Empty DataFrame
Columns: [Indicator, ALLTIME, CLOSERATIO, SMA100, SMA55, Current]
Index: []

/Users/hjabbour/opt/anaconda3/envs/ML/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.