Generate the easy band in the first section based on live data 
compare it to the entries in the second part

In [1]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta


#Data Source(Pandas Data Reader)

In [2]:
whitelist = 'POWR/USDT, MDT/USDT,BLZ/USDT, CHR/USDT, ORN/USDT, VIDT/USDT, IRIS/USDT, SHIB/USDT, MATIC/USDT,ALGO/USDT, BTC/USDT, ETH/USDT, AXS/USDT, SOL/USDT, MATIC/USDT, ADA/USDT, BNB/USDT, FIL/USDT, XRP/USDT, CVC/USDT, FTM/USDT, ICP/USDT, DOGE/USDT, XEC/USDT, IOTA/USDT, AVAX/USDT, DOT/USDT, LTC/USDT, EOS/USDT, IOST/USDT, STMX/USDT, FTT/USDT, TWT/USDT, ALICE/USDT, ATA/USDT, ETC/USDT, VET/USDT, SAND/USDT, LINK/USDT, THETA/USDT, SHIB/USDT, CHZ/USDT, LUNA/USDT, IOTX/USDT, TRX/USDT, TLM/USDT, BCH/USDT, REEF/USDT, CAKE/USDT, NEO/USDT,RVN/USDT, ATOM/USDT, SUSHI/USDT, ARDR/USDT, OMG/USDT, GRT/USDT, 1INCH/USDT, AAVE/USDT, C98/USDT, UNI/USDT, HBAR/USDT, CRV/USDT, DENT/USDT, MBOX/USDT, BTT/USDT, SRM/USDT, YFI/USDT, HOT/USDT, XLM/USDT, FIS/USDT, REQ/USDT, SXP/USDT, KSM/USDT, QNT/USDT, NEAR/USDT, COMP/USDT, QTUM/USDT, CHR/USDT, SC/USDT, XVS/USDT, ONT/USDT, COTI/USDT, NKN/USDT, RUNE/USDT, ANKR/USDT, MANA/USDT, CTXC/USDT, AR/USDT, RAY/USDT, BAKE/USDT, ARPA/USDT, XTZ/USDT, ZIL/USDT, ONG/USDT, ROSE/USDT, PNT/USDT,MINA/USDT, WIN/USDT, AUDIO/USDT, STORJ/USDT, EPS/USDT, MDX/USDT, ZEC/USDT, ENJ/USDT, HIVE/USDT, TFUEL/USDT, WRX/USDT, SNX/USDT, SKL/USDT, LINA/USDT, DODO/USDT, UNFI/USDT, XEM/USDT, EGLD/USDT, ICX/USDT, WAVES/USDT, ONE/USDT, DASH/USDT, KAVA/USDT, SUPER/USDT, TKO/USDT, OGN/USDT, XMR/USDT, OCEAN/USDT, CELO/USDT, BAT/USDT, FUN/USDT, LRC/USDT, ALPHA/USDT, MASK/USDT, TRU/USDT, DNT/USDT, LIT/USDT, FET/USDT, GTC/USDT, CELR/USDT, DEXE/USDT, ZEN/USDT, WAXP/USDT, CTSI/USDT, HNT/USDT, YFII/USDT, BEL/USDT, ZRX/USDT, DEGO/USDT, RSR/USDT, COS/USDT, FLM/USDT, BAL/USDT, MFT/USDT, RLC/USDT, KNC/USDT, REN/USDT, INJ/USDT, FLOW/USDT, SFP/USDT, BAND/USDT, CTK/USDT, SUN/USDT, AKRO/USDT, XVG/USDT, NANO/USDT, STRAX/USDT, PUNDIX/USDT, TVK/USDT, MKR/USDT, CLV/USDT, TRB/USDT, ETHUP/USDT, KEEP/USDT, TCT/USDT, POND/USDT, LTO/USDT, ANT/USDT, TOMO/USDT, ACM/USDT, FIO/USDT, VITE/USDT, MBL/USDT, JST/USDT, MTL/USDT, UTK/USDT, BLZ/USDT, ORN/USDT, STPT/USDT, CFX/USDT, OM/USDT, PERP/USDT, MIR/USDT, STX/USDT, ERN/USDT, TUSD/USDT, PSG/USDT, NULS/USDT, OXT/USDT, REP/USDT, BNBUP/USDT, DATA/USDT, WAN/USDT, BURGER/USDT, RAMP/USDT, ATM/USDT, DGB/USDT, DIA/USDT, BEAM/USDT, UMA/USDT, ETHDOWN/USDT, CKB/USDT, TRIBE/USDT, FARM/USDT, BTCUP/USDT, BZRX/USDT, ALPACA/USDT, DOTUP/USDT, BTS/USDT, FOR/USDT, ADAUP/USDT, HARD/USDT, LSK/USDT, POLS/USDT, FORTH/USDT, TORN/USDT, VTHO/USDT, BTG/USDT, QUICK/USDT, FILUP/USDT, PAX/USDT, MITH/USDT, SUSHIUP/USDT, BTCDOWN/USDT, XRPDOWN/USDT, BNBDOWN/USDT, DUSK/USDT, XRPUP/USDT, WTC/USDT, DOCK/USDT, AUTO/USDT, BTCST/USDT, KLAY/USDT, WNXM/USDT, KEY/USDT, FILDOWN/USDT, NU/USDT, IRIS/USDT, KMD/USDT, TROY/USDT, WING/USDT, AION/USDT, PHA/USDT, SUSHIDOWN/USDT, EOSUP/USDT, LTCUP/USDT, GHST/USDT, PAXG/USDT, BNT/USDT, AVA/USDT, BADGER/USDT, PERL/USDT, COCOS/USDT, GXS/USDT, MDT/USDT, 1INCHUP/USDT, GTO/USDT, LINKUP/USDT, AAVEUP/USDT, FIRO/USDT, JUV/USDT, MLN/USDT, UNIUP/USDT, LPT/USDT, NMR/USDT, AAVEDOWN/USDT, 1INCHDOWN/USDT, ASR/USDT, OG/USDT, BAR/USDT, DREP/USDT, BOND/USDT, DCR/USDT, GNO/USDT, NBS/USDT, RIF/USDT'
#whitelist = 'LINK/USDT, DOT/USDT'
startdate = '2020-01-01'
enddate = '2022-03-22'
enddate = pd.to_datetime('today')

interval = '1w'

In [3]:
def FRSI(series, period=14):
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    return 100 - (100 / (1 + rs))


# calculating Stoch RSI (gives the same values as TradingView)
# https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI) 
def STRSIA(series, period=14, smoothK=3, smoothD=3):
    # Calculate RSI 
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    rsi = 100 - 100 / (1 + rs)

    # Calculate StochRSI 
    stochrsi  = (rsi - rsi.rolling(period).min()) / (rsi.rolling(period).max() - rsi.rolling(period).min())
    stochrsi_K = stochrsi.rolling(smoothK).mean()
    stochrsi_D = stochrsi_K.rolling(smoothD).mean()
    return stochrsi, stochrsi_K, stochrsi_D

#Calulate SMA 
def SMA(series,size):
    sma = series.rolling(size).mean()
    return sma
#Calculate SMA55

In [4]:
whitelist=whitelist.lstrip()
array = whitelist.split(",")
array
wl = []
bl = []
blacklist = ""
whitelist = ""
symbols =[]
for i in range(0 ,len(array)):
    if (array[i].find('DOWN') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])
    elif (array[i].find('UP') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])

    else:
        wl.append(str(array[i]).lstrip().replace("/",""))
        whitelist +=str(array[i]).lstrip()
        #print ("Doesn't contains given substring")
    

    
#symbols to be used to get the prices from binance url
symbols = np.array(wl)


## get the data 
import os

live = pd.to_datetime('today')
start = pd.to_datetime(startdate)
end = pd.to_datetime(enddate)

root_url = 'https://api.binance.com/api/v1/klines'
symbol = 'STEEMETH'
#interval = '1d'
url = root_url + '?symbol=' + symbol + '&interval=' + interval
print(url)


directory = 'BN-main'
table = []
   
      
        

for symbol in symbols:
        url = root_url + '?symbol=' + symbol + '&interval=' + interval
        data = json.loads(requests.get(url).text)
        dflive = pd.DataFrame(data ,columns =['open_time',
              'o', 'h', 'l', 'c', 'v',
              'close_time', 'qav', 'num_trades',
              'taker_base_vol', 'taker_quote_vol', 'ignore'])
        dflive.open_time = pd.to_datetime(dflive['open_time'],unit='ms')
        dflive=dflive.loc[(dflive.open_time>start)]
        
        dflive = dflive.astype ({'o': float ,'h':float,'l':float ,'c':float ,'v':float})
        dflive['SMA21'] = SMA(dflive['c'],21)
        dflive['SMA55'] = SMA(dflive['c'],55)
        dflive['SMA100'] = SMA(dflive['c'],100)
        
        
        
        #print(symbol)
        lastrow = dflive.iloc[-1]
        now = float(lastrow.c)
        SMA21 = float(lastrow.SMA21)
        SMA55 = float(lastrow.SMA55)
        SMA100 = float(lastrow.SMA100)
        
        
        alth = dflive.h.max()
        altl = dflive.l.min()
        
        
        ## past 1 month 
        past_month = end - relativedelta(months=1)
        
        back1Mdata = dflive.loc[(dflive.open_time> past_month)]
        omh = back1Mdata.h.max()
        oml = back1Mdata.l.min()
        ## past 2 month
        
        past_2month = end - relativedelta(months=2)
        back2Mdata = dflive.loc[(dflive.open_time> past_2month)]
        tmh = back2Mdata.h.max()
        tml = back2Mdata.l.min()
        ## past 3 month 
        
        past_3month = end - relativedelta(months=3)
        back3Mdata = dflive.loc[(dflive.open_time> past_3month)]
        thmh = back3Mdata.h.max()
        thml = back3Mdata.l.min()
        
 
        tuple =(symbol,alth,altl,now,omh,oml,tmh,tml,thmh,thml,SMA21,SMA55,SMA100,)
        table.append(tuple)
        del dflive
        #print("name is: ",array[0] ,alth,altl)
        #print("name is: ",symbol)
        

table[0]
AllTime = pd.DataFrame(table,columns=['Indicator','ATH','ATL','Current','OMH','OML','TMH','TML','THMH','THML','SMA21','SMA55','SMA100'])
AllTime.ATH=AllTime.ATH.astype(float)
AllTime.ATL=AllTime.ATL.astype(float)
AllTime.Current=AllTime.Current.astype(float)
AllTime.OMH=AllTime.OMH.astype(float)
AllTime.OML=AllTime.OML.astype(float)
AllTime.TMH=AllTime.TMH.astype(float)
AllTime.TML=AllTime.TML.astype(float)
AllTime.THMH=AllTime.THMH.astype(float)
AllTime.THML=AllTime.THML.astype(float)
AllTime.dtypes

AllTime['ALLTIME']=(AllTime['Current']/AllTime['ATH'])*100
AllTime['MONTH']=(AllTime['Current']/AllTime['OMH'])*100
AllTime['2MONTH']=(AllTime['Current']/AllTime['TMH'])*100
AllTime['3MONTH']=(AllTime['Current']/AllTime['THMH'])*100
AllTime['SMADIFF']= abs(AllTime['SMA21']- AllTime['SMA55'])
AllTime['SMARATIO']= (AllTime['SMA21']/AllTime['SMA55'])
AllTime['GREEN'] = (AllTime['SMA21'])/2
AllTime['GREEN15'] = (AllTime['SMA21'])/1.5
AllTime['ORANGE'] = (AllTime['SMA21'])
AllTime['RED'] = (AllTime['SMA21'])*2
AllTime['CLOSERATIO']= ((AllTime['Current']- AllTime['GREEN']))/AllTime['GREEN']



AllTime.sort_values(by=['ALLTIME'],ascending=True,inplace = True)
#AllTime.sort_values(by='ATH',ascending=False)
#AllTime.to_csv("alltimeHL.csv", mode="w")
#data.sort_values("Name", axis = 0, ascending = True,inplace = True, na_position ='last')

## Display the Data 
AllTime

https://api.binance.com/api/v1/klines?symbol=STEEMETH&interval=1w

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,...,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,GREEN,GREEN15,ORANGE,RED,CLOSERATIO
42,LUNAUSDT,119.550,0.00004,0.00005,97.5000,0.00004,119.55000,0.00004,119.55000,0.00004,...,0.000051,0.000042,0.000042,28.541628,1.619735,37.298096,49.730795,74.596193,149.192386,-0.999999
157,SUNUSDT,54.560,0.00769,0.00901,0.0148,0.00769,0.02039,0.00769,0.02039,0.00769,...,60.878378,44.188328,44.188328,2.944809,0.004926,0.007288,0.009718,0.014577,0.029153,0.236222
218,PAXUSDT,999.000,0.93880,0.99960,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000014,0.999986,0.499755,0.666340,0.999510,1.999019,1.000181
21,ICPUSDT,2831.020,6.03000,8.24000,16.4000,6.03000,23.52000,6.03000,23.52000,6.03000,...,50.243902,35.034014,35.034014,NaN,NaN,9.529762,12.706349,19.059524,38.119048,-0.135340
45,TLMUSDT,5.950,0.02350,0.03480,0.0966,0.02350,0.14830,0.02350,0.14830,0.02350,...,36.024845,23.465947,23.465947,0.083652,0.569100,0.055240,0.073654,0.110481,0.220962,-0.370027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,BTCUSDT,69000.000,3782.13000,30170.72000,40797.3100,26700.00000,48189.84000,26700.00000,48189.84000,26700.00000,...,73.952719,62.608052,62.608052,4605.377498,0.895960,19829.954524,26439.939365,39659.909048,79319.818095,0.521472
16,BNBUSDT,691.770,6.38000,305.70000,413.6000,218.80000,460.00000,218.80000,460.00000,218.80000,...,73.911992,66.456522,66.456522,28.355567,0.933681,199.604762,266.139683,399.209524,798.419048,0.531527
235,GHSTUSDT,3.400,1.50800,1.59400,1.9310,1.55300,2.19900,1.55300,2.19900,1.55300,...,82.547903,72.487494,72.487494,NaN,NaN,0.982476,1.309968,1.964952,3.929905,0.622431
167,KEEPUSDT,1.209,0.21130,0.62510,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.322624,0.430165,0.645248,1.290495,0.937551
236,PAXGUSDT,2100.850,1687.57000,1850.00000,1954.0000,1791.00000,1999.00000,1791.00000,2076.00000,1791.00000,...,94.677584,92.546273,89.113680,48.362649,1.026222,946.357143,1261.809524,1892.714286,3785.428571,0.954865

In [5]:
#for i, j in zip(range(0,len(AllTime.index),70), range(70,len(AllTime.index),70)):
    #print(i,j)
    #print(AllTime.iloc[i:j,0:5])
    #if j+70 > len(AllTime.index):
        #print(j,len(AllTime.index))
        #print(AllTime.iloc[j:len(AllTime.index),0:5])
test=AllTime.loc[AllTime['Indicator']=='CRVUSDT']
test

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,...,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,GREEN,GREEN15,ORANGE,RED,CLOSERATIO
61,CRVUSDT,23.255,0.328,1.172,2.777,0.987,3.053,0.987,3.053,0.987,...,42.203817,38.38847,38.38847,0.014397,0.994888,1.400929,1.867905,2.801857,5.603714,-0.163412

In [6]:
#drop = AllTime.loc[(AllTime['RSI'] < 30)& (AllTime['STRSI'] < 0.1)]
#drop = AllTime.loc[(AllTime['SMARATIO'] <  1.05 ) &(AllTime['SMARATIO'] > 0.95)& (AllTime['ALLTIME'] <70) ]
#drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21'])]
drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21']/1.8)]
#drop = AllTime.loc[(AllTime['Current'] <= AllTime['GREEN15'])]

#drop = AllTime.loc[(AllTime['SMARATIO'] <  1 ) &(AllTime['SMARATIO'] > 0.95) & (AllTime['ALLTIME'] <70)]

#drop = AllTime.loc[(AllTime['MONTH'] < 80)&(AllTime[ '2MONTH'] < 70)&(AllTime['ALLTIME'] < 40)]
#drop = AllTime.loc[(AllTime['MONTH'] <70)&(AllTime['2MONTH'] > (AllTime['3MONTH']))]

sort = drop.sort_values(by=['CLOSERATIO'],ascending=False,inplace = True) 
#sort = drop.sort_values(by=['ALLTIME'],ascending=True,inplace = True) 

#drop = drop.loc[(drop['ALLTIME'] < drop['3MONTH'])]
display = drop[['Indicator','ATH','RED','ORANGE','GREEN','Current']]
#print(drop)
save = drop[['Indicator','ATH','CLOSERATIO','RED','ORANGE','GREEN','Current']]
save=save.drop_duplicates(subset='Indicator',keep='last')

#print(save)

save.to_csv("easyband.csv")
print(str(date.today()))
#print(date)
save.to_csv("easyband"+str(date.today())+".csv")

print("Low EASY Band")

display    
#print(display.iloc[0:60,0:14])
#print(display.iloc[60:110,])
#print(display.iloc[110:160,])

2022-05-19
Low EASY Band

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

    Indicator        ATH         RED     ORANGE      GREEN   Current
208   BTSUSDT    0.17458    0.046087   0.023043   0.011522   0.01280
247   MLNUSDT  234.80000  113.723810  56.861905  28.430952  31.50000
238   AVAUSDT    6.46760    2.655143   1.327571   0.663786   0.73300
53   ARDRUSDT    0.79000    0.397590   0.198795   0.099398   0.10940
15    ADAUSDT    3.10100    1.946229   0.973114   0.486557   0.53450
..        ...        ...         ...        ...        ...       ...
94   ROSEUSDT    0.59800    0.524174   0.262087   0.131044   0.07123
20    FTMUSDT    3.48420    3.079305   1.539652   0.769826   0.34200
185  PERPUSDT   26.21000   10.202857   5.101429   2.550714   1.13000
186   MIRUSDT   14.55000    2.745529   1.372764   0.686382   0.24083
42   LUNAUSDT  119.55000  149.192386  74.596193  37.298096   0.00005

[176 rows x 6 columns]

In [7]:
allbands = AllTime[['Indicator','RED','ORANGE','GREEN','Current']]
allbands.to_csv("allbands.csv")
allbands

    Indicator           RED        ORANGE         GREEN      Current
42   LUNAUSDT    149.192386     74.596193     37.298096      0.00005
157   SUNUSDT      0.029153      0.014577      0.007288      0.00901
218   PAXUSDT      1.999019      0.999510      0.499755      0.99960
21    ICPUSDT     38.119048     19.059524      9.529762      8.24000
45    TLMUSDT      0.220962      0.110481      0.055240      0.03480
..        ...           ...           ...           ...          ...
10    BTCUSDT  79319.818095  39659.909048  19829.954524  30170.72000
16    BNBUSDT    798.419048    399.209524    199.604762    305.70000
235  GHSTUSDT      3.929905      1.964952      0.982476      1.59400
167  KEEPUSDT      1.290495      0.645248      0.322624      0.62510
236  PAXGUSDT   3785.428571   1892.714286    946.357143   1850.00000

[259 rows x 5 columns]

In [8]:
# red band 

## band to sell in down trends
redband = AllTime.loc[(AllTime['Current'] >= 2*AllTime['SMA21'])]
redband.to_csv("redband.csv")
redband

Empty DataFrame
Columns: [Indicator, ATH, ATL, Current, OMH, OML, TMH, TML, THMH, THML, SMA21, SMA55, SMA100, ALLTIME, MONTH, 2MONTH, 3MONTH, SMADIFF, SMARATIO, GREEN, GREEN15, ORANGE, RED, CLOSERATIO]
Index: []

[0 rows x 24 columns]

In [9]:
## band to sell in down trends
orangeband = AllTime.loc[(AllTime['Current'] >= AllTime['SMA21'])]
test = orangeband[['Indicator','GREEN','ORANGE','RED','Current']]
test.to_csv("orangeband.csv")
test

    Indicator     GREEN    ORANGE       RED  Current
218   PAXUSDT  0.499755  0.999510  1.999019  0.99960
242   GXSUSDT  0.853738  1.707476  3.414952  1.79230
189  TUSDUSDT  0.499950  0.999900  1.999800  1.00110
44    TRXUSDT  0.033218  0.066436  0.132872  0.07376

In [10]:
#easybandlist = display['Indicator']
#easybandlist

## GREEN 15

In [11]:
## GREEN 15
#display.Current.astype(float)

display = display.loc[:] 
display['ORatio'] = display['ORANGE']/display['Current'] 
#display = display.loc[display.Current < display.GREEN*1.05]
display = display.loc[display.Current < display.GREEN*0.8]

#display = display.loc[display['CLOSERATIO']> 0.01]
display

#display

,Indicator,ATH,RED,ORANGE,GREEN,Current,ORatio
181,ORNUSDT,29.85000,7.117238,3.558619,1.779310,1.42300,2.500786e+00
4,ORNUSDT,29.85000,7.117238,3.558619,1.779310,1.42300,2.500786e+00
188,ERNUSDT,24.80000,10.503524,5.251762,2.625881,2.09900,2.502030e+00
37,SANDUSDT,8.48760,6.505524,3.252762,1.626381,1.29900,2.504051e+00
34,ATAUSDT,4.50000,0.786371,0.393186,0.196593,0.15700,2.504368e+00
17,FILUSDT,430.00000,40.606667,20.303333,10.151667,8.09000,2.509683e+00
187,STXUSDT,3.25600,2.655810,1.327905,0.663952,0.52700,2.519743e+00
109,LINAUSDT,1.00000,0.046729,0.023364,0.011682,0.00927,2.520419e+00
240,PERLUSDT,0.29632,0.093761,0.046880,0.023440,0.01855,2.527249e+00
143,DEGOUSDT,34.70000,6.789524,3.394762,1.697381,1.34000,2.533404e+00
233,AIONUSDT,0.69520,0.177305,0.088652,0.044326,0.03480,2.547482e+00
105,TFUELUSDT,0.67999,0.323552,0.161776,0.080888,0.06320,2.559750e+00
203,CKBUSDT,0.04447,0.025528,0.012764,0.006382,0.00497,2.568171e+00
254,BONDUSDT,75.00000,18.134286,9.067143,4.533571,3.53000,2.568596e+00
6,IRISUSDT,0.32000,0.124311,0.062156,0.031078,0.02393,2.597397e+00
229,IRISUSDT,0.32000,0.124299,0.062150,0.031075,0.02380,2.611325e+00
232,WINGUSDT,300.00000,18.199048,9.099524,4.549762,3.47000,2.622341e+00
106,WRXUSDT,6.66660,1.370857,0.685429,0.342714,0.25500,2.687955e+00
88,RAYUSDT,17.80000,6.379714,3.189857,1.594929,1.17900,2.705562e+00
133,GTCUSDT,29.04300,13.862952,6.931476,3.465738,2.55000,2.718226e+00
141,BELUSDT,19.00000,1.784000,0.892000,0.446000,0.32700,2.727829e+00
134,CELRUSDT,0.19870,0.096519,0.048260,0.024130,0.01768,2.729611e+00
139,HNTUSDT,59.27000,45.756190,22.878095,11.439048,8.34000,2.743177e+00
115,WAVESUSDT,63.88000,34.222857,17.111429,8.555714,6.17000,2.773327e+00
163,TVKUSDT,0.55000,0.232686,0.116343,0.058171,0.04120,2.823856e+00
71,SXPUSDT,5.87000,2.597333,1.298667,0.649333,0.44400,2.924925e+00
52,SUSHIUSDT,23.43000,7.781429,3.890714,1.945357,1.32400,2.938606e+00
128,MASKUSDT,22.58100,10.841333,5.420667,2.710333,1.83900,2.947616e+00
196,BURGERUSDT,29.00000,3.178095,1.589048,0.794524,0.52800,3.009560e+00
58,C98USDT,6.44500,3.028571,1.514286,0.757143,0.50100,3.022526e+00
110,DODOUSDT,10.00000,0.926286,0.463143,0.231571,0.15000,3.087619e+00
45,TLMUSDT,5.95000,0.220962,0.110481,0.055240,0.03480,3.174740e+00
169,PONDUSDT,0.31800,0.071784,0.035892,0.017946,0.01130,3.176275e+00
171,ANTUSDT,43.00000,10.682667,5.341333,2.670667,1.67400,3.190761e+00
220,DUSKUSDT,1.17430,0.856648,0.428324,0.214162,0.13270,3.227760e+00
116,ONEUSDT,0.38000,0.317266,0.158633,0.079316,0.04682,3.388143e+00
144,RSRUSDT,0.11900,0.030832,0.015416,0.007708,0.00451,3.418224e+00
158,AKROUSDT,0.08850,0.025125,0.012562,0.006281,0.00349,3.599536e+00
94,ROSEUSDT,0.59800,0.524174,0.262087,0.131044,0.07123,3.679449e+00
20,FTMUSDT,3.48420,3.079305,1.539652,0.769826,0.34200,4.501908e+00
185,PERPUSDT,26.21000,10.202857,5.101429,2.550714,1.13000,4.514539e+00
186,MIRUSDT,14.55000,2.745529,1.372764,0.686382,0.24083,5.700138e+00
42,LUNAUSDT,119.55000,149.192386,74.596193,37.298096,0.00005,1.491924e+06

# entries

In [12]:

#entrylist =[['ANKRUSDT',0.07684],['AVAXUSDT',57],['WAXPUSDT',0.3818],['REEFUSDT',0.01131],['LINKUSDT',14.15],['ARUSDT',30],['ATOMUSDT',23],['MIRUSDT',2.343],['ALGOUSDT',0.909],['ZRXUSDT',0.60],['XTZUSDT',2.856],['KSMUSDT',163],['NEARUSDT',14],['WINUSDT',0.0003138],['CELRUSDT',0.05063],['DENTUSDT',0.002459],['LRCUSDT',0.7047],['CRVUSDT',3.529],['IMXUSDT',2.709],['SCRTUSDT',5],['RENUSDT',0.2547],['SUSHIUSDT',4.522],['CAKEUSDT',11.24],['XLMUSDT',0.2109],['HNTUSDT',30],['OMGUSDT',4.5],['LINAUSDT',0.024],['MIRUSDT',2.343],['FLUXUSDT',1.523]]
entrylist =[['ANKRUSDT',0.05415],['AVAXUSDT',33],['WAXPUSDT',0.2551],['REEFUSDT',0.00806],['LINKUSDT',12],['ARUSDT',14],['ATOMUSDT',9.75],['MIRUSDT',2.343],['ALGOUSDT',0.63],['ZRXUSDT',0.50],['XTZUSDT',2.856],['KSMUSDT',115],['NEARUSDT',6.1],['WINUSDT',0.00025],['DENTUSDT',0.002459],['LRCUSDT',0.677],['CRVUSDT',2.12],['IMXUSDT',1.30],['SCRTUSDT',3.7],['RENUSDT',0.3047],['SUSHIUSDT',3.5],['CAKEUSDT',11.24],['XLMUSDT',0.2109],['HNTUSDT',13.9],['OMGUSDT',4.5],['LINAUSDT',0.01759],['FLUXUSDT',1.523],['SRMUSDT',1.8],['VTHOUSDT',0.0031],['ANTUSDT',1.5],['RAYUSDT',2.5],['ROSEUSDT',0.06437],['MOVRUSDT',33.7],['TFUELUSDT',0.13],['GLMRUSDT',2.311],['COTIUSDT',0.2],['ONEUSDT',0.039],['VETUSDT',0.05138],['RUNEUSDT',3.709],['CELRUSDT',0.01331],['ONTUSDT',0.4652],['GALAUSDT',0.17],['GRTUSDT',0.3164],['DOTUSDT',15],['ZILUSDT',0.04410],['FILUSDT',20],['SCUSDT',0.011],['MATICUSDT',1.4],['FTMUSDT',0.31],['BANDUSDT',3.6],['1INCHUSDT',1.3],['AUDIOUSDT',0.375],['IOTXUSDT','0.02478'],['CTSIUSDT','0.32'],['LUNAUSDT','13'],['SOLUSDT','35'],['MINAUSDT','1.96'],['BTCUSDT','39000'],['ADAUSDT','0.51'],['STORJUSDT','0.4481'],['THETAUSDT','2.8'],['MANAUSDT','1.65'],['PAXGUSDT','1785'],['PERPUSDT','2.22']]
exposurelist =[['ANKRUSDT',311],['AVAXUSDT',3500],['WAXPUSDT',527],['REEFUSDT',700],['LINKUSDT',6000],['ARUSDT',2450],['ATOMUSDT',1863],['MIRUSDT',85],['ALGOUSDT',3300],['ZRXUSDT',245],['XTZUSDT',1200],['KSMUSDT',7800],['NEARUSDT',1360],['WINUSDT',285],['DENTUSDT',385],['LRCUSDT',660],['CRVUSDT',323],['IMXUSDT',269],['SCRTUSDT',601],['RENUSDT',684],['SUSHIUSDT',2730],['CAKEUSDT',4000],['XLMUSDT',368],['HNTUSDT',1250],['OMGUSDT',765],['LINAUSDT',205],['FLUXUSDT',224],['SRMUSDT',587],['VTHOUSDT',413],['ANTUSDT',200],['RAYUSDT',100],['ROSEUSDT',634],['MOVRUSDT',500],['TFUELUSDT',344],['GLMRUSDT',400],['COTIUSDT',500],['ONEUSDT',1000],['VETUSDT',500],['RUNEUSDT',750],['CELRUSDT',500],['ONTUSDT',400],['GALAUSDT',650],['GRTUSDT',1700],['DOTUSDT',10000],['ZILUSDT',1000],['FILUSDT',2000],['SCUSDT',200],['MATICUSDT',8000],['FTMUSDT',2000],['BANDUSDT',750],['1INCHUSDT',1000],['AUDIOUSDT',700],['IOTXUSDT',500],['CTSIUSDT',325],['LUNAUSDT',4000],['SOLUSDT',3000],['DOTUSDT',10000],['PERPUSDT',300],['MINAUSDT',300],['THETAUSDT',500],['INJUSDT',1000],['MANAUSDT',600],['BANDUSDT',1000],['CTSIUSDT',400]]
startdate = '2021-01-01'
entries = pd.DataFrame(entrylist, columns =['Indicator', 'lowest_entry'],dtype = float) 
entries
entries.lowest_entry.astype(float)

indicator_list = entries['Indicator']
#indicator_list
#entries
entries.to_csv("entries.csv")

exposure = pd.DataFrame(exposurelist, columns =['Indicator', 'exposure'],dtype = float) 
exposure
exposure.exposure.astype(float)
#indicator_list
#entries
exposure.to_csv("exposure.csv")

entries = entries.merge(exposure ,how="left",on="Indicator")
#entries

fixentries = entries.merge(display ,how='left',on=['Indicator'])
#fixentries = fixentries.merge(exposure,how='left',on=['Indicator'])
#fixentries
#entries1 = entries.merge(fixentries,how='left',on=['Indicator'])
fixentries = fixentries.dropna(axis=0,subset=['ATH'])
fixentries=fixentries.drop_duplicates(subset='Indicator',keep='last')
fixentries.lowest_entry.astype(float)
fixentries.Current.astype(float)


fixentries['DROP'] = ((fixentries.lowest_entry - fixentries.Current)/fixentries.lowest_entry)*100
fixentries.sort_values(by=['DROP'],ascending=False,inplace = True)
fixentries

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP
57,LUNAUSDT,13.00000,4000.0,119.55000,149.192386,74.596193,37.298096,0.00005,1.491924e+06,99.999615
7,MIRUSDT,2.34300,85.0,14.55000,2.745529,1.372764,0.686382,0.24083,5.700138e+00,89.721297
20,SUSHIUSDT,3.50000,2730.0,23.43000,7.781429,3.890714,1.945357,1.32400,2.938606e+00,62.171429
46,FILUSDT,20.00000,2000.0,430.00000,40.606667,20.303333,10.151667,8.09000,2.509683e+00,59.550000
30,RAYUSDT,2.50000,100.0,17.80000,6.379714,3.189857,1.594929,1.17900,2.705562e+00,52.840000
33,TFUELUSDT,0.13000,344.0,0.67999,0.323552,0.161776,0.080888,0.06320,2.559750e+00,51.384615
66,PERPUSDT,2.22000,300.0,26.21000,10.202857,5.101429,2.550714,1.13000,4.514539e+00,49.099099
25,LINAUSDT,0.01759,205.0,1.00000,0.046729,0.023364,0.011682,0.00927,2.520419e+00,47.299602
23,HNTUSDT,13.90000,1250.0,59.27000,45.756190,22.878095,11.439048,8.34000,2.743177e+00,40.000000
49,FTMUSDT,0.31000,2000.0,3.48420,3.079305,1.539652,0.769826,0.34200,4.501908e+00,-10.322581
31,ROSEUSDT,0.06437,634.0,0.59800,0.524174,0.262087,0.131044,0.07123,3.679449e+00,-10.657138
29,ANTUSDT,1.50000,200.0,43.00000,10.682667,5.341333,2.670667,1.67400,3.190761e+00,-11.600000
36,ONEUSDT,0.03900,1000.0,0.38000,0.317266,0.158633,0.079316,0.04682,3.388143e+00,-20.051282
39,CELRUSDT,0.01331,500.0,0.19870,0.096519,0.048260,0.024130,0.01768,2.729611e+00,-32.832457

# Red Band

In [13]:
## over red entries 
overred = redband.merge(entries ,how="left",on="Indicator")
overed = overred.dropna(axis=0,subset=['RED'])
overred= overred[['Indicator','GREEN','ORANGE','RED','Current']]
overred

Empty DataFrame
Columns: [Indicator, GREEN, ORANGE, RED, Current]
Index: []

# Orange Band

In [14]:
## over orange entries 
overorange = entries.merge(orangeband ,how="left",on="Indicator")
overorange = overorange.dropna(axis=0,subset=['GREEN'])
overoranged= overorange[['Indicator','GREEN','ORANGE','RED','Current']]
overoranged

Empty DataFrame
Columns: [Indicator, GREEN, ORANGE, RED, Current]
Index: []

In [15]:
save = fixentries
save.to_csv("fixoneasy.csv")
save
del fixentries

In [16]:
#Gap is an acceptable area for rebounce and exit
orangedrop = save.loc[:]
orangedrop['GapOrange']= orangedrop['ORANGE']/orangedrop['Current']
orangedrop['GapRed']= orangedrop['RED']/orangedrop['Current']
orangedrop['GapATH']= orangedrop['ATH']/orangedrop['Current']
#orangedrop['GapAORT']= (orangedrop['GapATH']*orangedrop['GapOrange'])


orangedrop

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH
57,LUNAUSDT,13.00000,4000.0,119.55000,149.192386,74.596193,37.298096,0.00005,1.491924e+06,99.999615,1.491924e+06,2.983848e+06,2.391000e+06
7,MIRUSDT,2.34300,85.0,14.55000,2.745529,1.372764,0.686382,0.24083,5.700138e+00,89.721297,5.700138e+00,1.140028e+01,6.041606e+01
20,SUSHIUSDT,3.50000,2730.0,23.43000,7.781429,3.890714,1.945357,1.32400,2.938606e+00,62.171429,2.938606e+00,5.877212e+00,1.769637e+01
46,FILUSDT,20.00000,2000.0,430.00000,40.606667,20.303333,10.151667,8.09000,2.509683e+00,59.550000,2.509683e+00,5.019365e+00,5.315204e+01
30,RAYUSDT,2.50000,100.0,17.80000,6.379714,3.189857,1.594929,1.17900,2.705562e+00,52.840000,2.705562e+00,5.411123e+00,1.509754e+01
33,TFUELUSDT,0.13000,344.0,0.67999,0.323552,0.161776,0.080888,0.06320,2.559750e+00,51.384615,2.559750e+00,5.119500e+00,1.075934e+01
66,PERPUSDT,2.22000,300.0,26.21000,10.202857,5.101429,2.550714,1.13000,4.514539e+00,49.099099,4.514539e+00,9.029077e+00,2.319469e+01
25,LINAUSDT,0.01759,205.0,1.00000,0.046729,0.023364,0.011682,0.00927,2.520419e+00,47.299602,2.520419e+00,5.040838e+00,1.078749e+02
23,HNTUSDT,13.90000,1250.0,59.27000,45.756190,22.878095,11.439048,8.34000,2.743177e+00,40.000000,2.743177e+00,5.486354e+00,7.106715e+00
49,FTMUSDT,0.31000,2000.0,3.48420,3.079305,1.539652,0.769826,0.34200,4.501908e+00,-10.322581,4.501908e+00,9.003815e+00,1.018772e+01
31,ROSEUSDT,0.06437,634.0,0.59800,0.524174,0.262087,0.131044,0.07123,3.679449e+00,-10.657138,3.679449e+00,7.358898e+00,8.395339e+00
29,ANTUSDT,1.50000,200.0,43.00000,10.682667,5.341333,2.670667,1.67400,3.190761e+00,-11.600000,3.190761e+00,6.381521e+00,2.568698e+01
36,ONEUSDT,0.03900,1000.0,0.38000,0.317266,0.158633,0.079316,0.04682,3.388143e+00,-20.051282,3.388143e+00,6.776286e+00,8.116190e+00
39,CELRUSDT,0.01331,500.0,0.19870,0.096519,0.048260,0.024130,0.01768,2.729611e+00,-32.832457,2.729611e+00,5.459222e+00,1.123869e+01

In [17]:
# multiplying the gap with the value of the drop for a reasonable recovery
exposuredrop = orangedrop
exposuredrop['Total']= exposuredrop['exposure']*exposuredrop['DROP']*exposuredrop['GapOrange']
#exposuredrop['Total']= exposuredrop['DROP']*exposuredrop['GapOrange']*exposuredrop['CLOSERATIO']
#exposuredrop['Total']= exposuredrop['GapOrange']*exposuredrop['DROP']
#exposuredrop = exposuredrop.loc[exposuredrop['DROP']>0]

#exposuredrop.sort_values(by=['GapOrange'],ascending=False,inplace = True)
#exposuredrop.sort_values(by=['CLOSERATIO'],ascending=False,inplace = True)

exposuredrop

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total
57,LUNAUSDT,13.00000,4000.0,119.55000,149.192386,74.596193,37.298096,0.00005,1.491924e+06,99.999615,1.491924e+06,2.983848e+06,2.391000e+06,5.967672e+11
7,MIRUSDT,2.34300,85.0,14.55000,2.745529,1.372764,0.686382,0.24083,5.700138e+00,89.721297,5.700138e+00,1.140028e+01,6.041606e+01,4.347102e+04
20,SUSHIUSDT,3.50000,2730.0,23.43000,7.781429,3.890714,1.945357,1.32400,2.938606e+00,62.171429,2.938606e+00,5.877212e+00,1.769637e+01,4.987637e+05
46,FILUSDT,20.00000,2000.0,430.00000,40.606667,20.303333,10.151667,8.09000,2.509683e+00,59.550000,2.509683e+00,5.019365e+00,5.315204e+01,2.989032e+05
30,RAYUSDT,2.50000,100.0,17.80000,6.379714,3.189857,1.594929,1.17900,2.705562e+00,52.840000,2.705562e+00,5.411123e+00,1.509754e+01,1.429619e+04
33,TFUELUSDT,0.13000,344.0,0.67999,0.323552,0.161776,0.080888,0.06320,2.559750e+00,51.384615,2.559750e+00,5.119500e+00,1.075934e+01,4.524693e+04
66,PERPUSDT,2.22000,300.0,26.21000,10.202857,5.101429,2.550714,1.13000,4.514539e+00,49.099099,4.514539e+00,9.029077e+00,2.319469e+01,6.649793e+04
25,LINAUSDT,0.01759,205.0,1.00000,0.046729,0.023364,0.011682,0.00927,2.520419e+00,47.299602,2.520419e+00,5.040838e+00,1.078749e+02,2.443904e+04
23,HNTUSDT,13.90000,1250.0,59.27000,45.756190,22.878095,11.439048,8.34000,2.743177e+00,40.000000,2.743177e+00,5.486354e+00,7.106715e+00,1.371588e+05
49,FTMUSDT,0.31000,2000.0,3.48420,3.079305,1.539652,0.769826,0.34200,4.501908e+00,-10.322581,4.501908e+00,9.003815e+00,1.018772e+01,-9.294261e+04
31,ROSEUSDT,0.06437,634.0,0.59800,0.524174,0.262087,0.131044,0.07123,3.679449e+00,-10.657138,3.679449e+00,7.358898e+00,8.395339e+00,-2.486066e+04
29,ANTUSDT,1.50000,200.0,43.00000,10.682667,5.341333,2.670667,1.67400,3.190761e+00,-11.600000,3.190761e+00,6.381521e+00,2.568698e+01,-7.402565e+03
36,ONEUSDT,0.03900,1000.0,0.38000,0.317266,0.158633,0.079316,0.04682,3.388143e+00,-20.051282,3.388143e+00,6.776286e+00,8.116190e+00,-6.793661e+04
39,CELRUSDT,0.01331,500.0,0.19870,0.096519,0.048260,0.024130,0.01768,2.729611e+00,-32.832457,2.729611e+00,5.459222e+00,1.123869e+01,-4.480992e+04

In [18]:
exposuredrop.to_csv("exposuredrop.csv")

In [19]:
# easy band and cap ratio
capratio = pd.read_csv('capratio.csv')
capratio = pd.DataFrame(capratio,columns=['Indicator','supply_ratio','cap_ratio'])
capratio

exposuredrop = exposuredrop.merge(capratio ,how='left',on=['Indicator'])
sort = exposuredrop.sort_values(by=['Total'],ascending=False,inplace = True)

exposuredrop

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total,supply_ratio,cap_ratio
0,LUNAUSDT,13.00000,4000.0,119.55000,149.192386,74.596193,37.298096,0.00005,1.491924e+06,99.999615,1.491924e+06,2.983848e+06,2.391000e+06,5.967672e+11,NaN,NaN
2,SUSHIUSDT,3.50000,2730.0,23.43000,7.781429,3.890714,1.945357,1.32400,2.938606e+00,62.171429,2.938606e+00,5.877212e+00,1.769637e+01,4.987637e+05,0.771157,0.771157
3,FILUSDT,20.00000,2000.0,430.00000,40.606667,20.303333,10.151667,8.09000,2.509683e+00,59.550000,2.509683e+00,5.019365e+00,5.315204e+01,2.989032e+05,NaN,NaN
8,HNTUSDT,13.90000,1250.0,59.27000,45.756190,22.878095,11.439048,8.34000,2.743177e+00,40.000000,2.743177e+00,5.486354e+00,7.106715e+00,1.371588e+05,NaN,NaN
6,PERPUSDT,2.22000,300.0,26.21000,10.202857,5.101429,2.550714,1.13000,4.514539e+00,49.099099,4.514539e+00,9.029077e+00,2.319469e+01,6.649793e+04,NaN,NaN
5,TFUELUSDT,0.13000,344.0,0.67999,0.323552,0.161776,0.080888,0.06320,2.559750e+00,51.384615,2.559750e+00,5.119500e+00,1.075934e+01,4.524693e+04,NaN,NaN
1,MIRUSDT,2.34300,85.0,14.55000,2.745529,1.372764,0.686382,0.24083,5.700138e+00,89.721297,5.700138e+00,1.140028e+01,6.041606e+01,4.347102e+04,NaN,NaN
7,LINAUSDT,0.01759,205.0,1.00000,0.046729,0.023364,0.011682,0.00927,2.520419e+00,47.299602,2.520419e+00,5.040838e+00,1.078749e+02,2.443904e+04,NaN,NaN
4,RAYUSDT,2.50000,100.0,17.80000,6.379714,3.189857,1.594929,1.17900,2.705562e+00,52.840000,2.705562e+00,5.411123e+00,1.509754e+01,1.429619e+04,NaN,NaN
11,ANTUSDT,1.50000,200.0,43.00000,10.682667,5.341333,2.670667,1.67400,3.190761e+00,-11.600000,3.190761e+00,6.381521e+00,2.568698e+01,-7.402565e+03,NaN,NaN
10,ROSEUSDT,0.06437,634.0,0.59800,0.524174,0.262087,0.131044,0.07123,3.679449e+00,-10.657138,3.679449e+00,7.358898e+00,8.395339e+00,-2.486066e+04,NaN,NaN
13,CELRUSDT,0.01331,500.0,0.19870,0.096519,0.048260,0.024130,0.01768,2.729611e+00,-32.832457,2.729611e+00,5.459222e+00,1.123869e+01,-4.480992e+04,NaN,NaN
12,ONEUSDT,0.03900,1000.0,0.38000,0.317266,0.158633,0.079316,0.04682,3.388143e+00,-20.051282,3.388143e+00,6.776286e+00,8.116190e+00,-6.793661e+04,0.916981,0.916981
9,FTMUSDT,0.31000,2000.0,3.48420,3.079305,1.539652,0.769826,0.34200,4.501908e+00,-10.322581,4.501908e+00,9.003815e+00,1.018772e+01,-9.294261e+04,0.800363,0.800363

In [20]:
undergreen = exposuredrop.loc[exposuredrop['Current'] < exposuredrop['GREEN']]
undergreen.sort_values(by=['ORatio'],ascending=False,inplace = True)
undergreen

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total,supply_ratio,cap_ratio
0,LUNAUSDT,13.00000,4000.0,119.55000,149.192386,74.596193,37.298096,0.00005,1.491924e+06,99.999615,1.491924e+06,2.983848e+06,2.391000e+06,5.967672e+11,NaN,NaN
1,MIRUSDT,2.34300,85.0,14.55000,2.745529,1.372764,0.686382,0.24083,5.700138e+00,89.721297,5.700138e+00,1.140028e+01,6.041606e+01,4.347102e+04,NaN,NaN
6,PERPUSDT,2.22000,300.0,26.21000,10.202857,5.101429,2.550714,1.13000,4.514539e+00,49.099099,4.514539e+00,9.029077e+00,2.319469e+01,6.649793e+04,NaN,NaN
9,FTMUSDT,0.31000,2000.0,3.48420,3.079305,1.539652,0.769826,0.34200,4.501908e+00,-10.322581,4.501908e+00,9.003815e+00,1.018772e+01,-9.294261e+04,0.800363,0.800363
10,ROSEUSDT,0.06437,634.0,0.59800,0.524174,0.262087,0.131044,0.07123,3.679449e+00,-10.657138,3.679449e+00,7.358898e+00,8.395339e+00,-2.486066e+04,NaN,NaN
12,ONEUSDT,0.03900,1000.0,0.38000,0.317266,0.158633,0.079316,0.04682,3.388143e+00,-20.051282,3.388143e+00,6.776286e+00,8.116190e+00,-6.793661e+04,0.916981,0.916981
11,ANTUSDT,1.50000,200.0,43.00000,10.682667,5.341333,2.670667,1.67400,3.190761e+00,-11.600000,3.190761e+00,6.381521e+00,2.568698e+01,-7.402565e+03,NaN,NaN
2,SUSHIUSDT,3.50000,2730.0,23.43000,7.781429,3.890714,1.945357,1.32400,2.938606e+00,62.171429,2.938606e+00,5.877212e+00,1.769637e+01,4.987637e+05,0.771157,0.771157
8,HNTUSDT,13.90000,1250.0,59.27000,45.756190,22.878095,11.439048,8.34000,2.743177e+00,40.000000,2.743177e+00,5.486354e+00,7.106715e+00,1.371588e+05,NaN,NaN
13,CELRUSDT,0.01331,500.0,0.19870,0.096519,0.048260,0.024130,0.01768,2.729611e+00,-32.832457,2.729611e+00,5.459222e+00,1.123869e+01,-4.480992e+04,NaN,NaN
4,RAYUSDT,2.50000,100.0,17.80000,6.379714,3.189857,1.594929,1.17900,2.705562e+00,52.840000,2.705562e+00,5.411123e+00,1.509754e+01,1.429619e+04,NaN,NaN
5,TFUELUSDT,0.13000,344.0,0.67999,0.323552,0.161776,0.080888,0.06320,2.559750e+00,51.384615,2.559750e+00,5.119500e+00,1.075934e+01,4.524693e+04,NaN,NaN
7,LINAUSDT,0.01759,205.0,1.00000,0.046729,0.023364,0.011682,0.00927,2.520419e+00,47.299602,2.520419e+00,5.040838e+00,1.078749e+02,2.443904e+04,NaN,NaN
3,FILUSDT,20.00000,2000.0,430.00000,40.606667,20.303333,10.151667,8.09000,2.509683e+00,59.550000,2.509683e+00,5.019365e+00,5.315204e+01,2.989032e+05,NaN,NaN