In [1]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta


#Data Source(Pandas Data Reader)

In [2]:
whitelist = 'LINA/USDT, CHR/USDT, ORN/USDT, VIDT/USDT, IRIS/USDT, SHIB/USDT, MATIC/USDT,ALGO/USDT, BTC/USDT, ETH/USDT, AXS/USDT, SOL/USDT, MATIC/USDT, ADA/USDT, BNB/USDT, FIL/USDT, XRP/USDT, CVC/USDT, FTM/USDT, ICP/USDT, DOGE/USDT, XEC/USDT, IOTA/USDT, AVAX/USDT, DOT/USDT, LTC/USDT, EOS/USDT, IOST/USDT, STMX/USDT, FTT/USDT, TWT/USDT, ALICE/USDT, ATA/USDT, ETC/USDT, VET/USDT, SAND/USDT, LINK/USDT, THETA/USDT, SHIB/USDT, CHZ/USDT, LUNA/USDT, IOTX/USDT, TRX/USDT, TLM/USDT, BCH/USDT, REEF/USDT, CAKE/USDT, NEO/USDT,RVN/USDT, ATOM/USDT, SUSHI/USDT, ARDR/USDT, OMG/USDT, GRT/USDT, 1INCH/USDT, AAVE/USDT, C98/USDT, UNI/USDT, HBAR/USDT, CRV/USDT, DENT/USDT, MBOX/USDT, BTT/USDT, SRM/USDT, YFI/USDT, HOT/USDT, XLM/USDT, FIS/USDT, REQ/USDT, SXP/USDT, KSM/USDT, QNT/USDT, NEAR/USDT, COMP/USDT, QTUM/USDT, CHR/USDT, SC/USDT, XVS/USDT, ONT/USDT, COTI/USDT, NKN/USDT, RUNE/USDT, ANKR/USDT, MANA/USDT, CTXC/USDT, AR/USDT, RAY/USDT, BAKE/USDT, ARPA/USDT, XTZ/USDT, ZIL/USDT, ONG/USDT, ROSE/USDT, PNT/USDT, ALGO/USDT, MINA/USDT, WIN/USDT, AUDIO/USDT, STORJ/USDT, EPS/USDT, MDX/USDT, ZEC/USDT, ENJ/USDT, HIVE/USDT, TFUEL/USDT, WRX/USDT, SNX/USDT, SKL/USDT, LINA/USDT, DODO/USDT, UNFI/USDT, XEM/USDT, EGLD/USDT, ICX/USDT, WAVES/USDT, ONE/USDT, DASH/USDT, KAVA/USDT, SUPER/USDT, TKO/USDT, OGN/USDT, XMR/USDT, OCEAN/USDT, CELO/USDT, BAT/USDT, FUN/USDT, LRC/USDT, ALPHA/USDT, MASK/USDT, TRU/USDT, DNT/USDT, LIT/USDT, FET/USDT, GTC/USDT, CELR/USDT, DEXE/USDT, ZEN/USDT, WAXP/USDT, CTSI/USDT, HNT/USDT, YFII/USDT, BEL/USDT, ZRX/USDT, DEGO/USDT, RSR/USDT, COS/USDT, FLM/USDT, BAL/USDT, MFT/USDT, RLC/USDT, KNC/USDT, REN/USDT, INJ/USDT, FLOW/USDT, SFP/USDT, BAND/USDT, CTK/USDT, SUN/USDT, AKRO/USDT, XVG/USDT, NANO/USDT, STRAX/USDT, PUNDIX/USDT, TVK/USDT, MKR/USDT, CLV/USDT, TRB/USDT, ETHUP/USDT, KEEP/USDT, TCT/USDT, POND/USDT, LTO/USDT, ANT/USDT, TOMO/USDT, ACM/USDT, FIO/USDT, VITE/USDT, MBL/USDT, JST/USDT, MTL/USDT, UTK/USDT, BLZ/USDT, ORN/USDT, STPT/USDT, CFX/USDT, OM/USDT, PERP/USDT, MIR/USDT, STX/USDT, ERN/USDT, TUSD/USDT, PSG/USDT, NULS/USDT, OXT/USDT, REP/USDT, BNBUP/USDT, DATA/USDT, WAN/USDT, BURGER/USDT, RAMP/USDT, ATM/USDT, DGB/USDT, DIA/USDT, BEAM/USDT, UMA/USDT, ETHDOWN/USDT, CKB/USDT, TRIBE/USDT, FARM/USDT, BTCUP/USDT, BZRX/USDT, ALPACA/USDT, DOTUP/USDT, BTS/USDT, FOR/USDT, ADAUP/USDT, HARD/USDT, LSK/USDT, POLS/USDT, FORTH/USDT, TORN/USDT, VTHO/USDT, BTG/USDT, QUICK/USDT, FILUP/USDT, PAX/USDT, MITH/USDT, SUSHIUP/USDT, BTCDOWN/USDT, XRPDOWN/USDT, BNBDOWN/USDT, DUSK/USDT, XRPUP/USDT, WTC/USDT, DOCK/USDT, AUTO/USDT, BTCST/USDT, KLAY/USDT, WNXM/USDT, KEY/USDT, FILDOWN/USDT, NU/USDT, IRIS/USDT, KMD/USDT, TROY/USDT, WING/USDT, AION/USDT, PHA/USDT, SUSHIDOWN/USDT, EOSUP/USDT, LTCUP/USDT, GHST/USDT, PAXG/USDT, BNT/USDT, AVA/USDT, BADGER/USDT, PERL/USDT, COCOS/USDT, GXS/USDT, MDT/USDT, 1INCHUP/USDT, GTO/USDT, LINKUP/USDT, AAVEUP/USDT, FIRO/USDT, JUV/USDT, MLN/USDT, UNIUP/USDT, LPT/USDT, NMR/USDT, AAVEDOWN/USDT, 1INCHDOWN/USDT, ASR/USDT, OG/USDT, BAR/USDT, DREP/USDT, BOND/USDT, DCR/USDT, GNO/USDT, NBS/USDT, RIF/USDT, NEAR/USDT'
#whitelist = 'LINK/USDT, DOT/USDT'
startdate = '2020-01-01'
enddate = '2022-02-17'
interval = '1w'

In [3]:
def FRSI(series, period=14):
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    return 100 - (100 / (1 + rs))


# calculating Stoch RSI (gives the same values as TradingView)
# https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI) 
def STRSIA(series, period=14, smoothK=3, smoothD=3):
    # Calculate RSI 
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    rsi = 100 - 100 / (1 + rs)

    # Calculate StochRSI 
    stochrsi  = (rsi - rsi.rolling(period).min()) / (rsi.rolling(period).max() - rsi.rolling(period).min())
    stochrsi_K = stochrsi.rolling(smoothK).mean()
    stochrsi_D = stochrsi_K.rolling(smoothD).mean()
    return stochrsi, stochrsi_K, stochrsi_D

#Calulate SMA 
def SMA(series,size):
    sma = series.rolling(size).mean()
    return sma
#Calculate SMA55

In [4]:
whitelist=whitelist.lstrip()
array = whitelist.split(",")
array
wl = []
bl = []
blacklist = ""
whitelist = ""
symbols =[]
for i in range(0 ,len(array)):
    if (array[i].find('DOWN') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])
    elif (array[i].find('UP') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])

    else:
        wl.append(str(array[i]).lstrip().replace("/",""))
        whitelist +=str(array[i]).lstrip()
        #print ("Doesn't contains given substring")
    

    
#symbols to be used to get the prices from binance url
symbols = np.array(wl)


## get the data 
import os

live = pd.to_datetime('today')
start = pd.to_datetime(startdate)
end = pd.to_datetime(enddate)

root_url = 'https://api.binance.com/api/v1/klines'
symbol = 'STEEMETH'
#interval = '1d'
url = root_url + '?symbol=' + symbol + '&interval=' + interval
print(url)


directory = 'BN-main'
table = []
   
      
        

for symbol in symbols:
        url = root_url + '?symbol=' + symbol + '&interval=' + interval
        data = json.loads(requests.get(url).text)
        dflive = pd.DataFrame(data ,columns =['open_time',
              'o', 'h', 'l', 'c', 'v',
              'close_time', 'qav', 'num_trades',
              'taker_base_vol', 'taker_quote_vol', 'ignore'])
        dflive.open_time = pd.to_datetime(dflive['open_time'],unit='ms')
        dflive=dflive.loc[(dflive.open_time>start)]
        
        dflive = dflive.astype ({'o': float ,'h':float,'l':float ,'c':float ,'v':float})
        dflive['SMA21'] = SMA(dflive['c'],21)
        dflive['SMA55'] = SMA(dflive['c'],55)
        dflive['SMA100'] = SMA(dflive['c'],100)
        
        
        
        
        lastrow = dflive.iloc[-1]
        now = float(lastrow.c)
        SMA21 = float(lastrow.SMA21)
        SMA55 = float(lastrow.SMA55)
        SMA100 = float(lastrow.SMA100)
        
        
        alth = dflive.h.max()
        altl = dflive.l.min()
        
        
        ## past 1 month 
        past_month = end - relativedelta(months=1)
        
        back1Mdata = dflive.loc[(dflive.open_time> past_month)]
        omh = back1Mdata.h.max()
        oml = back1Mdata.l.min()
        ## past 2 month
        
        past_2month = end - relativedelta(months=2)
        back2Mdata = dflive.loc[(dflive.open_time> past_2month)]
        tmh = back2Mdata.h.max()
        tml = back2Mdata.l.min()
        ## past 3 month 
        
        past_3month = end - relativedelta(months=3)
        back3Mdata = dflive.loc[(dflive.open_time> past_3month)]
        thmh = back3Mdata.h.max()
        thml = back3Mdata.l.min()
        
 
        tuple =(symbol,alth,altl,now,omh,oml,tmh,tml,thmh,thml,SMA21,SMA55,SMA100,)
        table.append(tuple)
        del dflive
        #print("name is: ",array[0] ,alth,altl)
        #print("name is: ",symbol)
        

table[0]
AllTime = pd.DataFrame(table,columns=['Indicator','ATH','ATL','Current','OMH','OML','TMH','TML','THMH','THML','SMA21','SMA55','SMA100'])
AllTime.ATH=AllTime.ATH.astype(float)
AllTime.ATL=AllTime.ATL.astype(float)
AllTime.Current=AllTime.Current.astype(float)
AllTime.OMH=AllTime.OMH.astype(float)
AllTime.OML=AllTime.OML.astype(float)
AllTime.TMH=AllTime.TMH.astype(float)
AllTime.TML=AllTime.TML.astype(float)
AllTime.THMH=AllTime.THMH.astype(float)
AllTime.THML=AllTime.THML.astype(float)
AllTime.dtypes

AllTime['ALLTIME']=(AllTime['Current']/AllTime['ATH'])*100
AllTime['MONTH']=(AllTime['Current']/AllTime['OMH'])*100
AllTime['2MONTH']=(AllTime['Current']/AllTime['TMH'])*100
AllTime['3MONTH']=(AllTime['Current']/AllTime['THMH'])*100
AllTime['SMADIFF']= abs(AllTime['SMA21']- AllTime['SMA55'])
AllTime['SMARATIO']= (AllTime['SMA21']/AllTime['SMA55'])
AllTime['CLOSERATIO']= (abs(AllTime['Current']- AllTime['SMA100'])/AllTime['SMA100'])
AllTime['GREENEASY'] = (AllTime['SMA21'])/2


AllTime.sort_values(by=['ALLTIME'],ascending=True,inplace = True)
#AllTime.sort_values(by='ATH',ascending=False)
#AllTime.to_csv("alltimeHL.csv", mode="w")
#data.sort_values("Name", axis = 0, ascending = True,inplace = True, na_position ='last')

## Display the Data 
AllTime

https://api.binance.com/api/v1/klines?symbol=STEEMETH&interval=1w

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,...,SMA55,SMA100,ALLTIME,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,CLOSERATIO,GREENEASY
156,SUNUSDT,54.56,0.01066,0.01154,0.0194,0.01066,0.02548,0.01066,0.03424,0.01066,...,9.032188,NaN,0.021151,59.484536,45.290424,33.703271,9.007618,0.002720,NaN,0.012285
217,PAXUSDT,999.00,0.93880,0.99960,NaN,NaN,NaN,NaN,NaN,NaN,...,0.999524,NaN,0.100060,NaN,NaN,NaN,0.000014,0.999986,NaN,0.499755
19,ICPUSDT,2831.02,14.68000,16.62000,24.6800,14.68000,38.02000,14.68000,45.92000,14.68000,...,NaN,NaN,0.587068,67.341977,43.713835,36.193380,NaN,NaN,NaN,16.333095
99,EPSUSDT,22.50,0.14180,0.15770,0.2950,0.14180,0.35760,0.14180,0.52000,0.14180,...,NaN,NaN,0.700889,53.457627,44.099553,30.326923,NaN,NaN,NaN,0.172064
223,BTCSTUSDT,1000.00,8.00000,13.58000,19.1700,12.21000,27.71000,12.21000,36.63000,12.21000,...,53.699327,NaN,1.358000,70.839854,49.007578,37.073437,26.745042,0.501948,NaN,13.477143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,ETHUSDT,4868.00,86.00000,2666.76000,3283.6600,2159.00000,4150.00000,2159.00000,4778.75000,2159.00000,...,2960.473455,1841.970,54.781430,81.213037,64.259277,55.804551,678.555593,1.229205,0.447776,1819.514524
8,BTCUSDT,69000.00,3782.13000,38437.99000,45821.0000,32917.17000,52088.00000,32917.17000,59444.00000,32917.17000,...,47700.573636,33005.667,55.707232,83.887279,73.794329,64.662523,2182.477316,1.045754,0.164588,24941.525476
234,GHSTUSDT,3.40,1.50800,1.97200,2.1260,1.92600,2.64500,1.92600,3.40000,1.92600,...,NaN,NaN,58.000000,92.756350,74.555766,58.000000,NaN,NaN,NaN,1.092190
40,LUNAUSDT,103.60,0.27330,62.30000,69.8100,43.44000,103.60000,43.44000,103.60000,37.82000,...,32.699271,NaN,60.135135,89.242229,60.135135,60.135135,26.785015,1.819132,NaN,29.742143
235,PAXGUSDT,2100.85,1687.57000,1913.00000,2076.0000,1787.00000,2076.00000,1772.00000,2076.00000,1759.00000,...,1810.390364,NaN,91.058381,92.148362,92.148362,92.148362,12.514398,1.006913,NaN,911.452381

In [7]:
#drop = AllTime.loc[(AllTime['RSI'] < 30)& (AllTime['STRSI'] < 0.1)]
#drop = AllTime.loc[(AllTime['SMARATIO'] <  1.05 ) &(AllTime['SMARATIO'] > 0.95)& (AllTime['ALLTIME'] <70) ]
#drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21'])]
drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21']/2)]

#drop = AllTime.loc[(AllTime['SMARATIO'] <  1 ) &(AllTime['SMARATIO'] > 0.95) & (AllTime['ALLTIME'] <70)]

#drop = AllTime.loc[(AllTime['MONTH'] < 80)&(AllTime[ '2MONTH'] < 70)&(AllTime['ALLTIME'] < 40)]
#drop = AllTime.loc[(AllTime['MONTH'] <70)&(AllTime['2MONTH'] > (AllTime['3MONTH']))]

sort = drop.sort_values(by=['CLOSERATIO'],ascending=False,inplace = True) 
#sort = drop.sort_values(by=['ALLTIME'],ascending=True,inplace = True) 

#drop = drop.loc[(drop['ALLTIME'] < drop['3MONTH'])]
display = drop[['Indicator','ATH','CLOSERATIO','SMA100','SMA55','Current']]
#print(drop)
save = drop[['Indicator','ATH','CLOSERATIO','SMA21','SMA55','GREENEASY']]
print(save)
print("Low EASY Band")
print(display.iloc[0:60,0:14])
print(display.iloc[60:110,])
print(display.iloc[110:160,])

    Indicator      ATH  CLOSERATIO      SMA21      SMA55  GREENEASY
119   OGNUSDT    3.390    0.541725   0.677038   0.896055   0.338519
194   WANUSDT    2.635    0.471828   0.690752   0.902965   0.345376
150   RENUSDT    1.840    0.453398   0.641833   0.711902   0.320917
113   ICXUSDT    3.200    0.405116   1.429048   1.524247   0.714524
171  TOMOUSDT    3.920    0.384439   1.983905   2.236189   0.991952
..        ...      ...         ...        ...        ...        ...
57    UNIUSDT   45.000         NaN  17.762381  23.318464   8.881190
135   ZENUSDT  169.230         NaN  67.571905  73.841727  33.785952
122  CELOUSDT   10.957         NaN   4.598810   4.238189   2.299405
3    VIDTUSDT    1.420         NaN   0.797681        NaN   0.398840
10    AXSUSDT  166.090         NaN  98.340952  54.061986  49.170476

[73 rows x 6 columns]
Low EASY Band
      Indicator         ATH  CLOSERATIO    SMA100       SMA55     Current
119     OGNUSDT    3.390000    0.541725  0.595494    0.896055    0.272900
194     WANUSDT    2.635000    0.471828  0.623660    0.902965    0.329400
150     RENUSDT    1.840000    0.453398  0.512256    0.711902    0.280000
113     ICXUSDT    3.200000    0.405116  1.025410    1.524247    0.610000
171    TOMOUSDT    3.920000    0.384439  1.561177    2.236189    0.961000
230    TROYUSDT    0.040128    0.377717  0.008535    0.012521    0.005311
221    DOCKUSDT    0.182000    0.361097  0.049303    0.078431    0.031500
159    NANOUSDT   17.700000    0.344233  3.391447    5.404011    2.224000
148     RLCUSDT   16.500000    0.318424  2.294683    3.434436    1.564000
34      VETUSDT    0.279829    0.313805  0.064122    0.105206    0.044000
52      OMGUSDT   20.124000    0.277030  5.160658    7.234564    3.731000
105     WRXUSDT    6.666600    0.268988  0.766061    1.302643    0.560000
65      HOTUSDT    0.031600    0.211138  0.005230    0.009026    0.004126
131     FETUSDT    1.198500    0.150508  0.307831    0.513721    0.261500
80      NKNUSDT    1.489000    0.107702  0.205537    0.355597    0.183400
133    CELRUSDT    0.198700    0.075366  0.039335    0.067187    0.036370
156     SUNUSDT   54.560000         NaN       NaN    9.032188    0.011540
99      EPSUSDT   22.500000         NaN       NaN         NaN    0.157700
43      TLMUSDT    5.950000         NaN       NaN         NaN    0.099400
108    LINAUSDT    1.000000         NaN       NaN         NaN    0.018390
0      LINAUSDT    1.000000         NaN       NaN         NaN    0.018420
45     REEFUSDT    0.300000         NaN       NaN    0.024922    0.009380
145     FLMUSDT    4.500000         NaN       NaN    0.516031    0.190300
109    DODOUSDT   10.000000         NaN       NaN         NaN    0.423000
140     BELUSDT   19.000000         NaN       NaN    2.167022    0.808000
15      FILUSDT  430.000000         NaN       NaN   67.858102   18.400000
195  BURGERUSDT   29.000000         NaN       NaN         NaN    1.332000
87     BAKEUSDT    8.487000         NaN       NaN         NaN    0.520000
196    RAMPUSDT    1.300000         NaN       NaN         NaN    0.079900
118     TKOUSDT   10.000000         NaN       NaN         NaN    0.639000
130     LITUSDT   18.826400         NaN       NaN    4.964311    1.227000
251     BARUSDT   73.800000         NaN       NaN         NaN    5.050000
185     MIRUSDT   14.550000         NaN       NaN         NaN    1.064000
142    DEGOUSDT   34.700000         NaN       NaN         NaN    2.640000
100     MDXUSDT    2.780000         NaN       NaN         NaN    0.216000
32      ATAUSDT    4.500000         NaN       NaN         NaN    0.358600
183      OMUSDT    0.887600         NaN       NaN         NaN    0.073500
168    PONDUSDT    0.318000         NaN       NaN         NaN    0.028180
253    BONDUSDT   75.000000         NaN       NaN         NaN    7.360000
126   ALPHAUSDT    2.943250         NaN       NaN    0.995999    0.298300
143     RSRUSDT    0.119000         NaN       NaN    0.043444    0.012710
201     UMAUSDT   43.998000         NaN       NaN   14.195436    4.826000
214    VTHOUSDT    0.028500         NaN       NaN    0.009131    0.003154
158     XVGUSDT    0.080000         NaN       NaN         NaN    0.008940
67      FISUSDT    4.880000         NaN       NaN         NaN    0.562200
165     TRBUSDT  164.050000         NaN       NaN   50.173291   19.070000
73     COMPUSDT  911.000000         NaN       NaN  362.968182  107.700000
238  BADGERUSDT   64.900000         NaN       NaN         NaN    7.740000
164     CLVUSDT    2.485000         NaN       NaN         NaN    0.313000
129     DNTUSDT    0.510000         NaN       NaN    0.184609    0.065000
63      SRMUSDT   13.732000         NaN       NaN    5.493713    1.837000
50    SUSHIUSDT   23.430000         NaN       NaN   10.503509    3.156000
157    AKROUSDT    0.088500         NaN       NaN    0.031914    0.012050
220     WTCUSDT    2.924200         NaN       NaN    0.983178    0.406600
153     SFPUSDT    4.450000         NaN       NaN    1.556231    0.619400
86      RAYUSDT   17.800000         NaN       NaN         NaN    2.540000
46     CAKEUSDT   44.278000         NaN       NaN         NaN    6.380000
97    AUDIOUSDT    4.990000         NaN       NaN    1.671075    0.770000
128     TRUUSDT    1.060000         NaN       NaN    0.374373    0.166400
81     RUNEUSDT   21.280000         NaN       NaN    8.365424    3.406000
     Indicator       ATH  CLOSERATIO  SMA100       SMA55   Current
54   1INCHUSDT    7.8748         NaN     NaN    3.334385    1.3330
233    PHAUSDT    1.2452         NaN     NaN         NaN    0.2212
162    TVKUSDT    0.5500         NaN     NaN         NaN    0.0986
127   MASKUSDT   22.5810         NaN     NaN         NaN    4.1410
70     KSMUSDT  625.0000         NaN     NaN  310.492036  117.1000
187    ERNUSDT   24.8000         NaN     NaN         NaN    4.7080
184   PERPUSDT   26.2100         NaN     NaN         NaN    5.0100
56     C98USDT    6.4450         NaN     NaN         NaN    1.2540
57     UNIUSDT   45.0000         NaN     NaN   23.318464    8.7700
135    ZENUSDT  169.2300         NaN     NaN   73.841727   33.1500
122   CELOUSDT   10.9570         NaN     NaN    4.238189    2.2720
3     VIDTUSDT    1.4200         NaN     NaN         NaN    0.3730
10     AXSUSDT  166.0900         NaN     NaN   54.061986   48.3200
Empty DataFrame
Columns: [Indicator, ATH, CLOSERATIO, SMA100, SMA55, Current]
Index: []

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [6]:
easybandlist = display['Indicator']
easybandlist

119     OGNUSDT
194     WANUSDT
150     RENUSDT
113     ICXUSDT
171    TOMOUSDT
         ...
57      UNIUSDT
135     ZENUSDT
122    CELOUSDT
3      VIDTUSDT
10      AXSUSDT
Name: Indicator, Length: 73, dtype: object

In [160]:
save.to_csv("easyband.csv")

In [9]:
display

    Indicator      ATH  CLOSERATIO    SMA100      SMA55  Current
119   OGNUSDT    3.390    0.541725  0.595494   0.896055   0.2729
194   WANUSDT    2.635    0.471828  0.623660   0.902965   0.3294
150   RENUSDT    1.840    0.453398  0.512256   0.711902   0.2800
113   ICXUSDT    3.200    0.405116  1.025410   1.524247   0.6100
171  TOMOUSDT    3.920    0.384439  1.561177   2.236189   0.9610
..        ...      ...         ...       ...        ...      ...
57    UNIUSDT   45.000         NaN       NaN  23.318464   8.7700
135   ZENUSDT  169.230         NaN       NaN  73.841727  33.1500
122  CELOUSDT   10.957         NaN       NaN   4.238189   2.2720
3    VIDTUSDT    1.420         NaN       NaN        NaN   0.3730
10    AXSUSDT  166.090         NaN       NaN  54.061986  48.3200

[73 rows x 6 columns]