Generate the easy band in the first section based on live data 
compare it to the entries in the second part

In [44]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta


#Data Source(Pandas Data Reader)

In [45]:
whitelist = 'POWR/USDT, MDT/USDT,BLZ/USDT, CHR/USDT, ORN/USDT, VIDT/USDT, IRIS/USDT, SHIB/USDT, MATIC/USDT,ALGO/USDT, BTC/USDT, ETH/USDT, AXS/USDT, SOL/USDT, MATIC/USDT, ADA/USDT, BNB/USDT, FIL/USDT, XRP/USDT, CVC/USDT, FTM/USDT, ICP/USDT, DOGE/USDT, XEC/USDT, IOTA/USDT, AVAX/USDT, DOT/USDT, LTC/USDT, EOS/USDT, IOST/USDT, STMX/USDT, FTT/USDT, TWT/USDT, ALICE/USDT, ATA/USDT, ETC/USDT, VET/USDT, SAND/USDT, LINK/USDT, THETA/USDT, SHIB/USDT, CHZ/USDT, LUNA/USDT, IOTX/USDT, TRX/USDT, TLM/USDT, BCH/USDT, REEF/USDT, CAKE/USDT, NEO/USDT,RVN/USDT, ATOM/USDT, SUSHI/USDT, ARDR/USDT, OMG/USDT, GRT/USDT, 1INCH/USDT, AAVE/USDT, C98/USDT, UNI/USDT, HBAR/USDT, CRV/USDT, DENT/USDT, MBOX/USDT, BTT/USDT, SRM/USDT, YFI/USDT, HOT/USDT, XLM/USDT, FIS/USDT, REQ/USDT, SXP/USDT, KSM/USDT, QNT/USDT, NEAR/USDT, COMP/USDT, QTUM/USDT, CHR/USDT, SC/USDT, XVS/USDT, ONT/USDT, COTI/USDT, NKN/USDT, RUNE/USDT, ANKR/USDT, MANA/USDT, CTXC/USDT, AR/USDT, RAY/USDT, BAKE/USDT, ARPA/USDT, XTZ/USDT, ZIL/USDT, ONG/USDT, ROSE/USDT, PNT/USDT,MINA/USDT, WIN/USDT, AUDIO/USDT, STORJ/USDT, EPS/USDT, MDX/USDT, ZEC/USDT, ENJ/USDT, HIVE/USDT, TFUEL/USDT, WRX/USDT, SNX/USDT, SKL/USDT, LINA/USDT, DODO/USDT, UNFI/USDT, XEM/USDT, EGLD/USDT, ICX/USDT, WAVES/USDT, ONE/USDT, DASH/USDT, KAVA/USDT, SUPER/USDT, TKO/USDT, OGN/USDT, XMR/USDT, OCEAN/USDT, CELO/USDT, BAT/USDT, FUN/USDT, LRC/USDT, ALPHA/USDT, MASK/USDT, TRU/USDT, DNT/USDT, LIT/USDT, FET/USDT, GTC/USDT, CELR/USDT, DEXE/USDT, ZEN/USDT, WAXP/USDT, CTSI/USDT, HNT/USDT, YFII/USDT, BEL/USDT, ZRX/USDT, DEGO/USDT, RSR/USDT, COS/USDT, FLM/USDT, BAL/USDT, MFT/USDT, RLC/USDT, KNC/USDT, REN/USDT, INJ/USDT, FLOW/USDT, SFP/USDT, BAND/USDT, CTK/USDT, SUN/USDT, AKRO/USDT, XVG/USDT, NANO/USDT, STRAX/USDT, PUNDIX/USDT, TVK/USDT, MKR/USDT, CLV/USDT, TRB/USDT, ETHUP/USDT, KEEP/USDT, TCT/USDT, POND/USDT, LTO/USDT, ANT/USDT, TOMO/USDT, ACM/USDT, FIO/USDT, VITE/USDT, MBL/USDT, JST/USDT, MTL/USDT, UTK/USDT, BLZ/USDT, ORN/USDT, STPT/USDT, CFX/USDT, OM/USDT, PERP/USDT, MIR/USDT, STX/USDT, ERN/USDT, TUSD/USDT, PSG/USDT, NULS/USDT, OXT/USDT, REP/USDT, BNBUP/USDT, DATA/USDT, WAN/USDT, BURGER/USDT, RAMP/USDT, ATM/USDT, DGB/USDT, DIA/USDT, BEAM/USDT, UMA/USDT, ETHDOWN/USDT, CKB/USDT, TRIBE/USDT, FARM/USDT, BTCUP/USDT, BZRX/USDT, ALPACA/USDT, DOTUP/USDT, BTS/USDT, FOR/USDT, ADAUP/USDT, HARD/USDT, LSK/USDT, POLS/USDT, FORTH/USDT, TORN/USDT, VTHO/USDT, BTG/USDT, QUICK/USDT, FILUP/USDT, PAX/USDT, MITH/USDT, SUSHIUP/USDT, BTCDOWN/USDT, XRPDOWN/USDT, BNBDOWN/USDT, DUSK/USDT, XRPUP/USDT, WTC/USDT, DOCK/USDT, AUTO/USDT, BTCST/USDT, KLAY/USDT, WNXM/USDT, KEY/USDT, FILDOWN/USDT, NU/USDT, IRIS/USDT, KMD/USDT, TROY/USDT, WING/USDT, AION/USDT, PHA/USDT, SUSHIDOWN/USDT, EOSUP/USDT, LTCUP/USDT, GHST/USDT, PAXG/USDT, BNT/USDT, AVA/USDT, BADGER/USDT, PERL/USDT, COCOS/USDT, GXS/USDT, MDT/USDT, 1INCHUP/USDT, GTO/USDT, LINKUP/USDT, AAVEUP/USDT, FIRO/USDT, JUV/USDT, MLN/USDT, UNIUP/USDT, LPT/USDT, NMR/USDT, AAVEDOWN/USDT, 1INCHDOWN/USDT, ASR/USDT, OG/USDT, BAR/USDT, DREP/USDT, BOND/USDT, DCR/USDT, GNO/USDT, NBS/USDT, RIF/USDT'
#whitelist = 'LINK/USDT, DOT/USDT'
startdate = '2020-01-01'
enddate = '2022-03-22'
enddate = pd.to_datetime('today')

interval = '1w'

In [46]:
def FRSI(series, period=14):
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    return 100 - (100 / (1 + rs))


# calculating Stoch RSI (gives the same values as TradingView)
# https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI) 
def STRSIA(series, period=14, smoothK=3, smoothD=3):
    # Calculate RSI 
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    rsi = 100 - 100 / (1 + rs)

    # Calculate StochRSI 
    stochrsi  = (rsi - rsi.rolling(period).min()) / (rsi.rolling(period).max() - rsi.rolling(period).min())
    stochrsi_K = stochrsi.rolling(smoothK).mean()
    stochrsi_D = stochrsi_K.rolling(smoothD).mean()
    return stochrsi, stochrsi_K, stochrsi_D

#Calulate SMA 
def SMA(series,size):
    sma = series.rolling(size).mean()
    return sma
#Calculate SMA55

In [47]:
whitelist=whitelist.lstrip()
array = whitelist.split(",")
array
wl = []
bl = []
blacklist = ""
whitelist = ""
symbols =[]
for i in range(0 ,len(array)):
    if (array[i].find('DOWN') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])
    elif (array[i].find('UP') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])

    else:
        wl.append(str(array[i]).lstrip().replace("/",""))
        whitelist +=str(array[i]).lstrip()
        #print ("Doesn't contains given substring")
    

    
#symbols to be used to get the prices from binance url
symbols = np.array(wl)


## get the data 
import os

live = pd.to_datetime('today')
start = pd.to_datetime(startdate)
end = pd.to_datetime(enddate)

root_url = 'https://api.binance.com/api/v1/klines'
symbol = 'STEEMETH'
#interval = '1d'
url = root_url + '?symbol=' + symbol + '&interval=' + interval
print(url)


directory = 'BN-main'
table = []
   
      
        

for symbol in symbols:
        url = root_url + '?symbol=' + symbol + '&interval=' + interval
        data = json.loads(requests.get(url).text)
        dflive = pd.DataFrame(data ,columns =['open_time',
              'o', 'h', 'l', 'c', 'v',
              'close_time', 'qav', 'num_trades',
              'taker_base_vol', 'taker_quote_vol', 'ignore'])
        dflive.open_time = pd.to_datetime(dflive['open_time'],unit='ms')
        dflive=dflive.loc[(dflive.open_time>start)]
        
        dflive = dflive.astype ({'o': float ,'h':float,'l':float ,'c':float ,'v':float})
        dflive['SMA21'] = SMA(dflive['c'],21)
        dflive['SMA55'] = SMA(dflive['c'],55)
        dflive['SMA100'] = SMA(dflive['c'],100)
        
        
        
        #print(symbol)
        lastrow = dflive.iloc[-1]
        now = float(lastrow.c)
        SMA21 = float(lastrow.SMA21)
        SMA55 = float(lastrow.SMA55)
        SMA100 = float(lastrow.SMA100)
        
        
        alth = dflive.h.max()
        altl = dflive.l.min()
        
        
        ## past 1 month 
        past_month = end - relativedelta(months=1)
        
        back1Mdata = dflive.loc[(dflive.open_time> past_month)]
        omh = back1Mdata.h.max()
        oml = back1Mdata.l.min()
        ## past 2 month
        
        past_2month = end - relativedelta(months=2)
        back2Mdata = dflive.loc[(dflive.open_time> past_2month)]
        tmh = back2Mdata.h.max()
        tml = back2Mdata.l.min()
        ## past 3 month 
        
        past_3month = end - relativedelta(months=3)
        back3Mdata = dflive.loc[(dflive.open_time> past_3month)]
        thmh = back3Mdata.h.max()
        thml = back3Mdata.l.min()
        
 
        tuple =(symbol,alth,altl,now,omh,oml,tmh,tml,thmh,thml,SMA21,SMA55,SMA100,)
        table.append(tuple)
        del dflive
        #print("name is: ",array[0] ,alth,altl)
        #print("name is: ",symbol)
        

table[0]
AllTime = pd.DataFrame(table,columns=['Indicator','ATH','ATL','Current','OMH','OML','TMH','TML','THMH','THML','SMA21','SMA55','SMA100'])
AllTime.ATH=AllTime.ATH.astype(float)
AllTime.ATL=AllTime.ATL.astype(float)
AllTime.Current=AllTime.Current.astype(float)
AllTime.OMH=AllTime.OMH.astype(float)
AllTime.OML=AllTime.OML.astype(float)
AllTime.TMH=AllTime.TMH.astype(float)
AllTime.TML=AllTime.TML.astype(float)
AllTime.THMH=AllTime.THMH.astype(float)
AllTime.THML=AllTime.THML.astype(float)
AllTime.dtypes

AllTime['ALLTIME']=(AllTime['Current']/AllTime['ATH'])*100
AllTime['MONTH']=(AllTime['Current']/AllTime['OMH'])*100
AllTime['2MONTH']=(AllTime['Current']/AllTime['TMH'])*100
AllTime['3MONTH']=(AllTime['Current']/AllTime['THMH'])*100
AllTime['SMADIFF']= abs(AllTime['SMA21']- AllTime['SMA55'])
AllTime['SMARATIO']= (AllTime['SMA21']/AllTime['SMA55'])
AllTime['GREEN'] = (AllTime['SMA21'])/2
AllTime['GREEN15'] = (AllTime['SMA21'])/1.5
AllTime['ORANGE'] = (AllTime['SMA21'])
AllTime['RED'] = (AllTime['SMA21'])*2
AllTime['CLOSERATIO']= ((AllTime['Current']- AllTime['GREEN']))/AllTime['GREEN']



AllTime.sort_values(by=['ALLTIME'],ascending=True,inplace = True)
#AllTime.sort_values(by='ATH',ascending=False)
#AllTime.to_csv("alltimeHL.csv", mode="w")
#data.sort_values("Name", axis = 0, ascending = True,inplace = True, na_position ='last')

## Display the Data 
AllTime

https://api.binance.com/api/v1/klines?symbol=STEEMETH&interval=1w

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,...,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,GREEN,GREEN15,ORANGE,RED,CLOSERATIO
157,SUNUSDT,54.560,0.00843,0.00914,0.01709,0.00843,0.02039,0.00843,0.02039,0.00843,...,53.481568,44.825895,44.825895,3.554478,0.004287,0.007652,0.010203,0.015305,0.030610,0.194400
218,PAXUSDT,999.000,0.93880,0.99960,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.000014,0.999986,0.499755,0.666340,0.999510,1.999019,1.000181
21,ICPUSDT,2831.020,6.74000,6.80000,17.85000,6.74000,23.52000,6.74000,23.52000,6.74000,...,38.095238,28.911565,28.911565,NaN,NaN,9.911190,13.214921,19.822381,39.644762,-0.313907
42,LUNAUSDT,119.550,0.27330,0.35670,99.43000,0.35550,119.55000,0.35550,119.55000,0.35550,...,0.358745,0.298369,0.298369,28.552127,1.619876,37.306588,49.742117,74.613176,149.226352,-0.990439
45,TLMUSDT,5.950,0.02890,0.02920,0.10480,0.02890,0.14830,0.02890,0.14830,0.02890,...,27.862595,19.689818,19.689818,0.086690,0.581408,0.060205,0.080273,0.120410,0.240819,-0.514989
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,BTCUSDT,69000.000,3782.13000,28506.91000,42976.00000,27785.00000,48189.84000,27785.00000,48189.84000,27785.00000,...,66.332162,59.155436,59.155436,4187.405429,0.906310,20253.354286,27004.472381,40506.708571,81013.417143,0.407515
44,TRXUSDT,0.180,0.00684,0.07587,0.09279,0.05886,0.09279,0.05774,0.09279,0.05540,...,81.765276,81.765276,81.765276,0.013738,0.829776,0.033485,0.044646,0.066970,0.133939,1.265807
235,GHSTUSDT,3.400,1.50800,1.67400,1.95000,1.66800,2.19900,1.66800,2.19900,1.66800,...,85.846154,76.125512,76.125512,NaN,NaN,1.003690,1.338254,2.007381,4.014762,0.667845
167,KEEPUSDT,1.209,0.21130,0.62510,NaN,NaN,NaN,NaN,0.67000,0.58000,...,NaN,NaN,93.298507,NaN,NaN,0.322624,0.430165,0.645248,1.290495,0.937551
236,PAXGUSDT,2100.850,1687.57000,1857.00000,1999.00000,1821.00000,1999.00000,1821.00000,2076.00000,1821.00000,...,92.896448,92.896448,89.450867,49.166476,1.026663,946.595238,1262.126984,1893.190476,3786.380952,0.961768

In [48]:
#for i, j in zip(range(0,len(AllTime.index),70), range(70,len(AllTime.index),70)):
    #print(i,j)
    #print(AllTime.iloc[i:j,0:5])
    #if j+70 > len(AllTime.index):
        #print(j,len(AllTime.index))
        #print(AllTime.iloc[j:len(AllTime.index),0:5])
test=AllTime.loc[AllTime['Indicator']=='INJUSDT']
test

,Indicator,ATH,ATL,Current,OMH,OML,TMH,TML,THMH,THML,...,MONTH,2MONTH,3MONTH,SMADIFF,SMARATIO,GREEN,GREEN15,ORANGE,RED,CLOSERATIO
152,INJUSDT,25.306,0.18,1.892,5.44,1.87,7.587,1.87,7.676,1.87,...,34.779412,24.937393,24.648254,3.109695,0.638012,2.740452,3.653937,5.480905,10.96181,-0.309603

In [49]:
#drop = AllTime.loc[(AllTime['RSI'] < 30)& (AllTime['STRSI'] < 0.1)]
#drop = AllTime.loc[(AllTime['SMARATIO'] <  1.05 ) &(AllTime['SMARATIO'] > 0.95)& (AllTime['ALLTIME'] <70) ]
#drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21'])]
drop = AllTime.loc[(AllTime['Current'] <= AllTime['SMA21']/1.8)]
#drop = AllTime.loc[(AllTime['Current'] <= AllTime['GREEN15'])]

#drop = AllTime.loc[(AllTime['SMARATIO'] <  1 ) &(AllTime['SMARATIO'] > 0.95) & (AllTime['ALLTIME'] <70)]

#drop = AllTime.loc[(AllTime['MONTH'] < 80)&(AllTime[ '2MONTH'] < 70)&(AllTime['ALLTIME'] < 40)]
#drop = AllTime.loc[(AllTime['MONTH'] <70)&(AllTime['2MONTH'] > (AllTime['3MONTH']))]

sort = drop.sort_values(by=['CLOSERATIO'],ascending=False,inplace = True) 
#sort = drop.sort_values(by=['ALLTIME'],ascending=True,inplace = True) 

#drop = drop.loc[(drop['ALLTIME'] < drop['3MONTH'])]
display = drop[['Indicator','ATH','RED','ORANGE','GREEN','Current']]
#print(drop)
save = drop[['Indicator','ATH','CLOSERATIO','RED','ORANGE','GREEN','Current']]
save=save.drop_duplicates(subset='Indicator',keep='last')

#print(save)

save.to_csv("easyband.csv")
print(str(date.today()))
#print(date)
save.to_csv("easyband"+str(date.today())+".csv")

print("Low EASY Band")

display    
#print(display.iloc[0:60,0:14])
#print(display.iloc[60:110,])
#print(display.iloc[110:160,])

2022-05-12
Low EASY Band

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

     Indicator       ATH         RED      ORANGE      GREEN   Current
56   1INCHUSDT    7.8748    3.370381    1.685190   0.842595   0.93300
27     LTCUSDT  413.4900  231.247619  115.623810  57.811905  63.30000
76    QTUMUSDT   35.6850   13.489810    6.744905   3.372452   3.67000
216    BTGUSDT  169.0000   66.594286   33.297143  16.648571  17.72000
142    ZRXUSDT    2.4000    1.314000    0.657000   0.328500   0.34950
..         ...       ...         ...         ...        ...       ...
185   PERPUSDT   26.2100   10.981905    5.490952   2.745476   1.20000
186    MIRUSDT   14.5500    2.982080    1.491040   0.745520   0.30884
169   PONDUSDT    0.3180    0.077424    0.038712   0.019356   0.00792
20     FTMUSDT    3.4842    3.257848    1.628924   0.814462   0.27410
42    LUNAUSDT  119.5500  149.226352   74.613176  37.306588   0.35670

[222 rows x 6 columns]

In [50]:
allbands = AllTime[['Indicator','RED','ORANGE','GREEN','Current']]
allbands.to_csv("allbands.csv")
allbands

    Indicator           RED        ORANGE         GREEN      Current
157   SUNUSDT      0.030610      0.015305      0.007652      0.00914
218   PAXUSDT      1.999019      0.999510      0.499755      0.99960
21    ICPUSDT     39.644762     19.822381      9.911190      6.80000
42   LUNAUSDT    149.226352     74.613176     37.306588      0.35670
45    TLMUSDT      0.240819      0.120410      0.060205      0.02920
..        ...           ...           ...           ...          ...
10    BTCUSDT  81013.417143  40506.708571  20253.354286  28506.91000
44    TRXUSDT      0.133939      0.066970      0.033485      0.07587
235  GHSTUSDT      4.014762      2.007381      1.003690      1.67400
167  KEEPUSDT      1.290495      0.645248      0.322624      0.62510
236  PAXGUSDT   3786.380952   1893.190476    946.595238   1857.00000

[259 rows x 5 columns]

In [51]:
# red band 

## band to sell in down trends
redband = AllTime.loc[(AllTime['Current'] >= 2*AllTime['SMA21'])]
redband.to_csv("redband.csv")
redband

Empty DataFrame
Columns: [Indicator, ATH, ATL, Current, OMH, OML, TMH, TML, THMH, THML, SMA21, SMA55, SMA100, ALLTIME, MONTH, 2MONTH, 3MONTH, SMADIFF, SMARATIO, GREEN, GREEN15, ORANGE, RED, CLOSERATIO]
Index: []

[0 rows x 24 columns]

In [52]:
## band to sell in down trends
orangeband = AllTime.loc[(AllTime['Current'] >= AllTime['SMA21'])]
test = orangeband[['Indicator','GREEN','ORANGE','RED','Current']]
test.to_csv("orangeband.csv")
test

    Indicator     GREEN    ORANGE       RED  Current
218   PAXUSDT  0.499755  0.999510  1.999019  0.99960
242   GXSUSDT  0.853738  1.707476  3.414952  1.79230
189  TUSDUSDT  0.500010  1.000019  2.000038  1.00530
44    TRXUSDT  0.033485  0.066970  0.133939  0.07587

In [53]:
#easybandlist = display['Indicator']
#easybandlist

## GREEN 15

In [64]:
## GREEN 15
#display.Current.astype(float)

display = display.loc[:] 
display['ORatio'] = display['ORANGE']/display['Current'] 
#display = display.loc[display.Current < display.GREEN*1.05]
display = display.loc[display.Current < display.GREEN*0.6]

#display = display.loc[display['CLOSERATIO']> 0.01]
display

#display

,Indicator,ATH,RED,ORANGE,GREEN,Current,ORatio
131,LITUSDT,18.82640,3.272286,1.636143,0.818071,0.48700,3.359636
33,ALICEUSDT,60.00000,15.190476,7.595238,3.797619,2.26000,3.360725
52,SUSHIUSDT,23.43000,8.394000,4.197000,2.098500,1.23800,3.390145
43,IOTXUSDT,0.26300,0.163160,0.081580,0.040790,0.02398,3.402002
85,MANAUSDT,5.90000,4.921276,2.460638,1.230319,0.72170,3.409503
233,AIONUSDT,0.69520,0.188381,0.094190,0.047095,0.02760,3.412698
229,IRISUSDT,0.32000,0.130718,0.065359,0.032680,0.01895,3.449026
6,IRISUSDT,0.32000,0.130706,0.065353,0.032676,0.01882,3.472522
71,SXPUSDT,5.87000,2.700476,1.350238,0.675119,0.38800,3.479995
5,VIDTUSDT,1.42000,0.987981,0.493990,0.246995,0.14190,3.481258
69,FISUSDT,4.88000,1.450790,0.725395,0.362698,0.20780,3.490834
201,BEAMUSDT,2.10000,0.736362,0.368181,0.184090,0.10450,3.523263
106,WRXUSDT,6.66660,1.462190,0.731095,0.365548,0.20700,3.531861
58,C98USDT,6.44500,3.215143,1.607571,0.803786,0.45500,3.533124
109,LINAUSDT,1.00000,0.050186,0.025093,0.012546,0.00705,3.559271
158,AKROUSDT,0.08850,0.027200,0.013600,0.006800,0.00381,3.569554
134,CELRUSDT,0.19870,0.102734,0.051367,0.025684,0.01435,3.579592
133,GTCUSDT,29.04300,15.023714,7.511857,3.755929,2.09400,3.587324
141,BELUSDT,19.00000,1.905714,0.952857,0.476429,0.26500,3.595687
220,DUSKUSDT,1.17430,0.908371,0.454186,0.227093,0.12060,3.766051
240,PERLUSDT,0.29632,0.100022,0.050011,0.025005,0.01320,3.788709
232,WINGUSDT,300.00000,19.363810,9.681905,4.840952,2.55000,3.796825
209,FORUSDT,0.14477,0.092596,0.046298,0.023149,0.01217,3.804281
128,MASKUSDT,22.58100,11.886190,5.943095,2.971548,1.55900,3.812120
163,TVKUSDT,0.55000,0.249990,0.124995,0.062498,0.03240,3.857878
144,RSRUSDT,0.11900,0.033510,0.016755,0.008377,0.00430,3.896456
221,WTCUSDT,2.92420,1.053381,0.526690,0.263345,0.13040,4.039037
94,ROSEUSDT,0.59800,0.550688,0.275344,0.137672,0.06764,4.070725
171,ANTUSDT,43.00000,11.435524,5.717762,2.858881,1.39300,4.104639
45,TLMUSDT,5.95000,0.240819,0.120410,0.060205,0.02920,4.123614
196,BURGERUSDT,29.00000,3.433905,1.716952,0.858476,0.39200,4.379981
116,ONEUSDT,0.38000,0.336637,0.168319,0.084159,0.03787,4.444641
143,DEGOUSDT,34.70000,7.276190,3.638095,1.819048,0.81000,4.491476
185,PERPUSDT,26.21000,10.981905,5.490952,2.745476,1.20000,4.575794
186,MIRUSDT,14.55000,2.982080,1.491040,0.745520,0.30884,4.827872
169,PONDUSDT,0.31800,0.077424,0.038712,0.019356,0.00792,4.887867
20,FTMUSDT,3.48420,3.257848,1.628924,0.814462,0.27410,5.942808
42,LUNAUSDT,119.55000,149.226352,74.613176,37.306588,0.35670,209.176272

# entries

In [55]:

#entrylist =[['ANKRUSDT',0.07684],['AVAXUSDT',57],['WAXPUSDT',0.3818],['REEFUSDT',0.01131],['LINKUSDT',14.15],['ARUSDT',30],['ATOMUSDT',23],['MIRUSDT',2.343],['ALGOUSDT',0.909],['ZRXUSDT',0.60],['XTZUSDT',2.856],['KSMUSDT',163],['NEARUSDT',14],['WINUSDT',0.0003138],['CELRUSDT',0.05063],['DENTUSDT',0.002459],['LRCUSDT',0.7047],['CRVUSDT',3.529],['IMXUSDT',2.709],['SCRTUSDT',5],['RENUSDT',0.2547],['SUSHIUSDT',4.522],['CAKEUSDT',11.24],['XLMUSDT',0.2109],['HNTUSDT',30],['OMGUSDT',4.5],['LINAUSDT',0.024],['MIRUSDT',2.343],['FLUXUSDT',1.523]]
entrylist =[['ANKRUSDT',0.05415],['AVAXUSDT',57],['WAXPUSDT',0.2551],['REEFUSDT',0.00806],['LINKUSDT',12],['ARUSDT',23],['ATOMUSDT',18],['MIRUSDT',2.343],['ALGOUSDT',0.63],['ZRXUSDT',0.50],['XTZUSDT',2.856],['KSMUSDT',115],['NEARUSDT',10.320],['WINUSDT',0.00025],['DENTUSDT',0.002459],['LRCUSDT',0.677],['CRVUSDT',2.12],['IMXUSDT',1.30],['SCRTUSDT',3.7],['RENUSDT',0.3047],['SUSHIUSDT',3.5],['CAKEUSDT',11.24],['XLMUSDT',0.2109],['HNTUSDT',13.9],['OMGUSDT',4.5],['LINAUSDT',0.01759],['FLUXUSDT',1.523],['SRMUSDT',1.8],['VTHOUSDT',0.0031],['ANTUSDT',3.8],['RAYUSDT',2.5],['ROSEUSDT',0.18],['MOVRUSDT',33.7],['TFUELUSDT',0.16],['GLMRUSDT',2.311],['COTIUSDT',0.2],['ONEUSDT',0.08],['VETUSDT',0.05138],['RUNEUSDT',3.709],['CELRUSDT',0.034063],['ONTUSDT',0.4652],['GALAUSDT',0.17],['GRTUSDT',0.3164],['DOTUSDT',15],['ZILUSDT',0.04410],['FILUSDT',20],['SCUSDT',0.011],['MATICUSDT',1.4],['FTMUSDT',0.72],['BANDUSDT',3.6],['1INCHUSDT',1.3],['AUDIOUSDT',1.0],['IOTXUSDT','0.07109'],['CTSIUSDT','0.32'],['LUNAUSDT','13'],['SOLUSDT','35'],['MINAUSDT','1.96'],['BTCUSDT','39000'],['ADAUSDT','0.86'],['STORJUSDT','1.05'],['THETAUSDT','2.8'],['MANAUSDT','1.65'],['PAXGUSDT','1785'],['INJUSDT','5'],['PERPUSDT','2.22']]
exposurelist =[['ANKRUSDT',311],['AVAXUSDT',2850],['WAXPUSDT',527],['REEFUSDT',700],['LINKUSDT',6000],['ARUSDT',2450],['ATOMUSDT',1863],['MIRUSDT',85],['ALGOUSDT',3300],['ZRXUSDT',245],['XTZUSDT',1200],['KSMUSDT',7800],['NEARUSDT',1360],['WINUSDT',285],['DENTUSDT',385],['LRCUSDT',660],['CRVUSDT',323],['IMXUSDT',269],['SCRTUSDT',601],['RENUSDT',684],['SUSHIUSDT',2730],['CAKEUSDT',4000],['XLMUSDT',368],['HNTUSDT',1250],['OMGUSDT',765],['LINAUSDT',205],['FLUXUSDT',224],['SRMUSDT',587],['VTHOUSDT',413],['ANTUSDT',200],['RAYUSDT',100],['ROSEUSDT',634],['MOVRUSDT',500],['TFUELUSDT',344],['GLMRUSDT',400],['COTIUSDT',500],['ONEUSDT',1000],['VETUSDT',500],['RUNEUSDT',750],['CELRUSDT',500],['ONTUSDT',400],['GALAUSDT',650],['GRTUSDT',1700],['DOTUSDT',10000],['ZILUSDT',1000],['FILUSDT',2000],['SCUSDT',200],['MATICUSDT',8000],['FTMUSDT',2000],['BANDUSDT',750],['1INCHUSDT',1000],['AUDIOUSDT',700],['IOTXUSDT',500],['CTSIUSDT',325],['LUNAUSDT','4000'],['SOLUSDT','3000'],['DOTUSDT','10000']]
startdate = '2021-01-01'
entries = pd.DataFrame(entrylist, columns =['Indicator', 'lowest_entry'],dtype = float) 
entries
entries.lowest_entry.astype(float)

indicator_list = entries['Indicator']
#indicator_list
#entries
entries.to_csv("entries.csv")

exposure = pd.DataFrame(exposurelist, columns =['Indicator', 'exposure'],dtype = float) 
exposure
exposure.exposure.astype(float)
#indicator_list
#entries
exposure.to_csv("exposure.csv")

entries = entries.merge(exposure ,how="left",on="Indicator")
#entries

fixentries = entries.merge(display ,how='left',on=['Indicator'])
#fixentries = fixentries.merge(exposure,how='left',on=['Indicator'])
#fixentries
#entries1 = entries.merge(fixentries,how='left',on=['Indicator'])
fixentries = fixentries.dropna(axis=0,subset=['ATH'])
fixentries=fixentries.drop_duplicates(subset='Indicator',keep='last')
fixentries.lowest_entry.astype(float)
fixentries.Current.astype(float)


fixentries['DROP'] = ((fixentries.lowest_entry - fixentries.Current)/fixentries.lowest_entry)*100
fixentries.sort_values(by=['DROP'],ascending=False,inplace = True)
fixentries

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised
  exec(code_obj, self.user_global_ns, self.user_ns)

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP
55,LUNAUSDT,13.000000,4000.0,119.55000,149.226352,74.613176,37.306588,0.35670,209.176272,97.256154
7,MIRUSDT,2.343000,85.0,14.55000,2.982080,1.491040,0.745520,0.30884,4.827872,86.818609
53,IOTXUSDT,0.071090,500.0,0.26300,0.163160,0.081580,0.040790,0.02398,3.402002,66.268111
20,SUSHIUSDT,3.500000,2730.0,23.43000,8.394000,4.197000,2.098500,1.23800,3.390145,64.628571
52,AUDIOUSDT,1.000000,700.0,4.99000,2.150857,1.075429,0.537714,0.36500,2.946380,63.500000
29,ANTUSDT,3.800000,200.0,43.00000,11.435524,5.717762,2.858881,1.39300,4.104639,63.342105
31,ROSEUSDT,0.180000,634.0,0.59800,0.550688,0.275344,0.137672,0.06764,4.070725,62.422222
64,INJUSDT,5.000000,NaN,25.30600,10.961810,5.480905,2.740452,1.89200,2.896884,62.160000
49,FTMUSDT,0.720000,2000.0,3.48420,3.257848,1.628924,0.814462,0.27410,5.942808,61.930556
2,WAXPUSDT,0.255100,527.0,0.98350,0.630257,0.315129,0.157564,0.09800,3.215598,61.583693
25,LINAUSDT,0.017590,205.0,1.00000,0.050186,0.025093,0.012546,0.00705,3.559271,59.920409
3,REEFUSDT,0.008060,700.0,0.30000,0.021267,0.010633,0.005317,0.00333,3.193193,58.684864
39,CELRUSDT,0.034063,500.0,0.19870,0.102734,0.051367,0.025684,0.01435,3.579592,57.872178
62,MANAUSDT,1.650000,NaN,5.90000,4.921276,2.460638,1.230319,0.72170,3.409503,56.260606
42,GRTUSDT,0.316400,1700.0,2.88073,0.843010,0.421505,0.210752,0.13980,3.015056,55.815424
36,ONEUSDT,0.080000,1000.0,0.38000,0.336637,0.168319,0.084159,0.03787,4.444641,52.662500
65,PERPUSDT,2.220000,NaN,26.21000,10.981905,5.490952,2.745476,1.20000,4.575794,45.945946
23,HNTUSDT,13.900000,1250.0,59.27000,48.385714,24.192857,12.096429,8.19000,2.953951,41.079137

# Red Band

In [56]:
## over red entries 
overred = redband.merge(entries ,how="left",on="Indicator")
overed = overred.dropna(axis=0,subset=['RED'])
overred= overred[['Indicator','GREEN','ORANGE','RED','Current']]
overred

Empty DataFrame
Columns: [Indicator, GREEN, ORANGE, RED, Current]
Index: []

# Orange Band

In [57]:
## over orange entries 
overorange = entries.merge(orangeband ,how="left",on="Indicator")
overorange = overorange.dropna(axis=0,subset=['GREEN'])
overoranged= overorange[['Indicator','GREEN','ORANGE','RED','Current']]
overoranged

Empty DataFrame
Columns: [Indicator, GREEN, ORANGE, RED, Current]
Index: []

In [58]:
save = fixentries
save.to_csv("fixoneasy.csv")
save
del fixentries

In [59]:
#Gap is an acceptable area for rebounce and exit
orangedrop = save.loc[:]
orangedrop['GapOrange']= orangedrop['ORANGE']/orangedrop['Current']
orangedrop['GapRed']= orangedrop['RED']/orangedrop['Current']
orangedrop['GapATH']= orangedrop['ATH']/orangedrop['Current']
#orangedrop['GapAORT']= (orangedrop['GapATH']*orangedrop['GapOrange'])


orangedrop

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH
55,LUNAUSDT,13.000000,4000.0,119.55000,149.226352,74.613176,37.306588,0.35670,209.176272,97.256154,209.176272,418.352544,335.155593
7,MIRUSDT,2.343000,85.0,14.55000,2.982080,1.491040,0.745520,0.30884,4.827872,86.818609,4.827872,9.655744,47.111773
53,IOTXUSDT,0.071090,500.0,0.26300,0.163160,0.081580,0.040790,0.02398,3.402002,66.268111,3.402002,6.804003,10.967473
20,SUSHIUSDT,3.500000,2730.0,23.43000,8.394000,4.197000,2.098500,1.23800,3.390145,64.628571,3.390145,6.780291,18.925687
52,AUDIOUSDT,1.000000,700.0,4.99000,2.150857,1.075429,0.537714,0.36500,2.946380,63.500000,2.946380,5.892759,13.671233
29,ANTUSDT,3.800000,200.0,43.00000,11.435524,5.717762,2.858881,1.39300,4.104639,63.342105,4.104639,8.209278,30.868629
31,ROSEUSDT,0.180000,634.0,0.59800,0.550688,0.275344,0.137672,0.06764,4.070725,62.422222,4.070725,8.141449,8.840923
64,INJUSDT,5.000000,NaN,25.30600,10.961810,5.480905,2.740452,1.89200,2.896884,62.160000,2.896884,5.793768,13.375264
49,FTMUSDT,0.720000,2000.0,3.48420,3.257848,1.628924,0.814462,0.27410,5.942808,61.930556,5.942808,11.885617,12.711419
2,WAXPUSDT,0.255100,527.0,0.98350,0.630257,0.315129,0.157564,0.09800,3.215598,61.583693,3.215598,6.431195,10.035714
25,LINAUSDT,0.017590,205.0,1.00000,0.050186,0.025093,0.012546,0.00705,3.559271,59.920409,3.559271,7.118541,141.843972
3,REEFUSDT,0.008060,700.0,0.30000,0.021267,0.010633,0.005317,0.00333,3.193193,58.684864,3.193193,6.386386,90.090090
39,CELRUSDT,0.034063,500.0,0.19870,0.102734,0.051367,0.025684,0.01435,3.579592,57.872178,3.579592,7.159184,13.846690
62,MANAUSDT,1.650000,NaN,5.90000,4.921276,2.460638,1.230319,0.72170,3.409503,56.260606,3.409503,6.819005,8.175142
42,GRTUSDT,0.316400,1700.0,2.88073,0.843010,0.421505,0.210752,0.13980,3.015056,55.815424,3.015056,6.030111,20.606080
36,ONEUSDT,0.080000,1000.0,0.38000,0.336637,0.168319,0.084159,0.03787,4.444641,52.662500,4.444641,8.889283,10.034328
65,PERPUSDT,2.220000,NaN,26.21000,10.981905,5.490952,2.745476,1.20000,4.575794,45.945946,4.575794,9.151587,21.841667
23,HNTUSDT,13.900000,1250.0,59.27000,48.385714,24.192857,12.096429,8.19000,2.953951,41.079137,2.953951,5.907902,7.236874

In [60]:
# multiplying the gap with the value of the drop for a reasonable recovery
exposuredrop = orangedrop
exposuredrop['Total']= exposuredrop['exposure']*exposuredrop['DROP']*exposuredrop['GapOrange']
#exposuredrop['Total']= exposuredrop['DROP']*exposuredrop['GapOrange']*exposuredrop['CLOSERATIO']
#exposuredrop['Total']= exposuredrop['GapOrange']*exposuredrop['DROP']
#exposuredrop = exposuredrop.loc[exposuredrop['DROP']>0]

#exposuredrop.sort_values(by=['GapOrange'],ascending=False,inplace = True)
#exposuredrop.sort_values(by=['CLOSERATIO'],ascending=False,inplace = True)

exposuredrop

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total
55,LUNAUSDT,13.000000,4000.0,119.55000,149.226352,74.613176,37.306588,0.35670,209.176272,97.256154,209.176272,418.352544,335.155593,8.137472e+07
7,MIRUSDT,2.343000,85.0,14.55000,2.982080,1.491040,0.745520,0.30884,4.827872,86.818609,4.827872,9.655744,47.111773,3.562768e+04
53,IOTXUSDT,0.071090,500.0,0.26300,0.163160,0.081580,0.040790,0.02398,3.402002,66.268111,3.402002,6.804003,10.967473,1.127221e+05
20,SUSHIUSDT,3.500000,2730.0,23.43000,8.394000,4.197000,2.098500,1.23800,3.390145,64.628571,3.390145,6.780291,18.925687,5.981437e+05
52,AUDIOUSDT,1.000000,700.0,4.99000,2.150857,1.075429,0.537714,0.36500,2.946380,63.500000,2.946380,5.892759,13.671233,1.309666e+05
29,ANTUSDT,3.800000,200.0,43.00000,11.435524,5.717762,2.858881,1.39300,4.104639,63.342105,4.104639,8.209278,30.868629,5.199929e+04
31,ROSEUSDT,0.180000,634.0,0.59800,0.550688,0.275344,0.137672,0.06764,4.070725,62.422222,4.070725,8.141449,8.840923,1.611017e+05
64,INJUSDT,5.000000,NaN,25.30600,10.961810,5.480905,2.740452,1.89200,2.896884,62.160000,2.896884,5.793768,13.375264,NaN
49,FTMUSDT,0.720000,2000.0,3.48420,3.257848,1.628924,0.814462,0.27410,5.942808,61.930556,5.942808,11.885617,12.711419,7.360829e+05
2,WAXPUSDT,0.255100,527.0,0.98350,0.630257,0.315129,0.157564,0.09800,3.215598,61.583693,3.215598,6.431195,10.035714,1.043610e+05
25,LINAUSDT,0.017590,205.0,1.00000,0.050186,0.025093,0.012546,0.00705,3.559271,59.920409,3.559271,7.118541,141.843972,4.372095e+04
3,REEFUSDT,0.008060,700.0,0.30000,0.021267,0.010633,0.005317,0.00333,3.193193,58.684864,3.193193,6.386386,90.090090,1.311745e+05
39,CELRUSDT,0.034063,500.0,0.19870,0.102734,0.051367,0.025684,0.01435,3.579592,57.872178,3.579592,7.159184,13.846690,1.035794e+05
62,MANAUSDT,1.650000,NaN,5.90000,4.921276,2.460638,1.230319,0.72170,3.409503,56.260606,3.409503,6.819005,8.175142,NaN
42,GRTUSDT,0.316400,1700.0,2.88073,0.843010,0.421505,0.210752,0.13980,3.015056,55.815424,3.015056,6.030111,20.606080,2.860872e+05
36,ONEUSDT,0.080000,1000.0,0.38000,0.336637,0.168319,0.084159,0.03787,4.444641,52.662500,4.444641,8.889283,10.034328,2.340659e+05
65,PERPUSDT,2.220000,NaN,26.21000,10.981905,5.490952,2.745476,1.20000,4.575794,45.945946,4.575794,9.151587,21.841667,NaN
23,HNTUSDT,13.900000,1250.0,59.27000,48.385714,24.192857,12.096429,8.19000,2.953951,41.079137,2.953951,5.907902,7.236874,1.516822e+05

In [61]:
exposuredrop.to_csv("exposuredrop.csv")

In [62]:
# easy band and cap ratio
capratio = pd.read_csv('capratio.csv')
capratio = pd.DataFrame(capratio,columns=['Indicator','supply_ratio','cap_ratio'])
capratio

exposuredrop = exposuredrop.merge(capratio ,how='left',on=['Indicator'])
sort = exposuredrop.sort_values(by=['Total'],ascending=False,inplace = True)

exposuredrop

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total,supply_ratio,cap_ratio
0,LUNAUSDT,13.000000,4000.0,119.55000,149.226352,74.613176,37.306588,0.35670,209.176272,97.256154,209.176272,418.352544,335.155593,8.137472e+07,NaN,NaN
8,FTMUSDT,0.720000,2000.0,3.48420,3.257848,1.628924,0.814462,0.27410,5.942808,61.930556,5.942808,11.885617,12.711419,7.360829e+05,0.800363,0.800363
3,SUSHIUSDT,3.500000,2730.0,23.43000,8.394000,4.197000,2.098500,1.23800,3.390145,64.628571,3.390145,6.780291,18.925687,5.981437e+05,0.771157,0.771157
14,GRTUSDT,0.316400,1700.0,2.88073,0.843010,0.421505,0.210752,0.13980,3.015056,55.815424,3.015056,6.030111,20.606080,2.860872e+05,0.615723,0.615723
15,ONEUSDT,0.080000,1000.0,0.38000,0.336637,0.168319,0.084159,0.03787,4.444641,52.662500,4.444641,8.889283,10.034328,2.340659e+05,0.898427,0.898427
6,ROSEUSDT,0.180000,634.0,0.59800,0.550688,0.275344,0.137672,0.06764,4.070725,62.422222,4.070725,8.141449,8.840923,1.611017e+05,NaN,NaN
17,HNTUSDT,13.900000,1250.0,59.27000,48.385714,24.192857,12.096429,8.19000,2.953951,41.079137,2.953951,5.907902,7.236874,1.516822e+05,NaN,NaN
11,REEFUSDT,0.008060,700.0,0.30000,0.021267,0.010633,0.005317,0.00333,3.193193,58.684864,3.193193,6.386386,90.090090,1.311745e+05,NaN,NaN
4,AUDIOUSDT,1.000000,700.0,4.99000,2.150857,1.075429,0.537714,0.36500,2.946380,63.500000,2.946380,5.892759,13.671233,1.309666e+05,0.568268,0.568268
2,IOTXUSDT,0.071090,500.0,0.26300,0.163160,0.081580,0.040790,0.02398,3.402002,66.268111,3.402002,6.804003,10.967473,1.127221e+05,0.999427,0.999427
9,WAXPUSDT,0.255100,527.0,0.98350,0.630257,0.315129,0.157564,0.09800,3.215598,61.583693,3.215598,6.431195,10.035714,1.043610e+05,0.522609,0.522609
12,CELRUSDT,0.034063,500.0,0.19870,0.102734,0.051367,0.025684,0.01435,3.579592,57.872178,3.579592,7.159184,13.846690,1.035794e+05,NaN,NaN
5,ANTUSDT,3.800000,200.0,43.00000,11.435524,5.717762,2.858881,1.39300,4.104639,63.342105,4.104639,8.209278,30.868629,5.199929e+04,NaN,NaN
10,LINAUSDT,0.017590,205.0,1.00000,0.050186,0.025093,0.012546,0.00705,3.559271,59.920409,3.559271,7.118541,141.843972,4.372095e+04,NaN,NaN
1,MIRUSDT,2.343000,85.0,14.55000,2.982080,1.491040,0.745520,0.30884,4.827872,86.818609,4.827872,9.655744,47.111773,3.562768e+04,NaN,NaN
7,INJUSDT,5.000000,NaN,25.30600,10.961810,5.480905,2.740452,1.89200,2.896884,62.160000,2.896884,5.793768,13.375264,NaN,NaN,NaN
13,MANAUSDT,1.650000,NaN,5.90000,4.921276,2.460638,1.230319,0.72170,3.409503,56.260606,3.409503,6.819005,8.175142,NaN,0.688859,0.688859
16,PERPUSDT,2.220000,NaN,26.21000,10.981905,5.490952,2.745476,1.20000,4.575794,45.945946,4.575794,9.151587,21.841667,NaN,NaN,NaN

In [63]:
undergreen = exposuredrop.loc[exposuredrop['Current'] < exposuredrop['GREEN']]
undergreen

,Indicator,lowest_entry,exposure,ATH,RED,ORANGE,GREEN,Current,ORatio,DROP,GapOrange,GapRed,GapATH,Total,supply_ratio,cap_ratio
0,LUNAUSDT,13.000000,4000.0,119.55000,149.226352,74.613176,37.306588,0.35670,209.176272,97.256154,209.176272,418.352544,335.155593,8.137472e+07,NaN,NaN
8,FTMUSDT,0.720000,2000.0,3.48420,3.257848,1.628924,0.814462,0.27410,5.942808,61.930556,5.942808,11.885617,12.711419,7.360829e+05,0.800363,0.800363
3,SUSHIUSDT,3.500000,2730.0,23.43000,8.394000,4.197000,2.098500,1.23800,3.390145,64.628571,3.390145,6.780291,18.925687,5.981437e+05,0.771157,0.771157
14,GRTUSDT,0.316400,1700.0,2.88073,0.843010,0.421505,0.210752,0.13980,3.015056,55.815424,3.015056,6.030111,20.606080,2.860872e+05,0.615723,0.615723
15,ONEUSDT,0.080000,1000.0,0.38000,0.336637,0.168319,0.084159,0.03787,4.444641,52.662500,4.444641,8.889283,10.034328,2.340659e+05,0.898427,0.898427
6,ROSEUSDT,0.180000,634.0,0.59800,0.550688,0.275344,0.137672,0.06764,4.070725,62.422222,4.070725,8.141449,8.840923,1.611017e+05,NaN,NaN
17,HNTUSDT,13.900000,1250.0,59.27000,48.385714,24.192857,12.096429,8.19000,2.953951,41.079137,2.953951,5.907902,7.236874,1.516822e+05,NaN,NaN
11,REEFUSDT,0.008060,700.0,0.30000,0.021267,0.010633,0.005317,0.00333,3.193193,58.684864,3.193193,6.386386,90.090090,1.311745e+05,NaN,NaN
4,AUDIOUSDT,1.000000,700.0,4.99000,2.150857,1.075429,0.537714,0.36500,2.946380,63.500000,2.946380,5.892759,13.671233,1.309666e+05,0.568268,0.568268
2,IOTXUSDT,0.071090,500.0,0.26300,0.163160,0.081580,0.040790,0.02398,3.402002,66.268111,3.402002,6.804003,10.967473,1.127221e+05,0.999427,0.999427
9,WAXPUSDT,0.255100,527.0,0.98350,0.630257,0.315129,0.157564,0.09800,3.215598,61.583693,3.215598,6.431195,10.035714,1.043610e+05,0.522609,0.522609
12,CELRUSDT,0.034063,500.0,0.19870,0.102734,0.051367,0.025684,0.01435,3.579592,57.872178,3.579592,7.159184,13.846690,1.035794e+05,NaN,NaN
5,ANTUSDT,3.800000,200.0,43.00000,11.435524,5.717762,2.858881,1.39300,4.104639,63.342105,4.104639,8.209278,30.868629,5.199929e+04,NaN,NaN
10,LINAUSDT,0.017590,205.0,1.00000,0.050186,0.025093,0.012546,0.00705,3.559271,59.920409,3.559271,7.118541,141.843972,4.372095e+04,NaN,NaN
1,MIRUSDT,2.343000,85.0,14.55000,2.982080,1.491040,0.745520,0.30884,4.827872,86.818609,4.827872,9.655744,47.111773,3.562768e+04,NaN,NaN
7,INJUSDT,5.000000,NaN,25.30600,10.961810,5.480905,2.740452,1.89200,2.896884,62.160000,2.896884,5.793768,13.375264,NaN,NaN,NaN
13,MANAUSDT,1.650000,NaN,5.90000,4.921276,2.460638,1.230319,0.72170,3.409503,56.260606,3.409503,6.819005,8.175142,NaN,0.688859,0.688859
16,PERPUSDT,2.220000,NaN,26.21000,10.981905,5.490952,2.745476,1.20000,4.575794,45.945946,4.575794,9.151587,21.841667,NaN,NaN,NaN