In [1]:
import numpy as np 
import pandas as pd 
from datetime import date

In [5]:
import os

start = pd.to_datetime('2021-02-01')
end = pd.to_datetime('2021-06-30')

## adjust the timeperiods fro 15 x 4 or it will be 15min 1 hour and 2 hours 
## from 5 minutes charts the multiplier should be x12 from 5 to 60 

#ada2021 = ada15.loc[(ada15['date']> start)& (ada15['date']< end)].copy()
directory = 'BN-main'
table = []
for filename in os.listdir(directory):
    if filename.endswith('1h.json'):
        df = pd.read_json(directory+'/'+filename)
        df.columns=['date','open','high','low','close','volume']
        df.date = pd.to_datetime(df['date'],unit='ms')
        df = df.loc[(df['date']> start)& (df['date']< end)].copy()
        alth = df.high.max()
        altl = df.low.min()
        array = filename.split("_")
        tuple =(array[0] ,alth,altl)
        table.append(tuple)
        #print("name is: ",array[0] ,alth,altl)
        
    else:
        continue
table[0]
AllTime = pd.DataFrame(table,columns=['Indicator','ATH','ATL'])
AllTime['percent']=(AllTime['ATL']/AllTime['ATH'])*100
AllTime.sort_values('percent')

   Indicator           ATH           ATL    percent
21     MATIC      2.700000      0.036200   1.340741
52      DENT      0.022700      0.000334   1.470485
16       CHZ      0.944900      0.020998   2.222246
35       HOT      0.031600      0.000731   2.312658
29       BTT      0.013578      0.000372   2.741280
48      STMX      0.099672      0.002959   2.968737
2        WIN      0.002970      0.000104   3.499327
38       MBL      0.043380      0.001528   3.522361
41       ONE      0.224030      0.008140   3.633442
26      DOGE      0.739950      0.028770   3.888101
51     TFUEL      0.679990      0.026867   3.951088
7        ETC    179.830000      7.300000   4.059389
5      AUDIO      4.990000      0.204890   4.106012
14      VTHO      0.028500      0.001267   4.445614
49      NPXS      0.009092      0.000405   4.454514
44       CHR      0.766620      0.034170   4.457228
34      ANKR      0.216617      0.011173   5.157952
3       LUNA     22.400000      1.441400   6.434821
4        RVN      0.292930      0.022660   7.735637
10       ENJ      4.000000      0.314260   7.856500
46       KEY      0.034750      0.002810   8.086331
36      MANA      1.670000      0.145130   8.690419
22       VET      0.279829      0.024654   8.810381
47      COTI      0.600000      0.060700  10.116667
6         SC      0.064000      0.006655  10.398437
0      STORJ      3.833000      0.414100  10.803548
17     THETA     15.880000      1.870000  11.775819
42      PERL      0.296320      0.037000  12.486501
32      IOTX      0.085600      0.011000  12.850467
54      HIVE      1.050000      0.135300  12.885714
15       ADA      2.470000      0.335710  13.591498
37      IOTA      2.677300      0.397500  14.847047
8        NEO    141.000000     21.872000  15.512057
11       RSR      0.119000      0.018530  15.571429
55       NBS      0.052000      0.008240  15.846154
20       BLZ      0.667890      0.108190  16.198775
24     OCEAN      1.941400      0.322400  16.606573
57      HBAR      0.455500      0.078000  17.124040
19       ONT      2.958300      0.508800  17.199067
12       XRP      1.966890      0.340100  17.291257
31       TRX      0.180000      0.031520  17.511111
33       BAT      1.649800      0.292900  17.753667
43      CAKE     44.278000      8.300000  18.745201
56       EOS     14.900000      2.893000  19.416107
39      REEF      0.058701      0.011900  20.272227
25       SXP      5.870000      1.203000  20.494037
45       FUN      0.068655      0.015266  22.235817
50     1INCH      7.874800      1.777700  22.574542
28       CRV      4.650000      1.057000  22.731183
27       ZIL      0.256910      0.059700  23.237710
18      ATOM     32.324000      7.830000  24.223487
23       AVA      6.467600      1.600100  24.740244
53       XTZ      8.420000      2.117500  25.148456
9        LTC    413.490000    104.920000  25.374253
30      LINK     53.000000     15.000000  28.301887
13       ETH   4372.720000   1277.760000  29.221171
40      ALGO      1.840000      0.615900  33.472826
1        BTC  64854.000000  28805.000000  44.415148