# Read STRSI MACD file

In [60]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta

In [61]:
MLDATA = pd.read_csv('MLSTRSIMACDBTTOP.csv')

In [62]:
MLDATA.tail()

,Unnamed: 0,Indicator,O5m,C5m,H5m,L5m,V5m,OM5m,CM5m,HM5m,...,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,BOTTOMPM1w,TOPPM1w,Time
320,666,THETAUSDT,1.246,1.2390,1.2460,1.2360,92491.2000,1.2570,1.2460,1.2660,...,NaN,-1.798495,-1.511927,-1.496956,-1.368643,1.2280,4.390,2.271,5.2440,2022-05-12 07:30:45.669183
321,677,MANAUSDT,0.723,0.7144,0.7241,0.7142,305898.0000,0.7309,0.7226,0.7336,...,NaN,-0.689371,-0.324500,-0.416990,-0.142064,0.7113,2.846,1.705,3.5497,2022-05-12 07:30:45.669183
322,688,PAXGUSDT,1856.000,1858.0000,1858.0000,1856.0000,7.5302,1859.0000,1858.0000,1861.0000,...,NaN,22.137101,47.524323,40.590218,60.217935,1821.0000,2071.000,1772.000,2076.0000,2022-05-12 07:30:45.669183
323,699,INJUSDT,1.886,1.8790,1.8880,1.8790,1929.0000,1.9120,1.8830,1.9150,...,NaN,-3.120525,-2.566411,-2.582250,-2.289354,1.8760,7.587,3.750,10.0590,2022-05-12 07:30:45.669183
324,710,PERPUSDT,1.200,1.2000,1.2000,1.2000,1175.7300,1.2100,1.2000,1.2200,...,NaN,-4.426083,-4.061279,-4.034663,-3.878877,1.2000,5.620,3.600,9.9000,2022-05-12 07:30:45.669183

In [63]:
MLDATA.head()

,Unnamed: 0,Indicator,O5m,C5m,H5m,L5m,V5m,OM5m,CM5m,HM5m,...,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,BOTTOMPM1w,TOPPM1w,Time
0,10,ANKRUSDT,0.03149,0.03292,0.03306,0.03132,1492990.40,0.03187,0.03141,0.03200,...,NaN,-0.025720,-0.017258,-0.017303,-0.013028,0.03000,0.10295,0.05107,0.11929,2022-05-12 01:08:12.562301
1,21,AVAXUSDT,28.34000,29.83000,29.85000,28.22000,80469.57,28.24000,28.34000,28.40000,...,NaN,-15.683587,-4.073532,-6.021144,1.731496,26.11000,103.62000,52.95000,114.13000,2022-05-12 01:08:12.562301
2,32,WAXPUSDT,0.10390,0.10780,0.10870,0.10390,400233.00,0.10430,0.10370,0.10460,...,NaN,-0.137762,-0.102387,-0.107074,-0.084700,0.10260,0.39500,0.23280,0.51000,2022-05-12 01:08:12.562301
3,43,REEFUSDT,0.00350,0.00368,0.00368,0.00350,19295055.00,0.00355,0.00351,0.00355,...,NaN,-0.007438,-0.006759,-0.006584,-0.006419,0.00347,0.01275,0.00791,0.01867,2022-05-12 01:08:12.562301
4,54,LINKUSDT,6.70000,6.93000,6.93000,6.68000,109406.14,6.73000,6.70000,6.76000,...,NaN,-7.520805,-6.279995,-6.357714,-5.659590,6.65000,18.32000,11.40000,28.71000,2022-05-12 01:08:12.562301

In [64]:
MLDATA

,Unnamed: 0,Indicator,O5m,C5m,H5m,L5m,V5m,OM5m,CM5m,HM5m,...,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,BOTTOMPM1w,TOPPM1w,Time
0,10,ANKRUSDT,0.03149,0.03292,0.03306,0.03132,1.492990e+06,0.03187,0.03141,0.03200,...,NaN,-0.025720,-0.017258,-0.017303,-0.013028,0.03000,0.10295,0.05107,0.11929,2022-05-12 01:08:12.562301
1,21,AVAXUSDT,28.34000,29.83000,29.85000,28.22000,8.046957e+04,28.24000,28.34000,28.40000,...,NaN,-15.683587,-4.073532,-6.021144,1.731496,26.11000,103.62000,52.95000,114.13000,2022-05-12 01:08:12.562301
2,32,WAXPUSDT,0.10390,0.10780,0.10870,0.10390,4.002330e+05,0.10430,0.10370,0.10460,...,NaN,-0.137762,-0.102387,-0.107074,-0.084700,0.10260,0.39500,0.23280,0.51000,2022-05-12 01:08:12.562301
3,43,REEFUSDT,0.00350,0.00368,0.00368,0.00350,1.929506e+07,0.00355,0.00351,0.00355,...,NaN,-0.007438,-0.006759,-0.006584,-0.006419,0.00347,0.01275,0.00791,0.01867,2022-05-12 01:08:12.562301
4,54,LINKUSDT,6.70000,6.93000,6.93000,6.68000,1.094061e+05,6.73000,6.70000,6.76000,...,NaN,-7.520805,-6.279995,-6.357714,-5.659590,6.65000,18.32000,11.40000,28.71000,2022-05-12 01:08:12.562301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,666,THETAUSDT,1.24600,1.23900,1.24600,1.23600,9.249120e+04,1.25700,1.24600,1.26600,...,NaN,-1.798495,-1.511927,-1.496956,-1.368643,1.22800,4.39000,2.27100,5.24400,2022-05-12 07:30:45.669183
321,677,MANAUSDT,0.72300,0.71440,0.72410,0.71420,3.058980e+05,0.73090,0.72260,0.73360,...,NaN,-0.689371,-0.324500,-0.416990,-0.142064,0.71130,2.84600,1.70500,3.54970,2022-05-12 07:30:45.669183
322,688,PAXGUSDT,1856.00000,1858.00000,1858.00000,1856.00000,7.530200e+00,1859.00000,1858.00000,1861.00000,...,NaN,22.137101,47.524323,40.590218,60.217935,1821.00000,2071.00000,1772.00000,2076.00000,2022-05-12 07:30:45.669183
323,699,INJUSDT,1.88600,1.87900,1.88800,1.87900,1.929000e+03,1.91200,1.88300,1.91500,...,NaN,-3.120525,-2.566411,-2.582250,-2.289354,1.87600,7.58700,3.75000,10.05900,2022-05-12 07:30:45.669183
324,710,PERPUSDT,1.20000,1.20000,1.20000,1.20000,1.175730e+03,1.21000,1.20000,1.22000,...,NaN,-4.426083,-4.061279,-4.034663,-3.878877,1.20000,5.62000,3.60000,9.90000,2022-05-12 07:30:45.669183