In [1]:
## need to add open close for each time frame ,
## support resistance
##  pivots ,
## and write it down each 15 minutes to create data set for AI ML bot 
## bot with GAN or CAN

In [2]:
import numpy as np 
import pandas as pd 
from datetime import date
#Data Source (Pandas Data Reader)
from pandas_datareader import data
import requests 
import json
from dateutil.relativedelta import relativedelta


#Data Source(Pandas Data Reader)

In [3]:
## choose either white list or read from fix entries 

#fixentries= pd.read_csv('easyband.csv')
#fixentries= pd.read_csv('fixoneasy.csv')
#fixentries= pd.read_csv('fixentries.csv')
fixentries= pd.read_csv('entries.csv')


fixentries
whitelist = []
whitelist = fixentries['Indicator'].array
whitelist[0]
#final = pd.DataFrame(fixentries['Indicator']) 
#final.set_index('Indicator')

'ANKRUSDT'

In [4]:
#alllist = 'GALA/USDT, ANT/USDT,IMX/USDT, MATIC/USDT, ZRX/USDT,  ALGO/USDT, BTC/USDT, ETH/USDT, AXS/USDT, SOL/USDT, MATIC/USDT, ADA/USDT, BNB/USDT, FIL/USDT, XRP/USDT, CVC/USDT, FTM/USDT, ICP/USDT, DOGE/USDT, XEC/USDT, IOTA/USDT, AVAX/USDT, DOT/USDT, LTC/USDT, EOS/USDT, IOST/USDT, STMX/USDT, FTT/USDT, TWT/USDT, ALICE/USDT, ATA/USDT, ETC/USDT, VET/USDT, SAND/USDT, LINK/USDT, THETA/USDT, SHIB/USDT, CHZ/USDT, LUNA/USDT, IOTX/USDT, TRX/USDT, TLM/USDT, BCH/USDT, REEF/USDT, CAKE/USDT, NEO/USDT, SLP/USDT, RVN/USDT, ATOM/USDT, SUSHI/USDT, ARDR/USDT, OMG/USDT, GRT/USDT, 1INCH/USDT, AAVE/USDT, C98/USDT, UNI/USDT, HBAR/USDT, CRV/USDT, DENT/USDT, MBOX/USDT, BTT/USDT, SRM/USDT, YFI/USDT, HOT/USDT, XLM/USDT, FIS/USDT, REQ/USDT, SXP/USDT, KSM/USDT, QNT/USDT, NEAR/USDT, COMP/USDT, QTUM/USDT, CHR/USDT, SC/USDT, XVS/USDT, ONT/USDT, COTI/USDT, NKN/USDT, RUNE/USDT, ANKR/USDT, MANA/USDT, CTXC/USDT, AR/USDT, RAY/USDT, BAKE/USDT, ARPA/USDT, XTZ/USDT, ZIL/USDT, ONG/USDT, ROSE/USDT, PNT/USDT, ALGO/USDT, MINA/USDT, WIN/USDT, AUDIO/USDT, STORJ/USDT, EPS/USDT, MDX/USDT, ZEC/USDT, ENJ/USDT, HIVE/USDT, TFUEL/USDT, WRX/USDT, SNX/USDT, SKL/USDT, LINA/USDT, DODO/USDT, UNFI/USDT, XEM/USDT, EGLD/USDT, ICX/USDT, WAVES/USDT, ONE/USDT, DASH/USDT, KAVA/USDT, SUPER/USDT, TKO/USDT, OGN/USDT, XMR/USDT, OCEAN/USDT, CELO/USDT, BAT/USDT, FUN/USDT, LRC/USDT, ALPHA/USDT, MASK/USDT, TRU/USDT, DNT/USDT, LIT/USDT, FET/USDT, GTC/USDT, CELR/USDT, DEXE/USDT, ZEN/USDT, WAXP/USDT, CTSI/USDT, HNT/USDT, YFII/USDT, BEL/USDT, ZRX/USDT, DEGO/USDT, RSR/USDT, COS/USDT, FLM/USDT, BAL/USDT, MFT/USDT, RLC/USDT, KNC/USDT, REN/USDT, INJ/USDT, FLOW/USDT, SFP/USDT, BAND/USDT, CTK/USDT, SUN/USDT, AKRO/USDT, XVG/USDT, NANO/USDT, STRAX/USDT, PUNDIX/USDT, TVK/USDT, MKR/USDT, CLV/USDT, TRB/USDT, ETHUP/USDT, KEEP/USDT, TCT/USDT, POND/USDT, LTO/USDT, ANT/USDT, TOMO/USDT, ACM/USDT, FIO/USDT, VITE/USDT, MBL/USDT, JST/USDT, MTL/USDT, UTK/USDT, BLZ/USDT, ORN/USDT, STPT/USDT, CFX/USDT, OM/USDT, PERP/USDT, MIR/USDT, STX/USDT, ERN/USDT, TUSD/USDT, PSG/USDT, NULS/USDT, OXT/USDT, REP/USDT, BNBUP/USDT, DATA/USDT, WAN/USDT, BURGER/USDT, RAMP/USDT, ATM/USDT, DGB/USDT, DIA/USDT, BEAM/USDT, UMA/USDT, ETHDOWN/USDT, CKB/USDT, TRIBE/USDT, FARM/USDT, BTCUP/USDT, BZRX/USDT, ALPACA/USDT, DOTUP/USDT, BTS/USDT, FOR/USDT, ADAUP/USDT, HARD/USDT, LSK/USDT, POLS/USDT, FORTH/USDT, TORN/USDT, VTHO/USDT, BTG/USDT, QUICK/USDT, FILUP/USDT, PAX/USDT, MITH/USDT, SUSHIUP/USDT, BTCDOWN/USDT, XRPDOWN/USDT, BNBDOWN/USDT, DUSK/USDT, XRPUP/USDT, WTC/USDT, DOCK/USDT, AUTO/USDT, BTCST/USDT, KLAY/USDT, WNXM/USDT, KEY/USDT, FILDOWN/USDT, NU/USDT, IRIS/USDT, KMD/USDT, TROY/USDT, WING/USDT, AION/USDT, PHA/USDT, SUSHIDOWN/USDT, EOSUP/USDT, LTCUP/USDT, GHST/USDT, PAXG/USDT, BNT/USDT, AVA/USDT, BADGER/USDT, PERL/USDT, COCOS/USDT, GXS/USDT, MDT/USDT, 1INCHUP/USDT, GTO/USDT, LINKUP/USDT, AAVEUP/USDT, FIRO/USDT, JUV/USDT, MLN/USDT, UNIUP/USDT, LPT/USDT, NMR/USDT, AAVEDOWN/USDT, 1INCHDOWN/USDT, ASR/USDT, OG/USDT, BAR/USDT, DREP/USDT, ADADOWN/USDT, BOND/USDT, DCR/USDT, DOTDOWN/USDT, GNO/USDT, NBS/USDT, SXPUP/USDT, EOSDOWN/USDT, YFIUP/USDT, RIF/USDT, LTCDOWN/USDT, XLMUP/USDT, YFIDOWN/USDT, LINKDOWN/USDT, TRXUP/USDT, BCHUP/USDT, XTZUP/USDT, SXPDOWN/USDT, UNIDOWN/USDT, XTZDOWN/USDT, BCHDOWN/USDT, TRXDOWN/USDT, XLMDOWN/USDT, SUSD/USDT'
#whitelist = 'LINK/USDT, DOT/USDT'
#whitelist =str(fixentries['Indicator'])

startdate = '2020-01-01'
enddate = pd.to_datetime('today')
intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']
#intervals = ['8h']

In [5]:
#print (enddate)

In [6]:
def FRSI(series, period=14):
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    return 100 - (100 / (1 + rs))


# calculating Stoch RSI (gives the same values as TradingView)
# https://www.tradingview.com/wiki/Stochastic_RSI_(STOCH_RSI) 
def STRSIA(series, period=14, smoothK=3, smoothD=3):
    # Calculate RSI 
    delta = series.diff().dropna()
    ups = delta * 0
    downs = ups.copy()
    ups[delta > 0] = delta[delta > 0]
    downs[delta < 0] = -delta[delta < 0]
    ups[ups.index[period-1]] = np.mean( ups[:period] ) #first value is sum of avg gains
    ups = ups.drop(ups.index[:(period-1)])
    downs[downs.index[period-1]] = np.mean( downs[:period] ) #first value is sum of avg losses
    downs = downs.drop(downs.index[:(period-1)])
    rs = ups.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() / \
         downs.ewm(com=period-1,min_periods=0,adjust=False,ignore_na=False).mean() 
    rsi = 100 - 100 / (1 + rs)

    # Calculate StochRSI 
    stochrsi  = (rsi - rsi.rolling(period).min()) / (rsi.rolling(period).max() - rsi.rolling(period).min())
    stochrsi_K = stochrsi.rolling(smoothK).mean()
    stochrsi_D = stochrsi_K.rolling(smoothD).mean()
    return stochrsi, stochrsi_K, stochrsi_D

#Calulate SMA 
def SMA(series,size):
    sma = series.rolling(size).mean()
    return sma
#Calculate SMA55

## MACD 
def MMACD(series,fast=5,slow=35,sig=5):
    ## defaults original f 12, s 26, s9
    exp1 = series.ewm(span=fast, adjust=False).mean()
    exp2 = series.ewm(span=slow, adjust=False).mean()
    macd = exp1-exp2
    signal = macd.ewm(span=sig, adjust=False).mean()
    return macd,signal
## Bottom price 
def FBOTTOMP (series,size):
    bottomp=series.rolling(size).min()
    return bottomp
## top price 
def FTOPP (series,size):
    topp=series.rolling(size).max()
    return topp

In [7]:
#alllist=alllist.lstrip()
#array = alllist.split(",")
#array = whitelist
array = whitelist
array

wl = []
bl = []
blacklist = ""
whitelist = ""
symbols =[]

for i in range(0 ,len(array)):
    if (array[i].find('DOWN') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])
    elif (array[i].find('UP') != -1):
        bl.append(str(array[i]).lstrip())
        #print ("Contains given substring ")
        blacklist += str(array[i])

    else:
        wl.append(str(array[i]).lstrip().replace("/",""))
        whitelist +=str(array[i]).lstrip()
        #print ("Doesn't contains given substring")
    

    
#symbols to be used to get the prices from binance url
symbols = np.array(wl)

#print(intervals)
## get the data 
import os

live = pd.to_datetime('today')
start = pd.to_datetime(startdate)
end = pd.to_datetime(enddate)

root_url = 'https://api.binance.com/api/v1/klines'
#symbol = 'STEEMETH'
#interval = '1d'
#url = root_url + '?symbol=' + symbol + '&interval=' + interval
#print(url)


directory = 'BN-main'
table = []
interval = ''
final = pd.DataFrame(symbols,columns =['Indicator'])
#final.set_index('Indicator')

for interval in intervals:
    

    for symbol in symbols:
            url = root_url + '?symbol=' + symbol + '&interval=' + interval
            data = json.loads(requests.get(url).text)
            dflive = pd.DataFrame(data ,columns =['open_time',
                  'o', 'h', 'l', 'c', 'v',
                  'close_time', 'qav', 'num_trades',
                  'taker_base_vol', 'taker_quote_vol', 'ignore'])
            dflive.open_time = pd.to_datetime(dflive['open_time'],unit='ms')
            dflive=dflive.loc[(dflive.open_time>start)]
            
            if dflive.size > 300 :
                
                
                

                dflive = dflive.astype ({'o': float ,'h':float,'l':float ,'c':float ,'v':float})
                dflive['RSI'] = FRSI(dflive['c'])
                dflive['STRSI'] = STRSIA(dflive['c'])[0]
                dflive['STRSIK'] = STRSIA(dflive['c'])[1]
                dflive['STRSID'] = STRSIA(dflive['c'])[2]
                dflive['SMA21'] = SMA(dflive['c'],21)
                dflive['SMA55'] = SMA(dflive['c'],55)
                dflive['SMA100'] = SMA(dflive['c'],100)
                dflive['SMA200'] = SMA(dflive['c'],200)
                dflive['MACD'] = MMACD(dflive['c'])[0]
                dflive['MACDSIGNAL'] = MMACD(dflive['c'])[1]
                dflive['BTTOMP'] = FBOTTOMP(dflive['l'],21)
                dflive['TPP'] = FTOPP(dflive['h'],21)


                
                



                #print(dflive)


                lastrow = dflive.iloc[-1]
                beforelast = dflive.iloc[-2]
                O = float(lastrow.o)
                C = float(lastrow.c)
                H = float(lastrow.h)
                L = float(lastrow.l)
                V = float(lastrow.v)
                OM = float(beforelast.o)
                CM = float(beforelast.c)
                HM = float(beforelast.h)
                LM = float(beforelast.l)
                VM = float(beforelast.v)
                RSI = float(lastrow.RSI)
                RSIM = float(beforelast.RSI)
                STRSI = float(lastrow.STRSI)
                STRSIK = float(lastrow.STRSIK)
                STRSIKM = float(beforelast.STRSIK)
                STRSID = float(lastrow.STRSID)
                STRSIDM = float(beforelast.STRSID)
                SMA21 = float(lastrow.SMA21)
                SMA21M = float(beforelast.SMA21)
                SMA55 = float(lastrow.SMA55)
                SMA55M = float(beforelast.SMA55)
                SMA100 = float(lastrow.SMA100)
                SMA100M = float(beforelast.SMA100)
                SMA200 = float(lastrow.SMA200)
                SMA200M = float(beforelast.SMA200)
                MACD = float(lastrow.MACD)
                MACDSIGNAL = float(lastrow.MACDSIGNAL)
                MACDM = float(beforelast.MACD)
                MACDSIGNALM = float(beforelast.MACDSIGNAL)
                BTTOMP = lastrow.BTTOMP
                TPP = lastrow.TPP


                tuple =(symbol,O,C,H,L,V,OM,CM,HM,LM,VM,RSI,RSIM,STRSI,STRSIK,STRSIKM,STRSID,STRSIDM,SMA21,SMA21M,SMA55,SMA55M,SMA100,SMA100M,SMA200,SMA200M,MACD,MACDSIGNAL,MACDM,MACDSIGNALM,BTTOMP,TPP)
                table.append(tuple)
                #print(table)
                del dflive
            else:
                pass
            #print("name is: ",array[0])


    table[0]
    AllTime = pd.DataFrame(table,columns=['Indicator','O','C','H','L','V','OM','CM','HM','LM','VM','RSI','RSIM','STRSI','STRSIK','STRSIKM','STRSID','STRSIDM','SMA21','SMA21M','SMA55','SMA55M','SMA100','SMA100M','SMA200','SMA200M','MACD','MACDSIGNAL','MACDM','MACDSIGNALM','BOTTOMP','TOPP'])


    #AllTime.Current=AllTime.Current.astype(float)

    AllTime.dtypes


    #AllTime.sort_values(by='ATH',ascending=False)
    #AllTime.to_csv("alltimeHL.csv", mode="w")
    #data.sort_values("Name", axis = 0, ascending = True,inplace = True, na_position ='last')

    ## Display the Data 

    test=AllTime.rename(columns={'O':('O'+interval),'OM':('OM'+interval),'C':('C'+interval),'CM':('CM'+interval),'H':('H'+interval),'HM':('HM'+interval),'L':('L'+interval),'LM':('LM'+interval),'V':('V'+interval),'VM':('VM'+interval),'RSI':('RSI'+interval),\
                                 'RSIM':('RSIM'+interval),'STRSI':('STRSI'+interval),'STRSIK':('STRSIK'+interval),'STRSIKM':('STRSIKM'+interval),\
                                 'STRSID':('STRSID'+interval),'STRSIDM':('STRSIDM'+interval),'SMA21':('SMA21'+interval),'SMA21M':('SMA21M'+interval),\
                                 'SMA55':('SMA55'+interval),'SMA55M':('SMA55M'+interval),'SMA100':('SMA100'+interval),'SMA100M':('SMA100M'+interval),\
                                 'SMA200':('SMA200'+interval),'SMA200M':('SMA200M'+interval),'MACD':('MACD'+interval),'MACDSIGNAL':('MACDSIGNAL'+interval),'MACDM':('MACDM'+interval),'MACDSIGNALM':('MACDSIGNALM'+interval),'BOTTOMP':('BOTTOMP'+interval),'TOPP':('TOPP'+interval)})
    test.set_index(['Indicator'])
    final=final.merge(test,how='left',on=['Indicator'])
    ## add the current date column
            

#final

In [8]:
#final.Indicator

In [9]:
final=final.drop_duplicates(subset='Indicator',keep='last')
#final= final.drop(columns=['Current_x','Current_y'])
final['Time'] = pd.to_datetime('today')
final.to_csv("MLSTRSIMACDBTTOP.csv")
#final.to_csv("STRSISMA3D1H"+str(date.today())+".csv")
final.to_csv('MLSTRSIMACDBTTOP.csv', mode='a', index=False, header=False)

final

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
40319,ANKRUSDT,0.06583,0.06593,0.06595,0.06582,1.814409e+05,0.06686,0.06584,0.06688,0.06582,...,0.063906,NaN,NaN,-0.014089,-0.011956,-0.013035,-0.010890,0.05107,0.11941,2022-05-05 12:05:18.955001
80639,AVAXUSDT,67.16000,67.28000,67.31000,67.10000,1.369070e+03,66.98000,67.14000,67.38000,66.73000,...,NaN,NaN,NaN,-1.798922,3.138903,-0.433112,5.607816,52.95000,127.32000,2022-05-05 12:05:18.955001
120959,WAXPUSDT,0.22470,0.22480,0.22490,0.22460,2.452100e+04,0.22390,0.22490,0.22510,0.22210,...,NaN,NaN,NaN,-0.093935,-0.080320,-0.086685,-0.073513,0.20480,0.53050,2022-05-05 12:05:18.955001
161279,REEFUSDT,0.00755,0.00757,0.00757,0.00754,3.043442e+06,0.00754,0.00755,0.00757,0.00748,...,NaN,NaN,NaN,-0.006253,-0.006309,-0.006242,-0.006337,0.00674,0.02230,2022-05-05 12:05:18.955001
201599,LINKUSDT,11.99000,12.01000,12.02000,11.98000,4.800610e+03,11.96000,12.00000,12.02000,11.91000,...,20.101752,NaN,NaN,-5.813270,-5.478109,-5.717577,-5.310528,10.65000,28.71000,2022-05-05 12:05:18.955001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399039,STORJUSDT,0.94130,0.94420,0.94490,0.94120,2.316000e+03,0.94120,0.94120,0.94680,0.93640,...,NaN,NaN,NaN,-0.246280,-0.209630,-0.229412,-0.191304,0.77140,2.18560,2022-05-05 12:05:18.955001
2439359,THETAUSDT,2.56400,2.56100,2.56400,2.55500,3.746130e+04,2.54900,2.56400,2.56800,2.52800,...,4.159050,NaN,NaN,-1.369178,-1.326050,-1.351659,-1.304486,2.13000,5.94600,2022-05-05 12:05:18.955001
2479679,MANAUSDT,1.63080,1.63130,1.63240,1.62900,2.496100e+04,1.62940,1.63080,1.63590,1.61430,...,NaN,NaN,NaN,-0.335879,-0.115027,-0.245342,-0.004601,1.33750,3.96940,2022-05-05 12:05:18.955001
2519999,PAXGUSDT,1896.00000,1895.00000,1896.00000,1895.00000,3.331300e+00,1898.00000,1895.00000,1898.00000,1894.00000,...,NaN,NaN,NaN,43.367996,61.143861,57.233692,70.031793,1759.00000,2076.00000,2022-05-05 12:05:18.955001
2560319,INJUSDT,4.22200,4.22300,4.22300,4.22200,1.714000e+02,4.25200,4.22200,4.25200,4.22100,...,NaN,NaN,NaN,-2.398083,-2.227965,-2.382864,-2.142906,3.41800,10.33700,2022-05-05 12:05:18.955001

In [10]:
#Rules
MACDU1w = (final['MACD1w'] > final['MACDM1w'])
MACDD1w = (final['MACD1w'] < final['MACDM1w'])
MACDGAPU1w = ((final['MACD1w'] - final['MACDSIGNAL1w']) < (final['MACDM1w'] - final['MACDSIGNALM1w']) )
MACDGAPD1w = ((final['MACD1w'] - final['MACDSIGNAL1w']) > (final['MACDM1w'] - final['MACDSIGNALM1w']) )
MACDCROSS1w =  (final['MACD1w'] > final['MACDSIGNAL1w'])



MACDU3d = (final['MACD3d'] > final['MACDM3d'])
MACDD3d = (final['MACD3d'] < final['MACDM3d'])

MACDGAPU3d = (((abs(final['MACD3d']) - abs(final['MACDSIGNAL3d'])) > (abs(final['MACDM3d']) - abs(final['MACDSIGNALM3d']))) & (abs(final['MACD3d']) < abs(final['MACDSIGNAL3d'])))
MACDGAPD3d = (((abs(final['MACD3d']) - abs(final['MACDSIGNAL3d'])) < (abs(final['MACDM3d']) - abs(final['MACDSIGNALM3d']))) & (abs(final['MACD3d']) < abs(final['MACDSIGNAL3d'])))

#MACDGAPU3d = (((abs(final['MACD3d']) - abs(final['MACDSIGNAL3d'])) > (abs(final['MACDM3d']) - abs(final['MACDSIGNALM3d']))) & (abs(final['MACD3d']) < abs(final['MACDSIGNAL3d'])))
#MACDGAPD3d = ((abs(final['MACD3d'] - final['MACDSIGNAL3d']) < abs(final['MACDM3d'] - final['MACDSIGNALM3d'])) & (final['MACD3d'] < final['MACDSIGNAL3d']))
#MACDGAPU3d = (((final['MACD3d'] - final['MACDSIGNAL3d']) > (final['MACDM3d'] - final['MACDSIGNALM3d'])) & (final['MACD3d'] < final['MACDSIGNAL3d']))
#MACDGAPD3d = (((final['MACD3d'] - final['MACDSIGNAL3d']) < (final['MACDM3d'] - final['MACDSIGNALM3d'])) & (final['MACD3d'] < final['MACDSIGNAL3d']))
MACDCROSS3d =  (final['MACD3d'] > final['MACDSIGNAL3d'])

MACDU1d = (final['MACD1d'] > final['MACDM1d'])
MACDD1d = (final['MACD1d'] < final['MACDM1d'])
MACDGAPU1d = ((final['MACD1d'] - final['MACDSIGNAL1d']) < (final['MACDM1d'] - final['MACDSIGNALM1d']) )
MACDGAPD1d = ((final['MACD1d'] - final['MACDSIGNAL1d']) > (final['MACDM1d'] - final['MACDSIGNALM1d']) )
MACDCROSS1d =  (final['MACD1d'] > final['MACDSIGNAL1d'])


MACDU12h = (final['MACD12h'] > final['MACDM12h'])
MACDD12h = (final['MACD12h'] < final['MACDM12h'])
MACDGAPU12h = ((final['MACD12h'] - final['MACDSIGNAL12h']) < (final['MACDM12h'] - final['MACDSIGNALM12h']) )
MACDGAPD12h = ((final['MACD12h'] - final['MACDSIGNAL12h']) > (final['MACDM12h'] - final['MACDSIGNALM12h']) )
MACDCROSS12h =  (final['MACD12h'] > final['MACDSIGNAL12h'])


MACDU8h = (final['MACD8h'] > final['MACDM8h'])
MACDD8h = (final['MACD8h'] < final['MACDM8h'])
MACDGAPU8h = ((final['MACD8h'] - final['MACDSIGNAL8h']) < (final['MACDM8h'] - final['MACDSIGNALM8h']) )
MACDGAPD8h = ((final['MACD8h'] - final['MACDSIGNAL8h']) > (final['MACDM8h'] - final['MACDSIGNALM8h']) )
MACDCROSS8h =  (final['MACD8h'] > final['MACDSIGNAL8h'])


MACDU4h = (final['MACD4h'] > final['MACDM4h'])
MACDD4h = (final['MACD4h'] < final['MACDM4h'])
MACDGAPU4h = ((final['MACD4h'] - final['MACDSIGNAL4h']) < (final['MACDM4h'] - final['MACDSIGNALM4h']) )
MACDGAPD4h = ((final['MACD4h'] - final['MACDSIGNAL4h']) > (final['MACDM4h'] - final['MACDSIGNALM4h']) )
MACDCROSS4h =  (final['MACD4h'] > final['MACDSIGNAL4h'])

rule12under = (final['STRSIK12h'] < final['STRSID12h'])
rule12over = (final['STRSIK12h'] > final['STRSID12h'])
rule12kdown = (final['STRSIK12h'] < final['STRSIKM12h'])
rule12kup = (final['STRSIK12h'] > final['STRSIKM12h'])
rule12RSIup = (final['RSI12h'] > final['RSIM12h'])
rule12RSIdown = (final['RSI12h'] < final['RSIM12h'])

bottom12h = (final['STRSIK12h']< 0.2)
bottomr12h = (final['RSI12h'] < 30)
top12h = (final['STRSIK12h'] > 0.8)
topr12h = (final['RSI12h'] > 70)
room12h = (final['STRSIK12h'] < 0.8)
roomr12h = (final['RSI12h'] < 70)

shift12h = (rule12under & (rule12kup | rule12RSIup))
dshift12h = (rule12over & (rule12kdown | rule12RSIdown))
uptrend12h = (rule12over & (rule12kup & rule12RSIup))
downtrend12h = (rule12under & (rule12kdown & rule12RSIdown))



rule8under = (final['STRSIK8h']< final['STRSID8h'])
rule8over = (final['STRSIK8h'] > final['STRSID8h'])
rule8kdown = (final['STRSIK8h']< final['STRSIKM8h'])
rule8kup = (final['STRSIK8h'] > final['STRSIKM8h'])
rule8RSIup = (final['RSI8h'] > final['RSIM8h'])
rule8RSIdown = (final['RSI8h'] < final['RSIM8h'])

bottom8h = (final['STRSIK8h']< 0.2)
bottomr8h = (final['RSI8h'] < 30)
top8h = (final['STRSIK8h'] > 0.8)
topr8h = (final['RSI8h'] > 70)
room8h = (final['STRSIK8h'] < 0.8)
roomr8h = (final['RSI8h'] < 70)

shift8h = (rule8under & (rule8kup | rule8RSIup))
dshift8h = (rule8over & (rule8kdown | rule8RSIdown))
uptrend8h = (rule8over & (rule8kup & rule8RSIup))
downtrend8h = (rule8under & (rule8kdown & rule8RSIdown))

rule4under = (final['STRSIK4h']< final['STRSID4h'])
rule4over = (final['STRSIK4h'] > final['STRSID4h'])
rule4kdown = (final['STRSIK4h']< final['STRSIKM4h'])
rule4kup = (final['STRSIK4h'] > final['STRSIKM4h'])
rule4RSIup = (final['RSI4h'] > final['RSIM4h'])
rule4RSIdown = (final['RSI4h'] < final['RSIM4h'])

bottom4h = (final['STRSIK4h']< 0.2)
bottomr4h = (final['RSI4h'] < 30)
top4h = (final['STRSIK4h'] > 0.8)
topr4h = (final['RSI4h'] > 70)
room4h = (final['STRSIK4h'] < 0.8)
roomr4h = (final['RSI4h'] < 70)

shift4h = (rule4under & (rule4kup | rule4RSIup))
dshift4h = (rule4over & (rule4kdown | rule4RSIdown))
uptrend4h = (rule4over & (rule4kup & rule4RSIup))
downtrend4h = (rule4under & (rule4kdown & rule4RSIdown))



rule2under = (final['STRSIK2h']< final['STRSID2h'])
rule2over = (final['STRSIK2h'] > final['STRSID2h'])
rule2kdown = (final['STRSIK2h']< final['STRSIKM2h'])
rule2kup = (final['STRSIK2h'] > final['STRSIKM2h'])
rule2RSIup = (final['RSI2h'] > final['RSIM2h'])
rule2RSIdown = (final['RSI2h'] < final['RSIM2h'])

bottom2h = (final['STRSIK2h']< 0.2)
bottomr2h = (final['RSI2h'] < 30)
top2h = (final['STRSIK2h'] > 0.8)
topr2h = (final['RSI2h'] > 70)
room2h = (final['STRSIK2h'] < 0.8)
roomr2h = (final['RSI2h'] < 70)


shift2h = (rule2under & (rule2kup | rule2RSIup))
dshift2h = (rule2over & (rule2kdown | rule2RSIdown))
uptrend2h = (rule2over & (rule2kup & rule2RSIup))
downtrend2h = (rule2under & (rule2kdown & rule2RSIdown))


rule1under = (final['STRSIK1h']< final['STRSID1h'])
rule1over = (final['STRSIK1h'] > final['STRSID1h'])
rule1kdown = (final['STRSIK1h']< final['STRSIKM1h'])
rule1kup = (final['STRSIK1h'] > final['STRSIKM1h'])
rule1RSIup = (final['RSI1h'] > final['RSIM1h'])
rule1RSIdown = (final['RSI1h'] < final['RSIM1h'])

bottom1h = (final['STRSIK1h']< 0.2)
bottomr1h = (final['RSI1h'] < 30)
top1h = (final['STRSIK1h'] > 0.8)
topr1h = (final['RSI1h'] > 70)
room1h = (final['STRSIK1h'] < 0.8)
roomr1h = (final['RSI1h'] < 70)


shift1h = (rule1under & (rule1kup | rule1RSIup))
dshift1h = (rule1over & (rule1kdown | rule1RSIdown))
uptrend1h = (rule1over & (rule1kup & rule1RSIup))
downtrend1h = (rule1under & (rule1kdown & rule1RSIdown))



rule1dunder = (final['STRSIK1d']< final['STRSID1d'])
rule1dover = (final['STRSIK1d'] > final['STRSID1d'])
rule1dkdown = (final['STRSIK1d']< final['STRSIKM1d'])
rule1dkup = (final['STRSIK1d'] > final['STRSIKM1d'])
rule1dRSIup = (final['RSI1d'] > final['RSIM1d'])
rule1dRSIdown = (final['RSI1d'] < final['RSIM1d'])

bottom1d = (final['STRSIK1d']< 0.2)
bottomr1d = (final['RSI1d'] < 30)
top1d = (final['STRSIK1d'] > 0.8)
topr1d = (final['RSI1d'] > 70)
room1d = (final['STRSIK1d'] < 0.8)
roomr1d = (final['RSI1d'] < 70)

shift1d = (rule1dunder & (rule1dkup | rule1dRSIup))
dshift1d = (rule1dover & (rule1dkdown | rule1dRSIdown))
uptrend1d = (rule1dover & (rule1dkup & rule1dRSIup))
downtrend1d = (rule1dunder & (rule1dkdown & rule1dRSIdown))


rule3dunder = (final['STRSIK3d']< final['STRSID3d'])
rule3dover = (final['STRSIK3d'] > final['STRSID3d'])
rule3dkdown = (final['STRSIK3d']< final['STRSIKM3d'])
rule3dkup = (final['STRSIK3d'] > final['STRSIKM3d'])
rule3dRSIup = (final['RSI3d'] > final['RSIM3d'])
rule3dRSIdown = (final['RSI3d'] < final['RSIM3d'])

bottom3d = (final['STRSIK3d']< 0.2)
bottomr3d = (final['RSI3d'] < 30)
top3d = (final['STRSIK3d'] > 0.8)
topr3d = (final['RSI3d'] > 70)
room3d = (final['STRSIK3d'] < 0.8)
roomr3d = (final['RSI3d'] < 70)


shift3d = (rule3dunder & (rule3dkup | rule3dRSIup))
dshift3d = (rule3dover & (rule3dkdown | rule3dRSIdown))
uptrend3d = (rule3dover & (rule3dkup & rule3dRSIup))
downtrend3d = (rule3dunder & (rule3dkdown & rule3dRSIdown))


rule1wunder = (final['STRSIK1w']< final['STRSID1w'])
rule1wover = (final['STRSIK1w'] > final['STRSID1w'])
rule1wkdown = (final['STRSIK1w']< final['STRSIKM1w'])
rule1wkup = (final['STRSIK1w'] > final['STRSIKM1w'])
rule1wRSIup = (final['RSI1w'] > final['RSIM1w'])
rule1wRSIdown = (final['RSI1w'] < final['RSIM1w'])

bottom1w = (final['STRSIK1w']< 0.2)
bottomr1w = (final['RSI1w'] < 30)
top1w = (final['STRSIK1w'] > 0.8)
topr1w = (final['RSI1w'] > 70)
room1w = (final['STRSIK1w'] < 0.8)
roomr1w = (final['RSI1w'] < 70)

shift1w = (rule1wunder & (rule1wkup | rule1wRSIup))
dshift1w = (rule1wover & (rule1wkdown | rule1wRSIdown))
uptrend1w = (rule1wover & (rule1wkup & rule1wRSIup))
downtrend1w = (rule1wunder & (rule1wkdown & rule1wRSIdown))




rule13over = (final['STRSIK3d'] > final['STRSID3d']) & (final['STRSIK1d'] > final['STRSID1d'])
rule13under =(final['STRSIK3d'] < final['STRSID3d']) & (final['STRSIK1d'] < final['STRSID1d'])




#final.dropna()

# Summary  draft rules

In [11]:
# drop = final.loc[bottom4h & (shift4h | rule4over)]
drop = final.loc[(bottom4h | (uptrend4h | shift4h)) & (uptrend8h | shift8h) ]
#drop = final.loc[((uptrend4h | shift4h)) & (uptrend8h | shift8h) ]
#drop = final.loc[(uptrend8h | shift8h) & (uptrend12h | shift12h) & (uptrend1d | shift1d)]
#drop = final.loc[(uptrend2h | shift2h) & (uptrend4h | shift4h) ]
#drop = final.loc[(uptrend4h | shift4h)]

#drop = final.loc[bottom8h | (shift8h | rule8over)]
#drop = final.loc[bottom12h | (shift12h | rule12over)]
#drop = final.loc[(uptrend8h)]
#drop = final.loc[bottom12h | (shift12h | uptrend12h)]
#drop = final.loc[bottom1d | (shift1d | uptrend1d)]
#drop = final.loc[top4h]
#drop = final.loc[(uptrend3d)]
#drop = final.loc[dshift4h]
#drop = final.loc[shift2h]

#drop = final.loc[(bottom4h & bottom12h & bottom3d)]
#drop = final.loc[(uptrend8h)]
#drop = final.loc[(downtrend8h & downtrend4h & downtrend12h)]
#drop = final.loc[(bottom4h & bottom2h & bottom3d)]
#drop = final.loc[shift3d & bottom4h]

#drop = final.loc[(bottom12h)]
#drop = final.loc[ ((rule4kup |rule4RSIup))]

#drop = final.loc[((uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend4h | shift4h) ]
#drop = final.loc[((uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) ]

# 4 hours will go down or slow down
#drop = final.loc[( (bottom3d) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) & dshift4h) ]
#drop = final.loc[( (bottom3d) & (uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
#drop = final.loc[( (bottom3d) & (uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) &  (uptrend2h | shift2h) &  (uptrend1h | shift1h)]

#drop = final.loc[( (uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]

drop = final.loc[( (bottom4h) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h)) ]
#drop = final.loc[((bottom1d) & (bottom3d))]
#drop = drop.loc[( (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h))]
#drop = final.loc[dshift4h]

#drop = final.loc[( (uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) & (downtrend2h |dshift2h) ]
#drop = final.loc[( (bottom3d) & (uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
#drop = final.loc[dshift2h]
#drop = final.loc[( (bottom8h) & (bottom12h) & (bottom4h) & (bottom2h))]
#drop = final.loc[( (bottom8h) & (bottom12h) & (bottom4h))]

#drop= final.loc[(shift4h) & (shift12h)]
#drop = final.loc[(dshift4h | downtrend4h)]
#drop = final.loc[( (bottom4h)&(bottom8h) & (bottom12h) & (bottom1d) & (dshift4h | downtrend4h))]
#drop = final.loc[( (bottom4h)&(bottom8h) & (bottom12h) & (bottom1d) & (shift2h))]

#drop = final.loc[downtrend1d & downtrend12h & downtrend8h & downtrend4h]
#drop = final.loc[top8h]

#drop



    

#bottomtable['bottoms'] = bottomtable.apply(get_key(listb,bottomtable.loc('Indicator'),axis=1)

#bottomtable
#reversetable
#bottomstable = pd.DataFrame(reversetable,columns=['Indicator','Bottoms'])
#print (bottomstable)
#listb
#listd = pd.DataFrame(listb,columns=['Bottoms','Indicator'])
#print (listb)
#print(reversetable)
#listd.head()
#test = final.loc[(MACDGAP3d)]
test = final.loc[(MACDCROSS3d)]
test = final.loc[(MACDCROSS1d)]
test = final.loc[(MACDGAPU3d)]
test = final.loc[(MACDGAPD3d)& rule3dover & rule3dRSIup]
#macd3d = final.loc[(MACDGAPU3d)& rule3dRSIup]
macd1d = final.loc[(MACDGAPD1d)& rule1dRSIup]
macd3du = final.loc[(MACDGAPU3d)]
macd3dd = final.loc[(MACDGAPD3d)]


macd3d1d = final.loc[(MACDGAPD1d &  (MACDGAPD3d)  & rule3dRSIup & rule1dRSIup )]
macd1dcross = final.loc[MACDCROSS1d]
macd12hcross = final.loc[MACDCROSS12h]
macd8hcross = final.loc[MACDCROSS8h]
macd4hcross = final.loc[MACDCROSS4h]

macd3dd
#macd12hcross
#macd12hcross
#macd4hcross
#macd3d1d
#macd1d
pmacdu = macd3du[['Indicator','MACD3d','MACDSIGNAL3d','MACDM3d','MACDSIGNALM3d']]
pmacdu['diff']=abs(macd3du['MACD3d'])-abs(macd3du['MACDSIGNAL3d'])
pmacdu['diffm']=abs(macd3du['MACDM3d'])-abs(macd3du['MACDSIGNALM3d'])

pmacdd = macd3dd[['Indicator','MACD3d','MACDSIGNAL3d','MACDM3d','MACDSIGNALM3d']]
pmacdd['diff']=abs(macd3dd['MACD3d'])-abs(macd3dd['MACDSIGNAL3d'])
pmacdd['diffm']=abs(macd3dd['MACDM3d'])-abs(macd3dd['MACDSIGNALM3d'])

print(pmacdu)
print(pmacdd)

        Indicator    MACD3d  MACDSIGNAL3d   MACDM3d  MACDSIGNALM3d      diff  \
403199    ZRXUSDT  0.050948      0.064281  0.047274       0.070947 -0.013333
524159   NEARUSDT -0.039096      0.765094  0.008656       1.167188 -0.725998
1794239   ZILUSDT  0.004655      0.012471  0.003196       0.016379 -0.007816
2197439  LUNAUSDT  3.052996      5.394789  2.961853       6.565686 -2.341793
2519999  PAXGUSDT -4.799901      7.660354 -0.988849      13.890482 -2.860453

             diffm
403199   -0.023673
524159   -1.158532
1794239  -0.013183
2197439  -3.603833
2519999 -12.901632
        Indicator     MACD3d  MACDSIGNAL3d    MACDM3d  MACDSIGNALM3d  \
362879   ALGOUSDT  -0.196147     -0.206298  -0.217501      -0.211374
685439    CRVUSDT  -0.306807     -0.374485  -0.427400      -0.408324
720719    IMXUSDT  -0.479047     -0.490996  -0.550871      -0.496970
1073519  FLUXUSDT  -0.094990     -0.143075  -0.148361      -0.167117
1315439  MOVRUSDT -37.241118    -37.614723 -38.751254     -37.801526

             diff     diffm
362879  -0.010151  0.006127
685439  -0.067678  0.019075
720719  -0.011949  0.053900
1073519 -0.048084 -0.018755
1315439 -0.373605  0.949728

/var/folders/t3/7kfp7_l943j4z41f1p54xwdm0000gn/T/ipykernel_189/4099794870.py:97: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pmacdu['diff']=abs(macd3du['MACD3d'])-abs(macd3du['MACDSIGNAL3d'])
/var/folders/t3/7kfp7_l943j4z41f1p54xwdm0000gn/T/ipykernel_189/4099794870.py:98: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pmacdu['diffm']=abs(macd3du['MACDM3d'])-abs(macd3du['MACDSIGNALM3d'])
/var/folders/t3/7kfp7_l943j4z41f1p54xwdm0000gn/T/ipykernel_189/4099794870.py:101: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pmacdd['diff']=abs(macd3dd['MACD3d'])-abs(macd3dd['MACDSIGNAL3d'])
/var/folders/t3/7kfp7_l943j4z41f1p54xwdm0000gn/T/ipykernel_189/4099794870.py:102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pmacdd['diffm']=abs(macd3dd['MACDM3d'])-abs(macd3dd['MACDSIGNALM3d'])

# Functions

In [12]:
#DRAFT functions

## return a list of timeframes per ta indicator taname  for specific sympbol
#series to list 
def srtolist(final:pd,taname)->[]:
    #ta = globals()[taname]
    array = final[taname].values
    array= str(array[0]).split(",")
    
    for k in range(0,len(array)):
            print (k)
            print (f" {taname} = {array[k]} \n")
    return array

# list to string 
def ltos (mylist)->str:
    mystring = ''
    for x in mylist:
        if not mystring:
            mystring+=x
        else:
            mystring+=","+x
    return mystring

def get_key(my_dict,val):
        keylist = []
        for key, value in my_dict.items():
             if val in value:
                keylist.append(key)
        return keylist
    
def to_df(final:pd ,func,name):
    listb = func(final)
    res = list(sorted({ele for val in listb.values() for ele in val}))
    reversetable = []
    for indi in res:
        ttuple = (indi,ltos(get_key(listb,indi)))
        reversetable.append(ttuple)
    dframe = pd.DataFrame(reversetable,columns=['Indicator',name])
    return dframe
                                                
    
def tops(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['top'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : query.append(i)
        toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist


def uptrend(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['uptrend'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def downtrend(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['downtrend'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def shift(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['shift'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def dshift(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['dshift'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def topr(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['topr'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def bottomr(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['bottomr'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def bottoms(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    bottomlist ={}
    for i in intervals:
        var = globals()['bottom'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            bottomlist[i]=test['Indicator'].tolist()
 
    return bottomlist

def room(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['room'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def roomr(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['roomr'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def rsiup(final:pd)-> pd :
    intervals = ['1','2','4','8','12','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['rule'+i+'RSIup']
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def rsidown(final:pd)-> pd :
    intervals = ['1','2','4','8','12','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['rule'+i+'RSIdown']
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def stover(final:pd)-> pd :
    intervals = ['1','2','4','8','12','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['rule'+i+'over']
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def stunder(final:pd)-> pd :
    intervals = ['1','2','4','8','12','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['rule'+i+'under']
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def stkup(final:pd)-> pd :
    intervals = ['1','2','4','8','12','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['rule'+i+'kup']
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

def stkdown(final:pd)-> pd :
    intervals = ['1','2','4','8','12','1d','3d','1w']        
    query = []
    toplist ={}
    for i in intervals:
        var = globals()['rule'+i+'kdown']
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : 
            query.append(i)
            toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

    return toplist

#not used but defined for later 
def mergetables(final:pd,*arg)->pd:
    indicators=final[['Indicator']]
    for i in range(0,len(arg)):
        test = indicators.merge(arg[i] ,how="left",on="Indicator")
        indicators = test
    return test

# call the function and merge the tables 
def callfun(final:pd,*var)->pd:
    indicators=final[['Indicator']]
    for i in range(0,len(var)):
        test=to_df(final ,globals()[var[i]],var[i])
        indicators=indicators.merge(test ,how="left",on="Indicator")
    return indicators

In [71]:
# dframe=to_df(final ,bottoms,'bottoms')
dframe=to_df(final ,tops,'tops')
dframe=to_df(final ,uptrend,'uptrend')
dframe1=to_df(final ,downtrend,'downtrend')
#dframe=to_df(final ,shift,'shift')
#dframe=to_df(final ,dshift,'dshift')
#dframe=to_df(final ,topr,'topr')
#dframe=to_df(final ,bottomr,'bottomr')
#dframe=to_df(final ,room,'room')
#dframe=to_df(final ,roomr,'roomr')
#dframe=to_df(final ,rsiup,'rsiup')
dframe=to_df(final ,rsidown,'rsidown')
newframe=mergetables(final,dframe,dframe1)
#newframe=callfun(final,'rsidown')
newframe=callfun(final,'rsiup','rsidown','tops','bottoms','bottomr','uptrend','dshift','downtrend','shift')
newframe=callfun(final,'rsiup','rsidown','tops','bottoms','bottomr','stover','stunder','stkup','stkdown')
newframe=callfun(final,'rsiup','rsidown','tops','bottoms','topr','bottomr','stover','room','roomr','stunder','stkup','stkdown','uptrend','dshift','downtrend','shift')

#newframe=newframe.sort_values(by=['downtrend','dshift','bottoms'],ascending=[True,True,True])
newframe=newframe.sort_values(by=['bottoms','stkup','bottomr'],ascending=[False,True,False])
newframe=newframe.sort_values(by=['bottomr','bottoms','shift'],ascending=[False,False,False])
newframe=newframe.sort_values(by=['bottomr','bottoms','rsidown'],ascending=[False,False,False])

newframe.to_csv("allindi"+str(date.today())+".csv")

test = newframe.loc[(newframe['downtrend'] <= '1h')]
test = newframe.loc[(newframe['bottoms'] >= '1h')]
test = newframe.loc[(newframe['rsidown'] >= '2h')]
#test = newframe.loc[(newframe['rsiup'] >= '1,2')]
#test = newframe.loc[(newframe['bottoms'] >= '2h,4h') & (newframe['rsiup'] >= '1,2')]
#test = newframe.loc[(newframe['bottoms'] >= '2h') & (newframe['bottomr'] >= '1') ]
#test = newframe.loc[(newframe['bottomr'] >= '1') & (newframe['rsiup'] >= '1')]
#test = newframe.loc[(newframe['bottomr'].notnull()) &  (newframe['rsidown'].notnull()) ]
#test = newframe.loc[(newframe['bottomr'].notnull()) &  (newframe['shift'].notnull()) ]
#test = newframe.loc[(newframe['bottoms'].notnull()) & (newframe['uptrend'].notnull()) &  (newframe['bottomr'].notnull()) ]
#test = newframe.loc[(newframe['bottoms'].notnull()) &  (newframe['stkup'].notnull()) & (newframe['rsidown'].isnull()) & (newframe['tops'] <='4h') & (newframe['topr'].isnull()) ]
#test = newframe.loc[(newframe['stkdown'].isnull()) &  (newframe['bottoms'].notnull()) ]
#test = newframe.loc[(newframe['stunder'] <= '3d') &  (newframe['rsiup'] <= '1d') ]
#test = newframe.loc[(newframe['shift'].notnull()) &  (newframe['uptrend'].notnull()) ]
#test = newframe.loc[(newframe['stunder'] <= '3d') &  (newframe['rsiup'] <= '1d') & (newframe['rsidown'].isnull())]
#test = newframe.loc[(newframe['rsiup'] <= '1d') & (newframe['rsidown'].isnull())]


#test = newframe.loc[(newframe['rsidown'].isnull()) &  (newframe['stkup'].notnull()) ]
#test = newframe.loc[(newframe['rsidown'].notnull()) &  (newframe['stkup'].notnull()) ]
#test = newframe.loc[(newframe['rsidown'].notnull()) &  (newframe['bottoms'].notnull())]


#test = newframe.loc[(newframe['bottomr'] >= '12h') &  (newframe['stkup'].notnull()) ]

#test = newframe.loc[(newframe['tops'].isnull()) &  (newframe['bottoms'].notnull()) ]
#test = newframe.loc[(newframe['stkup'].notnull()) &  (newframe['bottoms'].notnull()) & (newframe['tops'].isnull()) ]

#test = newframe.loc[(newframe['rsiup'] <= '2') & (newframe['bottoms'] >= '2h') ]

#test = newframe.loc[(newframe['rsidown'].isnull()) | (newframe['rsidown'] <= '1') ]

#test = newframe.loc[(newframe['shift'] >= '1h') &  (newframe['dshift'].isnull()) & (newframe['downtrend'].isnull()) ]
#test = newframe.loc[(newframe['shift'] >= '1h') &  (newframe['dshift'].isnull()) ]

#test = newframe.loc[(newframe['shift'] >= '12h,1d,3d')]

newframe

test

,Indicator,rsiup,rsidown,tops,bottoms,topr,bottomr,stover,room,roomr,stunder,stkup,stkdown,uptrend,dshift,downtrend,shift
50,1INCHUSDT,"1,8,12,1d,3d,1w",4,"2h,4h,8h,12h",3d,1h,NaN,"1,2,8,12,1d,3d","1h,1d,3d,1w","2h,4h,8h,12h,1d,3d,1w","4,1w","1,2,8,12,1d,3d","4,1w","1h,8h,12h,1d,3d",NaN,4h,1w
33,TFUELUSDT,"1,2,1w","8,12,1d,3d","4h,8h,12h","1h,3d",NaN,NaN,"12,1d,3d","1h,2h,1d,3d,1w","1h,2h,4h,8h,12h,1d,3d,1w","1,2,4,8,1w","12,1d,3d","1,2,4,8,1w",NaN,"12h,1d,3d",8h,"1h,2h,1w"
39,CELRUSDT,"1,2,1w","4,8,12,1d,3d","4h,8h,12h","1h,3d",NaN,NaN,"12,1d","1h,2h,1d,3d,1w","1h,2h,4h,8h,12h,1d,3d,1w","1,2,4,8,3d,1w","1,12,1d,3d","2,4,8,1w",NaN,"12h,1d","4h,8h","1h,2h,3d,1w"
54,LUNAUSDT,"1,2,3d,1w","4,8,12,1d","8h,12h","1h,3d",NaN,NaN,"8,12,1d","1h,2h,4h,1d,3d,1w","1h,2h,4h,8h,12h,1d,3d,1w","1,2,4,3d,1w","8,12,1d,3d,1w","1,2,4",NaN,"8h,12h,1d",4h,"1h,2h,3d,1w"
8,ALGOUSDT,"1,2,3d,1w","4,8,12,1d","8h,12h,1d",1h,NaN,NaN,"8,12,1d,3d,1w","1h,2h,4h,3d,1w","1h,2h,4h,8h,12h,1d,3d,1w","1,2,4","8,12,1d,3d,1w","1,2,4","3d,1w","8h,12h,1d",4h,"1h,2h"

In [14]:
## MACD gap and rsi up
newframe=callfun(macd3dd,'rsiup','rsidown','tops','bottoms','topr','bottomr','stover','room','roomr','stunder','stkup','stkdown','uptrend','dshift','downtrend','shift')
newframe=newframe.sort_values(by=['bottomr','bottoms','rsidown'],ascending=[False,False,False])
test = newframe.loc[(newframe['shift'].notnull()) & (newframe['uptrend'].notnull()) &  (newframe['bottomr'].notnull()) ]
test = newframe.loc[(newframe['uptrend'].notnull()) &  (newframe['bottoms'].notnull()) ]
#test = newframe.loc[(newframe['stkup'].notnull()) &  (newframe['bottoms'].notnull()) & (newframe['tops'].isnull()) ]


test

,Indicator,rsiup,rsidown,tops,bottoms,topr,bottomr,stover,room,roomr,stunder,stkup,stkdown,uptrend,dshift,downtrend,shift
4,MOVRUSDT,"1,2,4,8,12,1d,3d,1w",NaN,"4h,8h,12h",3d,NaN,1w,"8,12,1d","1h,2h,1d,3d","1h,2h,4h,8h,12h,1d,3d,1w","1,2,4,3d","8,12,1d","1,2,4,3d","8h,12h,1d",NaN,NaN,"1h,2h,4h,3d"
0,ALGOUSDT,"1,2,3d,1w","4,8,12,1d","8h,12h,1d",1h,NaN,NaN,"8,12,1d,3d,1w","1h,2h,4h,3d,1w","1h,2h,4h,8h,12h,1d,3d,1w","1,2,4","8,12,1d,3d,1w","1,2,4","3d,1w","8h,12h,1d",4h,"1h,2h"
2,IMXUSDT,"3d,1w","1,2,4,8,12,1d","4h,8h,12h,1d",1h,NaN,NaN,"8,12,1d,3d,1w","1h,2h,3d,1w","1h,2h,4h,8h,12h,1d,3d,1w","1,2,4","8,12,1d,3d,1w","1,2,4","3d,1w","8h,12h,1d","1h,2h,4h",NaN
1,CRVUSDT,"1,2,4,8,12,1d,3d,1w",NaN,"4h,8h,12h",1h,"2h,4h",NaN,"12,1d,1w","1h,2h,1d,3d,1w","1h,8h,12h,1d,3d,1w","1,2,4,3d","1,12,1d,3d,1w","2,4","12h,1d,1w",NaN,NaN,"1h,2h,4h,3d"

In [15]:
test = newframe.loc[(newframe['Indicator'] == 'BTCUSDT')]
test

Empty DataFrame
Columns: [Indicator, rsiup, rsidown, tops, bottoms, topr, bottomr, stover, room, roomr, stunder, stkup, stkdown, uptrend, dshift, downtrend, shift]
Index: []

# Create a function to filter the above 
    - things at the bottom and going up then go  down in timeframes 
    - 1d Bottom 
        - check 12 Bottom either going towards it
        - At the bottom of 12 
        - Already moved from the bottom of 12

In [16]:
## function to go through all metrics and choose buy and sell zones using string not direct rules make one with runes

def buyzone(dframe:pd)->pd:
    #print(dframe.columns)
    intervals = ['1','2','4','8','12','1d','3d','1w']
    metrics = ['Indicator','rsiup','rsidown','tops','bottoms','topr','bottomr','stover','room','stunder','stkup','stkdown','uptrend','dshift','downtrend','shift']
    tas = ['rsiup','rsidown','tops','bottoms','topr','bottomr','stover','room','stunder','stkup','stkdown','uptrend','dshift','downtrend','shift']
    rsiup,rsidown,tops,bottoms,topr,bottomr,stover,room,stunder,stkup,stkdown,uptrend,dshift,downtrend,shift=([] for i in range(15))

    dframe.set_index(metrics)
    indicators = dframe['Indicator']

    #print (type(indicators))
    #print(intervals[6])
    #print(metrics[15])
    print(len(tas))
        
    
    toplist ={}
    for i in indicators :
        print (i)
        var = dframe.loc[dframe['Indicator']==i]     
        for ta in tas :
            locals()[ta]=srtolist(var,ta)
        
        #for index, value in var.tops.items():
            #print(f"Index : {index}, Value : {value}")
        #if var : 
            #print (i,dframe[[i]].bottoms.values)
        #test = final.loc[(var)]
        #print(test[['Indicator']])
        #if len(test.index) > 0 : 
            #query.append(i)
            #toplist[i]=test['Indicator'].tolist()
        #print(query)
        #print(toplist)    

buyzone(test)

15

# Tops

# UP Trend

# UP with OR

In [17]:
## UP with K or RSI might show early reversal 
drop = final.loc[((rule3dkup | rule3dRSIup) & (rule1dkup | rule1dRSIup) & (rule12kup & rule12RSIup) & (rule8kup & rule8RSIup) & (rule4kup | rule4RSIup) & (final['STRSIK1d'] < 0.2) ) ]
#drop = final.loc[((rule3dkup | rule3dRSIup) & (rule1dkup | rule1dRSIup) & (rule12kup & rule12RSIup) & (rule8kup & rule8RSIup) & (rule4kup | rule4RSIup)  ) ]

#drop = final.loc[((rule3dkup | rule3dRSIup) & (rule1dkup | rule1dRSIup) & (rule12kup & rule12RSIup) & (rule8kup & rule8RSIup) & (rule4kup | rule4RSIup) &  (rule2kup | rule2RSIup) & (rule1kup | rule1RSIup) ) ]
#drop = final.loc[((rule3dkup | rule3dRSIup) & (rule1dkup | rule1dRSIup) & (rule12kup & rule12RSIup) & (rule8kup & rule8RSIup) & (rule4kup | rule4RSIup) &  (rule2kup | rule2RSIup) & (rule1kup | rule1RSIup) ) ]

#drop = final.loc[((uptrend3d) & (uptrend1d) & (uptrend12h) & (uptrend8h)) ]

#drop

# Up Shifts

In [18]:
# 3d to 8 hours with room
drop = final.loc[( (bottom3d) & (uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
drop = final.loc[((uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
drop = final.loc[((room1d & room12h & room8h & roomr3d & roomr1d & roomr12h & roomr8h) &(uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h)]
#drop = final.loc[((room3d) &(uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h)]

#drop = final.loc[((room3d & room1d & room12h & room8h & room4h & room2h) &(uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
#drop = final.loc[((room3d & room1d & room12h & room8h & room4h & room2h & room1h) &(uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) ]

#drop = final.loc[((uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) & (uptrend2h | shift2h) &  (uptrend1h | shift1h)]

#drop = final.loc[((uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h)]
#drop = final.loc[( (uptrend3d | shift3d) & (uptrend1d | shift1d) ) ]

#drop = drop.loc[((downtrend2h | dshift2h) | (downtrend1h | dshift1h) )]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [19]:
# UP alone shift alone
drop = final.loc[((uptrend3d)) & (uptrend8h) & (uptrend1d) & (uptrend12h) &  (uptrend4h) ]
#drop = final.loc[(shift3d) & (shift8h) & (shift1d) & (shift12h) &  (shift4h) ]
drop = final.loc[(shift8h) & (shift12h) &  (shift4h) ]
#drop = final.loc[(shift8h) & (shift12h) ]
#drop = final.loc[(shift8h)]
#drop = final.loc[(shift4h)]


#drop = final.loc[(shift8h) & (shift4h) ]


drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [20]:
# up with room till 12h
drop = final.loc[((roomr3d & roomr1d & roomr12h & room12h ) &(uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h)]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [21]:
# dshift on 4
drop = final.loc[(downtrend4h | dshift4h)]
drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
322559,MIRUSDT,1.16500,1.16300,1.16500,1.16200,8677.30,1.1530,1.16500,1.16800,1.14200,...,NaN,NaN,NaN,-1.064791,-1.064560,-1.067806,-1.064444,0.99400,2.7540,2022-05-05 12:05:18.955001
362879,ALGOUSDT,0.70470,0.70520,0.70600,0.70400,32468.00,0.7017,0.70480,0.70710,0.69730,...,0.924590,NaN,NaN,-0.347174,-0.346099,-0.365297,-0.345562,0.53730,1.8451,2022-05-05 12:05:18.955001
403199,ZRXUSDT,0.79170,0.79200,0.79230,0.79170,1211.00,0.7904,0.79250,0.79770,0.78780,...,0.820444,NaN,NaN,-0.037977,-0.072788,-0.056843,-0.090194,0.44810,1.1838,2022-05-05 12:05:18.955001
645119,LRCUSDT,0.81840,0.81820,0.81910,0.81760,11071.00,0.8063,0.81830,0.82170,0.80360,...,NaN,NaN,NaN,-0.163260,-0.138717,-0.157285,-0.126445,0.62680,2.4722,2022-05-05 12:05:18.955001
720719,IMXUSDT,1.78600,1.78500,1.78700,1.78400,3444.38,1.7800,1.78600,1.81000,1.77000,...,NaN,NaN,NaN,-0.479047,-0.490996,-0.550871,-0.496970,1.10100,2.8490,2022-05-05 12:05:18.955001
1073519,FLUXUSDT,1.64100,1.62900,1.64100,1.62500,26036.29,1.5820,1.64100,1.64600,1.57900,...,NaN,NaN,NaN,-0.094990,-0.143075,-0.148361,-0.167117,1.26500,2.1000,2022-05-05 12:05:18.955001
1592639,CELRUSDT,0.03852,0.03855,0.03856,0.03840,704505.60,0.0381,0.03852,0.03864,0.03790,...,0.043379,NaN,NaN,-0.016951,-0.015353,-0.015774,-0.014554,0.03089,0.1018,2022-05-05 12:05:18.955001
1794239,ZILUSDT,0.09208,0.09209,0.09262,0.09196,4871013.70,0.0959,0.09211,0.09693,0.09185,...,0.077769,NaN,NaN,0.010603,0.011919,0.012122,0.012577,0.03317,0.2307,2022-05-05 12:05:18.955001
2036159,1INCHUSDT,1.30600,1.31100,1.31500,1.30600,116585.80,1.2630,1.30600,1.32300,1.25900,...,NaN,NaN,NaN,-0.767362,-0.762773,-0.780029,-0.760478,1.07100,2.9820,2022-05-05 12:05:18.955001
2197439,LUNAUSDT,86.20000,86.29000,86.29000,86.19000,1074.93,85.8700,86.21000,86.26000,85.36000,...,NaN,NaN,NaN,20.036303,23.171286,21.478064,24.738777,43.44000,119.5500,2022-05-05 12:05:18.955001
2439359,THETAUSDT,2.56400,2.56100,2.56400,2.55500,37461.30,2.5490,2.56400,2.56800,2.52800,...,4.159050,NaN,NaN,-1.369178,-1.326050,-1.351659,-1.304486,2.13000,5.9460,2022-05-05 12:05:18.955001

In [22]:
# dshift on 2 
drop = final.loc[(downtrend2h | dshift2h)]
drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
322559,MIRUSDT,1.16500,1.16300,1.16500,1.16200,8677.30,1.1530,1.16500,1.16800,1.14200,...,NaN,NaN,NaN,-1.064791,-1.064560,-1.067806,-1.064444,0.99400,2.7540,2022-05-05 12:05:18.955001
645119,LRCUSDT,0.81840,0.81820,0.81910,0.81760,11071.00,0.8063,0.81830,0.82170,0.80360,...,NaN,NaN,NaN,-0.163260,-0.138717,-0.157285,-0.126445,0.62680,2.4722,2022-05-05 12:05:18.955001
720719,IMXUSDT,1.78600,1.78500,1.78700,1.78400,3444.38,1.7800,1.78600,1.81000,1.77000,...,NaN,NaN,NaN,-0.479047,-0.490996,-0.550871,-0.496970,1.10100,2.8490,2022-05-05 12:05:18.955001
1073519,FLUXUSDT,1.64100,1.62900,1.64100,1.62500,26036.29,1.5820,1.64100,1.64600,1.57900,...,NaN,NaN,NaN,-0.094990,-0.143075,-0.148361,-0.167117,1.26500,2.1000,2022-05-05 12:05:18.955001
1794239,ZILUSDT,0.09208,0.09209,0.09262,0.09196,4871013.70,0.0959,0.09211,0.09693,0.09185,...,0.077769,NaN,NaN,0.010603,0.011919,0.012122,0.012577,0.03317,0.2307,2022-05-05 12:05:18.955001
2439359,THETAUSDT,2.56400,2.56100,2.56400,2.55500,37461.30,2.5490,2.56400,2.56800,2.52800,...,4.159050,NaN,NaN,-1.369178,-1.326050,-1.351659,-1.304486,2.13000,5.9460,2022-05-05 12:05:18.955001
2479679,MANAUSDT,1.63080,1.63130,1.63240,1.62900,24961.00,1.6294,1.63080,1.63590,1.61430,...,NaN,NaN,NaN,-0.335879,-0.115027,-0.245342,-0.004601,1.33750,3.9694,2022-05-05 12:05:18.955001

In [23]:
# UP with room R till 8 hours
drop = final.loc[((room12h & roomr3d & roomr1d & roomr12h & roomr8h) &(uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [24]:
# UP with room till 4 hours
drop = final.loc[((room3d & room1d & room12h & room8h & room4h) &(uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [25]:
# UP with room till 2 hours
drop = final.loc[((room3d & room1d & room12h & room8h & room4h & room2h) &(uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [26]:
# UP trend shift 
#drop = final.loc[((downtrend2h | dshift2h) & (downtrend1h | dshift1h) )]
#drop = final.loc[((uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
drop = final.loc[((uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) ]

#drop = final.loc[((uptrend3d | shift3d)) & (uptrend1d | shift1d) & (uptrend12h | shift12h) ]

#drop = drop.loc[((downtrend2h | dshift2h) & (downtrend1h | dshift1h) )]
#drop = drop.loc[((downtrend2h | dshift2h))]
#drop = drop.loc[((downtrend2h | dshift2h))]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
1315439,MOVRUSDT,43.70000,43.70000,43.70000,43.60000,28.056,43.40000,43.6000,43.7000,43.20000,...,NaN,NaN,NaN,-110.309682,-117.103380,-113.584100,-120.500230,39.10000,240.00000,2022-05-05 12:05:18.955001
1471679,ONEUSDT,0.09021,0.09052,0.09059,0.09016,311385.000,0.09066,0.0902,0.0912,0.08949,...,0.101622,NaN,NaN,-0.056105,-0.045941,-0.052352,-0.040859,0.06953,0.37897,2022-05-05 12:05:18.955001
2036159,1INCHUSDT,1.30600,1.31100,1.31500,1.30600,116585.800,1.26300,1.3060,1.3230,1.25900,...,NaN,NaN,NaN,-0.767362,-0.762773,-0.780029,-0.760478,1.07100,2.98200,2022-05-05 12:05:18.955001

In [27]:
# UP with top 8 and 4 
drop = final.loc[((uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
drop = drop.loc[((top8h & top4h) &(uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (uptrend4h | shift4h) ]
drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
1315439,MOVRUSDT,43.70000,43.70000,43.70000,43.60000,28.056,43.40000,43.6000,43.7000,43.20000,...,NaN,NaN,NaN,-110.309682,-117.103380,-113.584100,-120.500230,39.10000,240.00000,2022-05-05 12:05:18.955001
1471679,ONEUSDT,0.09021,0.09052,0.09059,0.09016,311385.000,0.09066,0.0902,0.0912,0.08949,...,0.101622,NaN,NaN,-0.056105,-0.045941,-0.052352,-0.040859,0.06953,0.37897,2022-05-05 12:05:18.955001

In [28]:
# UP 3d to 8 hours and 4 hours down 
drop = final.loc[((uptrend3d | shift3d)) & (uptrend8h | shift8h) & (uptrend1d | shift1d) & (uptrend12h | shift12h) &  (dshift4h | downtrend4h) ]
drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
2036159,1INCHUSDT,1.306,1.311,1.315,1.306,116585.8,1.263,1.306,1.323,1.259,...,NaN,NaN,NaN,-0.767362,-0.762773,-0.780029,-0.760478,1.071,2.982,2022-05-05 12:05:18.955001

# Down options

In [29]:
#
drop = final.loc[(downtrend3d) & (downtrend8h) & (downtrend1d) & (downtrend12h) &  (downtrend4h) & (downtrend2h) & (downtrend1h)]
drop = final.loc[((downtrend3d)) & (downtrend8h) & (downtrend1d) & (downtrend12h) &  (downtrend4h) ]
#drop = final.loc[ (downtrend8h)  &  (downtrend4h) & (downtrend2h) & (downtrend1h)]
#drop = final.loc[ (downtrend4h) & (downtrend2h) & (downtrend1h)]

#drop = final.loc[((dshift3d)) & (dshift8h) & (dshift1d) & (dshift12h) &  (dshift4h) ]

#drop = final.loc[((downtrend3d | dshift3d)) & (downtrend8h | dshift8h) & (downtrend1d | dshift1d) & (downtrend12h | dshift12h) &  (downtrend4h | dshift4h) ]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [30]:
## FULL down options from 1 day till 4 hours 

drop = final.loc[((rule1dkdown & rule1dRSIdown) & (rule12kdown & rule12RSIdown) & (rule8kdown & rule8RSIdown) & (rule4kdown & rule4RSIdown))]
#drop = final.loc[((rule1dkdown & rule1dRSIdown) & (rule12kdown & rule12RSIdown) & (rule8kdown & rule8RSIdown))]
#drop = final.loc[((rule1dkdown & rule1dRSIdown) & (rule12kdown & rule12RSIdown))]


drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [31]:
##  FULL down options from 1 day till 2 hours  down option and & 
drop = final.loc[((rule1dkdown & rule1dRSIdown) & (rule12kdown & rule12RSIdown) & (rule8kdown & rule8RSIdown) & (rule4kdown & rule4RSIdown))]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

# UP options

In [32]:
###FULL  up option and | till 8

#drop = final.loc[((rule3dkup | rule3dRSIup) & (rule1dkup | rule1dRSIup) & (rule12kup | rule12RSIup) & (rule8kup | rule8RSIup) & (rule4kup | rule4RSIup) & (rule2kup | rule2RSIup))]
#drop = final.loc[((rule1dkup & rule1dRSIup) & (rule12kup & rule12RSIup) & (rule8kup & rule8RSIup) & (rule4kup & rule4RSIup))]
drop = final.loc[((rule1dkup & rule1dRSIup) & (rule12kup & rule12RSIup) & (rule8kup & rule8RSIup))]

#drop = final.loc[((rule1dkup & rule1dRSIup) | (rule12kup & rule12RSIup) | (rule8kup & rule8RSIup) )]
#drop = final.loc[((rule3dkup | rule3dRSIup) & (rule1dkup | rule1dRSIup) & (rule12kup | rule12RSIup) & (rule8kup | rule8RSIup)) ]
#drop = final.loc[((rule3dkup | rule3dRSIup) & (rule1dkup | rule1dRSIup) & (rule12kup | rule12RSIup) & (rule8kup | rule8RSIup) & (rule4kup | rule4RSIup) ) ]
#drop = drop.loc[(roomr3d & roomr12h & roomr8h & roomr4h)]
#drop = final.loc[((rule3dkup | rule3dRSIup) & (rule1dkup | rule1dRSIup) & (rule12kup | rule12RSIup) & (rule8kup | rule8RSIup) & (rule4kup | rule4RSIup) & (final['STRSIK1d'] < 0.2) ) ]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
1315439,MOVRUSDT,43.70000,43.70000,43.70000,43.60000,28.056,43.40000,43.6000,43.7000,43.20000,...,NaN,NaN,NaN,-110.309682,-117.103380,-113.584100,-120.500230,39.10000,240.00000,2022-05-05 12:05:18.955001
1471679,ONEUSDT,0.09021,0.09052,0.09059,0.09016,311385.000,0.09066,0.0902,0.0912,0.08949,...,0.101622,NaN,NaN,-0.056105,-0.045941,-0.052352,-0.040859,0.06953,0.37897,2022-05-05 12:05:18.955001
2036159,1INCHUSDT,1.30600,1.31100,1.31500,1.30600,116585.800,1.26300,1.3060,1.3230,1.25900,...,NaN,NaN,NaN,-0.767362,-0.762773,-0.780029,-0.760478,1.07100,2.98200,2022-05-05 12:05:18.955001

In [33]:
# up options but down on 4 

drop = final.loc[((rule3dkup | rule3dRSIup) & (rule1dkup | rule1dRSIup) & (rule12kup | rule12RSIup) & (rule8kup | rule8RSIup) & (dshift4h | downtrend4h)) ]
drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
362879,ALGOUSDT,0.7047,0.7052,0.7060,0.7040,32468.00,0.7017,0.7048,0.7071,0.6973,...,0.924590,NaN,NaN,-0.347174,-0.346099,-0.365297,-0.345562,0.5373,1.8451,2022-05-05 12:05:18.955001
403199,ZRXUSDT,0.7917,0.7920,0.7923,0.7917,1211.00,0.7904,0.7925,0.7977,0.7878,...,0.820444,NaN,NaN,-0.037977,-0.072788,-0.056843,-0.090194,0.4481,1.1838,2022-05-05 12:05:18.955001
645119,LRCUSDT,0.8184,0.8182,0.8191,0.8176,11071.00,0.8063,0.8183,0.8217,0.8036,...,NaN,NaN,NaN,-0.163260,-0.138717,-0.157285,-0.126445,0.6268,2.4722,2022-05-05 12:05:18.955001
720719,IMXUSDT,1.7860,1.7850,1.7870,1.7840,3444.38,1.7800,1.7860,1.8100,1.7700,...,NaN,NaN,NaN,-0.479047,-0.490996,-0.550871,-0.496970,1.1010,2.8490,2022-05-05 12:05:18.955001
1073519,FLUXUSDT,1.6410,1.6290,1.6410,1.6250,26036.29,1.5820,1.6410,1.6460,1.5790,...,NaN,NaN,NaN,-0.094990,-0.143075,-0.148361,-0.167117,1.2650,2.1000,2022-05-05 12:05:18.955001
2036159,1INCHUSDT,1.3060,1.3110,1.3150,1.3060,116585.80,1.2630,1.3060,1.3230,1.2590,...,NaN,NaN,NaN,-0.767362,-0.762773,-0.780029,-0.760478,1.0710,2.9820,2022-05-05 12:05:18.955001
2197439,LUNAUSDT,86.2000,86.2900,86.2900,86.1900,1074.93,85.8700,86.2100,86.2600,85.3600,...,NaN,NaN,NaN,20.036303,23.171286,21.478064,24.738777,43.4400,119.5500,2022-05-05 12:05:18.955001

In [34]:
### 3 days up option and |

#drop = final.loc[((rule3dkup | rule3dRSIup))]
#drop = final.loc[((rule3dkup | rule3dRSIup) & (final['STRSIK1d'] < 0.2) )]

#drop = final.loc[((rule3dkup & rule3dRSIup) & (rule3dover))]
#drop = final.loc[((rule3dkup & rule3dRSIup) & (rule1dkup))]


#drop

In [35]:
## 3days under 0.2 // about to go up 
#drop = final.loc[( (final['STRSIK3d'] < 0.2) )]
#drop

In [36]:
# 1 day under 0.2 about to go up 
#drop = final.loc[(  (final['STRSIK1d'] < 0.2) )]
#drop

In [37]:
# 1 and 3 day under 0.2
drop = final.loc[(  (final['STRSIK1d'] < 0.2) & (final['STRSIK3d'] < 0.2) )]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [38]:
# 1 and 3 days pointing up and still have room on 3 days < 0.7 

#drop = final.loc[( (final['STRSIK3d'] > final['STRSID3d']) & (final['STRSIK1d'] > final['STRSID1d'])  & (final['STRSIK3d'] < 0.7)  )]
drop = final.loc[( (rule3dkup) & (rule1dkup)  & (final['STRSIK3d'] < 0.8) & (final['STRSIK1d'] < 0.8)  )]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
40319,ANKRUSDT,0.065830,0.065930,0.065950,0.065820,1.814409e+05,0.066860,0.065840,0.066880,0.065820,...,0.063906,NaN,NaN,-0.014089,-0.011956,-0.013035,-0.010890,0.051070,0.11941,2022-05-05 12:05:18.955001
80639,AVAXUSDT,67.160000,67.280000,67.310000,67.100000,1.369070e+03,66.980000,67.140000,67.380000,66.730000,...,NaN,NaN,NaN,-1.798922,3.138903,-0.433112,5.607816,52.950000,127.32000,2022-05-05 12:05:18.955001
120959,WAXPUSDT,0.224700,0.224800,0.224900,0.224600,2.452100e+04,0.223900,0.224900,0.225100,0.222100,...,NaN,NaN,NaN,-0.093935,-0.080320,-0.086685,-0.073513,0.204800,0.53050,2022-05-05 12:05:18.955001
201599,LINKUSDT,11.990000,12.010000,12.020000,11.980000,4.800610e+03,11.960000,12.000000,12.020000,11.910000,...,20.101752,NaN,NaN,-5.813270,-5.478109,-5.717577,-5.310528,10.650000,28.71000,2022-05-05 12:05:18.955001
282239,ATOMUSDT,19.980000,20.010000,20.070000,19.970000,9.841370e+03,19.950000,19.980000,20.140000,19.870000,...,17.702010,NaN,NaN,-4.433399,-2.476045,-3.840063,-1.497368,17.220000,44.70000,2022-05-05 12:05:18.955001
443519,XTZUSDT,2.828000,2.839000,2.843000,2.828000,2.265280e+04,2.807000,2.827000,2.880000,2.798000,...,3.767740,NaN,NaN,-0.901297,-0.832343,-0.914350,-0.797865,2.390000,5.36500,2022-05-05 12:05:18.955001
524159,NEARUSDT,12.707000,12.724000,12.734000,12.705000,6.922100e+03,12.751000,12.706000,12.780000,12.646000,...,NaN,NaN,NaN,2.384499,2.906230,2.854220,3.167095,7.385000,20.59700,2022-05-05 12:05:18.955001
604799,DENTUSDT,0.002257,0.002258,0.002258,0.002256,1.356740e+05,0.002255,0.002258,0.002264,0.002243,...,0.003086,NaN,NaN,-0.000978,-0.000912,-0.000946,-0.000879,0.001934,0.00550,2022-05-05 12:05:18.955001
685439,CRVUSDT,2.603000,2.607000,2.609000,2.602000,1.257410e+04,2.634000,2.603000,2.637000,2.603000,...,NaN,NaN,NaN,-0.472869,-0.522246,-0.569052,-0.546934,1.868000,6.80000,2022-05-05 12:05:18.955001
755999,SCRTUSDT,3.921000,3.926000,3.926000,3.921000,5.753000e+02,3.919000,3.923000,3.930000,3.912000,...,NaN,NaN,NaN,-0.897122,-0.713231,-0.862354,-0.621286,3.605000,6.84800,2022-05-05 12:05:18.955001
796319,RENUSDT,0.305000,0.305300,0.305300,0.304800,2.301800e+04,0.303200,0.305300,0.305900,0.301100,...,0.538559,NaN,NaN,-0.161750,-0.159637,-0.162814,-0.158581,0.242600,0.77150,2022-05-05 12:05:18.955001
836639,SUSHIUSDT,2.592000,2.594000,2.594000,2.589000,1.637100e+04,2.575000,2.592000,2.597000,2.557000,...,NaN,NaN,NaN,-2.804007,-2.838111,-2.812371,-2.855162,2.240000,10.68400,2022-05-05 12:05:18.955001
917279,XLMUSDT,0.184900,0.185100,0.185200,0.184800,1.428830e+05,0.185600,0.184800,0.185700,0.184700,...,0.256641,NaN,NaN,-0.055395,-0.055582,-0.056384,-0.055676,0.161700,0.30590,2022-05-05 12:05:18.955001
997919,OMGUSDT,4.195000,4.204000,4.208000,4.195000,1.170000e+03,4.180000,4.194000,4.206000,4.158000,...,5.499918,NaN,NaN,-1.525861,-1.507688,-1.537666,-1.498602,3.326000,7.19700,2022-05-05 12:05:18.955001
1113839,SRMUSDT,1.997000,2.000000,2.001000,1.995000,5.981300e+03,1.990000,1.996000,2.003000,1.980000,...,NaN,NaN,NaN,-1.339587,-1.342796,-1.327951,-1.344400,1.652000,4.28300,2022-05-05 12:05:18.955001
1194479,ANTUSDT,3.541000,3.546000,3.548000,3.539000,3.360300e+03,3.536000,3.541000,3.547000,3.507000,...,NaN,NaN,NaN,-1.332916,-1.027002,-1.210500,-0.874045,3.057000,14.29300,2022-05-05 12:05:18.955001
1234799,RAYUSDT,2.227000,2.229000,2.229000,2.227000,1.227000e+03,2.218000,2.228000,2.232000,2.206000,...,NaN,NaN,NaN,-2.483595,-2.566998,-2.507520,-2.608699,2.000000,8.20000,2022-05-05 12:05:18.955001
1275119,ROSEUSDT,0.183740,0.183900,0.184000,0.183550,6.216510e+04,0.183240,0.183720,0.184270,0.181450,...,NaN,NaN,NaN,-0.032831,-0.013437,-0.024068,-0.003740,0.153610,0.59800,2022-05-05 12:05:18.955001
1355759,TFUELUSDT,0.141300,0.141300,0.141300,0.141200,2.278800e+04,0.141700,0.141200,0.141700,0.140100,...,0.182240,NaN,NaN,-0.056830,-0.052193,-0.054823,-0.049874,0.114000,0.25000,2022-05-05 12:05:18.955001
1431359,COTIUSDT,0.217000,0.217600,0.217600,0.216900,3.802100e+04,0.218500,0.217100,0.219100,0.216700,...,0.215047,NaN,NaN,-0.061528,-0.058805,-0.062955,-0.057444,0.170400,0.45980,2022-05-05 12:05:18.955001
1471679,ONEUSDT,0.090210,0.090520,0.090590,0.090160,3.113850e+05,0.090660,0.090200,0.091200,0.089490,...,0.101622,NaN,NaN,-0.056105,-0.045941,-0.052352,-0.040859,0.069530,0.37897,2022-05-05 12:05:18.955001
1511999,VETUSDT,0.052930,0.053080,0.053100,0.052920,1.117988e+06,0.053310,0.052940,0.053360,0.052690,...,0.069015,NaN,NaN,-0.019720,-0.019355,-0.019724,-0.019173,0.039050,0.10298,2022-05-05 12:05:18.955001
1552319,RUNEUSDT,7.343000,7.356000,7.365000,7.335000,5.725300e+03,7.307000,7.340000,7.402000,7.263000,...,NaN,NaN,NaN,0.060451,0.301811,0.157428,0.422491,3.015000,13.20300,2022-05-05 12:05:18.955001
1592639,CELRUSDT,0.038520,0.038550,0.038560,0.038400,7.045056e+05,0.038100,0.038520,0.038640,0.037900,...,0.043379,NaN,NaN,-0.016951,-0.015353,-0.015774,-0.014554,0.030890,0.10180,2022-05-05 12:05:18.955001
1632959,ONTUSDT,0.481800,0.482800,0.482800,0.481800,2.207300e+04,0.482700,0.481900,0.483600,0.480000,...,0.838844,NaN,NaN,-0.174534,-0.174241,-0.174743,-0.174095,0.405600,0.78090,2022-05-05 12:05:18.955001
1673279,GALAUSDT,0.157390,0.157850,0.157880,0.157370,6.622310e+05,0.157250,0.157400,0.158520,0.156580,...,NaN,NaN,NaN,-0.050284,-0.031434,-0.043893,-0.022009,0.120000,0.59880,2022-05-05 12:05:18.955001
1713599,GRTUSDT,0.332100,0.332800,0.332900,0.331800,8.501900e+04,0.333400,0.332100,0.334200,0.331000,...,NaN,NaN,NaN,-0.214135,-0.218761,-0.217859,-0.221073,0.290000,0.77700,2022-05-05 12:05:18.955001
1753919,DOTUSDT,16.180000,16.190000,16.200000,16.170000,8.096370e+03,16.160000,16.180000,16.230000,16.070000,...,NaN,NaN,NaN,-5.820978,-5.452171,-5.667417,-5.267768,14.050000,32.78000,2022-05-05 12:05:18.955001
1915199,MATICUSDT,1.158000,1.160000,1.161000,1.158000,8.498440e+04,1.161000,1.158000,1.163000,1.154000,...,0.851948,NaN,NaN,-0.235563,-0.149209,-0.200167,-0.106033,1.011000,2.92300,2022-05-05 12:05:18.955001
1955519,FTMUSDT,0.856900,0.858400,0.859800,0.856400,1.134090e+05,0.848800,0.856800,0.862000,0.844000,...,0.760668,NaN,NaN,-0.442431,-0.320300,-0.400219,-0.259235,0.651300,3.37880,2022-05-05 12:05:18.955001
1995839,BANDUSDT,3.319000,3.329000,3.330000,3.319000,4.639000e+02,3.326000,3.321000,3.338000,3.311000,...,7.701866,NaN,NaN,-1.831315,-1.820170,-1.842259,-1.814598,2.792000,7.00000,2022-05-05 12:05:18.955001
2036159,1INCHUSDT,1.306000,1.311000,1.315000,1.306000,1.165858e+05,1.263000,1.306000,1.323000,1.259000,...,NaN,NaN,NaN,-0.767362,-0.762773,-0.780029,-0.760478,1.071000,2.98200,2022-05-05 12:05:18.955001
2076479,AUDIOUSDT,0.907000,0.909000,0.909000,0.907000,5.479400e+03,0.910000,0.907000,0.914000,0.898000,...,NaN,NaN,NaN,-0.288984,-0.269661,-0.249257,-0.259999,0.653000,2.13100,2022-05-05 12:05:18.955001
2116799,IOTXUSDT,0.060560,0.060640,0.060660,0.060550,6.917000e+04,0.060350,0.060560,0.060810,0.060150,...,0.046689,NaN,NaN,-0.012784,-0.008132,-0.010291,-0.005806,0.054800,0.15314,2022-05-05 12:05:18.955001
2157119,CTSIUSDT,0.296900,0.297500,0.297700,0.296700,2.539100e+04,0.296900,0.297000,0.298000,0.294700,...,0.386062,NaN,NaN,-0.164673,-0.156559,-0.161912,-0.152501,0.252700,0.85200,2022-05-05 12:05:18.955001
2197439,LUNAUSDT,86.200000,86.290000,86.290000,86.190000,1.074930e+03,85.870000,86.210000,86.260000,85.360000,...,NaN,NaN,NaN,20.036303,23.171286,21.478064,24.738777,43.440000,119.55000,2022-05-05 12:05:18.955001
2278079,MINAUSDT,2.016000,2.027000,2.029000,2.015000,8.839200e+03,2.030000,2.016000,2.033000,2.000000,...,NaN,NaN,NaN,-0.751594,-0.699782,-0.740417,-0.673876,1.584000,4.24800,2022-05-05 12:05:18.955001
2318399,BTCUSDT,39588.850000,39605.410000,39607.800000,39585.220000,2.458828e+01,39549.280000,39588.840000,39619.940000,39516.920000,...,35963.226100,NaN,NaN,-3399.177718,-3043.917688,-3398.938884,-2866.287673,32917.170000,52088.00000,2022-05-05 12:05:18.955001
2358719,ADAUSDT,0.874300,0.874400,0.875000,0.872800,5.714922e+05,0.862500,0.874300,0.877900,0.861300,...,1.004927,NaN,NaN,-0.322923,-0.319323,-0.332197,-0.317523,0.735100,1.63800,2022-05-05 12:05:18.955001
2399039,STORJUSDT,0.941300,0.944200,0.944900,0.941200,2.316000e+03,0.941200,0.941200,0.946800,0.936400,...,NaN,NaN,NaN,-0.246280,-0.209630,-0.229412,-0.191304,0.771400,2.18560,2022-05-05 12:05:18.955001
2439359,THETAUSDT,2.564000,2.561000,2.564000,2.555000,3.746130e+04,2.549000,2.564000,2.568000,2.528000,...,4.159050,NaN,NaN,-1.369178,-1.326050,-1.351659,-1.304486,2.130000,5.94600,2022-05-05 12:05:18.955001
2479679,MANAUSDT,1.630800,1.631300,1.632400,1.629000,2.496100e+04,1.629400,1.630800,1.635900,1.614300,...,NaN,NaN,NaN,-0.335879,-0.115027,-0.245342,-0.004601,1.337500,3.96940,2022-05-05 12:05:18.955001
2519999,PAXGUSDT,1896.000000,1895.000000,1896.000000,1895.000000,3.331300e+00,1898.000000,1895.000000,1898.000000,1894.000000,...,NaN,NaN,NaN,43.367996,61.143861,57.233692,70.031793,1759.000000,2076.00000,2022-05-05 12:05:18.955001

In [39]:
## 1 day small room up
drop = final.loc[( (rule3dover) & (rule1dover)  & (top1d) & (final['STRSIK1d'] > 0.8)  & (rule1dRSIup) & (rule3dkup) & (rule1dkup) )]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [40]:
## 1 day will start go down 
drop = final.loc[( (rule3dover) & (rule1dover)  & (final['STRSIK1d'] > 0.8) & (rule1dRSIdown) )]
drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
241919,ARUSDT,26.0000,26.0400,26.040,26.000,170.89,25.9400,25.9900,26.0700,25.7000,...,NaN,NaN,NaN,-8.406501,-7.045464,-7.971154,-6.364945,22.0100,69.0000,2022-05-05 12:05:18.955001
322559,MIRUSDT,1.1650,1.1630,1.165,1.162,8677.30,1.1530,1.1650,1.1680,1.1420,...,NaN,NaN,NaN,-1.064791,-1.064560,-1.067806,-1.064444,0.9940,2.7540,2022-05-05 12:05:18.955001
362879,ALGOUSDT,0.7047,0.7052,0.706,0.704,32468.00,0.7017,0.7048,0.7071,0.6973,...,0.92459,NaN,NaN,-0.347174,-0.346099,-0.365297,-0.345562,0.5373,1.8451,2022-05-05 12:05:18.955001
720719,IMXUSDT,1.7860,1.7850,1.787,1.784,3444.38,1.7800,1.7860,1.8100,1.7700,...,NaN,NaN,NaN,-0.479047,-0.490996,-0.550871,-0.496970,1.1010,2.8490,2022-05-05 12:05:18.955001
957599,HNTUSDT,16.3200,16.3800,16.380,16.320,457.64,16.4200,16.3300,16.4400,16.2800,...,NaN,NaN,NaN,-5.607353,-4.065078,-5.326369,-3.293941,11.6100,45.1600,2022-05-05 12:05:18.955001
2560319,INJUSDT,4.2220,4.2230,4.223,4.222,171.40,4.2520,4.2220,4.2520,4.2210,...,NaN,NaN,NaN,-2.398083,-2.227965,-2.382864,-2.142906,3.4180,10.3370,2022-05-05 12:05:18.955001

In [41]:
# 1 day started to  go down 
drop = final.loc[( (rule1dkdown) & (rule1dover)  & (final['STRSIK1d'] > 0.8) & (rule1dRSIdown) )]

drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [42]:
# 12 H over and  RSI up
#drop = final.loc[(rule12over & rule12RSIup)]

#drop

In [43]:
# 12 H down  RSI down
#drop = final.loc[(rule12kdown & rule12RSIdown)]

#drop

In [44]:
# 12 down  RSI up
#drop = final.loc[(rule12kdown & rule12RSIup)]
#drop = final.loc[(rule12kdown & rule12RSIup)]

#drop

In [45]:
# 12 down  RSI up under 0.2
drop = final.loc[(rule12kdown & rule12RSIup & (final['STRSIK12h'] < 0.2) )]

#drop = final.loc[(rule12kdown & rule12RSIup)]

drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [46]:
# 12 up  RSI up under 0.2
drop = final.loc[(rule12kup & rule12RSIup & (final['STRSIK12h'] < 0.2) )]
drop = final.loc[((final['STRSIK12h'] < 0.2) )]

#drop = final.loc[(rule12kdown & rule12RSIup)]

drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [47]:
# 8 H down
drop = final.loc[(rule8kdown & rule8RSIdown)]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
1355759,TFUELUSDT,0.14130,0.14130,0.14130,0.14120,22788.0,0.1417,0.14120,0.14170,0.14010,...,0.182240,NaN,NaN,-0.056830,-0.052193,-0.054823,-0.049874,0.11400,0.2500,2022-05-05 12:05:18.955001
1592639,CELRUSDT,0.03852,0.03855,0.03856,0.03840,704505.6,0.0381,0.03852,0.03864,0.03790,...,0.043379,NaN,NaN,-0.016951,-0.015353,-0.015774,-0.014554,0.03089,0.1018,2022-05-05 12:05:18.955001
1794239,ZILUSDT,0.09208,0.09209,0.09262,0.09196,4871013.7,0.0959,0.09211,0.09693,0.09185,...,0.077769,NaN,NaN,0.010603,0.011919,0.012122,0.012577,0.03317,0.2307,2022-05-05 12:05:18.955001
2439359,THETAUSDT,2.56400,2.56100,2.56400,2.55500,37461.3,2.5490,2.56400,2.56800,2.52800,...,4.159050,NaN,NaN,-1.369178,-1.326050,-1.351659,-1.304486,2.13000,5.9460,2022-05-05 12:05:18.955001

In [48]:
# 8 H over RSI up
drop = final.loc[(rule8over & rule8RSIup)]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
80639,AVAXUSDT,67.16000,67.28000,67.31000,67.10000,1369.070,66.98000,67.14000,67.38000,66.73000,...,NaN,NaN,NaN,-1.798922,3.138903,-0.433112,5.607816,52.95000,127.32000,2022-05-05 12:05:18.955001
120959,WAXPUSDT,0.22470,0.22480,0.22490,0.22460,24521.000,0.22390,0.22490,0.22510,0.22210,...,NaN,NaN,NaN,-0.093935,-0.080320,-0.086685,-0.073513,0.20480,0.53050,2022-05-05 12:05:18.955001
241919,ARUSDT,26.00000,26.04000,26.04000,26.00000,170.890,25.94000,25.99000,26.07000,25.70000,...,NaN,NaN,NaN,-8.406501,-7.045464,-7.971154,-6.364945,22.01000,69.00000,2022-05-05 12:05:18.955001
282239,ATOMUSDT,19.98000,20.01000,20.07000,19.97000,9841.370,19.95000,19.98000,20.14000,19.87000,...,17.702010,NaN,NaN,-4.433399,-2.476045,-3.840063,-1.497368,17.22000,44.70000,2022-05-05 12:05:18.955001
443519,XTZUSDT,2.82800,2.83900,2.84300,2.82800,22652.800,2.80700,2.82700,2.88000,2.79800,...,3.767740,NaN,NaN,-0.901297,-0.832343,-0.914350,-0.797865,2.39000,5.36500,2022-05-05 12:05:18.955001
836639,SUSHIUSDT,2.59200,2.59400,2.59400,2.58900,16371.000,2.57500,2.59200,2.59700,2.55700,...,NaN,NaN,NaN,-2.804007,-2.838111,-2.812371,-2.855162,2.24000,10.68400,2022-05-05 12:05:18.955001
876959,CAKEUSDT,7.71600,7.71900,7.72100,7.71300,995.500,7.71800,7.71800,7.72500,7.68100,...,NaN,NaN,NaN,-3.131324,-3.495932,-3.136239,-3.678236,5.30000,13.50000,2022-05-05 12:05:18.955001
1038239,LINAUSDT,0.01949,0.01956,0.01957,0.01948,1017814.060,0.01953,0.01951,0.01971,0.01943,...,NaN,NaN,NaN,-0.016494,-0.017515,-0.016789,-0.018026,0.01633,0.05500,2022-05-05 12:05:18.955001
1315439,MOVRUSDT,43.70000,43.70000,43.70000,43.60000,28.056,43.40000,43.60000,43.70000,43.20000,...,NaN,NaN,NaN,-110.309682,-117.103380,-113.584100,-120.500230,39.10000,240.00000,2022-05-05 12:05:18.955001
1391039,GLMRUSDT,2.81000,2.81710,2.81910,2.81000,2388.200,2.79660,2.80930,2.82000,2.77620,...,NaN,NaN,NaN,-1.548201,-1.467644,-1.567746,-1.427365,2.18070,5.99000,2022-05-05 12:05:18.955001
1471679,ONEUSDT,0.09021,0.09052,0.09059,0.09016,311385.000,0.09066,0.09020,0.09120,0.08949,...,0.101622,NaN,NaN,-0.056105,-0.045941,-0.052352,-0.040859,0.06953,0.37897,2022-05-05 12:05:18.955001
1713599,GRTUSDT,0.33210,0.33280,0.33290,0.33180,85019.000,0.33340,0.33210,0.33420,0.33100,...,NaN,NaN,NaN,-0.214135,-0.218761,-0.217859,-0.221073,0.29000,0.77700,2022-05-05 12:05:18.955001
1995839,BANDUSDT,3.31900,3.32900,3.33000,3.31900,463.900,3.32600,3.32100,3.33800,3.31100,...,7.701866,NaN,NaN,-1.831315,-1.820170,-1.842259,-1.814598,2.79200,7.00000,2022-05-05 12:05:18.955001
2036159,1INCHUSDT,1.30600,1.31100,1.31500,1.30600,116585.800,1.26300,1.30600,1.32300,1.25900,...,NaN,NaN,NaN,-0.767362,-0.762773,-0.780029,-0.760478,1.07100,2.98200,2022-05-05 12:05:18.955001
2116799,IOTXUSDT,0.06056,0.06064,0.06066,0.06055,69170.000,0.06035,0.06056,0.06081,0.06015,...,0.046689,NaN,NaN,-0.012784,-0.008132,-0.010291,-0.005806,0.05480,0.15314,2022-05-05 12:05:18.955001
2157119,CTSIUSDT,0.29690,0.29750,0.29770,0.29670,25391.000,0.29690,0.29700,0.29800,0.29470,...,0.386062,NaN,NaN,-0.164673,-0.156559,-0.161912,-0.152501,0.25270,0.85200,2022-05-05 12:05:18.955001
2278079,MINAUSDT,2.01600,2.02700,2.02900,2.01500,8839.200,2.03000,2.01600,2.03300,2.00000,...,NaN,NaN,NaN,-0.751594,-0.699782,-0.740417,-0.673876,1.58400,4.24800,2022-05-05 12:05:18.955001

In [49]:
# 8 H down RSI up
drop = final.loc[(rule8kdown & rule8RSIup)]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
40319,ANKRUSDT,0.065830,0.065930,0.065950,0.065820,1.814409e+05,0.066860,0.065840,0.066880,0.065820,...,0.063906,NaN,NaN,-0.014089,-0.011956,-0.013035,-0.010890,0.051070,0.11941,2022-05-05 12:05:18.955001
524159,NEARUSDT,12.707000,12.724000,12.734000,12.705000,6.922100e+03,12.751000,12.706000,12.780000,12.646000,...,NaN,NaN,NaN,2.384499,2.906230,2.854220,3.167095,7.385000,20.59700,2022-05-05 12:05:18.955001
755999,SCRTUSDT,3.921000,3.926000,3.926000,3.921000,5.753000e+02,3.919000,3.923000,3.930000,3.912000,...,NaN,NaN,NaN,-0.897122,-0.713231,-0.862354,-0.621286,3.605000,6.84800,2022-05-05 12:05:18.955001
876959,CAKEUSDT,7.716000,7.719000,7.721000,7.713000,9.955000e+02,7.718000,7.718000,7.725000,7.681000,...,NaN,NaN,NaN,-3.131324,-3.495932,-3.136239,-3.678236,5.300000,13.50000,2022-05-05 12:05:18.955001
957599,HNTUSDT,16.320000,16.380000,16.380000,16.320000,4.576400e+02,16.420000,16.330000,16.440000,16.280000,...,NaN,NaN,NaN,-5.607353,-4.065078,-5.326369,-3.293941,11.610000,45.16000,2022-05-05 12:05:18.955001
997919,OMGUSDT,4.195000,4.204000,4.208000,4.195000,1.170000e+03,4.180000,4.194000,4.206000,4.158000,...,5.499918,NaN,NaN,-1.525861,-1.507688,-1.537666,-1.498602,3.326000,7.19700,2022-05-05 12:05:18.955001
1113839,SRMUSDT,1.997000,2.000000,2.001000,1.995000,5.981300e+03,1.990000,1.996000,2.003000,1.980000,...,NaN,NaN,NaN,-1.339587,-1.342796,-1.327951,-1.344400,1.652000,4.28300,2022-05-05 12:05:18.955001
1154159,VTHOUSDT,0.003323,0.003323,0.003323,0.003323,1.267860e+05,0.003342,0.003319,0.003342,0.003316,...,NaN,NaN,NaN,-0.001835,-0.001836,-0.001797,-0.001837,0.002738,0.01000,2022-05-05 12:05:18.955001
1194479,ANTUSDT,3.541000,3.546000,3.548000,3.539000,3.360300e+03,3.536000,3.541000,3.547000,3.507000,...,NaN,NaN,NaN,-1.332916,-1.027002,-1.210500,-0.874045,3.057000,14.29300,2022-05-05 12:05:18.955001
1234799,RAYUSDT,2.227000,2.229000,2.229000,2.227000,1.227000e+03,2.218000,2.228000,2.232000,2.206000,...,NaN,NaN,NaN,-2.483595,-2.566998,-2.507520,-2.608699,2.000000,8.20000,2022-05-05 12:05:18.955001
1275119,ROSEUSDT,0.183740,0.183900,0.184000,0.183550,6.216510e+04,0.183240,0.183720,0.184270,0.181450,...,NaN,NaN,NaN,-0.032831,-0.013437,-0.024068,-0.003740,0.153610,0.59800,2022-05-05 12:05:18.955001
1431359,COTIUSDT,0.217000,0.217600,0.217600,0.216900,3.802100e+04,0.218500,0.217100,0.219100,0.216700,...,0.215047,NaN,NaN,-0.061528,-0.058805,-0.062955,-0.057444,0.170400,0.45980,2022-05-05 12:05:18.955001
1511999,VETUSDT,0.052930,0.053080,0.053100,0.052920,1.117988e+06,0.053310,0.052940,0.053360,0.052690,...,0.069015,NaN,NaN,-0.019720,-0.019355,-0.019724,-0.019173,0.039050,0.10298,2022-05-05 12:05:18.955001
1552319,RUNEUSDT,7.343000,7.356000,7.365000,7.335000,5.725300e+03,7.307000,7.340000,7.402000,7.263000,...,NaN,NaN,NaN,0.060451,0.301811,0.157428,0.422491,3.015000,13.20300,2022-05-05 12:05:18.955001
1632959,ONTUSDT,0.481800,0.482800,0.482800,0.481800,2.207300e+04,0.482700,0.481900,0.483600,0.480000,...,0.838844,NaN,NaN,-0.174534,-0.174241,-0.174743,-0.174095,0.405600,0.78090,2022-05-05 12:05:18.955001
1915199,MATICUSDT,1.158000,1.160000,1.161000,1.158000,8.498440e+04,1.161000,1.158000,1.163000,1.154000,...,0.851948,NaN,NaN,-0.235563,-0.149209,-0.200167,-0.106033,1.011000,2.92300,2022-05-05 12:05:18.955001
1995839,BANDUSDT,3.319000,3.329000,3.330000,3.319000,4.639000e+02,3.326000,3.321000,3.338000,3.311000,...,7.701866,NaN,NaN,-1.831315,-1.820170,-1.842259,-1.814598,2.792000,7.00000,2022-05-05 12:05:18.955001
2318399,BTCUSDT,39588.850000,39605.410000,39607.800000,39585.220000,2.458828e+01,39549.280000,39588.840000,39619.940000,39516.920000,...,35963.226100,NaN,NaN,-3399.177718,-3043.917688,-3398.938884,-2866.287673,32917.170000,52088.00000,2022-05-05 12:05:18.955001
2358719,ADAUSDT,0.874300,0.874400,0.875000,0.872800,5.714922e+05,0.862500,0.874300,0.877900,0.861300,...,1.004927,NaN,NaN,-0.322923,-0.319323,-0.332197,-0.317523,0.735100,1.63800,2022-05-05 12:05:18.955001
2399039,STORJUSDT,0.941300,0.944200,0.944900,0.941200,2.316000e+03,0.941200,0.941200,0.946800,0.936400,...,NaN,NaN,NaN,-0.246280,-0.209630,-0.229412,-0.191304,0.771400,2.18560,2022-05-05 12:05:18.955001
2479679,MANAUSDT,1.630800,1.631300,1.632400,1.629000,2.496100e+04,1.629400,1.630800,1.635900,1.614300,...,NaN,NaN,NaN,-0.335879,-0.115027,-0.245342,-0.004601,1.337500,3.96940,2022-05-05 12:05:18.955001

In [50]:
# 8h under 0.2

drop = final.loc[((final['STRSIK8h']< 0.2) )]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [51]:
# 4 H down
drop = final.loc[(rule4kdown & rule4RSIdown)]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
322559,MIRUSDT,1.16500,1.16300,1.16500,1.16200,8677.30,1.1530,1.16500,1.16800,1.14200,...,NaN,NaN,NaN,-1.064791,-1.064560,-1.067806,-1.064444,0.99400,2.7540,2022-05-05 12:05:18.955001
362879,ALGOUSDT,0.70470,0.70520,0.70600,0.70400,32468.00,0.7017,0.70480,0.70710,0.69730,...,0.924590,NaN,NaN,-0.347174,-0.346099,-0.365297,-0.345562,0.53730,1.8451,2022-05-05 12:05:18.955001
403199,ZRXUSDT,0.79170,0.79200,0.79230,0.79170,1211.00,0.7904,0.79250,0.79770,0.78780,...,0.820444,NaN,NaN,-0.037977,-0.072788,-0.056843,-0.090194,0.44810,1.1838,2022-05-05 12:05:18.955001
645119,LRCUSDT,0.81840,0.81820,0.81910,0.81760,11071.00,0.8063,0.81830,0.82170,0.80360,...,NaN,NaN,NaN,-0.163260,-0.138717,-0.157285,-0.126445,0.62680,2.4722,2022-05-05 12:05:18.955001
720719,IMXUSDT,1.78600,1.78500,1.78700,1.78400,3444.38,1.7800,1.78600,1.81000,1.77000,...,NaN,NaN,NaN,-0.479047,-0.490996,-0.550871,-0.496970,1.10100,2.8490,2022-05-05 12:05:18.955001
1592639,CELRUSDT,0.03852,0.03855,0.03856,0.03840,704505.60,0.0381,0.03852,0.03864,0.03790,...,0.043379,NaN,NaN,-0.016951,-0.015353,-0.015774,-0.014554,0.03089,0.1018,2022-05-05 12:05:18.955001
1794239,ZILUSDT,0.09208,0.09209,0.09262,0.09196,4871013.70,0.0959,0.09211,0.09693,0.09185,...,0.077769,NaN,NaN,0.010603,0.011919,0.012122,0.012577,0.03317,0.2307,2022-05-05 12:05:18.955001
2036159,1INCHUSDT,1.30600,1.31100,1.31500,1.30600,116585.80,1.2630,1.30600,1.32300,1.25900,...,NaN,NaN,NaN,-0.767362,-0.762773,-0.780029,-0.760478,1.07100,2.9820,2022-05-05 12:05:18.955001
2197439,LUNAUSDT,86.20000,86.29000,86.29000,86.19000,1074.93,85.8700,86.21000,86.26000,85.36000,...,NaN,NaN,NaN,20.036303,23.171286,21.478064,24.738777,43.44000,119.5500,2022-05-05 12:05:18.955001
2439359,THETAUSDT,2.56400,2.56100,2.56400,2.55500,37461.30,2.5490,2.56400,2.56800,2.52800,...,4.159050,NaN,NaN,-1.369178,-1.326050,-1.351659,-1.304486,2.13000,5.9460,2022-05-05 12:05:18.955001

In [52]:
# 4 H reversal start
drop = final.loc[(rule4kdown & rule4RSIup &  (final['STRSIK4h']< 0.2))]

drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [53]:
# 4 hour K rising 
drop = final.loc[((rule4under & rule4kup) & (final['STRSIK4h']< 0.2) )]
#drop = final.loc[((rule4under & rule4kup)  )]

#drop = final.loc[(rule12kdown & rule12RSIup)]

drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [54]:
drop = final.loc[((rule4kup & rule4RSIup) )]
drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
1391039,GLMRUSDT,2.81,2.8171,2.8191,2.81,2388.2,2.7966,2.8093,2.82,2.7762,...,NaN,NaN,NaN,-1.548201,-1.467644,-1.567746,-1.427365,2.1807,5.99,2022-05-05 12:05:18.955001

In [55]:
# 4 H down RSI up
drop = final.loc[(rule4kdown & rule4RSIup)]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
40319,ANKRUSDT,0.065830,0.065930,0.065950,0.065820,1.814409e+05,0.066860,0.065840,0.066880,0.065820,...,0.063906,NaN,NaN,-0.014089,-0.011956,-0.013035,-0.010890,0.051070,0.119410,2022-05-05 12:05:18.955001
80639,AVAXUSDT,67.160000,67.280000,67.310000,67.100000,1.369070e+03,66.980000,67.140000,67.380000,66.730000,...,NaN,NaN,NaN,-1.798922,3.138903,-0.433112,5.607816,52.950000,127.320000,2022-05-05 12:05:18.955001
161279,REEFUSDT,0.007550,0.007570,0.007570,0.007540,3.043442e+06,0.007540,0.007550,0.007570,0.007480,...,NaN,NaN,NaN,-0.006253,-0.006309,-0.006242,-0.006337,0.006740,0.022300,2022-05-05 12:05:18.955001
201599,LINKUSDT,11.990000,12.010000,12.020000,11.980000,4.800610e+03,11.960000,12.000000,12.020000,11.910000,...,20.101752,NaN,NaN,-5.813270,-5.478109,-5.717577,-5.310528,10.650000,28.710000,2022-05-05 12:05:18.955001
241919,ARUSDT,26.000000,26.040000,26.040000,26.000000,1.708900e+02,25.940000,25.990000,26.070000,25.700000,...,NaN,NaN,NaN,-8.406501,-7.045464,-7.971154,-6.364945,22.010000,69.000000,2022-05-05 12:05:18.955001
282239,ATOMUSDT,19.980000,20.010000,20.070000,19.970000,9.841370e+03,19.950000,19.980000,20.140000,19.870000,...,17.702010,NaN,NaN,-4.433399,-2.476045,-3.840063,-1.497368,17.220000,44.700000,2022-05-05 12:05:18.955001
524159,NEARUSDT,12.707000,12.724000,12.734000,12.705000,6.922100e+03,12.751000,12.706000,12.780000,12.646000,...,NaN,NaN,NaN,2.384499,2.906230,2.854220,3.167095,7.385000,20.597000,2022-05-05 12:05:18.955001
564479,WINUSDT,0.000259,0.000259,0.000259,0.000258,1.031913e+08,0.000261,0.000259,0.000261,0.000258,...,0.000382,NaN,NaN,-0.000118,-0.000118,-0.000116,-0.000118,0.000238,0.000544,2022-05-05 12:05:18.955001
685439,CRVUSDT,2.603000,2.607000,2.609000,2.602000,1.257410e+04,2.634000,2.603000,2.637000,2.603000,...,NaN,NaN,NaN,-0.472869,-0.522246,-0.569052,-0.546934,1.868000,6.800000,2022-05-05 12:05:18.955001
755999,SCRTUSDT,3.921000,3.926000,3.926000,3.921000,5.753000e+02,3.919000,3.923000,3.930000,3.912000,...,NaN,NaN,NaN,-0.897122,-0.713231,-0.862354,-0.621286,3.605000,6.848000,2022-05-05 12:05:18.955001
796319,RENUSDT,0.305000,0.305300,0.305300,0.304800,2.301800e+04,0.303200,0.305300,0.305900,0.301100,...,0.538559,NaN,NaN,-0.161750,-0.159637,-0.162814,-0.158581,0.242600,0.771500,2022-05-05 12:05:18.955001
836639,SUSHIUSDT,2.592000,2.594000,2.594000,2.589000,1.637100e+04,2.575000,2.592000,2.597000,2.557000,...,NaN,NaN,NaN,-2.804007,-2.838111,-2.812371,-2.855162,2.240000,10.684000,2022-05-05 12:05:18.955001
876959,CAKEUSDT,7.716000,7.719000,7.721000,7.713000,9.955000e+02,7.718000,7.718000,7.725000,7.681000,...,NaN,NaN,NaN,-3.131324,-3.495932,-3.136239,-3.678236,5.300000,13.500000,2022-05-05 12:05:18.955001
957599,HNTUSDT,16.320000,16.380000,16.380000,16.320000,4.576400e+02,16.420000,16.330000,16.440000,16.280000,...,NaN,NaN,NaN,-5.607353,-4.065078,-5.326369,-3.293941,11.610000,45.160000,2022-05-05 12:05:18.955001
997919,OMGUSDT,4.195000,4.204000,4.208000,4.195000,1.170000e+03,4.180000,4.194000,4.206000,4.158000,...,5.499918,NaN,NaN,-1.525861,-1.507688,-1.537666,-1.498602,3.326000,7.197000,2022-05-05 12:05:18.955001
1038239,LINAUSDT,0.019490,0.019560,0.019570,0.019480,1.017814e+06,0.019530,0.019510,0.019710,0.019430,...,NaN,NaN,NaN,-0.016494,-0.017515,-0.016789,-0.018026,0.016330,0.055000,2022-05-05 12:05:18.955001
1113839,SRMUSDT,1.997000,2.000000,2.001000,1.995000,5.981300e+03,1.990000,1.996000,2.003000,1.980000,...,NaN,NaN,NaN,-1.339587,-1.342796,-1.327951,-1.344400,1.652000,4.283000,2022-05-05 12:05:18.955001
1154159,VTHOUSDT,0.003323,0.003323,0.003323,0.003323,1.267860e+05,0.003342,0.003319,0.003342,0.003316,...,NaN,NaN,NaN,-0.001835,-0.001836,-0.001797,-0.001837,0.002738,0.010000,2022-05-05 12:05:18.955001
1194479,ANTUSDT,3.541000,3.546000,3.548000,3.539000,3.360300e+03,3.536000,3.541000,3.547000,3.507000,...,NaN,NaN,NaN,-1.332916,-1.027002,-1.210500,-0.874045,3.057000,14.293000,2022-05-05 12:05:18.955001
1234799,RAYUSDT,2.227000,2.229000,2.229000,2.227000,1.227000e+03,2.218000,2.228000,2.232000,2.206000,...,NaN,NaN,NaN,-2.483595,-2.566998,-2.507520,-2.608699,2.000000,8.200000,2022-05-05 12:05:18.955001
1275119,ROSEUSDT,0.183740,0.183900,0.184000,0.183550,6.216510e+04,0.183240,0.183720,0.184270,0.181450,...,NaN,NaN,NaN,-0.032831,-0.013437,-0.024068,-0.003740,0.153610,0.598000,2022-05-05 12:05:18.955001
1315439,MOVRUSDT,43.700000,43.700000,43.700000,43.600000,2.805600e+01,43.400000,43.600000,43.700000,43.200000,...,NaN,NaN,NaN,-110.309682,-117.103380,-113.584100,-120.500230,39.100000,240.000000,2022-05-05 12:05:18.955001
1431359,COTIUSDT,0.217000,0.217600,0.217600,0.216900,3.802100e+04,0.218500,0.217100,0.219100,0.216700,...,0.215047,NaN,NaN,-0.061528,-0.058805,-0.062955,-0.057444,0.170400,0.459800,2022-05-05 12:05:18.955001
1471679,ONEUSDT,0.090210,0.090520,0.090590,0.090160,3.113850e+05,0.090660,0.090200,0.091200,0.089490,...,0.101622,NaN,NaN,-0.056105,-0.045941,-0.052352,-0.040859,0.069530,0.378970,2022-05-05 12:05:18.955001
1511999,VETUSDT,0.052930,0.053080,0.053100,0.052920,1.117988e+06,0.053310,0.052940,0.053360,0.052690,...,0.069015,NaN,NaN,-0.019720,-0.019355,-0.019724,-0.019173,0.039050,0.102980,2022-05-05 12:05:18.955001
1552319,RUNEUSDT,7.343000,7.356000,7.365000,7.335000,5.725300e+03,7.307000,7.340000,7.402000,7.263000,...,NaN,NaN,NaN,0.060451,0.301811,0.157428,0.422491,3.015000,13.203000,2022-05-05 12:05:18.955001
1632959,ONTUSDT,0.481800,0.482800,0.482800,0.481800,2.207300e+04,0.482700,0.481900,0.483600,0.480000,...,0.838844,NaN,NaN,-0.174534,-0.174241,-0.174743,-0.174095,0.405600,0.780900,2022-05-05 12:05:18.955001
1673279,GALAUSDT,0.157390,0.157850,0.157880,0.157370,6.622310e+05,0.157250,0.157400,0.158520,0.156580,...,NaN,NaN,NaN,-0.050284,-0.031434,-0.043893,-0.022009,0.120000,0.598800,2022-05-05 12:05:18.955001
1713599,GRTUSDT,0.332100,0.332800,0.332900,0.331800,8.501900e+04,0.333400,0.332100,0.334200,0.331000,...,NaN,NaN,NaN,-0.214135,-0.218761,-0.217859,-0.221073,0.290000,0.777000,2022-05-05 12:05:18.955001
1753919,DOTUSDT,16.180000,16.190000,16.200000,16.170000,8.096370e+03,16.160000,16.180000,16.230000,16.070000,...,NaN,NaN,NaN,-5.820978,-5.452171,-5.667417,-5.267768,14.050000,32.780000,2022-05-05 12:05:18.955001
1915199,MATICUSDT,1.158000,1.160000,1.161000,1.158000,8.498440e+04,1.161000,1.158000,1.163000,1.154000,...,0.851948,NaN,NaN,-0.235563,-0.149209,-0.200167,-0.106033,1.011000,2.923000,2022-05-05 12:05:18.955001
1955519,FTMUSDT,0.856900,0.858400,0.859800,0.856400,1.134090e+05,0.848800,0.856800,0.862000,0.844000,...,0.760668,NaN,NaN,-0.442431,-0.320300,-0.400219,-0.259235,0.651300,3.378800,2022-05-05 12:05:18.955001
1995839,BANDUSDT,3.319000,3.329000,3.330000,3.319000,4.639000e+02,3.326000,3.321000,3.338000,3.311000,...,7.701866,NaN,NaN,-1.831315,-1.820170,-1.842259,-1.814598,2.792000,7.000000,2022-05-05 12:05:18.955001
2116799,IOTXUSDT,0.060560,0.060640,0.060660,0.060550,6.917000e+04,0.060350,0.060560,0.060810,0.060150,...,0.046689,NaN,NaN,-0.012784,-0.008132,-0.010291,-0.005806,0.054800,0.153140,2022-05-05 12:05:18.955001
2157119,CTSIUSDT,0.296900,0.297500,0.297700,0.296700,2.539100e+04,0.296900,0.297000,0.298000,0.294700,...,0.386062,NaN,NaN,-0.164673,-0.156559,-0.161912,-0.152501,0.252700,0.852000,2022-05-05 12:05:18.955001
2237759,SOLUSDT,93.190000,93.250000,93.340000,93.130000,1.474130e+03,92.980000,93.190000,93.500000,92.810000,...,NaN,NaN,NaN,-15.605759,-13.953420,-14.620151,-13.127250,75.350000,204.750000,2022-05-05 12:05:18.955001
2278079,MINAUSDT,2.016000,2.027000,2.029000,2.015000,8.839200e+03,2.030000,2.016000,2.033000,2.000000,...,NaN,NaN,NaN,-0.751594,-0.699782,-0.740417,-0.673876,1.584000,4.248000,2022-05-05 12:05:18.955001
2318399,BTCUSDT,39588.850000,39605.410000,39607.800000,39585.220000,2.458828e+01,39549.280000,39588.840000,39619.940000,39516.920000,...,35963.226100,NaN,NaN,-3399.177718,-3043.917688,-3398.938884,-2866.287673,32917.170000,52088.000000,2022-05-05 12:05:18.955001
2358719,ADAUSDT,0.874300,0.874400,0.875000,0.872800,5.714922e+05,0.862500,0.874300,0.877900,0.861300,...,1.004927,NaN,NaN,-0.322923,-0.319323,-0.332197,-0.317523,0.735100,1.638000,2022-05-05 12:05:18.955001
2399039,STORJUSDT,0.941300,0.944200,0.944900,0.941200,2.316000e+03,0.941200,0.941200,0.946800,0.936400,...,NaN,NaN,NaN,-0.246280,-0.209630,-0.229412,-0.191304,0.771400,2.185600,2022-05-05 12:05:18.955001
2479679,MANAUSDT,1.630800,1.631300,1.632400,1.629000,2.496100e+04,1.629400,1.630800,1.635900,1.614300,...,NaN,NaN,NaN,-0.335879,-0.115027,-0.245342,-0.004601,1.337500,3.969400,2022-05-05 12:05:18.955001
2560319,INJUSDT,4.222000,4.223000,4.223000,4.222000,1.714000e+02,4.252000,4.222000,4.252000,4.221000,...,NaN,NaN,NaN,-2.398083,-2.227965,-2.382864,-2.142906,3.418000,10.337000,2022-05-05 12:05:18.955001

In [56]:
# 4H RSI DOWN 
drop = final.loc[(rule4RSIdown)]
drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
322559,MIRUSDT,1.16500,1.16300,1.16500,1.16200,8677.30,1.1530,1.16500,1.16800,1.14200,...,NaN,NaN,NaN,-1.064791,-1.064560,-1.067806,-1.064444,0.99400,2.7540,2022-05-05 12:05:18.955001
362879,ALGOUSDT,0.70470,0.70520,0.70600,0.70400,32468.00,0.7017,0.70480,0.70710,0.69730,...,0.924590,NaN,NaN,-0.347174,-0.346099,-0.365297,-0.345562,0.53730,1.8451,2022-05-05 12:05:18.955001
403199,ZRXUSDT,0.79170,0.79200,0.79230,0.79170,1211.00,0.7904,0.79250,0.79770,0.78780,...,0.820444,NaN,NaN,-0.037977,-0.072788,-0.056843,-0.090194,0.44810,1.1838,2022-05-05 12:05:18.955001
645119,LRCUSDT,0.81840,0.81820,0.81910,0.81760,11071.00,0.8063,0.81830,0.82170,0.80360,...,NaN,NaN,NaN,-0.163260,-0.138717,-0.157285,-0.126445,0.62680,2.4722,2022-05-05 12:05:18.955001
720719,IMXUSDT,1.78600,1.78500,1.78700,1.78400,3444.38,1.7800,1.78600,1.81000,1.77000,...,NaN,NaN,NaN,-0.479047,-0.490996,-0.550871,-0.496970,1.10100,2.8490,2022-05-05 12:05:18.955001
1073519,FLUXUSDT,1.64100,1.62900,1.64100,1.62500,26036.29,1.5820,1.64100,1.64600,1.57900,...,NaN,NaN,NaN,-0.094990,-0.143075,-0.148361,-0.167117,1.26500,2.1000,2022-05-05 12:05:18.955001
1592639,CELRUSDT,0.03852,0.03855,0.03856,0.03840,704505.60,0.0381,0.03852,0.03864,0.03790,...,0.043379,NaN,NaN,-0.016951,-0.015353,-0.015774,-0.014554,0.03089,0.1018,2022-05-05 12:05:18.955001
1794239,ZILUSDT,0.09208,0.09209,0.09262,0.09196,4871013.70,0.0959,0.09211,0.09693,0.09185,...,0.077769,NaN,NaN,0.010603,0.011919,0.012122,0.012577,0.03317,0.2307,2022-05-05 12:05:18.955001
2036159,1INCHUSDT,1.30600,1.31100,1.31500,1.30600,116585.80,1.2630,1.30600,1.32300,1.25900,...,NaN,NaN,NaN,-0.767362,-0.762773,-0.780029,-0.760478,1.07100,2.9820,2022-05-05 12:05:18.955001
2197439,LUNAUSDT,86.20000,86.29000,86.29000,86.19000,1074.93,85.8700,86.21000,86.26000,85.36000,...,NaN,NaN,NaN,20.036303,23.171286,21.478064,24.738777,43.44000,119.5500,2022-05-05 12:05:18.955001
2439359,THETAUSDT,2.56400,2.56100,2.56400,2.55500,37461.30,2.5490,2.56400,2.56800,2.52800,...,4.159050,NaN,NaN,-1.369178,-1.326050,-1.351659,-1.304486,2.13000,5.9460,2022-05-05 12:05:18.955001

In [57]:
# 4h under 0.2
#drop = final.loc[((rule4under & rule4kup) & (final['STRSIK4h']< 0.2) )]

drop = final.loc[((final['STRSIK4h']< 0.2) )]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [58]:
# 2h under 0.2
#drop = final.loc[((rule4under & rule4kup) & (final['STRSIK4h']< 0.2) )]

drop = final.loc[((final['STRSIK2h']< 0.2) )]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [59]:
# 2 H down RSI up
drop = final.loc[(rule2kdown & rule2RSIup)]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
40319,ANKRUSDT,0.065830,0.065930,0.065950,0.065820,1.814409e+05,0.066860,0.065840,0.066880,0.065820,...,0.063906,NaN,NaN,-0.014089,-0.011956,-0.013035,-0.010890,0.051070,0.119410,2022-05-05 12:05:18.955001
80639,AVAXUSDT,67.160000,67.280000,67.310000,67.100000,1.369070e+03,66.980000,67.140000,67.380000,66.730000,...,NaN,NaN,NaN,-1.798922,3.138903,-0.433112,5.607816,52.950000,127.320000,2022-05-05 12:05:18.955001
120959,WAXPUSDT,0.224700,0.224800,0.224900,0.224600,2.452100e+04,0.223900,0.224900,0.225100,0.222100,...,NaN,NaN,NaN,-0.093935,-0.080320,-0.086685,-0.073513,0.204800,0.530500,2022-05-05 12:05:18.955001
161279,REEFUSDT,0.007550,0.007570,0.007570,0.007540,3.043442e+06,0.007540,0.007550,0.007570,0.007480,...,NaN,NaN,NaN,-0.006253,-0.006309,-0.006242,-0.006337,0.006740,0.022300,2022-05-05 12:05:18.955001
201599,LINKUSDT,11.990000,12.010000,12.020000,11.980000,4.800610e+03,11.960000,12.000000,12.020000,11.910000,...,20.101752,NaN,NaN,-5.813270,-5.478109,-5.717577,-5.310528,10.650000,28.710000,2022-05-05 12:05:18.955001
241919,ARUSDT,26.000000,26.040000,26.040000,26.000000,1.708900e+02,25.940000,25.990000,26.070000,25.700000,...,NaN,NaN,NaN,-8.406501,-7.045464,-7.971154,-6.364945,22.010000,69.000000,2022-05-05 12:05:18.955001
282239,ATOMUSDT,19.980000,20.010000,20.070000,19.970000,9.841370e+03,19.950000,19.980000,20.140000,19.870000,...,17.702010,NaN,NaN,-4.433399,-2.476045,-3.840063,-1.497368,17.220000,44.700000,2022-05-05 12:05:18.955001
362879,ALGOUSDT,0.704700,0.705200,0.706000,0.704000,3.246800e+04,0.701700,0.704800,0.707100,0.697300,...,0.924590,NaN,NaN,-0.347174,-0.346099,-0.365297,-0.345562,0.537300,1.845100,2022-05-05 12:05:18.955001
403199,ZRXUSDT,0.791700,0.792000,0.792300,0.791700,1.211000e+03,0.790400,0.792500,0.797700,0.787800,...,0.820444,NaN,NaN,-0.037977,-0.072788,-0.056843,-0.090194,0.448100,1.183800,2022-05-05 12:05:18.955001
524159,NEARUSDT,12.707000,12.724000,12.734000,12.705000,6.922100e+03,12.751000,12.706000,12.780000,12.646000,...,NaN,NaN,NaN,2.384499,2.906230,2.854220,3.167095,7.385000,20.597000,2022-05-05 12:05:18.955001
564479,WINUSDT,0.000259,0.000259,0.000259,0.000258,1.031913e+08,0.000261,0.000259,0.000261,0.000258,...,0.000382,NaN,NaN,-0.000118,-0.000118,-0.000116,-0.000118,0.000238,0.000544,2022-05-05 12:05:18.955001
685439,CRVUSDT,2.603000,2.607000,2.609000,2.602000,1.257410e+04,2.634000,2.603000,2.637000,2.603000,...,NaN,NaN,NaN,-0.472869,-0.522246,-0.569052,-0.546934,1.868000,6.800000,2022-05-05 12:05:18.955001
755999,SCRTUSDT,3.921000,3.926000,3.926000,3.921000,5.753000e+02,3.919000,3.923000,3.930000,3.912000,...,NaN,NaN,NaN,-0.897122,-0.713231,-0.862354,-0.621286,3.605000,6.848000,2022-05-05 12:05:18.955001
836639,SUSHIUSDT,2.592000,2.594000,2.594000,2.589000,1.637100e+04,2.575000,2.592000,2.597000,2.557000,...,NaN,NaN,NaN,-2.804007,-2.838111,-2.812371,-2.855162,2.240000,10.684000,2022-05-05 12:05:18.955001
876959,CAKEUSDT,7.716000,7.719000,7.721000,7.713000,9.955000e+02,7.718000,7.718000,7.725000,7.681000,...,NaN,NaN,NaN,-3.131324,-3.495932,-3.136239,-3.678236,5.300000,13.500000,2022-05-05 12:05:18.955001
917279,XLMUSDT,0.184900,0.185100,0.185200,0.184800,1.428830e+05,0.185600,0.184800,0.185700,0.184700,...,0.256641,NaN,NaN,-0.055395,-0.055582,-0.056384,-0.055676,0.161700,0.305900,2022-05-05 12:05:18.955001
957599,HNTUSDT,16.320000,16.380000,16.380000,16.320000,4.576400e+02,16.420000,16.330000,16.440000,16.280000,...,NaN,NaN,NaN,-5.607353,-4.065078,-5.326369,-3.293941,11.610000,45.160000,2022-05-05 12:05:18.955001
997919,OMGUSDT,4.195000,4.204000,4.208000,4.195000,1.170000e+03,4.180000,4.194000,4.206000,4.158000,...,5.499918,NaN,NaN,-1.525861,-1.507688,-1.537666,-1.498602,3.326000,7.197000,2022-05-05 12:05:18.955001
1038239,LINAUSDT,0.019490,0.019560,0.019570,0.019480,1.017814e+06,0.019530,0.019510,0.019710,0.019430,...,NaN,NaN,NaN,-0.016494,-0.017515,-0.016789,-0.018026,0.016330,0.055000,2022-05-05 12:05:18.955001
1113839,SRMUSDT,1.997000,2.000000,2.001000,1.995000,5.981300e+03,1.990000,1.996000,2.003000,1.980000,...,NaN,NaN,NaN,-1.339587,-1.342796,-1.327951,-1.344400,1.652000,4.283000,2022-05-05 12:05:18.955001
1154159,VTHOUSDT,0.003323,0.003323,0.003323,0.003323,1.267860e+05,0.003342,0.003319,0.003342,0.003316,...,NaN,NaN,NaN,-0.001835,-0.001836,-0.001797,-0.001837,0.002738,0.010000,2022-05-05 12:05:18.955001
1194479,ANTUSDT,3.541000,3.546000,3.548000,3.539000,3.360300e+03,3.536000,3.541000,3.547000,3.507000,...,NaN,NaN,NaN,-1.332916,-1.027002,-1.210500,-0.874045,3.057000,14.293000,2022-05-05 12:05:18.955001
1234799,RAYUSDT,2.227000,2.229000,2.229000,2.227000,1.227000e+03,2.218000,2.228000,2.232000,2.206000,...,NaN,NaN,NaN,-2.483595,-2.566998,-2.507520,-2.608699,2.000000,8.200000,2022-05-05 12:05:18.955001
1275119,ROSEUSDT,0.183740,0.183900,0.184000,0.183550,6.216510e+04,0.183240,0.183720,0.184270,0.181450,...,NaN,NaN,NaN,-0.032831,-0.013437,-0.024068,-0.003740,0.153610,0.598000,2022-05-05 12:05:18.955001
1315439,MOVRUSDT,43.700000,43.700000,43.700000,43.600000,2.805600e+01,43.400000,43.600000,43.700000,43.200000,...,NaN,NaN,NaN,-110.309682,-117.103380,-113.584100,-120.500230,39.100000,240.000000,2022-05-05 12:05:18.955001
1355759,TFUELUSDT,0.141300,0.141300,0.141300,0.141200,2.278800e+04,0.141700,0.141200,0.141700,0.140100,...,0.182240,NaN,NaN,-0.056830,-0.052193,-0.054823,-0.049874,0.114000,0.250000,2022-05-05 12:05:18.955001
1391039,GLMRUSDT,2.810000,2.817100,2.819100,2.810000,2.388200e+03,2.796600,2.809300,2.820000,2.776200,...,NaN,NaN,NaN,-1.548201,-1.467644,-1.567746,-1.427365,2.180700,5.990000,2022-05-05 12:05:18.955001
1431359,COTIUSDT,0.217000,0.217600,0.217600,0.216900,3.802100e+04,0.218500,0.217100,0.219100,0.216700,...,0.215047,NaN,NaN,-0.061528,-0.058805,-0.062955,-0.057444,0.170400,0.459800,2022-05-05 12:05:18.955001
1471679,ONEUSDT,0.090210,0.090520,0.090590,0.090160,3.113850e+05,0.090660,0.090200,0.091200,0.089490,...,0.101622,NaN,NaN,-0.056105,-0.045941,-0.052352,-0.040859,0.069530,0.378970,2022-05-05 12:05:18.955001
1511999,VETUSDT,0.052930,0.053080,0.053100,0.052920,1.117988e+06,0.053310,0.052940,0.053360,0.052690,...,0.069015,NaN,NaN,-0.019720,-0.019355,-0.019724,-0.019173,0.039050,0.102980,2022-05-05 12:05:18.955001
1552319,RUNEUSDT,7.343000,7.356000,7.365000,7.335000,5.725300e+03,7.307000,7.340000,7.402000,7.263000,...,NaN,NaN,NaN,0.060451,0.301811,0.157428,0.422491,3.015000,13.203000,2022-05-05 12:05:18.955001
1592639,CELRUSDT,0.038520,0.038550,0.038560,0.038400,7.045056e+05,0.038100,0.038520,0.038640,0.037900,...,0.043379,NaN,NaN,-0.016951,-0.015353,-0.015774,-0.014554,0.030890,0.101800,2022-05-05 12:05:18.955001
1632959,ONTUSDT,0.481800,0.482800,0.482800,0.481800,2.207300e+04,0.482700,0.481900,0.483600,0.480000,...,0.838844,NaN,NaN,-0.174534,-0.174241,-0.174743,-0.174095,0.405600,0.780900,2022-05-05 12:05:18.955001
1673279,GALAUSDT,0.157390,0.157850,0.157880,0.157370,6.622310e+05,0.157250,0.157400,0.158520,0.156580,...,NaN,NaN,NaN,-0.050284,-0.031434,-0.043893,-0.022009,0.120000,0.598800,2022-05-05 12:05:18.955001
1713599,GRTUSDT,0.332100,0.332800,0.332900,0.331800,8.501900e+04,0.333400,0.332100,0.334200,0.331000,...,NaN,NaN,NaN,-0.214135,-0.218761,-0.217859,-0.221073,0.290000,0.777000,2022-05-05 12:05:18.955001
1753919,DOTUSDT,16.180000,16.190000,16.200000,16.170000,8.096370e+03,16.160000,16.180000,16.230000,16.070000,...,NaN,NaN,NaN,-5.820978,-5.452171,-5.667417,-5.267768,14.050000,32.780000,2022-05-05 12:05:18.955001
1874879,SCUSDT,0.008880,0.008890,0.008900,0.008880,1.075830e+05,0.008880,0.008890,0.008920,0.008820,...,NaN,NaN,NaN,-0.003373,-0.003220,-0.003252,-0.003143,0.007220,0.017840,2022-05-05 12:05:18.955001
1915199,MATICUSDT,1.158000,1.160000,1.161000,1.158000,8.498440e+04,1.161000,1.158000,1.163000,1.154000,...,0.851948,NaN,NaN,-0.235563,-0.149209,-0.200167,-0.106033,1.011000,2.923000,2022-05-05 12:05:18.955001
1955519,FTMUSDT,0.856900,0.858400,0.859800,0.856400,1.134090e+05,0.848800,0.856800,0.862000,0.844000,...,0.760668,NaN,NaN,-0.442431,-0.320300,-0.400219,-0.259235,0.651300,3.378800,2022-05-05 12:05:18.955001
1995839,BANDUSDT,3.319000,3.329000,3.330000,3.319000,4.639000e+02,3.326000,3.321000,3.338000,3.311000,...,7.701866,NaN,NaN,-1.831315,-1.820170,-1.842259,-1.814598,2.792000,7.000000,2022-05-05 12:05:18.955001
2076479,AUDIOUSDT,0.907000,0.909000,0.909000,0.907000,5.479400e+03,0.910000,0.907000,0.914000,0.898000,...,NaN,NaN,NaN,-0.288984,-0.269661,-0.249257,-0.259999,0.653000,2.131000,2022-05-05 12:05:18.955001
2116799,IOTXUSDT,0.060560,0.060640,0.060660,0.060550,6.917000e+04,0.060350,0.060560,0.060810,0.060150,...,0.046689,NaN,NaN,-0.012784,-0.008132,-0.010291,-0.005806,0.054800,0.153140,2022-05-05 12:05:18.955001
2157119,CTSIUSDT,0.296900,0.297500,0.297700,0.296700,2.539100e+04,0.296900,0.297000,0.298000,0.294700,...,0.386062,NaN,NaN,-0.164673,-0.156559,-0.161912,-0.152501,0.252700,0.852000,2022-05-05 12:05:18.955001
2197439,LUNAUSDT,86.200000,86.290000,86.290000,86.190000,1.074930e+03,85.870000,86.210000,86.260000,85.360000,...,NaN,NaN,NaN,20.036303,23.171286,21.478064,24.738777,43.440000,119.550000,2022-05-05 12:05:18.955001
2237759,SOLUSDT,93.190000,93.250000,93.340000,93.130000,1.474130e+03,92.980000,93.190000,93.500000,92.810000,...,NaN,NaN,NaN,-15.605759,-13.953420,-14.620151,-13.127250,75.350000,204.750000,2022-05-05 12:05:18.955001
2278079,MINAUSDT,2.016000,2.027000,2.029000,2.015000,8.839200e+03,2.030000,2.016000,2.033000,2.000000,...,NaN,NaN,NaN,-0.751594,-0.699782,-0.740417,-0.673876,1.584000,4.248000,2022-05-05 12:05:18.955001
2318399,BTCUSDT,39588.850000,39605.410000,39607.800000,39585.220000,2.458828e+01,39549.280000,39588.840000,39619.940000,39516.920000,...,35963.226100,NaN,NaN,-3399.177718,-3043.917688,-3398.938884,-2866.287673,32917.170000,52088.000000,2022-05-05 12:05:18.955001
2358719,ADAUSDT,0.874300,0.874400,0.875000,0.872800,5.714922e+05,0.862500,0.874300,0.877900,0.861300,...,1.004927,NaN,NaN,-0.322923,-0.319323,-0.332197,-0.317523,0.735100,1.638000,2022-05-05 12:05:18.955001
2399039,STORJUSDT,0.941300,0.944200,0.944900,0.941200,2.316000e+03,0.941200,0.941200,0.946800,0.936400,...,NaN,NaN,NaN,-0.246280,-0.209630,-0.229412,-0.191304,0.771400,2.185600,2022-05-05 12:05:18.955001
2519999,PAXGUSDT,1896.000000,1895.000000,1896.000000,1895.000000,3.331300e+00,1898.000000,1895.000000,1898.000000,1894.000000,...,NaN,NaN,NaN,43.367996,61.143861,57.233692,70.031793,1759.000000,2076.000000,2022-05-05 12:05:18.955001
2560319,INJUSDT,4.222000,4.223000,4.223000,4.222000,1.714000e+02,4.252000,4.222000,4.252000,4.221000,...,NaN,NaN,NaN,-2.398083,-2.227965,-2.382864,-2.142906,3.418000,10.337000,2022-05-05 12:05:18.955001

In [60]:
# 2 H down RSI down
drop = final.loc[(rule2kdown & rule2RSIdown) ]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
322559,MIRUSDT,1.16500,1.16300,1.16500,1.16200,8677.30,1.1530,1.16500,1.16800,1.14200,...,NaN,NaN,NaN,-1.064791,-1.064560,-1.067806,-1.064444,0.99400,2.7540,2022-05-05 12:05:18.955001
720719,IMXUSDT,1.78600,1.78500,1.78700,1.78400,3444.38,1.7800,1.78600,1.81000,1.77000,...,NaN,NaN,NaN,-0.479047,-0.490996,-0.550871,-0.496970,1.10100,2.8490,2022-05-05 12:05:18.955001
1073519,FLUXUSDT,1.64100,1.62900,1.64100,1.62500,26036.29,1.5820,1.64100,1.64600,1.57900,...,NaN,NaN,NaN,-0.094990,-0.143075,-0.148361,-0.167117,1.26500,2.1000,2022-05-05 12:05:18.955001
1794239,ZILUSDT,0.09208,0.09209,0.09262,0.09196,4871013.70,0.0959,0.09211,0.09693,0.09185,...,0.077769,NaN,NaN,0.010603,0.011919,0.012122,0.012577,0.03317,0.2307,2022-05-05 12:05:18.955001
2439359,THETAUSDT,2.56400,2.56100,2.56400,2.55500,37461.30,2.5490,2.56400,2.56800,2.52800,...,4.159050,NaN,NaN,-1.369178,-1.326050,-1.351659,-1.304486,2.13000,5.9460,2022-05-05 12:05:18.955001
2479679,MANAUSDT,1.63080,1.63130,1.63240,1.62900,24961.00,1.6294,1.63080,1.63590,1.61430,...,NaN,NaN,NaN,-0.335879,-0.115027,-0.245342,-0.004601,1.33750,3.9694,2022-05-05 12:05:18.955001

In [61]:
# 2 H up  RSI up
drop = final.loc[(rule2kup & rule2RSIup)]

drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
483839,KSMUSDT,141.8,142.1,142.2,141.8,21.999,142.0,141.9,142.9,140.8,...,NaN,NaN,NaN,-67.597996,-68.976297,-67.612915,-69.665447,105.2,345.0,2022-05-05 12:05:18.955001

# Second part to be cleaned

In [62]:
# 8 4 2 over and up

drop = final.loc[(rule8over & rule8kup & rule4over & rule4kup & rule2over) ]
#drop = final.loc[(rule4over & rule4kup & rule2over) ]

drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [63]:
# Split RSI and STCH  tables 
#finalRSI = final.loc[:,['Indicator','RSI2h','RSIM2h','RSI4h','RSIM4h','RSI8h','RSIM8h','RSI12h','RSIM12h','RSI1d','RSIM1d','RSI3d','RSIM3d']]
#finalSTRSIK = final.loc[:,['Indicator','STRSIK2h','STRSIKM2h','STRSIK4h','STRSIKM4h','STRSIK8h','STRSIKM8h','STRSIK12h','STRSIKM12h','STRSIK1d','STRSIKM1d','STRSIK3d','STRSIKM3d','STRSID2h','STRSIDM2h','STRSID4h','STRSIDM4h','STRSID8h','STRSIDM8h','STRSID12h','STRSIDM12h','STRSID1d','STRSIDM1d','STRSID3d','STRSIDM3d']]
finalRSI = final.loc[:,['Indicator','RSI2h','RSIM2h','RSI4h','RSIM4h','RSI8h','RSIM8h','RSI12h','RSIM12h','RSI1d','RSIM1d','RSI3d','RSIM3d']]
finalSTRSIK = final.loc[:,['Indicator','STRSIK2h','STRSIKM2h','STRSIK4h','STRSIKM4h','STRSIK8h','STRSIKM8h','STRSIK12h','STRSIKM12h','STRSIK1d','STRSIKM1d','STRSIK3d','STRSIKM3d','STRSID2h','STRSIDM2h','STRSID4h','STRSIDM4h','STRSID8h','STRSIDM8h','STRSID12h','STRSIDM12h','STRSID1d','STRSIDM1d','STRSID3d','STRSIDM3d']]
#finalST = 
finalSTRSIK

,Indicator,STRSIK2h,STRSIKM2h,STRSIK4h,STRSIKM4h,STRSIK8h,STRSIKM8h,STRSIK12h,STRSIKM12h,STRSIK1d,...,STRSID4h,STRSIDM4h,STRSID8h,STRSIDM8h,STRSID12h,STRSIDM12h,STRSID1d,STRSIDM1d,STRSID3d,STRSIDM3d
40319,ANKRUSDT,0.581460,0.707848,0.862283,0.930086,0.930920,0.956414,0.930766,0.784883,0.588887,...,0.930790,0.939507,0.959317,0.933564,0.802497,0.687072,0.449082,0.329770,0.044620,0.036750
80639,AVAXUSDT,0.713883,0.827230,0.873848,0.935227,0.995283,0.982012,0.998710,0.911717,0.762644,...,0.936201,0.957069,0.987476,0.965207,0.927801,0.855632,0.517075,0.313833,0.029975,0.024641
120959,WAXPUSDT,0.732728,0.831317,0.862931,0.931466,0.924181,0.847664,0.837660,0.662815,0.438621,...,0.931466,0.920717,0.828452,0.688246,0.683409,0.556686,0.298514,0.197049,0.023000,0.016077
161279,REEFUSDT,0.671958,0.782459,0.862942,0.923342,0.915834,0.935617,0.954325,0.821024,0.500313,...,0.925139,0.931361,0.931280,0.887686,0.859764,0.754133,0.369256,0.264403,0.053014,0.122696
201599,LINKUSDT,0.656367,0.740440,0.873658,0.928633,0.922464,0.922253,0.961598,0.861655,0.701113,...,0.929342,0.940280,0.934871,0.902453,0.871110,0.754472,0.463127,0.279217,0.026563,0.032804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399039,STORJUSDT,0.635413,0.748919,0.885736,0.938465,0.938272,0.967524,0.939840,0.803642,0.585692,...,0.941400,0.945937,0.968599,0.946503,0.826123,0.725645,0.387200,0.236839,0.062680,0.138338
2439359,THETAUSDT,0.613574,0.723483,0.914089,0.960113,0.952832,0.979059,0.948099,0.843310,0.526130,...,0.958067,0.971622,0.975131,0.958675,0.855468,0.737363,0.363123,0.235644,0.061295,0.114299
2479679,MANAUSDT,0.658391,0.765732,0.884983,0.940685,0.943086,0.972726,0.976894,0.918704,0.729770,...,0.941105,0.956944,0.971937,0.963781,0.938101,0.874906,0.508263,0.328993,0.043666,0.006652
2519999,PAXGUSDT,0.843677,0.914541,0.926076,0.963038,1.000000,0.797403,0.675182,0.457046,0.415388,...,0.963038,0.962315,0.802182,0.607482,0.438342,0.263533,0.217623,0.123367,0.035530,0.023815
2560319,INJUSDT,0.207954,0.250124,0.702048,0.716970,0.869233,0.867693,0.860538,0.890731,0.934930,...,0.719639,0.732973,0.854447,0.854638,0.851254,0.791593,0.634919,0.323275,0.121888,0.040832

In [64]:
drop = final.loc[( rule1dover & rule1dkup & rule12under &rule12kdown & rule8under & rule4kdown)]
drop

,Indicator,O1h,C1h,H1h,L1h,V1h,OM1h,CM1h,HM1h,LM1h,...,SMA100M1w,SMA2001w,SMA200M1w,MACD1w,MACDSIGNAL1w,MACDM1w,MACDSIGNALM1w,BOTTOMP1w,TOPP1w,Time
524159,NEARUSDT,12.707,12.724,12.734,12.705,6922.1,12.751,12.706,12.78,12.646,...,NaN,NaN,NaN,2.384499,2.90623,2.85422,3.167095,7.385,20.597,2022-05-05 12:05:18.955001

In [65]:
## Will go up below 0.2 k 4 and 8 still going up

drop = final.loc[((final['STRSIK8h'] > final['STRSIKM8h']) & (final['STRSIK4h'] > final['STRSIKM4h']) & (final['STRSIK8h'] < 0.2) &  (final['STRSIK8h'] > final['STRSID8h']))]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [66]:
## under 0.2 and will go down
## WILL GO DOWN still K > D , K are dropping on 4 hour and 8 hours still above D and under 0.2
drop = final.loc[((final['STRSIK8h'] < final['STRSIKM8h']) & (final['STRSIK4h'] < final['STRSIKM4h']) & (final['STRSIK4h'] < 0.2) &  (final['STRSIK8h'] > final['STRSID8h']))]
drop

Empty DataFrame
Columns: [Indicator, O1h, C1h, H1h, L1h, V1h, OM1h, CM1h, HM1h, LM1h, VM1h, RSI1h, RSIM1h, STRSI1h, STRSIK1h, STRSIKM1h, STRSID1h, STRSIDM1h, SMA211h, SMA21M1h, SMA551h, SMA55M1h, SMA1001h, SMA100M1h, SMA2001h, SMA200M1h, MACD1h, MACDSIGNAL1h, MACDM1h, MACDSIGNALM1h, BOTTOMP1h, TOPP1h, O2h, C2h, H2h, L2h, V2h, OM2h, CM2h, HM2h, LM2h, VM2h, RSI2h, RSIM2h, STRSI2h, STRSIK2h, STRSIKM2h, STRSID2h, STRSIDM2h, SMA212h, SMA21M2h, SMA552h, SMA55M2h, SMA1002h, SMA100M2h, SMA2002h, SMA200M2h, MACD2h, MACDSIGNAL2h, MACDM2h, MACDSIGNALM2h, BOTTOMP2h, TOPP2h, O4h, C4h, H4h, L4h, V4h, OM4h, CM4h, HM4h, LM4h, VM4h, RSI4h, RSIM4h, STRSI4h, STRSIK4h, STRSIKM4h, STRSID4h, STRSIDM4h, SMA214h, SMA21M4h, SMA554h, SMA55M4h, SMA1004h, SMA100M4h, SMA2004h, SMA200M4h, MACD4h, MACDSIGNAL4h, MACDM4h, MACDSIGNALM4h, BOTTOMP4h, TOPP4h, O8h, C8h, H8h, L8h, V8h, OM8h, ...]
Index: []

[0 rows x 250 columns]

In [67]:
#save = drop[['Indicator','RSI','STRSI']]
#save = save.rename(columns={'STRSI': 'STRSI1','RSI':'RSI1'})
#save
#save.to_csv("strsi1KD.csv")
RSITABLE = drop[['Indicator', 'RSI2h', 'RSIM2h','RSI4h', 'RSIM4h','RSI8h', 'RSIM8h']]
sort1 = RSITABLE.sort_values(by=['RSI2h'],ascending=True,inplace = True)


RSITABLE

/Users/hjabbour/opt/anaconda3/envs/cryptodev/lib/python3.8/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

Empty DataFrame
Columns: [Indicator, RSI2h, RSIM2h, RSI4h, RSIM4h, RSI8h, RSIM8h]
Index: []

In [68]:
STCHTABLE = drop[['Indicator','STRSIK2h', 'STRSID2h','STRSIK4h', 'STRSID4h','STRSIK8h', 'STRSID8h']]
STCHTABLE

Empty DataFrame
Columns: [Indicator, STRSIK2h, STRSID2h, STRSIK4h, STRSID4h, STRSIK8h, STRSID8h]
Index: []

In [69]:
# High 8 hours going down
STCHTABLEH = STCHTABLE.loc[STCHTABLE['STRSID8h']> 0.8]
STCHTABLEH
#save

Empty DataFrame
Columns: [Indicator, STRSIK2h, STRSID2h, STRSIK4h, STRSID4h, STRSIK8h, STRSID8h]
Index: []

In [70]:
#del final, whitelist ,dflive

def bottoms(final:pd)-> pd :
    intervals = ['1h','2h','4h','8h','12h','1d','3d']        
    query = []
    bottomlist ={}
    for i in intervals:
        var = globals()['bottom'+i]
        test = final.loc[(var)]
        #print(test[['Indicator']])
        if len(test.index) > 0 : query.append(i)
        #bottomlist[str(query)]=test['Indicator'].tolist()
        bottomlist[i]=test['Indicator'].tolist()
        #print(query)
        #print(bottomlist)
    
    #print(bottomlist)
    
    
    fquery=''
    for b in query[:-1]:
        #loop through all elements but last
        fquery += 'bottom'+b+'&'
        #test = final.loc[eval(fquery)]
        bottomlist[i]=test['Indicator'].tolist()
    fquery+='bottom'+query.pop()
    
    
    
    #fquery=fquery.lstrip('&')
    #print(fquery)
    #print(len(query))
    #print(test)
    #var1 = globals()[fquery]
    test = final.loc[eval(fquery)]
    #print(test)
    return bottomlist




check= bottoms(final)
#check
listb = bottoms(final)

#print(listb)
#print(get_key(listb,'CRVUSDT'))
#print("ltos =")
#print(ltos(get_key(listb,'CRVUSDT')))
## unique values
res = list(sorted({ele for val in listb.values() for ele in val}))

#print (res)
bottomtable = pd.DataFrame(res,columns=['Indicator'])

listofindi = bottomtable['Indicator'].tolist()
#print(listofindi)
reversetable = []
for indi in listofindi:
    ## two option add the tuple as key list or as key.string
    #ttuple = (indi,get_key(listb,indi))
    ttuple = (indi,ltos(get_key(listb,indi)))
    reversetable.append(ttuple)
    #print(indi,get_key(listb,indi))
    #bottomtable.loc[(bottomtable['Indicator']==indi)].bottoms =get_key(listb,indi)